# SPDX-License-Identifier: AGPL-3.0-or-later
"""sc_neurocore.analysis -- Tier: research (experimental / research)."""

__tier__ = "research"

from .explainability import SpikeToConceptMapper
from .spike_train_stats import (
    spike_times,
    isi,
    firing_rate,
    cv_isi,
    fano_factor,
    spike_count,
    psth,
    cross_correlation,
    pairwise_correlation,
    power_spectrum,
    burst_detection,
    instantaneous_rate,
    van_rossum_distance,
    victor_purpura_distance,
    isi_distance,
    cv2,
    local_variation,
    isi_entropy,
    event_synchronization,
    spike_train_coherence,
    first_spike_latency,
    response_onset,
    spike_triggered_average,
    bin_spike_train,
    population_rate,
    surrogate_isi_shuffle,
    surrogate_dither,
    surrogate_trial_shuffle,
    mutual_information,
    transfer_entropy,
    phase_locking_value,
    spike_field_coherence,
    spike_phase_histogram,
    spike_train_pca,
    population_vector_decode,
    functional_connectivity,
    significance_bootstrap,
)

__all__ = [
    "SpikeToConceptMapper",
    "spike_times",
    "isi",
    "firing_rate",
    "cv_isi",
    "fano_factor",
    "spike_count",
    "psth",
    "cross_correlation",
    "pairwise_correlation",
    "power_spectrum",
    "burst_detection",
    "instantaneous_rate",
    "van_rossum_distance",
    "victor_purpura_distance",
    "isi_distance",
    "cv2",
    "local_variation",
    "isi_entropy",
    "event_synchronization",
    "spike_train_coherence",
    "first_spike_latency",
    "response_onset",
    "spike_triggered_average",
    "bin_spike_train",
    "population_rate",
    "surrogate_isi_shuffle",
    "surrogate_dither",
    "surrogate_trial_shuffle",
    "mutual_information",
    "transfer_entropy",
    "phase_locking_value",
    "spike_field_coherence",
    "spike_phase_histogram",
    "spike_train_pca",
    "population_vector_decode",
    "functional_connectivity",
    "significance_bootstrap",
]
