# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Phi estimation for Integrated Information Theory

"""Approximate Phi (integrated information) for spiking networks.

Tononi 2004 / Oizumi, Albantakis & Tononi 2014 (IIT 3.0+).

Phi measures how much a system is "more than the sum of its parts" —
the amount of information generated by a system above and beyond its
parts. High Phi → high integration → candidate for consciousness.

Full Phi computation is NP-hard (requires evaluating all bipartitions).
This module provides tractable approximations:

1. phi_star: Geometric integrated information (Barrett & Seth 2011)
   Based on the mutual information between past and future states.

2. phi_ar: Autoregressive approximation (Mediano et al. 2019)
   Uses a VAR model to estimate the minimum information partition.

    from sc_neurocore.analysis.phi_estimation import phi_star

    phi = phi_star(spike_trains)  # shape (n_neurons, n_timesteps)
"""

from __future__ import annotations

from typing import Any
import numpy as np
from scipy.linalg import det as sla_det


def phi_star(data: np.ndarray[Any, Any], tau: int = 1) -> float:
    """Geometric integrated information (Barrett & Seth 2011).

    Phi* = MI(past; future) - max_partition sum MI(past_k; future_k)

    Approximated via Gaussian assumption: MI = 0.5 * log(det(Sigma_X) * det(Sigma_Y) / det(Sigma_XY)).

    Parameters
    ----------
    data : np.ndarray[Any, Any]
        Shape (n_channels, n_timesteps). Spike counts or continuous signals.
    tau : int
        Time lag for past→future mapping.

    Returns
    -------
    float
        Phi* estimate (bits). Non-negative; 0 = fully reducible.
    """
    n, T = data.shape
    if 2 * tau >= T or n < 2:
        return 0.0

    past = data[:, :-tau]
    future = data[:, tau:]

    # Joint mutual information I(past; future)
    mi_whole = _gaussian_mi(past, future)

    # Minimum information partition: try all bipartitions
    # For tractability, only try contiguous splits (first k vs rest)
    mi_parts_min = np.inf
    for k in range(1, n):
        idx_a = list(range(k))
        idx_b = list(range(k, n))
        mi_a = _gaussian_mi(past[idx_a], future[idx_a])
        mi_b = _gaussian_mi(past[idx_b], future[idx_b])
        mi_parts_min = min(mi_parts_min, mi_a + mi_b)

    phi = max(0.0, mi_whole - mi_parts_min)
    return float(phi)


def _gaussian_mi(x: np.ndarray[Any, Any], y: np.ndarray[Any, Any]) -> float:
    """Mutual information under Gaussian assumption.

    MI(X;Y) = 0.5 * log(det(Cov_X) * det(Cov_Y) / det(Cov_XY))
    """
    nx = x.shape[0]
    ny = y.shape[0]
    xy = np.vstack([x, y])

    cov_x = np.cov(x) if nx > 1 else np.atleast_2d(np.var(x))
    cov_y = np.cov(y) if ny > 1 else np.atleast_2d(np.var(y))
    cov_xy = np.cov(xy)

    # Regularize to avoid singular matrices
    eps = 1e-10
    cov_x += eps * np.eye(cov_x.shape[0])
    cov_y += eps * np.eye(cov_y.shape[0])
    cov_xy += eps * np.eye(cov_xy.shape[0])

    det_x = max(sla_det(cov_x), 1e-300)
    det_y = max(sla_det(cov_y), 1e-300)
    det_xy = max(sla_det(cov_xy), 1e-300)

    mi = 0.5 * np.log(det_x * det_y / det_xy)
    return max(0.0, float(mi))


def phi_from_spike_trains(spikes: np.ndarray[Any, Any], bin_size: int = 10, tau: int = 1) -> float:
    """Compute Phi* from binary spike trains.

    Parameters
    ----------
    spikes : np.ndarray[Any, Any]
        Shape (n_neurons, n_timesteps), binary {0, 1}.
    bin_size : int
        Number of timesteps per bin for spike count computation.
    tau : int
        Time lag in bins.

    Returns
    -------
    float
        Phi* in bits.
    """
    n_neurons, n_steps = spikes.shape
    n_bins = n_steps // bin_size
    if n_bins < 2 * tau + 2:
        return 0.0

    # Bin spike trains into spike counts
    binned = np.zeros((n_neurons, n_bins))
    for b in range(n_bins):
        binned[:, b] = spikes[:, b * bin_size : (b + 1) * bin_size].sum(axis=1)

    return phi_star(binned, tau=tau)
