# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /engine
    schedule:
      interval: weekly
    labels: [dependencies, rust]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [ci]
    open-pull-requests-limit: 3
