# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Reduced three-state Chay-Keizer pancreatic beta-cell burster

from __future__ import annotations

import math
from dataclasses import dataclass


@dataclass
class ChayKeizerMinimalNeuron:
    """Reduced three-state Chay-Keizer pancreatic beta-cell burster.

    The essential bursting dynamics of the original five-state Chay-Keizer model
    reduced to three variables: membrane potential ``v``, the delayed-rectifier
    potassium activation ``n``, and the free cytosolic calcium ``c`` (the slow
    variable). The calcium-current activation is taken at its instantaneous
    steady state, so the fast spikes are generated by the ``v``-``n`` subsystem
    while calcium slowly accumulates through the active phase, activates a
    calcium-dependent potassium conductance, and terminates the burst; calcium is
    then pumped down through the silent phase. A constant ATP-sensitive potassium
    conductance sets the excitability (the glucose handle).

    Currents follow the convention ``g (V - E_rev)`` (outward positive) in the
    physical units of the reference (picosiemens, femtofarads, femtoamperes,
    millivolts, micromolar, milliseconds). With the published parameters the cell
    bursts autonomously: fast spikes ride an active-phase plateau near -20 mV with
    a silent phase near -65 mV, while cytosolic calcium traces a slow sawtooth.

    Reference: Bertram, R., Marinelli, I., Fletcher, P.A., Satin, L.S. &
    Sherman, A.S. (2023). Deconstructing the integrated oscillator model for
    pancreatic beta-cells. Mathematical Biosciences 365:109085, Table 1
    (DOI 10.1016/j.mbs.2023.109015); the reduced model of Chay & Keizer (1983),
    Biophys. J. 42:181-190.
    """

    v: float = -60.0
    n: float = 0.0
    c: float = 0.1
    g_ca: float = 1000.0
    g_k: float = 2700.0
    g_kca: float = 400.0
    g_katp: float = 180.0
    c_m: float = 5300.0
    e_ca: float = 25.0
    e_k: float = -75.0
    v_m: float = -20.0
    v_n: float = -16.0
    s_m: float = 12.0
    s_n: float = 5.0
    n_hill: float = 3.0
    k_d: float = 0.3
    f_c: float = 0.001
    alpha: float = 1.125e-6
    k_pmca: float = 0.045
    tau_n: float = 20.0
    dt: float = 0.05
    # Spikes peak near -21 mV on the plateau; detect upward crossings below it.
    v_threshold: float = -35.0

    _MAX_SUBSTEP: float = 0.05
    _V_MIN: float = -200.0
    _V_MAX: float = 200.0
    _C_MAX: float = 100.0

    @staticmethod
    def _finite(value: float, name: str) -> float:
        value = float(value)
        if not math.isfinite(value):
            raise ValueError(f"{name} must be finite")
        return value

    @classmethod
    def _positive(cls, value: float, name: str) -> float:
        value = cls._finite(value, name)
        if value <= 0.0:
            raise ValueError(f"{name} must be positive")
        return value

    @classmethod
    def _nonnegative(cls, value: float, name: str) -> float:
        value = cls._finite(value, name)
        if value < 0.0:
            raise ValueError(f"{name} must be non-negative")
        return value

    @classmethod
    def _probability(cls, value: float, name: str) -> float:
        value = cls._finite(value, name)
        if not 0.0 <= value <= 1.0:
            raise ValueError(f"{name} must be in [0, 1]")
        return value

    @classmethod
    def _checked_exp(cls, exponent: float) -> float:
        if exponent < -700.0:
            return 0.0
        if exponent > 700.0:
            return math.exp(700.0)
        return math.exp(exponent)

    def _m_inf(self, v: float) -> float:
        return 1.0 / (1.0 + self._checked_exp((self.v_m - v) / self.s_m))

    def _n_inf(self, v: float) -> float:
        return 1.0 / (1.0 + self._checked_exp((self.v_n - v) / self.s_n))

    def _validated_state(self) -> tuple[float, float, float, int, float]:
        v = self._finite(self.v, "v")
        if not self._V_MIN <= v <= self._V_MAX:
            raise ValueError("v outside Chay-Keizer safety envelope")
        n = self._probability(self.n, "n")
        c = self._nonnegative(self.c, "c")
        if c > self._C_MAX:
            raise ValueError("c outside Chay-Keizer safety envelope")

        self._nonnegative(self.g_ca, "g_ca")
        self._nonnegative(self.g_k, "g_k")
        self._nonnegative(self.g_kca, "g_kca")
        self._nonnegative(self.g_katp, "g_katp")
        self._positive(self.c_m, "c_m")
        self._finite(self.e_ca, "e_ca")
        self._finite(self.e_k, "e_k")
        self._finite(self.v_m, "v_m")
        self._finite(self.v_n, "v_n")
        self._positive(self.s_m, "s_m")
        self._positive(self.s_n, "s_n")
        self._positive(self.n_hill, "n_hill")
        self._positive(self.k_d, "k_d")
        self._nonnegative(self.f_c, "f_c")
        self._finite(self.alpha, "alpha")
        self._nonnegative(self.k_pmca, "k_pmca")
        self._positive(self.tau_n, "tau_n")
        dt = self._positive(self.dt, "dt")
        self._finite(self.v_threshold, "v_threshold")

        substeps = max(1, math.ceil(dt / self._MAX_SUBSTEP))
        if substeps > 100000:
            raise ValueError("dt requires too many Chay-Keizer integration substeps")
        return v, n, c, substeps, dt / substeps

    def _candidate(
        self, v: float, n: float, c: float, current: float, step_dt: float
    ) -> tuple[float, float, float]:
        i_ca = self.g_ca * self._m_inf(v) * (v - self.e_ca)
        i_k = self.g_k * n * (v - self.e_k)
        c_pow = c**self.n_hill
        i_kca = self.g_kca * (c_pow / (self.k_d**self.n_hill + c_pow)) * (v - self.e_k)
        i_katp = self.g_katp * (v - self.e_k)
        j_mem = -(self.alpha * i_ca + self.k_pmca * c)

        v_next = v + (current - (i_ca + i_k + i_kca + i_katp)) / self.c_m * step_dt
        n_next = n + (self._n_inf(v) - n) / self.tau_n * step_dt
        c_next = c + self.f_c * j_mem * step_dt

        if not math.isfinite(v_next) or not self._V_MIN <= v_next <= self._V_MAX:
            raise ValueError("Chay-Keizer voltage candidate outside safety envelope")
        n_next = min(max(n_next, 0.0), 1.0)
        if not math.isfinite(c_next) or not 0.0 <= c_next <= self._C_MAX:
            raise ValueError("Chay-Keizer calcium candidate outside safety envelope")
        return v_next, n_next, c_next

    def step(self, current: float = 0.0) -> int:
        """Advance one timestep and return an upward-threshold spike flag.

        The default zero current is the autonomous bursting regime; a non-zero
        ``current`` (femtoamperes) is an applied membrane current.
        """

        current = self._finite(current, "current")
        v_initial = self.v
        v, n, c, substeps, step_dt = self._validated_state()

        crossed = False
        for _ in range(substeps):
            v_next, n, c = self._candidate(v, n, c, current, step_dt)
            crossed = crossed or (v_next >= self.v_threshold and v < self.v_threshold)
            v = v_next

        self.v, self.n, self.c = v, n, c
        return 1 if crossed and v_initial < self.v_threshold else 0

    def reset(self) -> None:
        self.v, self.n, self.c = -60.0, 0.0, 0.1
