# SPDX-License-Identifier: AGPL-3.0-or-later
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.rpt$'
      - id: end-of-file-fixer
        exclude: '\.rpt$'
      - id: check-yaml
        args: [--unsafe]
        exclude: "^conda/"
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c60c980e561ed3e73101667fe8365c609d19a438  # v0.15.9
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: d11834eeac776f87614aef80119b38800a9a2bac  # v1.29.5
    hooks:
      - id: typos
