# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Intelligence package re-exports

"""Compiler intelligence helpers for hardware-aware SC-NeuroCore flows."""

from __future__ import annotations

from ..platforms import (
    HardwareProfile,
    discover_platforms,
    get_profile,
    load_profiles_from_toml,
    register_platform_hook,
)
from ..platforms.registry import _DISCOVERY_HOOKS
from .auto_quantization import (
    QuantSweepResult,
    auto_quantisation_sweep,
    format_quantisation_report,
)
from .bitstream_flow import (
    generate_oss_makefile,
)
from .compilation_cache import (
    CompilationCache,
)
from .debug_probes import (
    DebugProbeSpec,
    insert_debug_probes,
)
from .digital_twin import (
    DriftCompensator,
    HILCalibration,
    ScrubSchedule,
    TelemetryResult,
    generate_digital_twin,
    generate_drift_compensator,
    generate_hil_calibration,
    ingest_telemetry,
    schedule_seu_scrubbing,
)
from .dispatch_planner import (
    DispatchPlan,
    plan_heterogeneous_dispatch,
)
from .dvs_bridge import (
    generate_dvs_aer_bridge,
)
from .exotic_physics import (
    AdiabaticPhase,
    CognitiveBounds,
    HolographicRouter,
    MEAMapping,
    Morphology,
    MZIWeightEncoding,
    OmniDispatchMap,
    ReversibleNetlist,
    dispatch_omni_paradigm,
    encode_mzi_weights,
    enforce_cognitive_bounds,
    generate_adiabatic_clocks,
    generate_mzi_config,
    map_wetware_mea,
    route_holographic_interconnects,
    synthesize_morphology,
    synthesize_reversible_logic,
)
from .hls_export import (
    generate_hls_cpp,
)
from .learning_export import (
    OnChipLearningParams,
    export_learning_config,
    generate_learning_params,
)
from .mxfp_encoding import (
    FP8_E4M3,
    MXFP4,
    MXFP6,
    MXFP8_E4M3,
    MXFP8_E5M2,
    MXFPConfig,
    mxfp_decode_block,
    mxfp_encode_block,
)
from .network_optimizer import (
    TopologyPlan,
    optimize_network_topology,
)
from .nir_import import (
    NIRGraph,
    import_nir_graph,
)
from .posit_arithmetic import (
    PositConfig,
    posit_decode,
    posit_encode,
)
from .power_and_thermal import (
    ApproximationConfig,
    EnergyHarvestBudget,
    EnergySchedule,
    ThermalEnvelopeEstimate,
    ThermalEstimate,
    configure_approximation,
    estimate_thermal_envelope,
    generate_dvfs_controller,
    generate_energy_schedule,
    generate_power_intent,
    generate_power_state_machine,
    generate_thermal_constraints,
    model_energy_harvest,
    thermal_analysis,
)
from .reconfig_planner import (
    ReconfigPartition,
    plan_partial_reconfiguration,
)
from .reporting import (
    ModelComplexity,
    ParetoPoint,
    PortabilityScore,
    ProvenanceRecord,
    TargetComparison,
    classify_model_complexity,
    compare_targets,
    explore_pareto,
    format_comparison_report,
    format_provenance_json,
    generate_compilation_report,
    generate_compilation_summary,
    generate_provenance_chain,
    score_portability,
)
from .security_and_compliance import (
    SBOM,
    CarbonEstimate,
    LicenseCheck,
    ObfuscationResult,
    PQCProtection,
    SideChannelFinding,
    SupplyChainRisk,
    TrojanLintResult,
    WatermarkResult,
    check_license_compliance,
    embed_model_checksum,
    embed_watermark,
    estimate_carbon_footprint,
    generate_bitstream_encryption,
    generate_sbom,
    lint_hardware_trojans,
    lint_side_channels,
    obfuscate_ip,
    protect_ip_pqc,
    score_supply_chain_risk,
)
from .soc_and_chiplet import (
    CXLMapping,
    FloorplanResult,
    MemoryMap,
    PIMLayout,
    StorageRecommendation,
    UCIeMapping,
    UCIePartition,
    advise_cxl_mapping,
    advise_ucie_partition,
    generate_bram_array,
    generate_cdc_synchroniser,
    generate_memory_map,
    generate_pipeline_wrapper,
    generate_power_domain_wrapper,
    generate_tmr_wrapper,
    map_ucie_protocol,
    plan_multi_die_floorplan,
    plan_pim_layout,
    storage_recommendation,
)
from .target_recommender import (
    TargetRecommendation,
    recommend_target,
)
from .tcl_gen import (
    generate_tcl_project,
)
from .timescale_partitioner import (
    TimescalePartition,
    partition_timescales,
)
from .verification_and_safety import (
    AgingPrediction,
    CDCReport,
    ComplianceEntry,
    EquivalenceSketch,
    FaultCampaignResult,
    FaultTree,
    RegressionCheck,
    ReliabilityEstimate,
    StabilityResult,
    TimingReport,
    analyze_cdc,
    check_regression,
    format_compliance_report,
    generate_bittrue_kernel,
    generate_compliance_matrix,
    generate_equivalence_sketch,
    generate_fault_tree,
    generate_testbench,
    predict_aging,
    predict_reliability,
    run_fault_campaign,
    verify_ode_stability,
    verify_timing_closure,
)
from .vhdl_emitter import (
    verilog_to_vhdl_wrapper,
)
from .weight_noise import (
    WeightNoiseProfile,
    create_noise_profile,
    inject_weight_noise,
)
from .weight_rom import (
    generate_weight_rom,
)

__all__ = [
    "AdiabaticPhase",
    "AgingPrediction",
    "ApproximationConfig",
    "CDCReport",
    "CXLMapping",
    "CarbonEstimate",
    "CognitiveBounds",
    "CompilationCache",
    "ComplianceEntry",
    "DebugProbeSpec",
    "DispatchPlan",
    "DriftCompensator",
    "EnergyHarvestBudget",
    "EnergySchedule",
    "EquivalenceSketch",
    "FP8_E4M3",
    "FaultCampaignResult",
    "FaultTree",
    "FloorplanResult",
    "HILCalibration",
    "HardwareProfile",
    "HolographicRouter",
    "LicenseCheck",
    "MEAMapping",
    "MXFPConfig",
    "MXFP4",
    "MXFP6",
    "MXFP8_E4M3",
    "MXFP8_E5M2",
    "MZIWeightEncoding",
    "MemoryMap",
    "ModelComplexity",
    "Morphology",
    "NIRGraph",
    "ObfuscationResult",
    "OmniDispatchMap",
    "OnChipLearningParams",
    "PIMLayout",
    "PQCProtection",
    "ParetoPoint",
    "PortabilityScore",
    "PositConfig",
    "ProvenanceRecord",
    "QuantSweepResult",
    "ReconfigPartition",
    "RegressionCheck",
    "ReliabilityEstimate",
    "ReversibleNetlist",
    "SBOM",
    "ScrubSchedule",
    "SideChannelFinding",
    "StabilityResult",
    "StorageRecommendation",
    "SupplyChainRisk",
    "TargetComparison",
    "TargetRecommendation",
    "TelemetryResult",
    "ThermalEnvelopeEstimate",
    "ThermalEstimate",
    "TimescalePartition",
    "TimingReport",
    "TopologyPlan",
    "TrojanLintResult",
    "UCIeMapping",
    "UCIePartition",
    "WatermarkResult",
    "WeightNoiseProfile",
    "_DISCOVERY_HOOKS",
    "advise_cxl_mapping",
    "advise_ucie_partition",
    "analyze_cdc",
    "auto_quantisation_sweep",
    "check_license_compliance",
    "check_regression",
    "classify_model_complexity",
    "compare_targets",
    "configure_approximation",
    "create_noise_profile",
    "discover_platforms",
    "dispatch_omni_paradigm",
    "embed_model_checksum",
    "embed_watermark",
    "encode_mzi_weights",
    "enforce_cognitive_bounds",
    "estimate_carbon_footprint",
    "estimate_thermal_envelope",
    "explore_pareto",
    "export_learning_config",
    "format_comparison_report",
    "format_compliance_report",
    "format_provenance_json",
    "format_quantisation_report",
    "generate_adiabatic_clocks",
    "generate_bitstream_encryption",
    "generate_bittrue_kernel",
    "generate_bram_array",
    "generate_cdc_synchroniser",
    "generate_compilation_report",
    "generate_compilation_summary",
    "generate_compliance_matrix",
    "generate_digital_twin",
    "generate_drift_compensator",
    "generate_dvfs_controller",
    "generate_dvs_aer_bridge",
    "generate_energy_schedule",
    "generate_equivalence_sketch",
    "generate_fault_tree",
    "generate_hil_calibration",
    "generate_hls_cpp",
    "generate_learning_params",
    "generate_memory_map",
    "generate_mzi_config",
    "generate_oss_makefile",
    "generate_pipeline_wrapper",
    "generate_power_domain_wrapper",
    "generate_power_intent",
    "generate_power_state_machine",
    "generate_provenance_chain",
    "generate_sbom",
    "generate_tcl_project",
    "generate_testbench",
    "generate_thermal_constraints",
    "generate_tmr_wrapper",
    "generate_weight_rom",
    "get_profile",
    "import_nir_graph",
    "ingest_telemetry",
    "inject_weight_noise",
    "insert_debug_probes",
    "lint_hardware_trojans",
    "lint_side_channels",
    "load_profiles_from_toml",
    "map_ucie_protocol",
    "map_wetware_mea",
    "model_energy_harvest",
    "mxfp_decode_block",
    "mxfp_encode_block",
    "obfuscate_ip",
    "optimize_network_topology",
    "partition_timescales",
    "plan_heterogeneous_dispatch",
    "plan_multi_die_floorplan",
    "plan_partial_reconfiguration",
    "plan_pim_layout",
    "posit_decode",
    "posit_encode",
    "predict_aging",
    "predict_reliability",
    "protect_ip_pqc",
    "recommend_target",
    "register_platform_hook",
    "route_holographic_interconnects",
    "run_fault_campaign",
    "schedule_seu_scrubbing",
    "score_portability",
    "score_supply_chain_risk",
    "storage_recommendation",
    "synthesize_morphology",
    "synthesize_reversible_logic",
    "thermal_analysis",
    "verify_ode_stability",
    "verify_timing_closure",
    "verilog_to_vhdl_wrapper",
]
