# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Compilation report generator

"""Generate comprehensive compilation report consolidating all metrics."""

from __future__ import annotations

from .carbon_footprint import estimate_carbon_footprint
from .aging_reliability import predict_reliability


def generate_compilation_report(
    module_name: str,
    equations: dict[str, str],
    profile_name: str,
    *,
    include_carbon: bool = True,
    include_reliability: bool = True,
) -> str:
    """Generate comprehensive compilation report.

    Consolidates Verilog, timing, power, carbon, risk,
    and reliability into a single markdown document.

    Parameters
    ----------
    module_name : str
        Module name.
    equations : dict[str, str]
        ODE equations.
    profile_name : str
        Target profile.
    include_carbon : bool
        Include carbon footprint section.
    include_reliability : bool
        Include reliability prediction.

    Returns
    -------
    str
        Markdown report.
    """
    from ...platforms import get_profile

    p = get_profile(profile_name)

    sections = [
        "# SC-NeuroCore Compilation Report",
        "",
        f"## Target: `{profile_name}`",
        f"- **Vendor**: {p.vendor}",
        f"- **Family**: {p.family}",
        f"- **Class**: {p.platform_class}",
        f"- **Width**: {p.data_width}-bit Q{p.data_width - p.fraction}.{p.fraction}",
        f"- **Overflow**: {p.overflow} | **Rounding**: {p.rounding}",
        "",
        f"## Module: `{module_name}`",
        f"- **State variables**: {len(equations)}",
        f"- **Equations**: {', '.join(equations.keys())}",
        "",
    ]

    if include_carbon:
        c = estimate_carbon_footprint(profile_name)
        sections.extend(
            [
                "## Carbon Footprint",
                f"- Manufacturing: {c.manufacturing_kg_co2} kg CO₂",
                f"- Operation (5yr): {c.total_5yr_kg_co2} kg CO₂",
                "",
            ]
        )

    if include_reliability:
        r = predict_reliability(voltage_v=0.9, temperature_c=85)
        sections.extend(
            [
                "## Reliability",
                f"- MTTF: {r.mttf_years} years",
                f"- Failure mode: {r.failure_mode}",
                "",
            ]
        )

    sections.extend(
        [
            "---",
            f"*Generated by SC-NeuroCore — {len(list(equations))} equations, "
            f"target {profile_name}*",
        ]
    )

    return "\n".join(sections)
