# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — DVFS controller generator

"""Dynamic Voltage and Frequency Scaling (DVFS) controller generation."""

from __future__ import annotations


def generate_dvfs_controller(
    module_name: str,
    *,
    operating_points: list[dict] | None = None,
    spike_rate_thresholds: list[float] | None = None,
) -> str:
    """Generate a Verilog DVFS controller FSM."""
    if operating_points is None:
        operating_points = [
            {"voltage_mv": 700, "freq_mhz": 100},
            {"voltage_mv": 900, "freq_mhz": 250},
            {"voltage_mv": 1100, "freq_mhz": 500},
        ]
    if spike_rate_thresholds is None:
        spike_rate_thresholds = [10.0, 50.0]

    n = len(operating_points)
    states = [f"OP_{i}" for i in range(n)]
    lines = [
        f"// DVFS Controller for {module_name}",
        "// Auto-generated by SC-NeuroCore §71",
        f"module {module_name}_dvfs_ctrl (",
        "    input  wire        clk,",
        "    input  wire        rst_n,",
        "    input  wire [15:0] spike_rate,",
        "    output reg  [15:0] target_freq_mhz,",
        "    output reg  [15:0] target_voltage_mv",
        ");",
        "",
    ]
    for i, s in enumerate(states):
        lines.append(f"    localparam {s} = {i};")
    lines.extend(
        [
            f"    reg [{max(1, n - 1).bit_length() - 1}:0] state;",
            "",
            "    always @(posedge clk or negedge rst_n) begin",
            "        if (!rst_n) begin",
            f"            state <= {states[0]};",
            f"            target_freq_mhz <= {operating_points[0]['freq_mhz']};",
            f"            target_voltage_mv <= {operating_points[0]['voltage_mv']};",
            "        end else begin",
            "            case (state)",
        ]
    )
    for i, op in enumerate(operating_points):
        lines.append(f"                {states[i]}: begin")
        lines.append(f"                    target_freq_mhz <= {op['freq_mhz']};")
        lines.append(f"                    target_voltage_mv <= {op['voltage_mv']};")
        if i < n - 1 and i < len(spike_rate_thresholds):
            th = int(spike_rate_thresholds[i])
            lines.append(f"                    if (spike_rate > {th}) state <= {states[i + 1]};")
        if i > 0 and i - 1 < len(spike_rate_thresholds):
            th = int(spike_rate_thresholds[i - 1])
            lines.append(f"                    if (spike_rate < {th}) state <= {states[i - 1]};")
        lines.append("                end")
    lines.extend(
        [
            "            endcase",
            "        end",
            "    end",
            "endmodule",
        ]
    )
    return "\n".join(lines)
