# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Power state machine generator

"""Sleep/wake/hibernate FSM generation for ultra-low-power designs."""

from __future__ import annotations


def generate_power_state_machine(
    module_name: str,
    *,
    states: list[str] | None = None,
) -> str:
    """Generate sleep/wake/hibernate FSM for ultra-low-power."""
    if states is None:
        states = ["ACTIVE", "IDLE", "SLEEP", "HIBERNATE"]

    lines = [
        f"// Power state machine for {module_name}",
        "// Generated by SC-NeuroCore",
        f"module {module_name}_power_fsm (",
        "    input  wire clk, rst_n, wake, sleep_req,",
        f"    output reg [{len(states).bit_length() - 1}:0] state",
        ");",
    ]
    for i, s in enumerate(states):
        lines.append(f"    localparam {s} = {i};")

    lines.extend(
        [
            "    always @(posedge clk or negedge rst_n) begin",
            "        if (!rst_n)",
            f"            state <= {states[0]};",
            "        else case (state)",
        ]
    )
    for i, s in enumerate(states):
        nxt = states[min(i + 1, len(states) - 1)]
        lines.append(f"            {s}: state <= sleep_req ? {nxt} : (wake ? {states[0]} : state);")
    lines.extend(
        [
            "        endcase",
            "    end",
            "endmodule",
        ]
    )

    return "\n".join(lines)
