# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Power intent generator

"""IEEE 1801 UPF power intent generation for multi-voltage designs."""

from __future__ import annotations


def generate_power_intent(
    module_name: str,
    *,
    num_domains: int = 2,
    always_on: bool = True,
) -> str:
    """Generate IEEE 1801 UPF power intent for neuron arrays."""
    lines = [
        f"# UPF Power Intent for {module_name}",
        "# Generated by SC-NeuroCore",
        "",
        f"set_scope {module_name}",
        "",
    ]
    if always_on:
        lines.append("create_power_domain PD_AON -include_scope")
        lines.append("create_supply_net VDD_AON -domain PD_AON")
        lines.append("create_supply_net VSS -domain PD_AON")
        lines.append("")

    for i in range(num_domains):
        lines.extend(
            [
                f"create_power_domain PD_NEURON_{i}",
                f"create_supply_net VDD_{i} -domain PD_NEURON_{i}",
                f"create_supply_net VSS -domain PD_NEURON_{i} -reuse",
                f"set_isolation iso_{i} -domain PD_NEURON_{i} "
                f"-isolation_power_net VDD_AON -isolation_ground_net VSS "
                f"-clamp_value 0",
                f"set_retention ret_{i} -domain PD_NEURON_{i} -retention_power_net VDD_AON",
                "",
            ]
        )

    lines.append("# Power states")
    lines.append("add_power_state PD_AON_ON -domain PD_AON -state ON {-supply_expr {VDD_AON == 1}}")

    return "\n".join(lines)
