# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Evolutionary substrate public API

"""Expose evolutionary-substrate contracts and compatibility imports."""

from sc_neurocore.evo_substrate.evo_substrate import (
    ActivationFunc,
    AgeRegulator,
    BloatMetrics,
    BloatPenalizer,
    CPPNEdge,
    CPPNGenome,
    CPPNNode,
    CoevoOrganism,
    CoevoRole,
    CoevolutionArena,
    ComplexityTracker,
    CrossoverEngine,
    EvoStatisticsTracker,
    ExtinctionDetector,
    FitnessEvaluator,
    FitnessResult,
    FitnessType,
    FormalSafetyGuard,
    GenerationStats,
    Genome,
    GenomeDiff,
    GenomeSerializer,
    HWFitnessCollector,
    HWFitnessReport,
    HallOfFame,
    Island,
    IslandModel,
    LineageRecord,
    LineageTracker,
    MutationConfig,
    MutationEngine,
    MutationType,
    NeuronGene,
    NoveltyArchive,
    Organism,
    OrganismEmitter,
    ParetoFront,
    PlasticityGene,
    ReplicationEngine,
    ResourceBudget,
    RuntimeFaultCheck,
    RuntimeFaultConfig,
    SafetyBounds,
    SafetyCheckResult,
    TileAllocation,
    TileDeploymentTracker,
    TopologyGene,
    TournamentSelector,
    assign_species,
    compute_bloat,
    dominates,
    genome_complexity,
    genome_diff,
    genomic_distance,
    population_diversity,
    shared_fitness,
)

__all__ = [
    "ActivationFunc",
    "AgeRegulator",
    "BloatMetrics",
    "BloatPenalizer",
    "CPPNEdge",
    "CPPNGenome",
    "CPPNNode",
    "CoevoOrganism",
    "CoevoRole",
    "CoevolutionArena",
    "ComplexityTracker",
    "CrossoverEngine",
    "EvoStatisticsTracker",
    "ExtinctionDetector",
    "FitnessEvaluator",
    "FitnessResult",
    "FitnessType",
    "FormalSafetyGuard",
    "GenerationStats",
    "Genome",
    "GenomeDiff",
    "GenomeSerializer",
    "HWFitnessCollector",
    "HWFitnessReport",
    "HallOfFame",
    "Island",
    "IslandModel",
    "LineageRecord",
    "LineageTracker",
    "MutationConfig",
    "MutationEngine",
    "MutationType",
    "NeuronGene",
    "NoveltyArchive",
    "Organism",
    "OrganismEmitter",
    "ParetoFront",
    "PlasticityGene",
    "ReplicationEngine",
    "ResourceBudget",
    "RuntimeFaultCheck",
    "RuntimeFaultConfig",
    "SafetyBounds",
    "SafetyCheckResult",
    "TileAllocation",
    "TileDeploymentTracker",
    "TopologyGene",
    "TournamentSelector",
    "assign_species",
    "compute_bloat",
    "dominates",
    "genome_complexity",
    "genome_diff",
    "genomic_distance",
    "population_diversity",
    "shared_fitness",
]
