// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = (-(v - v_rest) + delta_T * exp((v - v_rh) / delta_T)) / tau + (-w + I) / C, dw/dt = (a * (v - v_rest) - w) / tau_w)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_adex #(
    parameter signed [15:0] P_V_REST = 16'sd48896,
    parameter signed [15:0] P_V_RESET = 16'sd48128,
    parameter signed [15:0] P_V_RH = 16'sd51456,
    parameter signed [15:0] P_DELTA_T = 16'sd512,
    parameter signed [15:0] P_TAU = 16'sd5120,
    parameter signed [15:0] P_TAU_W = 16'sd25600,
    parameter signed [15:0] P_A = 16'sd128,
    parameter signed [15:0] P_B_ADAPT = 16'sd1792,
    parameter signed [15:0] P_C = 16'sd51200
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out,
    output reg signed [15:0] w_out
);

reg signed [15:0] v_reg;
reg signed [15:0] w_reg;

wire signed [15:0] _dop0 = (v_reg - P_V_RH);
wire signed [15:0] _dden0 = P_DELTA_T;
wire signed [31:0] _dnum0 = $signed({{16{_dop0[15]}}, _dop0}) <<< 8;
wire signed [31:0] _div0 = _dnum0 / $signed({{16{_dden0[15]}}, _dden0});
wire signed [15:0] _dres0 = _div0[15:0];
// _exp_lut lookup table (256 entries over [-16.0, 16.0), step 0.125)
wire signed [15:0] _exp_lut1_arg = _dres0;
wire signed [16:0] _exp_lut1_raw = (({{_exp_lut1_arg[15]}, _exp_lut1_arg}) + 17'sd4096) >>> 5;
wire [7:0] _exp_lut1_idx = (_exp_lut1_raw < 0) ? 8'd0 : ((_exp_lut1_raw > 17'sd255) ? 8'd255 : _exp_lut1_raw[7:0]);
reg signed [15:0] _exp_lut1_out;
always @(*) case (_exp_lut1_idx)
    8'd0: _exp_lut1_out = 16'sd0;
    8'd1: _exp_lut1_out = 16'sd0;
    8'd2: _exp_lut1_out = 16'sd0;
    8'd3: _exp_lut1_out = 16'sd0;
    8'd4: _exp_lut1_out = 16'sd0;
    8'd5: _exp_lut1_out = 16'sd0;
    8'd6: _exp_lut1_out = 16'sd0;
    8'd7: _exp_lut1_out = 16'sd0;
    8'd8: _exp_lut1_out = 16'sd0;
    8'd9: _exp_lut1_out = 16'sd0;
    8'd10: _exp_lut1_out = 16'sd0;
    8'd11: _exp_lut1_out = 16'sd0;
    8'd12: _exp_lut1_out = 16'sd0;
    8'd13: _exp_lut1_out = 16'sd0;
    8'd14: _exp_lut1_out = 16'sd0;
    8'd15: _exp_lut1_out = 16'sd0;
    8'd16: _exp_lut1_out = 16'sd0;
    8'd17: _exp_lut1_out = 16'sd0;
    8'd18: _exp_lut1_out = 16'sd0;
    8'd19: _exp_lut1_out = 16'sd0;
    8'd20: _exp_lut1_out = 16'sd0;
    8'd21: _exp_lut1_out = 16'sd0;
    8'd22: _exp_lut1_out = 16'sd0;
    8'd23: _exp_lut1_out = 16'sd0;
    8'd24: _exp_lut1_out = 16'sd0;
    8'd25: _exp_lut1_out = 16'sd0;
    8'd26: _exp_lut1_out = 16'sd0;
    8'd27: _exp_lut1_out = 16'sd0;
    8'd28: _exp_lut1_out = 16'sd0;
    8'd29: _exp_lut1_out = 16'sd0;
    8'd30: _exp_lut1_out = 16'sd0;
    8'd31: _exp_lut1_out = 16'sd0;
    8'd32: _exp_lut1_out = 16'sd0;
    8'd33: _exp_lut1_out = 16'sd0;
    8'd34: _exp_lut1_out = 16'sd0;
    8'd35: _exp_lut1_out = 16'sd0;
    8'd36: _exp_lut1_out = 16'sd0;
    8'd37: _exp_lut1_out = 16'sd0;
    8'd38: _exp_lut1_out = 16'sd0;
    8'd39: _exp_lut1_out = 16'sd0;
    8'd40: _exp_lut1_out = 16'sd0;
    8'd41: _exp_lut1_out = 16'sd0;
    8'd42: _exp_lut1_out = 16'sd0;
    8'd43: _exp_lut1_out = 16'sd0;
    8'd44: _exp_lut1_out = 16'sd0;
    8'd45: _exp_lut1_out = 16'sd0;
    8'd46: _exp_lut1_out = 16'sd0;
    8'd47: _exp_lut1_out = 16'sd0;
    8'd48: _exp_lut1_out = 16'sd0;
    8'd49: _exp_lut1_out = 16'sd0;
    8'd50: _exp_lut1_out = 16'sd0;
    8'd51: _exp_lut1_out = 16'sd0;
    8'd52: _exp_lut1_out = 16'sd0;
    8'd53: _exp_lut1_out = 16'sd0;
    8'd54: _exp_lut1_out = 16'sd0;
    8'd55: _exp_lut1_out = 16'sd0;
    8'd56: _exp_lut1_out = 16'sd0;
    8'd57: _exp_lut1_out = 16'sd0;
    8'd58: _exp_lut1_out = 16'sd0;
    8'd59: _exp_lut1_out = 16'sd0;
    8'd60: _exp_lut1_out = 16'sd0;
    8'd61: _exp_lut1_out = 16'sd0;
    8'd62: _exp_lut1_out = 16'sd0;
    8'd63: _exp_lut1_out = 16'sd0;
    8'd64: _exp_lut1_out = 16'sd0;
    8'd65: _exp_lut1_out = 16'sd0;
    8'd66: _exp_lut1_out = 16'sd0;
    8'd67: _exp_lut1_out = 16'sd0;
    8'd68: _exp_lut1_out = 16'sd0;
    8'd69: _exp_lut1_out = 16'sd0;
    8'd70: _exp_lut1_out = 16'sd0;
    8'd71: _exp_lut1_out = 16'sd0;
    8'd72: _exp_lut1_out = 16'sd0;
    8'd73: _exp_lut1_out = 16'sd0;
    8'd74: _exp_lut1_out = 16'sd0;
    8'd75: _exp_lut1_out = 16'sd0;
    8'd76: _exp_lut1_out = 16'sd0;
    8'd77: _exp_lut1_out = 16'sd0;
    8'd78: _exp_lut1_out = 16'sd0;
    8'd79: _exp_lut1_out = 16'sd1;
    8'd80: _exp_lut1_out = 16'sd1;
    8'd81: _exp_lut1_out = 16'sd1;
    8'd82: _exp_lut1_out = 16'sd1;
    8'd83: _exp_lut1_out = 16'sd1;
    8'd84: _exp_lut1_out = 16'sd1;
    8'd85: _exp_lut1_out = 16'sd1;
    8'd86: _exp_lut1_out = 16'sd1;
    8'd87: _exp_lut1_out = 16'sd2;
    8'd88: _exp_lut1_out = 16'sd2;
    8'd89: _exp_lut1_out = 16'sd2;
    8'd90: _exp_lut1_out = 16'sd2;
    8'd91: _exp_lut1_out = 16'sd3;
    8'd92: _exp_lut1_out = 16'sd3;
    8'd93: _exp_lut1_out = 16'sd3;
    8'd94: _exp_lut1_out = 16'sd4;
    8'd95: _exp_lut1_out = 16'sd4;
    8'd96: _exp_lut1_out = 16'sd5;
    8'd97: _exp_lut1_out = 16'sd5;
    8'd98: _exp_lut1_out = 16'sd6;
    8'd99: _exp_lut1_out = 16'sd7;
    8'd100: _exp_lut1_out = 16'sd8;
    8'd101: _exp_lut1_out = 16'sd9;
    8'd102: _exp_lut1_out = 16'sd10;
    8'd103: _exp_lut1_out = 16'sd11;
    8'd104: _exp_lut1_out = 16'sd13;
    8'd105: _exp_lut1_out = 16'sd14;
    8'd106: _exp_lut1_out = 16'sd16;
    8'd107: _exp_lut1_out = 16'sd19;
    8'd108: _exp_lut1_out = 16'sd21;
    8'd109: _exp_lut1_out = 16'sd24;
    8'd110: _exp_lut1_out = 16'sd27;
    8'd111: _exp_lut1_out = 16'sd31;
    8'd112: _exp_lut1_out = 16'sd35;
    8'd113: _exp_lut1_out = 16'sd39;
    8'd114: _exp_lut1_out = 16'sd44;
    8'd115: _exp_lut1_out = 16'sd50;
    8'd116: _exp_lut1_out = 16'sd57;
    8'd117: _exp_lut1_out = 16'sd65;
    8'd118: _exp_lut1_out = 16'sd73;
    8'd119: _exp_lut1_out = 16'sd83;
    8'd120: _exp_lut1_out = 16'sd94;
    8'd121: _exp_lut1_out = 16'sd107;
    8'd122: _exp_lut1_out = 16'sd121;
    8'd123: _exp_lut1_out = 16'sd137;
    8'd124: _exp_lut1_out = 16'sd155;
    8'd125: _exp_lut1_out = 16'sd176;
    8'd126: _exp_lut1_out = 16'sd199;
    8'd127: _exp_lut1_out = 16'sd226;
    8'd128: _exp_lut1_out = 16'sd256;
    8'd129: _exp_lut1_out = 16'sd290;
    8'd130: _exp_lut1_out = 16'sd329;
    8'd131: _exp_lut1_out = 16'sd372;
    8'd132: _exp_lut1_out = 16'sd422;
    8'd133: _exp_lut1_out = 16'sd478;
    8'd134: _exp_lut1_out = 16'sd542;
    8'd135: _exp_lut1_out = 16'sd614;
    8'd136: _exp_lut1_out = 16'sd696;
    8'd137: _exp_lut1_out = 16'sd789;
    8'd138: _exp_lut1_out = 16'sd894;
    8'd139: _exp_lut1_out = 16'sd1012;
    8'd140: _exp_lut1_out = 16'sd1147;
    8'd141: _exp_lut1_out = 16'sd1300;
    8'd142: _exp_lut1_out = 16'sd1473;
    8'd143: _exp_lut1_out = 16'sd1669;
    8'd144: _exp_lut1_out = 16'sd1892;
    8'd145: _exp_lut1_out = 16'sd2143;
    8'd146: _exp_lut1_out = 16'sd2429;
    8'd147: _exp_lut1_out = 16'sd2752;
    8'd148: _exp_lut1_out = 16'sd3119;
    8'd149: _exp_lut1_out = 16'sd3534;
    8'd150: _exp_lut1_out = 16'sd4005;
    8'd151: _exp_lut1_out = 16'sd4538;
    8'd152: _exp_lut1_out = 16'sd5142;
    8'd153: _exp_lut1_out = 16'sd5827;
    8'd154: _exp_lut1_out = 16'sd6602;
    8'd155: _exp_lut1_out = 16'sd7481;
    8'd156: _exp_lut1_out = 16'sd8478;
    8'd157: _exp_lut1_out = 16'sd9606;
    8'd158: _exp_lut1_out = 16'sd10885;
    8'd159: _exp_lut1_out = 16'sd12335;
    8'd160: _exp_lut1_out = 16'sd13977;
    8'd161: _exp_lut1_out = 16'sd15838;
    8'd162: _exp_lut1_out = 16'sd17947;
    8'd163: _exp_lut1_out = 16'sd20337;
    8'd164: _exp_lut1_out = 16'sd23044;
    8'd165: _exp_lut1_out = 16'sd26113;
    8'd166: _exp_lut1_out = 16'sd29590;
    8'd167: _exp_lut1_out = 16'sd32767;
    8'd168: _exp_lut1_out = 16'sd32767;
    8'd169: _exp_lut1_out = 16'sd32767;
    8'd170: _exp_lut1_out = 16'sd32767;
    8'd171: _exp_lut1_out = 16'sd32767;
    8'd172: _exp_lut1_out = 16'sd32767;
    8'd173: _exp_lut1_out = 16'sd32767;
    8'd174: _exp_lut1_out = 16'sd32767;
    8'd175: _exp_lut1_out = 16'sd32767;
    8'd176: _exp_lut1_out = 16'sd32767;
    8'd177: _exp_lut1_out = 16'sd32767;
    8'd178: _exp_lut1_out = 16'sd32767;
    8'd179: _exp_lut1_out = 16'sd32767;
    8'd180: _exp_lut1_out = 16'sd32767;
    8'd181: _exp_lut1_out = 16'sd32767;
    8'd182: _exp_lut1_out = 16'sd32767;
    8'd183: _exp_lut1_out = 16'sd32767;
    8'd184: _exp_lut1_out = 16'sd32767;
    8'd185: _exp_lut1_out = 16'sd32767;
    8'd186: _exp_lut1_out = 16'sd32767;
    8'd187: _exp_lut1_out = 16'sd32767;
    8'd188: _exp_lut1_out = 16'sd32767;
    8'd189: _exp_lut1_out = 16'sd32767;
    8'd190: _exp_lut1_out = 16'sd32767;
    8'd191: _exp_lut1_out = 16'sd32767;
    8'd192: _exp_lut1_out = 16'sd32767;
    8'd193: _exp_lut1_out = 16'sd32767;
    8'd194: _exp_lut1_out = 16'sd32767;
    8'd195: _exp_lut1_out = 16'sd32767;
    8'd196: _exp_lut1_out = 16'sd32767;
    8'd197: _exp_lut1_out = 16'sd32767;
    8'd198: _exp_lut1_out = 16'sd32767;
    8'd199: _exp_lut1_out = 16'sd32767;
    8'd200: _exp_lut1_out = 16'sd32767;
    8'd201: _exp_lut1_out = 16'sd32767;
    8'd202: _exp_lut1_out = 16'sd32767;
    8'd203: _exp_lut1_out = 16'sd32767;
    8'd204: _exp_lut1_out = 16'sd32767;
    8'd205: _exp_lut1_out = 16'sd32767;
    8'd206: _exp_lut1_out = 16'sd32767;
    8'd207: _exp_lut1_out = 16'sd32767;
    8'd208: _exp_lut1_out = 16'sd32767;
    8'd209: _exp_lut1_out = 16'sd32767;
    8'd210: _exp_lut1_out = 16'sd32767;
    8'd211: _exp_lut1_out = 16'sd32767;
    8'd212: _exp_lut1_out = 16'sd32767;
    8'd213: _exp_lut1_out = 16'sd32767;
    8'd214: _exp_lut1_out = 16'sd32767;
    8'd215: _exp_lut1_out = 16'sd32767;
    8'd216: _exp_lut1_out = 16'sd32767;
    8'd217: _exp_lut1_out = 16'sd32767;
    8'd218: _exp_lut1_out = 16'sd32767;
    8'd219: _exp_lut1_out = 16'sd32767;
    8'd220: _exp_lut1_out = 16'sd32767;
    8'd221: _exp_lut1_out = 16'sd32767;
    8'd222: _exp_lut1_out = 16'sd32767;
    8'd223: _exp_lut1_out = 16'sd32767;
    8'd224: _exp_lut1_out = 16'sd32767;
    8'd225: _exp_lut1_out = 16'sd32767;
    8'd226: _exp_lut1_out = 16'sd32767;
    8'd227: _exp_lut1_out = 16'sd32767;
    8'd228: _exp_lut1_out = 16'sd32767;
    8'd229: _exp_lut1_out = 16'sd32767;
    8'd230: _exp_lut1_out = 16'sd32767;
    8'd231: _exp_lut1_out = 16'sd32767;
    8'd232: _exp_lut1_out = 16'sd32767;
    8'd233: _exp_lut1_out = 16'sd32767;
    8'd234: _exp_lut1_out = 16'sd32767;
    8'd235: _exp_lut1_out = 16'sd32767;
    8'd236: _exp_lut1_out = 16'sd32767;
    8'd237: _exp_lut1_out = 16'sd32767;
    8'd238: _exp_lut1_out = 16'sd32767;
    8'd239: _exp_lut1_out = 16'sd32767;
    8'd240: _exp_lut1_out = 16'sd32767;
    8'd241: _exp_lut1_out = 16'sd32767;
    8'd242: _exp_lut1_out = 16'sd32767;
    8'd243: _exp_lut1_out = 16'sd32767;
    8'd244: _exp_lut1_out = 16'sd32767;
    8'd245: _exp_lut1_out = 16'sd32767;
    8'd246: _exp_lut1_out = 16'sd32767;
    8'd247: _exp_lut1_out = 16'sd32767;
    8'd248: _exp_lut1_out = 16'sd32767;
    8'd249: _exp_lut1_out = 16'sd32767;
    8'd250: _exp_lut1_out = 16'sd32767;
    8'd251: _exp_lut1_out = 16'sd32767;
    8'd252: _exp_lut1_out = 16'sd32767;
    8'd253: _exp_lut1_out = 16'sd32767;
    8'd254: _exp_lut1_out = 16'sd32767;
    8'd255: _exp_lut1_out = 16'sd32767;
    default: _exp_lut1_out = 16'sd0;
endcase
wire signed [31:0] _mul2 = P_DELTA_T * _exp_lut1_out;
wire signed [15:0] _t0 = (_mul2 >>> 8);
wire signed [15:0] _dop3 = ((-(v_reg - P_V_REST)) + _t0);
wire signed [15:0] _dden3 = P_TAU;
wire signed [31:0] _dnum3 = $signed({{16{_dop3[15]}}, _dop3}) <<< 8;
wire signed [31:0] _div3 = _dnum3 / $signed({{16{_dden3[15]}}, _dden3});
wire signed [15:0] _dres3 = _div3[15:0];
wire signed [15:0] _dop4 = ((-w_reg) + I_t);
wire signed [15:0] _dden4 = P_C;
wire signed [31:0] _dnum4 = $signed({{16{_dop4[15]}}, _dop4}) <<< 8;
wire signed [31:0] _div4 = _dnum4 / $signed({{16{_dden4[15]}}, _dden4});
wire signed [15:0] _dres4 = _div4[15:0];
wire signed [31:0] _dt_mul_v = ((_dres3 + _dres4)) * 16'sd26;
wire signed [15:0] _dt_trunc_v = (_dt_mul_v >>> 8);
wire signed [31:0] _mul5 = P_A * (v_reg - P_V_REST);
wire signed [15:0] _t1 = (_mul5 >>> 8);
wire signed [15:0] _dop6 = (_t1 - w_reg);
wire signed [15:0] _dden6 = P_TAU_W;
wire signed [31:0] _dnum6 = $signed({{16{_dop6[15]}}, _dop6}) <<< 8;
wire signed [31:0] _div6 = _dnum6 / $signed({{16{_dden6[15]}}, _dden6});
wire signed [15:0] _dres6 = _div6[15:0];
wire signed [31:0] _dt_mul_w = (_dres6) * 16'sd26;
wire signed [15:0] _dt_trunc_w = (_dt_mul_w >>> 8);

wire signed [15:0] dv = _dt_trunc_v;
wire signed [15:0] dw = _dt_trunc_w;

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];
wire signed [16:0] w_raw = w_reg + dw;
wire signed [15:0] w_next = (w_raw > 17'sd32767) ? 16'sd32767 : (w_raw < (-17'sd32768)) ? (-16'sd32768) : w_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd48896;
        v_out <= 16'sd48896;
        w_reg <= 16'sd0;
        w_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_next > (-16'sd12800))) begin
            spike_out <= 1'b1;
            v_reg <= P_V_RESET;
            v_out <= P_V_RESET;
            w_reg <= (w_next + P_B_ADAPT);
            w_out <= (w_next + P_B_ADAPT);
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            w_reg <= w_next;
            w_out <= w_next;
        end
    end
end

endmodule
