// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dx/dt = ((a1 + b1 * x) if x < x1 else ((a2 + b2 * x) if x < x2 else ((a3 + b3 * x) if x < x3 else (a4 + b4 * x)))) + alpha * (x if exponent < 1.5 else x * x) + I)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_cazelles_map #(
    parameter signed [15:0] P_ALPHA = 16'sd0,
    parameter signed [15:0] P_EXPONENT = 16'sd512,
    parameter signed [15:0] P_X0 = 16'sd0,
    parameter signed [15:0] P_X1 = 16'sd102,
    parameter signed [15:0] P_X2 = 16'sd154,
    parameter signed [15:0] P_X3 = 16'sd179,
    parameter signed [15:0] P_X4 = 16'sd256,
    parameter signed [15:0] P_A1 = 16'sd0,
    parameter signed [15:0] P_A2 = 16'sd384,
    parameter signed [15:0] P_A3 = 16'sd65306,
    parameter signed [15:0] P_A4 = 16'sd358,
    parameter signed [15:0] P_B1 = 16'sd269,
    parameter signed [15:0] P_B2 = 16'sd65216,
    parameter signed [15:0] P_B3 = 16'sd384,
    parameter signed [15:0] P_B4 = 16'sd65280
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] x_out
);

reg signed [15:0] x_reg;
reg _thr_prev;

wire signed [31:0] _mul0 = P_B1 * x_reg;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _mul1 = P_B2 * x_reg;
wire signed [15:0] _t1 = (_mul1 >>> 8);
wire signed [31:0] _mul2 = P_B3 * x_reg;
wire signed [15:0] _t2 = (_mul2 >>> 8);
wire signed [31:0] _mul3 = P_B4 * x_reg;
wire signed [15:0] _t3 = (_mul3 >>> 8);
wire signed [31:0] _mul4 = x_reg * x_reg;
wire signed [15:0] _t4 = (_mul4 >>> 8);
wire signed [31:0] _mul5 = P_ALPHA * (((P_EXPONENT < 16'sd384)) ? (x_reg) : (_t4));
wire signed [15:0] _t5 = (_mul5 >>> 8);

wire signed [15:0] dx = (((((x_reg < P_X1)) ? ((P_A1 + _t0)) : ((((x_reg < P_X2)) ? ((P_A2 + _t1)) : ((((x_reg < P_X3)) ? ((P_A3 + _t2)) : ((P_A4 + _t3))))))) + _t5) + I_t);

wire signed [16:0] x_raw = dx;
wire signed [15:0] x_next = (x_raw > 17'sd32767) ? 16'sd32767 : (x_raw < (-17'sd32768)) ? (-16'sd32768) : x_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        x_reg <= 16'sd26;
        x_out <= 16'sd26;
        spike_out <= 1'b0;
        _thr_prev <= 1'b1;
    end else begin
        if (((x_next < P_X1)) && !_thr_prev) begin
            spike_out <= 1'b1;
            x_reg <= x_next;
            x_out <= x_next;
        end else begin
            spike_out <= 1'b0;
            x_reg <= x_next;
            x_out <= x_next;
        end
        _thr_prev <= ((x_next < P_X1));
    end
end

endmodule
