// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dx/dt = min(2.0, max(-2.0, a * x * (1.0 - x) - y + I)), dy/dt = y + epsilon * (x - sigma))
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_cazelles_map #(
    parameter signed [15:0] P_A = 16'sd973,
    parameter signed [15:0] P_EPSILON = 16'sd3,
    parameter signed [15:0] P_SIGMA = 16'sd128,
    parameter signed [15:0] P_X_THRESHOLD = 16'sd230
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] x_out,
    output reg signed [15:0] y_out
);

reg signed [15:0] x_reg;
reg signed [15:0] y_reg;

wire signed [31:0] _mul0 = P_A * x_reg;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _mul1 = _t0 * (16'sd256 - x_reg);
wire signed [15:0] _t1 = (_mul1 >>> 8);
wire signed [31:0] _mul2 = P_EPSILON * (x_reg - P_SIGMA);
wire signed [15:0] _t2 = (_mul2 >>> 8);

wire signed [15:0] dx = ((16'sd512 < (((-16'sd512) > ((_t1 - y_reg) + I_t)) ? (-16'sd512) : ((_t1 - y_reg) + I_t))) ? 16'sd512 : (((-16'sd512) > ((_t1 - y_reg) + I_t)) ? (-16'sd512) : ((_t1 - y_reg) + I_t)));
wire signed [15:0] dy = (y_reg + _t2);

wire signed [16:0] x_raw = dx;
wire signed [15:0] x_next = (x_raw > 17'sd32767) ? 16'sd32767 : (x_raw < (-17'sd32768)) ? (-16'sd32768) : x_raw[15:0];
wire signed [16:0] y_raw = dy;
wire signed [15:0] y_next = (y_raw > 17'sd32767) ? 16'sd32767 : (y_raw < (-17'sd32768)) ? (-16'sd32768) : y_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        x_reg <= 16'sd26;
        x_out <= 16'sd26;
        y_reg <= 16'sd0;
        y_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((x_next >= P_X_THRESHOLD)) begin
            spike_out <= 1'b1;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
        end else begin
            spike_out <= 1'b0;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
        end
    end
end

endmodule
