// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dx/dt = x + ((-m0 * x) if x <= (a * m1 / (m0 + m1)) else (m1 * (x - a) if x < ((m0 + a * m1) / (m0 + m1)) else -m0 * (x - 1.0))) - y - beta * (1.0 if x >= d else 0.0) + I, dy/dt = y + eps * (x - j))
// Fixed-point: Q32.32 (64-bit signed)
`timescale 1ns / 1ps

module sc_courbage_nekorkin_map #(
    parameter signed [63:0] P_M0 = 64'sd1717986918,
    parameter signed [63:0] P_M1 = 64'sd2791728742,
    parameter signed [63:0] P_A = 64'sd858993459,
    parameter signed [63:0] P_D = 64'sd1288490189,
    parameter signed [63:0] P_J = 64'sd558345748,
    parameter signed [63:0] P_BETA = 64'sd1073741824,
    parameter signed [63:0] P_EPS = 64'sd8589935,
    parameter signed [63:0] P_X_THRESHOLD = 64'sd1288490189
)(
    input wire clk,
    input wire rst_n,
    input wire signed [63:0] I_t,
    output reg spike_out,
    output reg signed [63:0] x_out,
    output reg signed [63:0] y_out
);

reg signed [63:0] x_reg;
reg signed [63:0] y_reg;
reg _thr_prev;

wire signed [127:0] _mul0 = P_A * P_M1;
wire signed [63:0] _t0 = (_mul0 >>> 32);
wire signed [63:0] _dop1 = _t0;
wire signed [63:0] _dden1 = (P_M0 + P_M1);
wire signed [127:0] _dnum1 = $signed({{64{_dop1[63]}}, _dop1}) <<< 32;
wire signed [127:0] _div1 = _dnum1 / $signed({{64{_dden1[63]}}, _dden1});
wire signed [63:0] _dres1 = _div1[63:0];
wire signed [127:0] _mul2 = (-P_M0) * x_reg;
wire signed [63:0] _t1 = (_mul2 >>> 32);
wire signed [127:0] _mul3 = P_A * P_M1;
wire signed [63:0] _t2 = (_mul3 >>> 32);
wire signed [63:0] _dop4 = (P_M0 + _t2);
wire signed [63:0] _dden4 = (P_M0 + P_M1);
wire signed [127:0] _dnum4 = $signed({{64{_dop4[63]}}, _dop4}) <<< 32;
wire signed [127:0] _div4 = _dnum4 / $signed({{64{_dden4[63]}}, _dden4});
wire signed [63:0] _dres4 = _div4[63:0];
wire signed [127:0] _mul5 = P_M1 * (x_reg - P_A);
wire signed [63:0] _t3 = (_mul5 >>> 32);
wire signed [127:0] _mul6 = (-P_M0) * (x_reg - 64'sd4294967296);
wire signed [63:0] _t4 = (_mul6 >>> 32);
wire signed [127:0] _mul7 = P_BETA * (((x_reg >= P_D)) ? (64'sd4294967296) : (64'sd0));
wire signed [63:0] _t5 = (_mul7 >>> 32);
wire signed [127:0] _mul8 = P_EPS * (x_reg - P_J);
wire signed [63:0] _t6 = (_mul8 >>> 32);

wire signed [63:0] dx = ((((x_reg + (((x_reg <= _dres1)) ? (_t1) : ((((x_reg < _dres4)) ? (_t3) : (_t4))))) - y_reg) - _t5) + I_t);
wire signed [63:0] dy = (y_reg + _t6);

wire signed [64:0] x_raw = dx;
wire signed [63:0] x_next = (x_raw > 65'sd9223372036854775807) ? 64'sd9223372036854775807 : (x_raw < (-65'sd9223372036854775808)) ? (-64'sd9223372036854775808) : x_raw[63:0];
wire signed [64:0] y_raw = dy;
wire signed [63:0] y_next = (y_raw > 65'sd9223372036854775807) ? 64'sd9223372036854775807 : (y_raw < (-65'sd9223372036854775808)) ? (-64'sd9223372036854775808) : y_raw[63:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        x_reg <= 64'sd0;
        x_out <= 64'sd0;
        y_reg <= 64'sd0;
        y_out <= 64'sd0;
        spike_out <= 1'b0;
        _thr_prev <= 1'b0;
    end else begin
        if (((x_next >= P_X_THRESHOLD)) && !_thr_prev) begin
            spike_out <= 1'b1;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
        end else begin
            spike_out <= 1'b0;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
        end
        _thr_prev <= ((x_next >= P_X_THRESHOLD));
    end
end

endmodule
