// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(di_mem/dt = (-i_mem + gain * I + i_leak) / tau)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_dpineuron #(
    parameter signed [15:0] P_I_THRESHOLD = 16'sd256,
    parameter signed [15:0] P_I_RESET = 16'sd0,
    parameter signed [15:0] P_I_LEAK = 16'sd3,
    parameter signed [15:0] P_TAU = 16'sd5120,
    parameter signed [15:0] P_GAIN = 16'sd256
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] i_mem_out
);

reg signed [15:0] i_mem_reg;

wire signed [31:0] _mul0 = P_GAIN * I_t;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [15:0] _dop1 = (((-i_mem_reg) + _t0) + P_I_LEAK);
wire signed [15:0] _dden1 = P_TAU;
wire signed [31:0] _dnum1 = $signed({{16{_dop1[15]}}, _dop1}) <<< 8;
wire signed [31:0] _div1 = _dnum1 / $signed({{16{_dden1[15]}}, _dden1});
wire signed [15:0] _dres1 = _div1[15:0];
wire signed [31:0] _dt_mul_i_mem = (_dres1) * 16'sd256;
wire signed [15:0] _dt_trunc_i_mem = (_dt_mul_i_mem >>> 8);

wire signed [15:0] di_mem = _dt_trunc_i_mem;

wire signed [16:0] i_mem_raw = i_mem_reg + di_mem;
wire signed [15:0] i_mem_next = (i_mem_raw > 17'sd32767) ? 16'sd32767 : (i_mem_raw < (-17'sd32768)) ? (-16'sd32768) : i_mem_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        i_mem_reg <= 16'sd0;
        i_mem_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((i_mem_next >= P_I_THRESHOLD)) begin
            spike_out <= 1'b1;
            i_mem_reg <= P_I_RESET;
            i_mem_out <= P_I_RESET;
        end else begin
            spike_out <= 1'b0;
            i_mem_reg <= i_mem_next;
            i_mem_out <= i_mem_next;
        end
    end
end

endmodule
