// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dr/dt = delta / (pi * tau**2) + 2.0 * r * v / tau, dv/dt = (v**2 + eta_bar + I + j * tau * r - (pi * tau * r)**2) / tau)
// Fixed-point: Q32.32 (64-bit signed)
`timescale 1ns / 1ps

module sc_ermentroutkopellpopulation #(
    parameter signed [63:0] P_TAU = 64'sd4294967296,
    parameter signed [63:0] P_DELTA = 64'sd4294967296,
    parameter signed [63:0] P_ETA_BAR = 64'sd18446744052234715136,
    parameter signed [63:0] P_J = 64'sd64424509440,
    parameter signed [63:0] P_PI = 64'sd13493037705
)(
    input wire clk,
    input wire rst_n,
    input wire signed [63:0] I_t,
    output reg spike_out,
    output reg signed [63:0] r_out,
    output reg signed [63:0] v_out
);

reg signed [63:0] r_reg;
reg signed [63:0] v_reg;

wire signed [127:0] _mul0 = P_TAU * P_TAU;
wire signed [63:0] _t0 = (_mul0 >>> 32);
wire signed [127:0] _mul1 = P_PI * _t0;
wire signed [63:0] _t1 = (_mul1 >>> 32);
wire signed [63:0] _dop2 = P_DELTA;
wire signed [63:0] _dden2 = _t1;
wire signed [127:0] _dnum2 = $signed({{64{_dop2[63]}}, _dop2}) <<< 32;
wire signed [127:0] _div2 = _dnum2 / $signed({{64{_dden2[63]}}, _dden2});
wire signed [63:0] _dres2 = _div2[63:0];
wire signed [127:0] _mul3 = 64'sd8589934592 * r_reg;
wire signed [63:0] _t2 = (_mul3 >>> 32);
wire signed [127:0] _mul4 = _t2 * v_reg;
wire signed [63:0] _t3 = (_mul4 >>> 32);
wire signed [63:0] _dop5 = _t3;
wire signed [63:0] _dden5 = P_TAU;
wire signed [127:0] _dnum5 = $signed({{64{_dop5[63]}}, _dop5}) <<< 32;
wire signed [127:0] _div5 = _dnum5 / $signed({{64{_dden5[63]}}, _dden5});
wire signed [63:0] _dres5 = _div5[63:0];
wire signed [127:0] _dt_mul_r = ((_dres2 + _dres5)) * 64'sd42949673;
wire signed [63:0] _dt_trunc_r = (_dt_mul_r >>> 32);
wire signed [127:0] _mul6 = v_reg * v_reg;
wire signed [63:0] _t4 = (_mul6 >>> 32);
wire signed [127:0] _mul7 = P_J * P_TAU;
wire signed [63:0] _t5 = (_mul7 >>> 32);
wire signed [127:0] _mul8 = _t5 * r_reg;
wire signed [63:0] _t6 = (_mul8 >>> 32);
wire signed [127:0] _mul9 = P_PI * P_TAU;
wire signed [63:0] _t7 = (_mul9 >>> 32);
wire signed [127:0] _mul10 = _t7 * r_reg;
wire signed [63:0] _t8 = (_mul10 >>> 32);
wire signed [127:0] _mul11 = _t8 * _t8;
wire signed [63:0] _t9 = (_mul11 >>> 32);
wire signed [63:0] _dop12 = ((((_t4 + P_ETA_BAR) + I_t) + _t6) - _t9);
wire signed [63:0] _dden12 = P_TAU;
wire signed [127:0] _dnum12 = $signed({{64{_dop12[63]}}, _dop12}) <<< 32;
wire signed [127:0] _div12 = _dnum12 / $signed({{64{_dden12[63]}}, _dden12});
wire signed [63:0] _dres12 = _div12[63:0];
wire signed [127:0] _dt_mul_v = (_dres12) * 64'sd42949673;
wire signed [63:0] _dt_trunc_v = (_dt_mul_v >>> 32);

wire signed [63:0] dr = _dt_trunc_r;
wire signed [63:0] dv = _dt_trunc_v;

wire signed [64:0] r_raw = r_reg + dr;
wire signed [63:0] r_next = (r_raw > 65'sd9223372036854775807) ? 64'sd9223372036854775807 : (r_raw < (-65'sd9223372036854775808)) ? (-64'sd9223372036854775808) : r_raw[63:0];
wire signed [64:0] v_raw = v_reg + dv;
wire signed [63:0] v_next = (v_raw > 65'sd9223372036854775807) ? 64'sd9223372036854775807 : (v_raw < (-65'sd9223372036854775808)) ? (-64'sd9223372036854775808) : v_raw[63:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        r_reg <= 64'sd429496730;
        r_out <= 64'sd429496730;
        v_reg <= 64'sd18446744065119617024;
        v_out <= 64'sd18446744065119617024;
        spike_out <= 1'b0;
    end else begin
        spike_out <= 1'b0;
        r_reg <= r_next;
        r_out <= r_next;
        v_reg <= v_next;
        v_out <= v_next;
    end
end

endmodule
