// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = v - v * v * v / 3.0 - w + I, dw/dt = epsilon * (v + a - b * w))
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_fitzhugh_nagumo #(
    parameter signed [15:0] P_A = 16'sd179,
    parameter signed [15:0] P_B = 16'sd205,
    parameter signed [15:0] P_EPSILON = 16'sd20,
    parameter signed [15:0] P_V_THRESHOLD = 16'sd256
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out,
    output reg signed [15:0] w_out
);

reg signed [15:0] v_reg;
reg signed [15:0] w_reg;
reg _thr_prev;

wire signed [31:0] _mul0 = v_reg * v_reg;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _mul1 = _t0 * v_reg;
wire signed [15:0] _t1 = (_mul1 >>> 8);
wire signed [31:0] _mul2 = _t1 * 16'sd85;
wire signed [15:0] _t2 = (_mul2 >>> 8);
wire signed [15:0] _k1_v = (((v_reg - _t2) - w_reg) + I_t);
wire signed [31:0] _mul3 = P_B * w_reg;
wire signed [15:0] _t3 = (_mul3 >>> 8);
wire signed [31:0] _mul4 = P_EPSILON * ((v_reg + P_A) - _t3);
wire signed [15:0] _t4 = (_mul4 >>> 8);
wire signed [15:0] _k1_w = _t4;
wire signed [31:0] _rk1mul_v = _k1_v * 16'sd13;
wire signed [15:0] _rk1tr_v = (_rk1mul_v >>> 8);
wire signed [15:0] _s1_v = v_reg + _rk1tr_v;
wire signed [31:0] _rk1mul_w = _k1_w * 16'sd13;
wire signed [15:0] _rk1tr_w = (_rk1mul_w >>> 8);
wire signed [15:0] _s1_w = w_reg + _rk1tr_w;
wire signed [31:0] _mul5 = _s1_v * _s1_v;
wire signed [15:0] _t5 = (_mul5 >>> 8);
wire signed [31:0] _mul6 = _t5 * _s1_v;
wire signed [15:0] _t6 = (_mul6 >>> 8);
wire signed [31:0] _mul7 = _t6 * 16'sd85;
wire signed [15:0] _t7 = (_mul7 >>> 8);
wire signed [15:0] _k2_v = (((_s1_v - _t7) - _s1_w) + I_t);
wire signed [31:0] _mul8 = P_B * _s1_w;
wire signed [15:0] _t8 = (_mul8 >>> 8);
wire signed [31:0] _mul9 = P_EPSILON * ((_s1_v + P_A) - _t8);
wire signed [15:0] _t9 = (_mul9 >>> 8);
wire signed [15:0] _k2_w = _t9;
wire signed [31:0] _rk2mul_v = _k2_v * 16'sd13;
wire signed [15:0] _rk2tr_v = (_rk2mul_v >>> 8);
wire signed [15:0] _s2_v = v_reg + _rk2tr_v;
wire signed [31:0] _rk2mul_w = _k2_w * 16'sd13;
wire signed [15:0] _rk2tr_w = (_rk2mul_w >>> 8);
wire signed [15:0] _s2_w = w_reg + _rk2tr_w;
wire signed [31:0] _mul10 = _s2_v * _s2_v;
wire signed [15:0] _t10 = (_mul10 >>> 8);
wire signed [31:0] _mul11 = _t10 * _s2_v;
wire signed [15:0] _t11 = (_mul11 >>> 8);
wire signed [31:0] _mul12 = _t11 * 16'sd85;
wire signed [15:0] _t12 = (_mul12 >>> 8);
wire signed [15:0] _k3_v = (((_s2_v - _t12) - _s2_w) + I_t);
wire signed [31:0] _mul13 = P_B * _s2_w;
wire signed [15:0] _t13 = (_mul13 >>> 8);
wire signed [31:0] _mul14 = P_EPSILON * ((_s2_v + P_A) - _t13);
wire signed [15:0] _t14 = (_mul14 >>> 8);
wire signed [15:0] _k3_w = _t14;
wire signed [31:0] _rk3mul_v = _k3_v * 16'sd26;
wire signed [15:0] _rk3tr_v = (_rk3mul_v >>> 8);
wire signed [15:0] _s3_v = v_reg + _rk3tr_v;
wire signed [31:0] _rk3mul_w = _k3_w * 16'sd26;
wire signed [15:0] _rk3tr_w = (_rk3mul_w >>> 8);
wire signed [15:0] _s3_w = w_reg + _rk3tr_w;
wire signed [31:0] _mul15 = _s3_v * _s3_v;
wire signed [15:0] _t15 = (_mul15 >>> 8);
wire signed [31:0] _mul16 = _t15 * _s3_v;
wire signed [15:0] _t16 = (_mul16 >>> 8);
wire signed [31:0] _mul17 = _t16 * 16'sd85;
wire signed [15:0] _t17 = (_mul17 >>> 8);
wire signed [15:0] _k4_v = (((_s3_v - _t17) - _s3_w) + I_t);
wire signed [31:0] _mul18 = P_B * _s3_w;
wire signed [15:0] _t18 = (_mul18 >>> 8);
wire signed [31:0] _mul19 = P_EPSILON * ((_s3_v + P_A) - _t18);
wire signed [15:0] _t19 = (_mul19 >>> 8);
wire signed [15:0] _k4_w = _t19;
wire signed [18:0] _rkw_v = _k1_v + _k2_v + _k2_v + _k3_v + _k3_v + _k4_v;
wire signed [34:0] _rk6mul_v = _rkw_v * 16'sd4;
wire signed [18:0] _rkw_w = _k1_w + _k2_w + _k2_w + _k3_w + _k3_w + _k4_w;
wire signed [34:0] _rk6mul_w = _rkw_w * 16'sd4;

wire signed [15:0] dv = (_rk6mul_v >>> 8);
wire signed [15:0] dw = (_rk6mul_w >>> 8);

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];
wire signed [16:0] w_raw = w_reg + dw;
wire signed [15:0] w_next = (w_raw > 17'sd32767) ? 16'sd32767 : (w_raw < (-17'sd32768)) ? (-16'sd32768) : w_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd65280;
        v_out <= 16'sd65280;
        w_reg <= 16'sd65408;
        w_out <= 16'sd65408;
        spike_out <= 1'b0;
        _thr_prev <= 1'b0;
    end else begin
        if (((v_next >= P_V_THRESHOLD)) && !_thr_prev) begin
            spike_out <= 1'b1;
            v_reg <= v_next;
            w_reg <= w_next;
            v_out <= v_reg;
            w_out <= w_reg;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            w_reg <= w_next;
            w_out <= w_next;
        end
        _thr_prev <= ((v_next >= P_V_THRESHOLD));
    end
end

endmodule
