// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Retained four-state GLIF fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = (-(v - v_rest) + resistance * I + i_asc1 + i_asc2) / tau_m, dtheta/dt = (theta_inf - theta + a_theta * (v - v_rest)) / tau_theta, di_asc1/dt = -i_asc1 / tau_asc1, di_asc2/dt = -i_asc2 / tau_asc2)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_four_state_glif #(
    parameter signed [15:0] P_V_REST = 16'sd47616,
    parameter signed [15:0] P_V_RESET = 16'sd47616,
    parameter signed [15:0] P_THETA_INF = 16'sd52736,
    parameter signed [15:0] P_TAU_M = 16'sd2560,
    parameter signed [15:0] P_TAU_THETA = 16'sd25600,
    parameter signed [15:0] P_TAU_ASC1 = 16'sd2560,
    parameter signed [15:0] P_TAU_ASC2 = 16'sd51200,
    parameter signed [15:0] P_A_THETA = 16'sd3,
    parameter signed [15:0] P_DELTA_THETA = 16'sd512,
    parameter signed [15:0] P_R_ASC1 = 16'sd256,
    parameter signed [15:0] P_R_ASC2 = 16'sd128,
    parameter signed [15:0] P_RESISTANCE = 16'sd256
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out,
    output reg signed [15:0] theta_out,
    output reg signed [15:0] i_asc1_out,
    output reg signed [15:0] i_asc2_out
);

reg signed [15:0] v_reg;
reg signed [15:0] theta_reg;
reg signed [15:0] i_asc1_reg;
reg signed [15:0] i_asc2_reg;

wire signed [31:0] _mul0 = P_RESISTANCE * I_t;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [15:0] _dop1 = ((((-(v_reg - P_V_REST)) + _t0) + i_asc1_reg) + i_asc2_reg);
wire signed [15:0] _dden1 = P_TAU_M;
wire signed [31:0] _dnum1 = $signed({{16{_dop1[15]}}, _dop1}) <<< 8;
wire signed [31:0] _div1 = _dnum1 / $signed({{16{_dden1[15]}}, _dden1});
wire signed [15:0] _dres1 = _div1[15:0];
wire signed [15:0] _k1_v = _dres1;
wire signed [31:0] _mul2 = P_A_THETA * (v_reg - P_V_REST);
wire signed [15:0] _t1 = (_mul2 >>> 8);
wire signed [15:0] _dop3 = ((P_THETA_INF - theta_reg) + _t1);
wire signed [15:0] _dden3 = P_TAU_THETA;
wire signed [31:0] _dnum3 = $signed({{16{_dop3[15]}}, _dop3}) <<< 8;
wire signed [31:0] _div3 = _dnum3 / $signed({{16{_dden3[15]}}, _dden3});
wire signed [15:0] _dres3 = _div3[15:0];
wire signed [15:0] _k1_theta = _dres3;
wire signed [15:0] _dop4 = (-i_asc1_reg);
wire signed [15:0] _dden4 = P_TAU_ASC1;
wire signed [31:0] _dnum4 = $signed({{16{_dop4[15]}}, _dop4}) <<< 8;
wire signed [31:0] _div4 = _dnum4 / $signed({{16{_dden4[15]}}, _dden4});
wire signed [15:0] _dres4 = _div4[15:0];
wire signed [15:0] _k1_i_asc1 = _dres4;
wire signed [15:0] _dop5 = (-i_asc2_reg);
wire signed [15:0] _dden5 = P_TAU_ASC2;
wire signed [31:0] _dnum5 = $signed({{16{_dop5[15]}}, _dop5}) <<< 8;
wire signed [31:0] _div5 = _dnum5 / $signed({{16{_dden5[15]}}, _dden5});
wire signed [15:0] _dres5 = _div5[15:0];
wire signed [15:0] _k1_i_asc2 = _dres5;
wire signed [31:0] _rk1mul_v = _k1_v * 16'sd128;
wire signed [15:0] _rk1tr_v = (_rk1mul_v >>> 8);
wire signed [15:0] _s1_v = v_reg + _rk1tr_v;
wire signed [31:0] _rk1mul_theta = _k1_theta * 16'sd128;
wire signed [15:0] _rk1tr_theta = (_rk1mul_theta >>> 8);
wire signed [15:0] _s1_theta = theta_reg + _rk1tr_theta;
wire signed [31:0] _rk1mul_i_asc1 = _k1_i_asc1 * 16'sd128;
wire signed [15:0] _rk1tr_i_asc1 = (_rk1mul_i_asc1 >>> 8);
wire signed [15:0] _s1_i_asc1 = i_asc1_reg + _rk1tr_i_asc1;
wire signed [31:0] _rk1mul_i_asc2 = _k1_i_asc2 * 16'sd128;
wire signed [15:0] _rk1tr_i_asc2 = (_rk1mul_i_asc2 >>> 8);
wire signed [15:0] _s1_i_asc2 = i_asc2_reg + _rk1tr_i_asc2;
wire signed [31:0] _mul6 = P_RESISTANCE * I_t;
wire signed [15:0] _t2 = (_mul6 >>> 8);
wire signed [15:0] _dop7 = ((((-(_s1_v - P_V_REST)) + _t2) + _s1_i_asc1) + _s1_i_asc2);
wire signed [15:0] _dden7 = P_TAU_M;
wire signed [31:0] _dnum7 = $signed({{16{_dop7[15]}}, _dop7}) <<< 8;
wire signed [31:0] _div7 = _dnum7 / $signed({{16{_dden7[15]}}, _dden7});
wire signed [15:0] _dres7 = _div7[15:0];
wire signed [15:0] _k2_v = _dres7;
wire signed [31:0] _mul8 = P_A_THETA * (_s1_v - P_V_REST);
wire signed [15:0] _t3 = (_mul8 >>> 8);
wire signed [15:0] _dop9 = ((P_THETA_INF - _s1_theta) + _t3);
wire signed [15:0] _dden9 = P_TAU_THETA;
wire signed [31:0] _dnum9 = $signed({{16{_dop9[15]}}, _dop9}) <<< 8;
wire signed [31:0] _div9 = _dnum9 / $signed({{16{_dden9[15]}}, _dden9});
wire signed [15:0] _dres9 = _div9[15:0];
wire signed [15:0] _k2_theta = _dres9;
wire signed [15:0] _dop10 = (-_s1_i_asc1);
wire signed [15:0] _dden10 = P_TAU_ASC1;
wire signed [31:0] _dnum10 = $signed({{16{_dop10[15]}}, _dop10}) <<< 8;
wire signed [31:0] _div10 = _dnum10 / $signed({{16{_dden10[15]}}, _dden10});
wire signed [15:0] _dres10 = _div10[15:0];
wire signed [15:0] _k2_i_asc1 = _dres10;
wire signed [15:0] _dop11 = (-_s1_i_asc2);
wire signed [15:0] _dden11 = P_TAU_ASC2;
wire signed [31:0] _dnum11 = $signed({{16{_dop11[15]}}, _dop11}) <<< 8;
wire signed [31:0] _div11 = _dnum11 / $signed({{16{_dden11[15]}}, _dden11});
wire signed [15:0] _dres11 = _div11[15:0];
wire signed [15:0] _k2_i_asc2 = _dres11;
wire signed [31:0] _rk2mul_v = _k2_v * 16'sd128;
wire signed [15:0] _rk2tr_v = (_rk2mul_v >>> 8);
wire signed [15:0] _s2_v = v_reg + _rk2tr_v;
wire signed [31:0] _rk2mul_theta = _k2_theta * 16'sd128;
wire signed [15:0] _rk2tr_theta = (_rk2mul_theta >>> 8);
wire signed [15:0] _s2_theta = theta_reg + _rk2tr_theta;
wire signed [31:0] _rk2mul_i_asc1 = _k2_i_asc1 * 16'sd128;
wire signed [15:0] _rk2tr_i_asc1 = (_rk2mul_i_asc1 >>> 8);
wire signed [15:0] _s2_i_asc1 = i_asc1_reg + _rk2tr_i_asc1;
wire signed [31:0] _rk2mul_i_asc2 = _k2_i_asc2 * 16'sd128;
wire signed [15:0] _rk2tr_i_asc2 = (_rk2mul_i_asc2 >>> 8);
wire signed [15:0] _s2_i_asc2 = i_asc2_reg + _rk2tr_i_asc2;
wire signed [31:0] _mul12 = P_RESISTANCE * I_t;
wire signed [15:0] _t4 = (_mul12 >>> 8);
wire signed [15:0] _dop13 = ((((-(_s2_v - P_V_REST)) + _t4) + _s2_i_asc1) + _s2_i_asc2);
wire signed [15:0] _dden13 = P_TAU_M;
wire signed [31:0] _dnum13 = $signed({{16{_dop13[15]}}, _dop13}) <<< 8;
wire signed [31:0] _div13 = _dnum13 / $signed({{16{_dden13[15]}}, _dden13});
wire signed [15:0] _dres13 = _div13[15:0];
wire signed [15:0] _k3_v = _dres13;
wire signed [31:0] _mul14 = P_A_THETA * (_s2_v - P_V_REST);
wire signed [15:0] _t5 = (_mul14 >>> 8);
wire signed [15:0] _dop15 = ((P_THETA_INF - _s2_theta) + _t5);
wire signed [15:0] _dden15 = P_TAU_THETA;
wire signed [31:0] _dnum15 = $signed({{16{_dop15[15]}}, _dop15}) <<< 8;
wire signed [31:0] _div15 = _dnum15 / $signed({{16{_dden15[15]}}, _dden15});
wire signed [15:0] _dres15 = _div15[15:0];
wire signed [15:0] _k3_theta = _dres15;
wire signed [15:0] _dop16 = (-_s2_i_asc1);
wire signed [15:0] _dden16 = P_TAU_ASC1;
wire signed [31:0] _dnum16 = $signed({{16{_dop16[15]}}, _dop16}) <<< 8;
wire signed [31:0] _div16 = _dnum16 / $signed({{16{_dden16[15]}}, _dden16});
wire signed [15:0] _dres16 = _div16[15:0];
wire signed [15:0] _k3_i_asc1 = _dres16;
wire signed [15:0] _dop17 = (-_s2_i_asc2);
wire signed [15:0] _dden17 = P_TAU_ASC2;
wire signed [31:0] _dnum17 = $signed({{16{_dop17[15]}}, _dop17}) <<< 8;
wire signed [31:0] _div17 = _dnum17 / $signed({{16{_dden17[15]}}, _dden17});
wire signed [15:0] _dres17 = _div17[15:0];
wire signed [15:0] _k3_i_asc2 = _dres17;
wire signed [31:0] _rk3mul_v = _k3_v * 16'sd256;
wire signed [15:0] _rk3tr_v = (_rk3mul_v >>> 8);
wire signed [15:0] _s3_v = v_reg + _rk3tr_v;
wire signed [31:0] _rk3mul_theta = _k3_theta * 16'sd256;
wire signed [15:0] _rk3tr_theta = (_rk3mul_theta >>> 8);
wire signed [15:0] _s3_theta = theta_reg + _rk3tr_theta;
wire signed [31:0] _rk3mul_i_asc1 = _k3_i_asc1 * 16'sd256;
wire signed [15:0] _rk3tr_i_asc1 = (_rk3mul_i_asc1 >>> 8);
wire signed [15:0] _s3_i_asc1 = i_asc1_reg + _rk3tr_i_asc1;
wire signed [31:0] _rk3mul_i_asc2 = _k3_i_asc2 * 16'sd256;
wire signed [15:0] _rk3tr_i_asc2 = (_rk3mul_i_asc2 >>> 8);
wire signed [15:0] _s3_i_asc2 = i_asc2_reg + _rk3tr_i_asc2;
wire signed [31:0] _mul18 = P_RESISTANCE * I_t;
wire signed [15:0] _t6 = (_mul18 >>> 8);
wire signed [15:0] _dop19 = ((((-(_s3_v - P_V_REST)) + _t6) + _s3_i_asc1) + _s3_i_asc2);
wire signed [15:0] _dden19 = P_TAU_M;
wire signed [31:0] _dnum19 = $signed({{16{_dop19[15]}}, _dop19}) <<< 8;
wire signed [31:0] _div19 = _dnum19 / $signed({{16{_dden19[15]}}, _dden19});
wire signed [15:0] _dres19 = _div19[15:0];
wire signed [15:0] _k4_v = _dres19;
wire signed [31:0] _mul20 = P_A_THETA * (_s3_v - P_V_REST);
wire signed [15:0] _t7 = (_mul20 >>> 8);
wire signed [15:0] _dop21 = ((P_THETA_INF - _s3_theta) + _t7);
wire signed [15:0] _dden21 = P_TAU_THETA;
wire signed [31:0] _dnum21 = $signed({{16{_dop21[15]}}, _dop21}) <<< 8;
wire signed [31:0] _div21 = _dnum21 / $signed({{16{_dden21[15]}}, _dden21});
wire signed [15:0] _dres21 = _div21[15:0];
wire signed [15:0] _k4_theta = _dres21;
wire signed [15:0] _dop22 = (-_s3_i_asc1);
wire signed [15:0] _dden22 = P_TAU_ASC1;
wire signed [31:0] _dnum22 = $signed({{16{_dop22[15]}}, _dop22}) <<< 8;
wire signed [31:0] _div22 = _dnum22 / $signed({{16{_dden22[15]}}, _dden22});
wire signed [15:0] _dres22 = _div22[15:0];
wire signed [15:0] _k4_i_asc1 = _dres22;
wire signed [15:0] _dop23 = (-_s3_i_asc2);
wire signed [15:0] _dden23 = P_TAU_ASC2;
wire signed [31:0] _dnum23 = $signed({{16{_dop23[15]}}, _dop23}) <<< 8;
wire signed [31:0] _div23 = _dnum23 / $signed({{16{_dden23[15]}}, _dden23});
wire signed [15:0] _dres23 = _div23[15:0];
wire signed [15:0] _k4_i_asc2 = _dres23;
wire signed [18:0] _rkw_v = _k1_v + _k2_v + _k2_v + _k3_v + _k3_v + _k4_v;
wire signed [34:0] _rk6mul_v = _rkw_v * 16'sd43;
wire signed [18:0] _rkw_theta = _k1_theta + _k2_theta + _k2_theta + _k3_theta + _k3_theta + _k4_theta;
wire signed [34:0] _rk6mul_theta = _rkw_theta * 16'sd43;
wire signed [18:0] _rkw_i_asc1 = _k1_i_asc1 + _k2_i_asc1 + _k2_i_asc1 + _k3_i_asc1 + _k3_i_asc1 + _k4_i_asc1;
wire signed [34:0] _rk6mul_i_asc1 = _rkw_i_asc1 * 16'sd43;
wire signed [18:0] _rkw_i_asc2 = _k1_i_asc2 + _k2_i_asc2 + _k2_i_asc2 + _k3_i_asc2 + _k3_i_asc2 + _k4_i_asc2;
wire signed [34:0] _rk6mul_i_asc2 = _rkw_i_asc2 * 16'sd43;

wire signed [15:0] dv = (_rk6mul_v >>> 8);
wire signed [15:0] dtheta = (_rk6mul_theta >>> 8);
wire signed [15:0] di_asc1 = (_rk6mul_i_asc1 >>> 8);
wire signed [15:0] di_asc2 = (_rk6mul_i_asc2 >>> 8);

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];
wire signed [16:0] theta_raw = theta_reg + dtheta;
wire signed [15:0] theta_next = (theta_raw > 17'sd32767) ? 16'sd32767 : (theta_raw < (-17'sd32768)) ? (-16'sd32768) : theta_raw[15:0];
wire signed [16:0] i_asc1_raw = i_asc1_reg + di_asc1;
wire signed [15:0] i_asc1_next = (i_asc1_raw > 17'sd32767) ? 16'sd32767 : (i_asc1_raw < (-17'sd32768)) ? (-16'sd32768) : i_asc1_raw[15:0];
wire signed [16:0] i_asc2_raw = i_asc2_reg + di_asc2;
wire signed [15:0] i_asc2_next = (i_asc2_raw > 17'sd32767) ? 16'sd32767 : (i_asc2_raw < (-17'sd32768)) ? (-16'sd32768) : i_asc2_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd47616;
        v_out <= 16'sd47616;
        theta_reg <= 16'sd52736;
        theta_out <= 16'sd52736;
        i_asc1_reg <= 16'sd0;
        i_asc1_out <= 16'sd0;
        i_asc2_reg <= 16'sd0;
        i_asc2_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_next >= theta_next)) begin
            spike_out <= 1'b1;
            v_reg <= P_V_RESET;
            v_out <= P_V_RESET;
            theta_reg <= (theta_next + P_DELTA_THETA);
            theta_out <= (theta_next + P_DELTA_THETA);
            i_asc1_reg <= (i_asc1_next + P_R_ASC1);
            i_asc1_out <= (i_asc1_next + P_R_ASC1);
            i_asc2_reg <= (i_asc2_next + P_R_ASC2);
            i_asc2_out <= (i_asc2_next + P_R_ASC2);
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            theta_reg <= theta_next;
            theta_out <= theta_next;
            i_asc1_reg <= i_asc1_next;
            i_asc1_out <= i_asc1_next;
            i_asc2_reg <= i_asc2_next;
            i_asc2_out <= i_asc2_next;
        end
    end
end

endmodule
