// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = v - v * v * v / 3.0 - w + y + I, dw/dt = delta * (a + v - b * w), dy/dt = mu * (c - v - d * y))
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_fitzhugh_rinzel #(
    parameter signed [15:0] P_A = 16'sd179,
    parameter signed [15:0] P_B = 16'sd205,
    parameter signed [15:0] P_C = 16'sd65338,
    parameter signed [15:0] P_D = 16'sd256,
    parameter signed [15:0] P_DELTA = 16'sd20,
    parameter signed [15:0] P_MU = 16'sd0,
    parameter signed [15:0] P_V_THRESHOLD = 16'sd256
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out,
    output reg signed [15:0] w_out,
    output reg signed [15:0] y_out
);

reg signed [15:0] v_reg;
reg signed [15:0] w_reg;
reg signed [15:0] y_reg;
reg _thr_prev;

wire signed [31:0] _mul0 = v_reg * v_reg;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _mul1 = _t0 * v_reg;
wire signed [15:0] _t1 = (_mul1 >>> 8);
wire signed [31:0] _mul2 = _t1 * 16'sd85;
wire signed [15:0] _t2 = (_mul2 >>> 8);
wire signed [15:0] _k1_v = ((((v_reg - _t2) - w_reg) + y_reg) + I_t);
wire signed [31:0] _mul3 = P_B * w_reg;
wire signed [15:0] _t3 = (_mul3 >>> 8);
wire signed [31:0] _mul4 = P_DELTA * ((P_A + v_reg) - _t3);
wire signed [15:0] _t4 = (_mul4 >>> 8);
wire signed [15:0] _k1_w = _t4;
wire signed [31:0] _mul5 = P_D * y_reg;
wire signed [15:0] _t5 = (_mul5 >>> 8);
wire signed [31:0] _mul6 = P_MU * ((P_C - v_reg) - _t5);
wire signed [15:0] _t6 = (_mul6 >>> 8);
wire signed [15:0] _k1_y = _t6;
wire signed [31:0] _rk1mul_v = _k1_v * 16'sd13;
wire signed [15:0] _rk1tr_v = (_rk1mul_v >>> 8);
wire signed [15:0] _s1_v = v_reg + _rk1tr_v;
wire signed [31:0] _rk1mul_w = _k1_w * 16'sd13;
wire signed [15:0] _rk1tr_w = (_rk1mul_w >>> 8);
wire signed [15:0] _s1_w = w_reg + _rk1tr_w;
wire signed [31:0] _rk1mul_y = _k1_y * 16'sd13;
wire signed [15:0] _rk1tr_y = (_rk1mul_y >>> 8);
wire signed [15:0] _s1_y = y_reg + _rk1tr_y;
wire signed [31:0] _mul7 = _s1_v * _s1_v;
wire signed [15:0] _t7 = (_mul7 >>> 8);
wire signed [31:0] _mul8 = _t7 * _s1_v;
wire signed [15:0] _t8 = (_mul8 >>> 8);
wire signed [31:0] _mul9 = _t8 * 16'sd85;
wire signed [15:0] _t9 = (_mul9 >>> 8);
wire signed [15:0] _k2_v = ((((_s1_v - _t9) - _s1_w) + _s1_y) + I_t);
wire signed [31:0] _mul10 = P_B * _s1_w;
wire signed [15:0] _t10 = (_mul10 >>> 8);
wire signed [31:0] _mul11 = P_DELTA * ((P_A + _s1_v) - _t10);
wire signed [15:0] _t11 = (_mul11 >>> 8);
wire signed [15:0] _k2_w = _t11;
wire signed [31:0] _mul12 = P_D * _s1_y;
wire signed [15:0] _t12 = (_mul12 >>> 8);
wire signed [31:0] _mul13 = P_MU * ((P_C - _s1_v) - _t12);
wire signed [15:0] _t13 = (_mul13 >>> 8);
wire signed [15:0] _k2_y = _t13;
wire signed [31:0] _rk2mul_v = _k2_v * 16'sd13;
wire signed [15:0] _rk2tr_v = (_rk2mul_v >>> 8);
wire signed [15:0] _s2_v = v_reg + _rk2tr_v;
wire signed [31:0] _rk2mul_w = _k2_w * 16'sd13;
wire signed [15:0] _rk2tr_w = (_rk2mul_w >>> 8);
wire signed [15:0] _s2_w = w_reg + _rk2tr_w;
wire signed [31:0] _rk2mul_y = _k2_y * 16'sd13;
wire signed [15:0] _rk2tr_y = (_rk2mul_y >>> 8);
wire signed [15:0] _s2_y = y_reg + _rk2tr_y;
wire signed [31:0] _mul14 = _s2_v * _s2_v;
wire signed [15:0] _t14 = (_mul14 >>> 8);
wire signed [31:0] _mul15 = _t14 * _s2_v;
wire signed [15:0] _t15 = (_mul15 >>> 8);
wire signed [31:0] _mul16 = _t15 * 16'sd85;
wire signed [15:0] _t16 = (_mul16 >>> 8);
wire signed [15:0] _k3_v = ((((_s2_v - _t16) - _s2_w) + _s2_y) + I_t);
wire signed [31:0] _mul17 = P_B * _s2_w;
wire signed [15:0] _t17 = (_mul17 >>> 8);
wire signed [31:0] _mul18 = P_DELTA * ((P_A + _s2_v) - _t17);
wire signed [15:0] _t18 = (_mul18 >>> 8);
wire signed [15:0] _k3_w = _t18;
wire signed [31:0] _mul19 = P_D * _s2_y;
wire signed [15:0] _t19 = (_mul19 >>> 8);
wire signed [31:0] _mul20 = P_MU * ((P_C - _s2_v) - _t19);
wire signed [15:0] _t20 = (_mul20 >>> 8);
wire signed [15:0] _k3_y = _t20;
wire signed [31:0] _rk3mul_v = _k3_v * 16'sd26;
wire signed [15:0] _rk3tr_v = (_rk3mul_v >>> 8);
wire signed [15:0] _s3_v = v_reg + _rk3tr_v;
wire signed [31:0] _rk3mul_w = _k3_w * 16'sd26;
wire signed [15:0] _rk3tr_w = (_rk3mul_w >>> 8);
wire signed [15:0] _s3_w = w_reg + _rk3tr_w;
wire signed [31:0] _rk3mul_y = _k3_y * 16'sd26;
wire signed [15:0] _rk3tr_y = (_rk3mul_y >>> 8);
wire signed [15:0] _s3_y = y_reg + _rk3tr_y;
wire signed [31:0] _mul21 = _s3_v * _s3_v;
wire signed [15:0] _t21 = (_mul21 >>> 8);
wire signed [31:0] _mul22 = _t21 * _s3_v;
wire signed [15:0] _t22 = (_mul22 >>> 8);
wire signed [31:0] _mul23 = _t22 * 16'sd85;
wire signed [15:0] _t23 = (_mul23 >>> 8);
wire signed [15:0] _k4_v = ((((_s3_v - _t23) - _s3_w) + _s3_y) + I_t);
wire signed [31:0] _mul24 = P_B * _s3_w;
wire signed [15:0] _t24 = (_mul24 >>> 8);
wire signed [31:0] _mul25 = P_DELTA * ((P_A + _s3_v) - _t24);
wire signed [15:0] _t25 = (_mul25 >>> 8);
wire signed [15:0] _k4_w = _t25;
wire signed [31:0] _mul26 = P_D * _s3_y;
wire signed [15:0] _t26 = (_mul26 >>> 8);
wire signed [31:0] _mul27 = P_MU * ((P_C - _s3_v) - _t26);
wire signed [15:0] _t27 = (_mul27 >>> 8);
wire signed [15:0] _k4_y = _t27;
wire signed [18:0] _rkw_v = _k1_v + _k2_v + _k2_v + _k3_v + _k3_v + _k4_v;
wire signed [34:0] _rk6mul_v = _rkw_v * 16'sd4;
wire signed [18:0] _rkw_w = _k1_w + _k2_w + _k2_w + _k3_w + _k3_w + _k4_w;
wire signed [34:0] _rk6mul_w = _rkw_w * 16'sd4;
wire signed [18:0] _rkw_y = _k1_y + _k2_y + _k2_y + _k3_y + _k3_y + _k4_y;
wire signed [34:0] _rk6mul_y = _rkw_y * 16'sd4;

wire signed [15:0] dv = (_rk6mul_v >>> 8);
wire signed [15:0] dw = (_rk6mul_w >>> 8);
wire signed [15:0] dy = (_rk6mul_y >>> 8);

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];
wire signed [16:0] w_raw = w_reg + dw;
wire signed [15:0] w_next = (w_raw > 17'sd32767) ? 16'sd32767 : (w_raw < (-17'sd32768)) ? (-16'sd32768) : w_raw[15:0];
wire signed [16:0] y_raw = y_reg + dy;
wire signed [15:0] y_next = (y_raw > 17'sd32767) ? 16'sd32767 : (y_raw < (-17'sd32768)) ? (-16'sd32768) : y_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd65280;
        v_out <= 16'sd65280;
        w_reg <= 16'sd65408;
        w_out <= 16'sd65408;
        y_reg <= 16'sd0;
        y_out <= 16'sd0;
        spike_out <= 1'b0;
        _thr_prev <= 1'b0;
    end else begin
        if (((v_next >= P_V_THRESHOLD)) && !_thr_prev) begin
            spike_out <= 1'b1;
            v_reg <= v_next;
            v_out <= v_next;
            w_reg <= w_next;
            w_out <= w_next;
            y_reg <= y_next;
            y_out <= y_next;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            w_reg <= w_next;
            w_out <= w_next;
            y_reg <= y_next;
            y_out <= y_next;
        end
        _thr_prev <= ((v_next >= P_V_THRESHOLD));
    end
end

endmodule
