// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = (-(v - v_rest) + resistance * I + i_asc1 + i_asc2) / tau_m, dtheta/dt = (theta_inf - theta + a_theta * (v - v_rest)) / tau_theta, di_asc1/dt = -i_asc1 / tau_asc1, di_asc2/dt = -i_asc2 / tau_asc2)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_glif #(
    parameter signed [15:0] P_V_REST = 16'sd47616,
    parameter signed [15:0] P_V_RESET = 16'sd47616,
    parameter signed [15:0] P_THETA_INF = 16'sd52736,
    parameter signed [15:0] P_TAU_M = 16'sd2560,
    parameter signed [15:0] P_TAU_THETA = 16'sd25600,
    parameter signed [15:0] P_TAU_ASC1 = 16'sd2560,
    parameter signed [15:0] P_TAU_ASC2 = 16'sd51200,
    parameter signed [15:0] P_A_THETA = 16'sd3,
    parameter signed [15:0] P_DELTA_THETA = 16'sd512,
    parameter signed [15:0] P_R_ASC1 = 16'sd256,
    parameter signed [15:0] P_R_ASC2 = 16'sd128,
    parameter signed [15:0] P_RESISTANCE = 16'sd256
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out,
    output reg signed [15:0] theta_out,
    output reg signed [15:0] i_asc1_out,
    output reg signed [15:0] i_asc2_out
);

reg signed [15:0] v_reg;
reg signed [15:0] theta_reg;
reg signed [15:0] i_asc1_reg;
reg signed [15:0] i_asc2_reg;

wire signed [31:0] _mul0 = P_RESISTANCE * I_t;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [15:0] _dop1 = ((((-(v_reg - P_V_REST)) + _t0) + i_asc1_reg) + i_asc2_reg);
wire signed [15:0] _dden1 = P_TAU_M;
wire signed [31:0] _dnum1 = $signed({{16{_dop1[15]}}, _dop1}) <<< 8;
wire signed [31:0] _div1 = _dnum1 / $signed({{16{_dden1[15]}}, _dden1});
wire signed [15:0] _dres1 = _div1[15:0];
wire signed [31:0] _dt_mul_v = (_dres1) * 16'sd256;
wire signed [15:0] _dt_trunc_v = (_dt_mul_v >>> 8);
wire signed [31:0] _mul2 = P_A_THETA * (v_reg - P_V_REST);
wire signed [15:0] _t1 = (_mul2 >>> 8);
wire signed [15:0] _dop3 = ((P_THETA_INF - theta_reg) + _t1);
wire signed [15:0] _dden3 = P_TAU_THETA;
wire signed [31:0] _dnum3 = $signed({{16{_dop3[15]}}, _dop3}) <<< 8;
wire signed [31:0] _div3 = _dnum3 / $signed({{16{_dden3[15]}}, _dden3});
wire signed [15:0] _dres3 = _div3[15:0];
wire signed [31:0] _dt_mul_theta = (_dres3) * 16'sd256;
wire signed [15:0] _dt_trunc_theta = (_dt_mul_theta >>> 8);
wire signed [15:0] _dop4 = (-i_asc1_reg);
wire signed [15:0] _dden4 = P_TAU_ASC1;
wire signed [31:0] _dnum4 = $signed({{16{_dop4[15]}}, _dop4}) <<< 8;
wire signed [31:0] _div4 = _dnum4 / $signed({{16{_dden4[15]}}, _dden4});
wire signed [15:0] _dres4 = _div4[15:0];
wire signed [31:0] _dt_mul_i_asc1 = (_dres4) * 16'sd256;
wire signed [15:0] _dt_trunc_i_asc1 = (_dt_mul_i_asc1 >>> 8);
wire signed [15:0] _dop5 = (-i_asc2_reg);
wire signed [15:0] _dden5 = P_TAU_ASC2;
wire signed [31:0] _dnum5 = $signed({{16{_dop5[15]}}, _dop5}) <<< 8;
wire signed [31:0] _div5 = _dnum5 / $signed({{16{_dden5[15]}}, _dden5});
wire signed [15:0] _dres5 = _div5[15:0];
wire signed [31:0] _dt_mul_i_asc2 = (_dres5) * 16'sd256;
wire signed [15:0] _dt_trunc_i_asc2 = (_dt_mul_i_asc2 >>> 8);

wire signed [15:0] dv = _dt_trunc_v;
wire signed [15:0] dtheta = _dt_trunc_theta;
wire signed [15:0] di_asc1 = _dt_trunc_i_asc1;
wire signed [15:0] di_asc2 = _dt_trunc_i_asc2;

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];
wire signed [16:0] theta_raw = theta_reg + dtheta;
wire signed [15:0] theta_next = (theta_raw > 17'sd32767) ? 16'sd32767 : (theta_raw < (-17'sd32768)) ? (-16'sd32768) : theta_raw[15:0];
wire signed [16:0] i_asc1_raw = i_asc1_reg + di_asc1;
wire signed [15:0] i_asc1_next = (i_asc1_raw > 17'sd32767) ? 16'sd32767 : (i_asc1_raw < (-17'sd32768)) ? (-16'sd32768) : i_asc1_raw[15:0];
wire signed [16:0] i_asc2_raw = i_asc2_reg + di_asc2;
wire signed [15:0] i_asc2_next = (i_asc2_raw > 17'sd32767) ? 16'sd32767 : (i_asc2_raw < (-17'sd32768)) ? (-16'sd32768) : i_asc2_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd47616;
        v_out <= 16'sd47616;
        theta_reg <= 16'sd52736;
        theta_out <= 16'sd52736;
        i_asc1_reg <= 16'sd0;
        i_asc1_out <= 16'sd0;
        i_asc2_reg <= 16'sd0;
        i_asc2_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_next > theta_next)) begin
            spike_out <= 1'b1;
            v_reg <= P_V_RESET;
            theta_reg <= (theta_reg + P_DELTA_THETA);
            i_asc1_reg <= (i_asc1_reg + P_R_ASC1);
            i_asc2_reg <= (i_asc2_reg + P_R_ASC2);
            v_out <= v_reg;
            theta_out <= theta_reg;
            i_asc1_out <= i_asc1_reg;
            i_asc2_out <= i_asc2_reg;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            theta_reg <= theta_next;
            theta_out <= theta_next;
            i_asc1_reg <= i_asc1_next;
            i_asc1_out <= i_asc1_next;
            i_asc2_reg <= i_asc2_next;
            i_asc2_out <= i_asc2_next;
        end
    end
end

endmodule
