// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dx/dt = y - x**3 + b * x**2 - z + I, dy/dt = 1 - 5 * x**2 - y, dz/dt = r * (s * (x - x_rest) - z))
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_hindmarsh_rose #(
    parameter signed [15:0] P_B = 16'sd768,
    parameter signed [15:0] P_R = 16'sd0,
    parameter signed [15:0] P_S = 16'sd1024,
    parameter signed [15:0] P_X_REST = 16'sd65126,
    parameter signed [15:0] P_X_THRESHOLD = 16'sd256
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] x_out,
    output reg signed [15:0] y_out,
    output reg signed [15:0] z_out
);

reg signed [15:0] x_reg;
reg signed [15:0] y_reg;
reg signed [15:0] z_reg;
reg _thr_prev;

wire signed [31:0] _mul0 = x_reg * x_reg;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _mul1 = _t0 * x_reg;
wire signed [15:0] _t1 = (_mul1 >>> 8);
wire signed [31:0] _mul2 = x_reg * x_reg;
wire signed [15:0] _t2 = (_mul2 >>> 8);
wire signed [31:0] _mul3 = P_B * _t2;
wire signed [15:0] _t3 = (_mul3 >>> 8);
wire signed [15:0] _k1_x = ((((y_reg - _t1) + _t3) - z_reg) + I_t);
wire signed [31:0] _mul4 = x_reg * x_reg;
wire signed [15:0] _t4 = (_mul4 >>> 8);
wire signed [31:0] _mul5 = 16'sd1280 * _t4;
wire signed [15:0] _t5 = (_mul5 >>> 8);
wire signed [15:0] _k1_y = ((16'sd256 - _t5) - y_reg);
wire signed [31:0] _mul6 = P_S * (x_reg - P_X_REST);
wire signed [15:0] _t6 = (_mul6 >>> 8);
wire signed [31:0] _mul7 = P_R * (_t6 - z_reg);
wire signed [15:0] _t7 = (_mul7 >>> 8);
wire signed [15:0] _k1_z = _t7;
wire signed [31:0] _rk1mul_x = _k1_x * 16'sd13;
wire signed [15:0] _rk1tr_x = (_rk1mul_x >>> 8);
wire signed [15:0] _s1_x = x_reg + _rk1tr_x;
wire signed [31:0] _rk1mul_y = _k1_y * 16'sd13;
wire signed [15:0] _rk1tr_y = (_rk1mul_y >>> 8);
wire signed [15:0] _s1_y = y_reg + _rk1tr_y;
wire signed [31:0] _rk1mul_z = _k1_z * 16'sd13;
wire signed [15:0] _rk1tr_z = (_rk1mul_z >>> 8);
wire signed [15:0] _s1_z = z_reg + _rk1tr_z;
wire signed [31:0] _mul8 = _s1_x * _s1_x;
wire signed [15:0] _t8 = (_mul8 >>> 8);
wire signed [31:0] _mul9 = _t8 * _s1_x;
wire signed [15:0] _t9 = (_mul9 >>> 8);
wire signed [31:0] _mul10 = _s1_x * _s1_x;
wire signed [15:0] _t10 = (_mul10 >>> 8);
wire signed [31:0] _mul11 = P_B * _t10;
wire signed [15:0] _t11 = (_mul11 >>> 8);
wire signed [15:0] _k2_x = ((((_s1_y - _t9) + _t11) - _s1_z) + I_t);
wire signed [31:0] _mul12 = _s1_x * _s1_x;
wire signed [15:0] _t12 = (_mul12 >>> 8);
wire signed [31:0] _mul13 = 16'sd1280 * _t12;
wire signed [15:0] _t13 = (_mul13 >>> 8);
wire signed [15:0] _k2_y = ((16'sd256 - _t13) - _s1_y);
wire signed [31:0] _mul14 = P_S * (_s1_x - P_X_REST);
wire signed [15:0] _t14 = (_mul14 >>> 8);
wire signed [31:0] _mul15 = P_R * (_t14 - _s1_z);
wire signed [15:0] _t15 = (_mul15 >>> 8);
wire signed [15:0] _k2_z = _t15;
wire signed [31:0] _rk2mul_x = _k2_x * 16'sd13;
wire signed [15:0] _rk2tr_x = (_rk2mul_x >>> 8);
wire signed [15:0] _s2_x = x_reg + _rk2tr_x;
wire signed [31:0] _rk2mul_y = _k2_y * 16'sd13;
wire signed [15:0] _rk2tr_y = (_rk2mul_y >>> 8);
wire signed [15:0] _s2_y = y_reg + _rk2tr_y;
wire signed [31:0] _rk2mul_z = _k2_z * 16'sd13;
wire signed [15:0] _rk2tr_z = (_rk2mul_z >>> 8);
wire signed [15:0] _s2_z = z_reg + _rk2tr_z;
wire signed [31:0] _mul16 = _s2_x * _s2_x;
wire signed [15:0] _t16 = (_mul16 >>> 8);
wire signed [31:0] _mul17 = _t16 * _s2_x;
wire signed [15:0] _t17 = (_mul17 >>> 8);
wire signed [31:0] _mul18 = _s2_x * _s2_x;
wire signed [15:0] _t18 = (_mul18 >>> 8);
wire signed [31:0] _mul19 = P_B * _t18;
wire signed [15:0] _t19 = (_mul19 >>> 8);
wire signed [15:0] _k3_x = ((((_s2_y - _t17) + _t19) - _s2_z) + I_t);
wire signed [31:0] _mul20 = _s2_x * _s2_x;
wire signed [15:0] _t20 = (_mul20 >>> 8);
wire signed [31:0] _mul21 = 16'sd1280 * _t20;
wire signed [15:0] _t21 = (_mul21 >>> 8);
wire signed [15:0] _k3_y = ((16'sd256 - _t21) - _s2_y);
wire signed [31:0] _mul22 = P_S * (_s2_x - P_X_REST);
wire signed [15:0] _t22 = (_mul22 >>> 8);
wire signed [31:0] _mul23 = P_R * (_t22 - _s2_z);
wire signed [15:0] _t23 = (_mul23 >>> 8);
wire signed [15:0] _k3_z = _t23;
wire signed [31:0] _rk3mul_x = _k3_x * 16'sd26;
wire signed [15:0] _rk3tr_x = (_rk3mul_x >>> 8);
wire signed [15:0] _s3_x = x_reg + _rk3tr_x;
wire signed [31:0] _rk3mul_y = _k3_y * 16'sd26;
wire signed [15:0] _rk3tr_y = (_rk3mul_y >>> 8);
wire signed [15:0] _s3_y = y_reg + _rk3tr_y;
wire signed [31:0] _rk3mul_z = _k3_z * 16'sd26;
wire signed [15:0] _rk3tr_z = (_rk3mul_z >>> 8);
wire signed [15:0] _s3_z = z_reg + _rk3tr_z;
wire signed [31:0] _mul24 = _s3_x * _s3_x;
wire signed [15:0] _t24 = (_mul24 >>> 8);
wire signed [31:0] _mul25 = _t24 * _s3_x;
wire signed [15:0] _t25 = (_mul25 >>> 8);
wire signed [31:0] _mul26 = _s3_x * _s3_x;
wire signed [15:0] _t26 = (_mul26 >>> 8);
wire signed [31:0] _mul27 = P_B * _t26;
wire signed [15:0] _t27 = (_mul27 >>> 8);
wire signed [15:0] _k4_x = ((((_s3_y - _t25) + _t27) - _s3_z) + I_t);
wire signed [31:0] _mul28 = _s3_x * _s3_x;
wire signed [15:0] _t28 = (_mul28 >>> 8);
wire signed [31:0] _mul29 = 16'sd1280 * _t28;
wire signed [15:0] _t29 = (_mul29 >>> 8);
wire signed [15:0] _k4_y = ((16'sd256 - _t29) - _s3_y);
wire signed [31:0] _mul30 = P_S * (_s3_x - P_X_REST);
wire signed [15:0] _t30 = (_mul30 >>> 8);
wire signed [31:0] _mul31 = P_R * (_t30 - _s3_z);
wire signed [15:0] _t31 = (_mul31 >>> 8);
wire signed [15:0] _k4_z = _t31;
wire signed [18:0] _rkw_x = _k1_x + _k2_x + _k2_x + _k3_x + _k3_x + _k4_x;
wire signed [34:0] _rk6mul_x = _rkw_x * 16'sd4;
wire signed [18:0] _rkw_y = _k1_y + _k2_y + _k2_y + _k3_y + _k3_y + _k4_y;
wire signed [34:0] _rk6mul_y = _rkw_y * 16'sd4;
wire signed [18:0] _rkw_z = _k1_z + _k2_z + _k2_z + _k3_z + _k3_z + _k4_z;
wire signed [34:0] _rk6mul_z = _rkw_z * 16'sd4;

wire signed [15:0] dx = (_rk6mul_x >>> 8);
wire signed [15:0] dy = (_rk6mul_y >>> 8);
wire signed [15:0] dz = (_rk6mul_z >>> 8);

wire signed [16:0] x_raw = x_reg + dx;
wire signed [15:0] x_next = (x_raw > 17'sd32767) ? 16'sd32767 : (x_raw < (-17'sd32768)) ? (-16'sd32768) : x_raw[15:0];
wire signed [16:0] y_raw = y_reg + dy;
wire signed [15:0] y_next = (y_raw > 17'sd32767) ? 16'sd32767 : (y_raw < (-17'sd32768)) ? (-16'sd32768) : y_raw[15:0];
wire signed [16:0] z_raw = z_reg + dz;
wire signed [15:0] z_next = (z_raw > 17'sd32767) ? 16'sd32767 : (z_raw < (-17'sd32768)) ? (-16'sd32768) : z_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        x_reg <= 16'sd65126;
        x_out <= 16'sd65126;
        y_reg <= 16'sd62976;
        y_out <= 16'sd62976;
        z_reg <= 16'sd512;
        z_out <= 16'sd512;
        spike_out <= 1'b0;
        _thr_prev <= 1'b0;
    end else begin
        if (((x_next >= P_X_THRESHOLD)) && !_thr_prev) begin
            spike_out <= 1'b1;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
            z_reg <= z_next;
            z_out <= z_next;
        end else begin
            spike_out <= 1'b0;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
            z_reg <= z_next;
            z_out <= z_next;
        end
        _thr_prev <= ((x_next >= P_X_THRESHOLD));
    end
end

endmodule
