// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = (k * (v - vr) * (v - vt) - u + I) / C, du/dt = a * (b * (v - vr) - u))
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_izhikevich2007 #(
    parameter signed [15:0] P_C = 16'sd25600,
    parameter signed [15:0] P_K = 16'sd179,
    parameter signed [15:0] P_VR = 16'sd50176,
    parameter signed [15:0] P_VT = 16'sd55296,
    parameter signed [15:0] P_VPEAK = 16'sd8960,
    parameter signed [15:0] P_A = 16'sd8,
    parameter signed [15:0] P_B = 16'sd65024,
    parameter signed [15:0] P_c = 16'sd52736,
    parameter signed [15:0] P_D = 16'sd25600
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out,
    output reg signed [15:0] u_out
);

reg signed [15:0] v_reg;
reg signed [15:0] u_reg;

wire signed [31:0] _mul0 = P_K * (v_reg - P_VR);
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _mul1 = _t0 * (v_reg - P_VT);
wire signed [15:0] _t1 = (_mul1 >>> 8);
wire signed [15:0] _dop2 = ((_t1 - u_reg) + I_t);
wire signed [15:0] _dden2 = P_C;
wire signed [31:0] _dnum2 = $signed({{16{_dop2[15]}}, _dop2}) <<< 8;
wire signed [31:0] _div2 = _dnum2 / $signed({{16{_dden2[15]}}, _dden2});
wire signed [15:0] _dres2 = _div2[15:0];
wire signed [31:0] _dt_mul_v = (_dres2) * 16'sd26;
wire signed [15:0] _dt_trunc_v = (_dt_mul_v >>> 8);
wire signed [31:0] _mul3 = P_B * (v_reg - P_VR);
wire signed [15:0] _t2 = (_mul3 >>> 8);
wire signed [31:0] _mul4 = P_A * (_t2 - u_reg);
wire signed [15:0] _t3 = (_mul4 >>> 8);
wire signed [31:0] _dt_mul_u = (_t3) * 16'sd26;
wire signed [15:0] _dt_trunc_u = (_dt_mul_u >>> 8);

wire signed [15:0] dv = _dt_trunc_v;
wire signed [15:0] du = _dt_trunc_u;

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];
wire signed [16:0] u_raw = u_reg + du;
wire signed [15:0] u_next = (u_raw > 17'sd32767) ? 16'sd32767 : (u_raw < (-17'sd32768)) ? (-16'sd32768) : u_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd50176;
        v_out <= 16'sd50176;
        u_reg <= 16'sd0;
        u_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_next >= P_VPEAK)) begin
            spike_out <= 1'b1;
            v_reg <= P_c;
            u_reg <= (u_reg + P_D);
            v_out <= v_reg;
            u_out <= u_reg;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            u_reg <= u_next;
            u_out <= u_next;
        end
    end
end

endmodule
