// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = max(v_min, v + (((a * (v_rest - v)) // 8 if v < branch_point else (b * (v - v_threshold)) // 8) + I)))
// Fixed-point: Q32.0 (32-bit signed)
`timescale 1ns / 1ps

module sc_integerqifneuron #(
    parameter signed [31:0] P_V_REST = 32'sd128,
    parameter signed [31:0] P_V_THRESHOLD = 32'sd200,
    parameter signed [31:0] P_V_RESET = 32'sd128,
    parameter signed [31:0] P_A = 32'sd1,
    parameter signed [31:0] P_B = 32'sd1,
    parameter signed [31:0] P_V_MAX = 32'sd255,
    parameter signed [31:0] P_V_MIN = 32'sd0,
    parameter signed [31:0] P_BRANCH_POINT = 32'sd164
)(
    input wire clk,
    input wire rst_n,
    input wire signed [31:0] I_t,
    output reg spike_out,
    output reg signed [31:0] v_out
);

reg signed [31:0] v_reg;

wire signed [63:0] _mul0 = P_A * (P_V_REST - v_reg);
wire signed [31:0] _t0 = (_mul0 >>> 0);
wire signed [31:0] _floordiv1_dividend = _t0;
wire signed [31:0] _floordiv1_integer = $signed(_floordiv1_dividend) >>> 3;
wire signed [31:0] _floordiv1 = _floordiv1_integer;
wire signed [63:0] _mul2 = P_B * (v_reg - P_V_THRESHOLD);
wire signed [31:0] _t1 = (_mul2 >>> 0);
wire signed [31:0] _floordiv3_dividend = _t1;
wire signed [31:0] _floordiv3_integer = $signed(_floordiv3_dividend) >>> 3;
wire signed [31:0] _floordiv3 = _floordiv3_integer;

wire signed [31:0] dv = ((P_V_MIN > (v_reg + ((((v_reg < P_BRANCH_POINT)) ? (_floordiv1) : (_floordiv3)) + I_t))) ? P_V_MIN : (v_reg + ((((v_reg < P_BRANCH_POINT)) ? (_floordiv1) : (_floordiv3)) + I_t)));

wire signed [32:0] v_raw = dv;
wire signed [31:0] v_next = (v_raw > 33'sd2147483647) ? 32'sd2147483647 : (v_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : v_raw[31:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 32'sd128;
        v_out <= 32'sd128;
        spike_out <= 1'b0;
    end else begin
        if ((v_next > P_V_MAX)) begin
            spike_out <= 1'b1;
            v_reg <= P_V_RESET;
            v_out <= P_V_RESET;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
        end
    end
end

endmodule
