// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = ((-(alpha * alpha) / 4.0 - alpha + I + u) if v < (-1.0 - alpha / 2.0) else (alpha * v + (v + 1.0) * (v + 1.0) + I + u if v <= 0.0 else (1.0 + I + u if v < (1.0 + I + u) else -1.0))), du/dt = u - mu * (v + 1.0 - sigma))
// Fixed-point: Q16.16 (32-bit signed)
`timescale 1ns / 1ps

module sc_ibarz_tanaka_rulkov_map #(
    parameter signed [31:0] P_ALPHA = 32'sd65536,
    parameter signed [31:0] P_MU = 32'sd66,
    parameter signed [31:0] P_SIGMA = 32'sd6554
)(
    input wire clk,
    input wire rst_n,
    input wire signed [31:0] I_t,
    output reg spike_out,
    output reg signed [31:0] v_out,
    output reg signed [31:0] u_out
);

reg signed [31:0] v_reg;
reg signed [31:0] u_reg;

wire signed [63:0] _mul0 = P_ALPHA * 32'sd32768;
wire signed [31:0] _t0 = (_mul0 >>> 16);
wire signed [63:0] _mul1 = P_ALPHA * P_ALPHA;
wire signed [31:0] _t1 = (_mul1 >>> 16);
wire signed [63:0] _mul2 = (-_t1) * 32'sd16384;
wire signed [31:0] _t2 = (_mul2 >>> 16);
wire signed [63:0] _mul3 = P_ALPHA * v_reg;
wire signed [31:0] _t3 = (_mul3 >>> 16);
wire signed [63:0] _mul4 = (v_reg + 32'sd65536) * (v_reg + 32'sd65536);
wire signed [31:0] _t4 = (_mul4 >>> 16);
wire signed [63:0] _mul5 = P_MU * ((v_reg + 32'sd65536) - P_SIGMA);
wire signed [31:0] _t5 = (_mul5 >>> 16);

wire signed [31:0] dv = (((v_reg < ((-32'sd65536) - _t0))) ? ((((_t2 - P_ALPHA) + I_t) + u_reg)) : ((((v_reg <= 32'sd0)) ? ((((_t3 + _t4) + I_t) + u_reg)) : ((((v_reg < ((32'sd65536 + I_t) + u_reg))) ? (((32'sd65536 + I_t) + u_reg)) : ((-32'sd65536)))))));
wire signed [31:0] du = (u_reg - _t5);

wire signed [32:0] v_raw = dv;
wire signed [31:0] v_next = (v_raw > 33'sd2147483647) ? 32'sd2147483647 : (v_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : v_raw[31:0];
wire signed [32:0] u_raw = du;
wire signed [31:0] u_next = (u_raw > 33'sd2147483647) ? 32'sd2147483647 : (u_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : u_raw[31:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 32'sd4294901760;
        v_out <= 32'sd4294901760;
        u_reg <= 32'sd4294960742;
        u_out <= 32'sd4294960742;
        spike_out <= 1'b0;
    end else begin
        if ((v_reg >= ((32'sd65536 + I_t) + u_reg))) begin
            spike_out <= 1'b1;
            v_reg <= v_next;
            v_out <= v_next;
            u_reg <= u_next;
            u_out <= u_next;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            u_reg <= u_next;
            u_out <= u_next;
        end
    end
end

endmodule
