// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = (-(v - v_rest) + resistance * I) / tau)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_lapicque #(
    parameter signed [15:0] P_V_REST = 16'sd0,
    parameter signed [15:0] P_V_RESET = 16'sd0,
    parameter signed [15:0] P_V_THRESHOLD = 16'sd256,
    parameter signed [15:0] P_TAU = 16'sd5120,
    parameter signed [15:0] P_RESISTANCE = 16'sd256
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out
);

reg signed [15:0] v_reg;

wire signed [31:0] _mul0 = P_RESISTANCE * I_t;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [15:0] _dop1 = ((-(v_reg - P_V_REST)) + _t0);
wire signed [15:0] _dden1 = P_TAU;
wire signed [31:0] _dnum1 = $signed({{16{_dop1[15]}}, _dop1}) <<< 8;
wire signed [31:0] _div1 = _dnum1 / $signed({{16{_dden1[15]}}, _dden1});
wire signed [15:0] _dres1 = _div1[15:0];
wire signed [31:0] _mul2 = _dres1 * 16'sd256;
wire signed [15:0] _t1 = (_mul2 >>> 8);
wire signed [15:0] _dop3 = (-16'sd256);
wire signed [15:0] _dden3 = P_TAU;
wire signed [31:0] _dnum3 = $signed({{16{_dop3[15]}}, _dop3}) <<< 8;
wire signed [31:0] _div3 = _dnum3 / $signed({{16{_dden3[15]}}, _dden3});
wire signed [15:0] _dres3 = _div3[15:0];
wire signed [31:0] _mul4 = _dres3 * 16'sd256;
wire signed [15:0] _t2 = (_mul4 >>> 8);
// _exprel_lut lookup table (256 entries over [-16.0, 16.0), step 0.125)
wire signed [15:0] _exprel_lut5_arg = _t2;
wire signed [16:0] _exprel_lut5_raw = (({{_exprel_lut5_arg[15]}, _exprel_lut5_arg}) + 17'sd4096) >>> 5;
wire [7:0] _exprel_lut5_idx = (_exprel_lut5_raw < 0) ? 8'd0 : ((_exprel_lut5_raw > 17'sd255) ? 8'd255 : _exprel_lut5_raw[7:0]);
reg signed [15:0] _exprel_lut5_out;
always @(*) case (_exprel_lut5_idx)
    8'd0: _exprel_lut5_out = 16'sd16;
    8'd1: _exprel_lut5_out = 16'sd16;
    8'd2: _exprel_lut5_out = 16'sd16;
    8'd3: _exprel_lut5_out = 16'sd16;
    8'd4: _exprel_lut5_out = 16'sd17;
    8'd5: _exprel_lut5_out = 16'sd17;
    8'd6: _exprel_lut5_out = 16'sd17;
    8'd7: _exprel_lut5_out = 16'sd17;
    8'd8: _exprel_lut5_out = 16'sd17;
    8'd9: _exprel_lut5_out = 16'sd17;
    8'd10: _exprel_lut5_out = 16'sd17;
    8'd11: _exprel_lut5_out = 16'sd18;
    8'd12: _exprel_lut5_out = 16'sd18;
    8'd13: _exprel_lut5_out = 16'sd18;
    8'd14: _exprel_lut5_out = 16'sd18;
    8'd15: _exprel_lut5_out = 16'sd18;
    8'd16: _exprel_lut5_out = 16'sd18;
    8'd17: _exprel_lut5_out = 16'sd18;
    8'd18: _exprel_lut5_out = 16'sd19;
    8'd19: _exprel_lut5_out = 16'sd19;
    8'd20: _exprel_lut5_out = 16'sd19;
    8'd21: _exprel_lut5_out = 16'sd19;
    8'd22: _exprel_lut5_out = 16'sd19;
    8'd23: _exprel_lut5_out = 16'sd20;
    8'd24: _exprel_lut5_out = 16'sd20;
    8'd25: _exprel_lut5_out = 16'sd20;
    8'd26: _exprel_lut5_out = 16'sd20;
    8'd27: _exprel_lut5_out = 16'sd20;
    8'd28: _exprel_lut5_out = 16'sd20;
    8'd29: _exprel_lut5_out = 16'sd21;
    8'd30: _exprel_lut5_out = 16'sd21;
    8'd31: _exprel_lut5_out = 16'sd21;
    8'd32: _exprel_lut5_out = 16'sd21;
    8'd33: _exprel_lut5_out = 16'sd22;
    8'd34: _exprel_lut5_out = 16'sd22;
    8'd35: _exprel_lut5_out = 16'sd22;
    8'd36: _exprel_lut5_out = 16'sd22;
    8'd37: _exprel_lut5_out = 16'sd23;
    8'd38: _exprel_lut5_out = 16'sd23;
    8'd39: _exprel_lut5_out = 16'sd23;
    8'd40: _exprel_lut5_out = 16'sd23;
    8'd41: _exprel_lut5_out = 16'sd24;
    8'd42: _exprel_lut5_out = 16'sd24;
    8'd43: _exprel_lut5_out = 16'sd24;
    8'd44: _exprel_lut5_out = 16'sd24;
    8'd45: _exprel_lut5_out = 16'sd25;
    8'd46: _exprel_lut5_out = 16'sd25;
    8'd47: _exprel_lut5_out = 16'sd25;
    8'd48: _exprel_lut5_out = 16'sd26;
    8'd49: _exprel_lut5_out = 16'sd26;
    8'd50: _exprel_lut5_out = 16'sd26;
    8'd51: _exprel_lut5_out = 16'sd27;
    8'd52: _exprel_lut5_out = 16'sd27;
    8'd53: _exprel_lut5_out = 16'sd27;
    8'd54: _exprel_lut5_out = 16'sd28;
    8'd55: _exprel_lut5_out = 16'sd28;
    8'd56: _exprel_lut5_out = 16'sd28;
    8'd57: _exprel_lut5_out = 16'sd29;
    8'd58: _exprel_lut5_out = 16'sd29;
    8'd59: _exprel_lut5_out = 16'sd30;
    8'd60: _exprel_lut5_out = 16'sd30;
    8'd61: _exprel_lut5_out = 16'sd31;
    8'd62: _exprel_lut5_out = 16'sd31;
    8'd63: _exprel_lut5_out = 16'sd31;
    8'd64: _exprel_lut5_out = 16'sd32;
    8'd65: _exprel_lut5_out = 16'sd32;
    8'd66: _exprel_lut5_out = 16'sd33;
    8'd67: _exprel_lut5_out = 16'sd34;
    8'd68: _exprel_lut5_out = 16'sd34;
    8'd69: _exprel_lut5_out = 16'sd35;
    8'd70: _exprel_lut5_out = 16'sd35;
    8'd71: _exprel_lut5_out = 16'sd36;
    8'd72: _exprel_lut5_out = 16'sd37;
    8'd73: _exprel_lut5_out = 16'sd37;
    8'd74: _exprel_lut5_out = 16'sd38;
    8'd75: _exprel_lut5_out = 16'sd39;
    8'd76: _exprel_lut5_out = 16'sd39;
    8'd77: _exprel_lut5_out = 16'sd40;
    8'd78: _exprel_lut5_out = 16'sd41;
    8'd79: _exprel_lut5_out = 16'sd42;
    8'd80: _exprel_lut5_out = 16'sd43;
    8'd81: _exprel_lut5_out = 16'sd43;
    8'd82: _exprel_lut5_out = 16'sd44;
    8'd83: _exprel_lut5_out = 16'sd45;
    8'd84: _exprel_lut5_out = 16'sd46;
    8'd85: _exprel_lut5_out = 16'sd47;
    8'd86: _exprel_lut5_out = 16'sd49;
    8'd87: _exprel_lut5_out = 16'sd50;
    8'd88: _exprel_lut5_out = 16'sd51;
    8'd89: _exprel_lut5_out = 16'sd52;
    8'd90: _exprel_lut5_out = 16'sd53;
    8'd91: _exprel_lut5_out = 16'sd55;
    8'd92: _exprel_lut5_out = 16'sd56;
    8'd93: _exprel_lut5_out = 16'sd58;
    8'd94: _exprel_lut5_out = 16'sd59;
    8'd95: _exprel_lut5_out = 16'sd61;
    8'd96: _exprel_lut5_out = 16'sd63;
    8'd97: _exprel_lut5_out = 16'sd65;
    8'd98: _exprel_lut5_out = 16'sd67;
    8'd99: _exprel_lut5_out = 16'sd69;
    8'd100: _exprel_lut5_out = 16'sd71;
    8'd101: _exprel_lut5_out = 16'sd73;
    8'd102: _exprel_lut5_out = 16'sd76;
    8'd103: _exprel_lut5_out = 16'sd78;
    8'd104: _exprel_lut5_out = 16'sd81;
    8'd105: _exprel_lut5_out = 16'sd84;
    8'd106: _exprel_lut5_out = 16'sd87;
    8'd107: _exprel_lut5_out = 16'sd90;
    8'd108: _exprel_lut5_out = 16'sd94;
    8'd109: _exprel_lut5_out = 16'sd98;
    8'd110: _exprel_lut5_out = 16'sd102;
    8'd111: _exprel_lut5_out = 16'sd106;
    8'd112: _exprel_lut5_out = 16'sd111;
    8'd113: _exprel_lut5_out = 16'sd116;
    8'd114: _exprel_lut5_out = 16'sd121;
    8'd115: _exprel_lut5_out = 16'sd127;
    8'd116: _exprel_lut5_out = 16'sd133;
    8'd117: _exprel_lut5_out = 16'sd139;
    8'd118: _exprel_lut5_out = 16'sd146;
    8'd119: _exprel_lut5_out = 16'sd154;
    8'd120: _exprel_lut5_out = 16'sd162;
    8'd121: _exprel_lut5_out = 16'sd171;
    8'd122: _exprel_lut5_out = 16'sd180;
    8'd123: _exprel_lut5_out = 16'sd190;
    8'd124: _exprel_lut5_out = 16'sd201;
    8'd125: _exprel_lut5_out = 16'sd213;
    8'd126: _exprel_lut5_out = 16'sd227;
    8'd127: _exprel_lut5_out = 16'sd241;
    8'd128: _exprel_lut5_out = 16'sd256;
    8'd129: _exprel_lut5_out = 16'sd273;
    8'd130: _exprel_lut5_out = 16'sd291;
    8'd131: _exprel_lut5_out = 16'sd311;
    8'd132: _exprel_lut5_out = 16'sd332;
    8'd133: _exprel_lut5_out = 16'sd356;
    8'd134: _exprel_lut5_out = 16'sd381;
    8'd135: _exprel_lut5_out = 16'sd409;
    8'd136: _exprel_lut5_out = 16'sd440;
    8'd137: _exprel_lut5_out = 16'sd473;
    8'd138: _exprel_lut5_out = 16'sd510;
    8'd139: _exprel_lut5_out = 16'sd550;
    8'd140: _exprel_lut5_out = 16'sd594;
    8'd141: _exprel_lut5_out = 16'sd643;
    8'd142: _exprel_lut5_out = 16'sd696;
    8'd143: _exprel_lut5_out = 16'sd754;
    8'd144: _exprel_lut5_out = 16'sd818;
    8'd145: _exprel_lut5_out = 16'sd888;
    8'd146: _exprel_lut5_out = 16'sd966;
    8'd147: _exprel_lut5_out = 16'sd1051;
    8'd148: _exprel_lut5_out = 16'sd1145;
    8'd149: _exprel_lut5_out = 16'sd1249;
    8'd150: _exprel_lut5_out = 16'sd1363;
    8'd151: _exprel_lut5_out = 16'sd1489;
    8'd152: _exprel_lut5_out = 16'sd1629;
    8'd153: _exprel_lut5_out = 16'sd1783;
    8'd154: _exprel_lut5_out = 16'sd1953;
    8'd155: _exprel_lut5_out = 16'sd2141;
    8'd156: _exprel_lut5_out = 16'sd2349;
    8'd157: _exprel_lut5_out = 16'sd2579;
    8'd158: _exprel_lut5_out = 16'sd2835;
    8'd159: _exprel_lut5_out = 16'sd3117;
    8'd160: _exprel_lut5_out = 16'sd3430;
    8'd161: _exprel_lut5_out = 16'sd3777;
    8'd162: _exprel_lut5_out = 16'sd4163;
    8'd163: _exprel_lut5_out = 16'sd4590;
    8'd164: _exprel_lut5_out = 16'sd5064;
    8'd165: _exprel_lut5_out = 16'sd5591;
    8'd166: _exprel_lut5_out = 16'sd6175;
    8'd167: _exprel_lut5_out = 16'sd6825;
    8'd168: _exprel_lut5_out = 16'sd7548;
    8'd169: _exprel_lut5_out = 16'sd8351;
    8'd170: _exprel_lut5_out = 16'sd9244;
    8'd171: _exprel_lut5_out = 16'sd10237;
    8'd172: _exprel_lut5_out = 16'sd11343;
    8'd173: _exprel_lut5_out = 16'sd12573;
    8'd174: _exprel_lut5_out = 16'sd13944;
    8'd175: _exprel_lut5_out = 16'sd15470;
    8'd176: _exprel_lut5_out = 16'sd17170;
    8'd177: _exprel_lut5_out = 16'sd19065;
    8'd178: _exprel_lut5_out = 16'sd21177;
    8'd179: _exprel_lut5_out = 16'sd23531;
    8'd180: _exprel_lut5_out = 16'sd26157;
    8'd181: _exprel_lut5_out = 16'sd29086;
    8'd182: _exprel_lut5_out = 16'sd32353;
    8'd183: _exprel_lut5_out = 16'sd32767;
    8'd184: _exprel_lut5_out = 16'sd32767;
    8'd185: _exprel_lut5_out = 16'sd32767;
    8'd186: _exprel_lut5_out = 16'sd32767;
    8'd187: _exprel_lut5_out = 16'sd32767;
    8'd188: _exprel_lut5_out = 16'sd32767;
    8'd189: _exprel_lut5_out = 16'sd32767;
    8'd190: _exprel_lut5_out = 16'sd32767;
    8'd191: _exprel_lut5_out = 16'sd32767;
    8'd192: _exprel_lut5_out = 16'sd32767;
    8'd193: _exprel_lut5_out = 16'sd32767;
    8'd194: _exprel_lut5_out = 16'sd32767;
    8'd195: _exprel_lut5_out = 16'sd32767;
    8'd196: _exprel_lut5_out = 16'sd32767;
    8'd197: _exprel_lut5_out = 16'sd32767;
    8'd198: _exprel_lut5_out = 16'sd32767;
    8'd199: _exprel_lut5_out = 16'sd32767;
    8'd200: _exprel_lut5_out = 16'sd32767;
    8'd201: _exprel_lut5_out = 16'sd32767;
    8'd202: _exprel_lut5_out = 16'sd32767;
    8'd203: _exprel_lut5_out = 16'sd32767;
    8'd204: _exprel_lut5_out = 16'sd32767;
    8'd205: _exprel_lut5_out = 16'sd32767;
    8'd206: _exprel_lut5_out = 16'sd32767;
    8'd207: _exprel_lut5_out = 16'sd32767;
    8'd208: _exprel_lut5_out = 16'sd32767;
    8'd209: _exprel_lut5_out = 16'sd32767;
    8'd210: _exprel_lut5_out = 16'sd32767;
    8'd211: _exprel_lut5_out = 16'sd32767;
    8'd212: _exprel_lut5_out = 16'sd32767;
    8'd213: _exprel_lut5_out = 16'sd32767;
    8'd214: _exprel_lut5_out = 16'sd32767;
    8'd215: _exprel_lut5_out = 16'sd32767;
    8'd216: _exprel_lut5_out = 16'sd32767;
    8'd217: _exprel_lut5_out = 16'sd32767;
    8'd218: _exprel_lut5_out = 16'sd32767;
    8'd219: _exprel_lut5_out = 16'sd32767;
    8'd220: _exprel_lut5_out = 16'sd32767;
    8'd221: _exprel_lut5_out = 16'sd32767;
    8'd222: _exprel_lut5_out = 16'sd32767;
    8'd223: _exprel_lut5_out = 16'sd32767;
    8'd224: _exprel_lut5_out = 16'sd32767;
    8'd225: _exprel_lut5_out = 16'sd32767;
    8'd226: _exprel_lut5_out = 16'sd32767;
    8'd227: _exprel_lut5_out = 16'sd32767;
    8'd228: _exprel_lut5_out = 16'sd32767;
    8'd229: _exprel_lut5_out = 16'sd32767;
    8'd230: _exprel_lut5_out = 16'sd32767;
    8'd231: _exprel_lut5_out = 16'sd32767;
    8'd232: _exprel_lut5_out = 16'sd32767;
    8'd233: _exprel_lut5_out = 16'sd32767;
    8'd234: _exprel_lut5_out = 16'sd32767;
    8'd235: _exprel_lut5_out = 16'sd32767;
    8'd236: _exprel_lut5_out = 16'sd32767;
    8'd237: _exprel_lut5_out = 16'sd32767;
    8'd238: _exprel_lut5_out = 16'sd32767;
    8'd239: _exprel_lut5_out = 16'sd32767;
    8'd240: _exprel_lut5_out = 16'sd32767;
    8'd241: _exprel_lut5_out = 16'sd32767;
    8'd242: _exprel_lut5_out = 16'sd32767;
    8'd243: _exprel_lut5_out = 16'sd32767;
    8'd244: _exprel_lut5_out = 16'sd32767;
    8'd245: _exprel_lut5_out = 16'sd32767;
    8'd246: _exprel_lut5_out = 16'sd32767;
    8'd247: _exprel_lut5_out = 16'sd32767;
    8'd248: _exprel_lut5_out = 16'sd32767;
    8'd249: _exprel_lut5_out = 16'sd32767;
    8'd250: _exprel_lut5_out = 16'sd32767;
    8'd251: _exprel_lut5_out = 16'sd32767;
    8'd252: _exprel_lut5_out = 16'sd32767;
    8'd253: _exprel_lut5_out = 16'sd32767;
    8'd254: _exprel_lut5_out = 16'sd32767;
    8'd255: _exprel_lut5_out = 16'sd32767;
    default: _exprel_lut5_out = 16'sd0;
endcase
wire signed [31:0] _mul6 = _t1 * _exprel_lut5_out;
wire signed [15:0] _t3 = (_mul6 >>> 8);

wire signed [15:0] dv = _t3;

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd0;
        v_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_next >= P_V_THRESHOLD)) begin
            spike_out <= 1'b1;
            v_reg <= P_V_RESET;
            v_out <= P_V_RESET;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
        end
    end
end

endmodule
