// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = I + i1 + i2 - leak_rate * (v - v_rest), dtheta/dt = threshold_voltage_coupling * (v - v_rest) - threshold_decay_rate * (theta - theta_inf), di1/dt = -current_decay_rate_1 * i1, di2/dt = -current_decay_rate_2 * i2)
// Fixed-point: Q32.32 (64-bit signed)
`timescale 1ns / 1ps

module sc_mihalasnieburneuron #(
    parameter signed [63:0] P_V_REST = 64'sd18446744073408903905,
    parameter signed [63:0] P_V_RESET = 64'sd18446744073408903905,
    parameter signed [63:0] P_THETA_RESET = 64'sd18446744073451853578,
    parameter signed [63:0] P_THETA_INF = 64'sd18446744073494803251,
    parameter signed [63:0] P_LEAK_RATE = 64'sd214748365,
    parameter signed [63:0] P_THRESHOLD_VOLTAGE_COUPLING = 64'sd21474836,
    parameter signed [63:0] P_THRESHOLD_DECAY_RATE = 64'sd42949673,
    parameter signed [63:0] P_CURRENT_DECAY_RATE_1 = 64'sd858993459,
    parameter signed [63:0] P_CURRENT_DECAY_RATE_2 = 64'sd85899346,
    parameter signed [63:0] P_CURRENT_RETENTION_1 = 64'sd0,
    parameter signed [63:0] P_CURRENT_RETENTION_2 = 64'sd4294967296,
    parameter signed [63:0] P_CURRENT_JUMP_1 = 64'sd0,
    parameter signed [63:0] P_CURRENT_JUMP_2 = 64'sd0
)(
    input wire clk,
    input wire rst_n,
    input wire signed [63:0] I_t,
    output reg spike_out,
    output reg signed [63:0] v_out,
    output reg signed [63:0] theta_out,
    output reg signed [63:0] i1_out,
    output reg signed [63:0] i2_out
);

reg signed [63:0] v_reg;
reg signed [63:0] theta_reg;
reg signed [63:0] i1_reg;
reg signed [63:0] i2_reg;

wire signed [127:0] _mul0 = P_LEAK_RATE * (v_reg - P_V_REST);
wire signed [63:0] _t0 = (_mul0 >>> 32);
wire signed [63:0] _k1_v = (((I_t + i1_reg) + i2_reg) - _t0);
wire signed [127:0] _mul1 = P_THRESHOLD_VOLTAGE_COUPLING * (v_reg - P_V_REST);
wire signed [63:0] _t1 = (_mul1 >>> 32);
wire signed [127:0] _mul2 = P_THRESHOLD_DECAY_RATE * (theta_reg - P_THETA_INF);
wire signed [63:0] _t2 = (_mul2 >>> 32);
wire signed [63:0] _k1_theta = (_t1 - _t2);
wire signed [127:0] _mul3 = (-P_CURRENT_DECAY_RATE_1) * i1_reg;
wire signed [63:0] _t3 = (_mul3 >>> 32);
wire signed [63:0] _k1_i1 = _t3;
wire signed [127:0] _mul4 = (-P_CURRENT_DECAY_RATE_2) * i2_reg;
wire signed [63:0] _t4 = (_mul4 >>> 32);
wire signed [63:0] _k1_i2 = _t4;
wire signed [127:0] _rk1mul_v = _k1_v * 64'sd214748365;
wire signed [63:0] _rk1tr_v = (_rk1mul_v >>> 32);
wire signed [63:0] _s1_v = v_reg + _rk1tr_v;
wire signed [127:0] _rk1mul_theta = _k1_theta * 64'sd214748365;
wire signed [63:0] _rk1tr_theta = (_rk1mul_theta >>> 32);
wire signed [63:0] _s1_theta = theta_reg + _rk1tr_theta;
wire signed [127:0] _rk1mul_i1 = _k1_i1 * 64'sd214748365;
wire signed [63:0] _rk1tr_i1 = (_rk1mul_i1 >>> 32);
wire signed [63:0] _s1_i1 = i1_reg + _rk1tr_i1;
wire signed [127:0] _rk1mul_i2 = _k1_i2 * 64'sd214748365;
wire signed [63:0] _rk1tr_i2 = (_rk1mul_i2 >>> 32);
wire signed [63:0] _s1_i2 = i2_reg + _rk1tr_i2;
wire signed [127:0] _mul5 = P_LEAK_RATE * (_s1_v - P_V_REST);
wire signed [63:0] _t5 = (_mul5 >>> 32);
wire signed [63:0] _k2_v = (((I_t + _s1_i1) + _s1_i2) - _t5);
wire signed [127:0] _mul6 = P_THRESHOLD_VOLTAGE_COUPLING * (_s1_v - P_V_REST);
wire signed [63:0] _t6 = (_mul6 >>> 32);
wire signed [127:0] _mul7 = P_THRESHOLD_DECAY_RATE * (_s1_theta - P_THETA_INF);
wire signed [63:0] _t7 = (_mul7 >>> 32);
wire signed [63:0] _k2_theta = (_t6 - _t7);
wire signed [127:0] _mul8 = (-P_CURRENT_DECAY_RATE_1) * _s1_i1;
wire signed [63:0] _t8 = (_mul8 >>> 32);
wire signed [63:0] _k2_i1 = _t8;
wire signed [127:0] _mul9 = (-P_CURRENT_DECAY_RATE_2) * _s1_i2;
wire signed [63:0] _t9 = (_mul9 >>> 32);
wire signed [63:0] _k2_i2 = _t9;
wire signed [127:0] _rk2mul_v = _k2_v * 64'sd214748365;
wire signed [63:0] _rk2tr_v = (_rk2mul_v >>> 32);
wire signed [63:0] _s2_v = v_reg + _rk2tr_v;
wire signed [127:0] _rk2mul_theta = _k2_theta * 64'sd214748365;
wire signed [63:0] _rk2tr_theta = (_rk2mul_theta >>> 32);
wire signed [63:0] _s2_theta = theta_reg + _rk2tr_theta;
wire signed [127:0] _rk2mul_i1 = _k2_i1 * 64'sd214748365;
wire signed [63:0] _rk2tr_i1 = (_rk2mul_i1 >>> 32);
wire signed [63:0] _s2_i1 = i1_reg + _rk2tr_i1;
wire signed [127:0] _rk2mul_i2 = _k2_i2 * 64'sd214748365;
wire signed [63:0] _rk2tr_i2 = (_rk2mul_i2 >>> 32);
wire signed [63:0] _s2_i2 = i2_reg + _rk2tr_i2;
wire signed [127:0] _mul10 = P_LEAK_RATE * (_s2_v - P_V_REST);
wire signed [63:0] _t10 = (_mul10 >>> 32);
wire signed [63:0] _k3_v = (((I_t + _s2_i1) + _s2_i2) - _t10);
wire signed [127:0] _mul11 = P_THRESHOLD_VOLTAGE_COUPLING * (_s2_v - P_V_REST);
wire signed [63:0] _t11 = (_mul11 >>> 32);
wire signed [127:0] _mul12 = P_THRESHOLD_DECAY_RATE * (_s2_theta - P_THETA_INF);
wire signed [63:0] _t12 = (_mul12 >>> 32);
wire signed [63:0] _k3_theta = (_t11 - _t12);
wire signed [127:0] _mul13 = (-P_CURRENT_DECAY_RATE_1) * _s2_i1;
wire signed [63:0] _t13 = (_mul13 >>> 32);
wire signed [63:0] _k3_i1 = _t13;
wire signed [127:0] _mul14 = (-P_CURRENT_DECAY_RATE_2) * _s2_i2;
wire signed [63:0] _t14 = (_mul14 >>> 32);
wire signed [63:0] _k3_i2 = _t14;
wire signed [127:0] _rk3mul_v = _k3_v * 64'sd429496730;
wire signed [63:0] _rk3tr_v = (_rk3mul_v >>> 32);
wire signed [63:0] _s3_v = v_reg + _rk3tr_v;
wire signed [127:0] _rk3mul_theta = _k3_theta * 64'sd429496730;
wire signed [63:0] _rk3tr_theta = (_rk3mul_theta >>> 32);
wire signed [63:0] _s3_theta = theta_reg + _rk3tr_theta;
wire signed [127:0] _rk3mul_i1 = _k3_i1 * 64'sd429496730;
wire signed [63:0] _rk3tr_i1 = (_rk3mul_i1 >>> 32);
wire signed [63:0] _s3_i1 = i1_reg + _rk3tr_i1;
wire signed [127:0] _rk3mul_i2 = _k3_i2 * 64'sd429496730;
wire signed [63:0] _rk3tr_i2 = (_rk3mul_i2 >>> 32);
wire signed [63:0] _s3_i2 = i2_reg + _rk3tr_i2;
wire signed [127:0] _mul15 = P_LEAK_RATE * (_s3_v - P_V_REST);
wire signed [63:0] _t15 = (_mul15 >>> 32);
wire signed [63:0] _k4_v = (((I_t + _s3_i1) + _s3_i2) - _t15);
wire signed [127:0] _mul16 = P_THRESHOLD_VOLTAGE_COUPLING * (_s3_v - P_V_REST);
wire signed [63:0] _t16 = (_mul16 >>> 32);
wire signed [127:0] _mul17 = P_THRESHOLD_DECAY_RATE * (_s3_theta - P_THETA_INF);
wire signed [63:0] _t17 = (_mul17 >>> 32);
wire signed [63:0] _k4_theta = (_t16 - _t17);
wire signed [127:0] _mul18 = (-P_CURRENT_DECAY_RATE_1) * _s3_i1;
wire signed [63:0] _t18 = (_mul18 >>> 32);
wire signed [63:0] _k4_i1 = _t18;
wire signed [127:0] _mul19 = (-P_CURRENT_DECAY_RATE_2) * _s3_i2;
wire signed [63:0] _t19 = (_mul19 >>> 32);
wire signed [63:0] _k4_i2 = _t19;
wire signed [66:0] _rkw_v = _k1_v + _k2_v + _k2_v + _k3_v + _k3_v + _k4_v;
wire signed [130:0] _rk6mul_v = _rkw_v * 64'sd71582788;
wire signed [66:0] _rkw_theta = _k1_theta + _k2_theta + _k2_theta + _k3_theta + _k3_theta + _k4_theta;
wire signed [130:0] _rk6mul_theta = _rkw_theta * 64'sd71582788;
wire signed [66:0] _rkw_i1 = _k1_i1 + _k2_i1 + _k2_i1 + _k3_i1 + _k3_i1 + _k4_i1;
wire signed [130:0] _rk6mul_i1 = _rkw_i1 * 64'sd71582788;
wire signed [66:0] _rkw_i2 = _k1_i2 + _k2_i2 + _k2_i2 + _k3_i2 + _k3_i2 + _k4_i2;
wire signed [130:0] _rk6mul_i2 = _rkw_i2 * 64'sd71582788;
wire signed [127:0] _mul20 = P_CURRENT_RETENTION_1 * i1_next;
wire signed [63:0] _t20 = (_mul20 >>> 32);
wire signed [127:0] _mul21 = P_CURRENT_RETENTION_2 * i2_next;
wire signed [63:0] _t21 = (_mul21 >>> 32);

wire signed [63:0] dv = (_rk6mul_v >>> 32);
wire signed [63:0] dtheta = (_rk6mul_theta >>> 32);
wire signed [63:0] di1 = (_rk6mul_i1 >>> 32);
wire signed [63:0] di2 = (_rk6mul_i2 >>> 32);

wire signed [64:0] v_raw = v_reg + dv;
wire signed [63:0] v_next = (v_raw > 65'sd9223372036854775807) ? 64'sd9223372036854775807 : (v_raw < (-65'sd9223372036854775808)) ? (-64'sd9223372036854775808) : v_raw[63:0];
wire signed [64:0] theta_raw = theta_reg + dtheta;
wire signed [63:0] theta_next = (theta_raw > 65'sd9223372036854775807) ? 64'sd9223372036854775807 : (theta_raw < (-65'sd9223372036854775808)) ? (-64'sd9223372036854775808) : theta_raw[63:0];
wire signed [64:0] i1_raw = i1_reg + di1;
wire signed [63:0] i1_next = (i1_raw > 65'sd9223372036854775807) ? 64'sd9223372036854775807 : (i1_raw < (-65'sd9223372036854775808)) ? (-64'sd9223372036854775808) : i1_raw[63:0];
wire signed [64:0] i2_raw = i2_reg + di2;
wire signed [63:0] i2_next = (i2_raw > 65'sd9223372036854775807) ? 64'sd9223372036854775807 : (i2_raw < (-65'sd9223372036854775808)) ? (-64'sd9223372036854775808) : i2_raw[63:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 64'sd18446744073408903905;
        v_out <= 64'sd18446744073408903905;
        theta_reg <= 64'sd18446744073494803251;
        theta_out <= 64'sd18446744073494803251;
        i1_reg <= 64'sd0;
        i1_out <= 64'sd0;
        i2_reg <= 64'sd0;
        i2_out <= 64'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_next >= theta_next)) begin
            spike_out <= 1'b1;
            v_reg <= P_V_RESET;
            v_out <= P_V_RESET;
            theta_reg <= ((P_THETA_RESET > theta_next) ? P_THETA_RESET : theta_next);
            theta_out <= ((P_THETA_RESET > theta_next) ? P_THETA_RESET : theta_next);
            i1_reg <= (_t20 + P_CURRENT_JUMP_1);
            i1_out <= (_t20 + P_CURRENT_JUMP_1);
            i2_reg <= (_t21 + P_CURRENT_JUMP_2);
            i2_out <= (_t21 + P_CURRENT_JUMP_2);
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            theta_reg <= theta_next;
            theta_out <= theta_next;
            i1_reg <= i1_next;
            i1_out <= i1_next;
            i2_reg <= i2_next;
            i2_out <= i2_next;
        end
    end
end

endmodule
