// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = min(max(-v, v - a), 1 - v) - w + I, dw/dt = epsilon * (v - gamma * w))
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_mckeanneuron #(
    parameter signed [15:0] P_A = 16'sd64,
    parameter signed [15:0] P_EPSILON = 16'sd51,
    parameter signed [15:0] P_GAMMA = 16'sd128,
    parameter signed [15:0] P_V_PEAK = 16'sd205
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out,
    output reg signed [15:0] w_out
);

reg signed [15:0] v_reg;
reg signed [15:0] w_reg;
reg _thr_prev;

wire signed [15:0] _k1_v = (((((((-v_reg) > (v_reg - P_A)) ? (-v_reg) : (v_reg - P_A)) < (16'sd256 - v_reg)) ? (((-v_reg) > (v_reg - P_A)) ? (-v_reg) : (v_reg - P_A)) : (16'sd256 - v_reg)) - w_reg) + I_t);
wire signed [31:0] _mul0 = P_GAMMA * w_reg;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _mul1 = P_EPSILON * (v_reg - _t0);
wire signed [15:0] _t1 = (_mul1 >>> 8);
wire signed [15:0] _k1_w = _t1;
wire signed [31:0] _rk1mul_v = _k1_v * 16'sd13;
wire signed [15:0] _rk1tr_v = (_rk1mul_v >>> 8);
wire signed [15:0] _s1_v = v_reg + _rk1tr_v;
wire signed [31:0] _rk1mul_w = _k1_w * 16'sd13;
wire signed [15:0] _rk1tr_w = (_rk1mul_w >>> 8);
wire signed [15:0] _s1_w = w_reg + _rk1tr_w;
wire signed [15:0] _k2_v = (((((((-_s1_v) > (_s1_v - P_A)) ? (-_s1_v) : (_s1_v - P_A)) < (16'sd256 - _s1_v)) ? (((-_s1_v) > (_s1_v - P_A)) ? (-_s1_v) : (_s1_v - P_A)) : (16'sd256 - _s1_v)) - _s1_w) + I_t);
wire signed [31:0] _mul2 = P_GAMMA * _s1_w;
wire signed [15:0] _t2 = (_mul2 >>> 8);
wire signed [31:0] _mul3 = P_EPSILON * (_s1_v - _t2);
wire signed [15:0] _t3 = (_mul3 >>> 8);
wire signed [15:0] _k2_w = _t3;
wire signed [31:0] _rk2mul_v = _k2_v * 16'sd13;
wire signed [15:0] _rk2tr_v = (_rk2mul_v >>> 8);
wire signed [15:0] _s2_v = v_reg + _rk2tr_v;
wire signed [31:0] _rk2mul_w = _k2_w * 16'sd13;
wire signed [15:0] _rk2tr_w = (_rk2mul_w >>> 8);
wire signed [15:0] _s2_w = w_reg + _rk2tr_w;
wire signed [15:0] _k3_v = (((((((-_s2_v) > (_s2_v - P_A)) ? (-_s2_v) : (_s2_v - P_A)) < (16'sd256 - _s2_v)) ? (((-_s2_v) > (_s2_v - P_A)) ? (-_s2_v) : (_s2_v - P_A)) : (16'sd256 - _s2_v)) - _s2_w) + I_t);
wire signed [31:0] _mul4 = P_GAMMA * _s2_w;
wire signed [15:0] _t4 = (_mul4 >>> 8);
wire signed [31:0] _mul5 = P_EPSILON * (_s2_v - _t4);
wire signed [15:0] _t5 = (_mul5 >>> 8);
wire signed [15:0] _k3_w = _t5;
wire signed [31:0] _rk3mul_v = _k3_v * 16'sd26;
wire signed [15:0] _rk3tr_v = (_rk3mul_v >>> 8);
wire signed [15:0] _s3_v = v_reg + _rk3tr_v;
wire signed [31:0] _rk3mul_w = _k3_w * 16'sd26;
wire signed [15:0] _rk3tr_w = (_rk3mul_w >>> 8);
wire signed [15:0] _s3_w = w_reg + _rk3tr_w;
wire signed [15:0] _k4_v = (((((((-_s3_v) > (_s3_v - P_A)) ? (-_s3_v) : (_s3_v - P_A)) < (16'sd256 - _s3_v)) ? (((-_s3_v) > (_s3_v - P_A)) ? (-_s3_v) : (_s3_v - P_A)) : (16'sd256 - _s3_v)) - _s3_w) + I_t);
wire signed [31:0] _mul6 = P_GAMMA * _s3_w;
wire signed [15:0] _t6 = (_mul6 >>> 8);
wire signed [31:0] _mul7 = P_EPSILON * (_s3_v - _t6);
wire signed [15:0] _t7 = (_mul7 >>> 8);
wire signed [15:0] _k4_w = _t7;
wire signed [18:0] _rkw_v = _k1_v + _k2_v + _k2_v + _k3_v + _k3_v + _k4_v;
wire signed [34:0] _rk6mul_v = _rkw_v * 16'sd4;
wire signed [18:0] _rkw_w = _k1_w + _k2_w + _k2_w + _k3_w + _k3_w + _k4_w;
wire signed [34:0] _rk6mul_w = _rkw_w * 16'sd4;

wire signed [15:0] dv = (_rk6mul_v >>> 8);
wire signed [15:0] dw = (_rk6mul_w >>> 8);

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];
wire signed [16:0] w_raw = w_reg + dw;
wire signed [15:0] w_next = (w_raw > 17'sd32767) ? 16'sd32767 : (w_raw < (-17'sd32768)) ? (-16'sd32768) : w_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd0;
        v_out <= 16'sd0;
        w_reg <= 16'sd0;
        w_out <= 16'sd0;
        spike_out <= 1'b0;
        _thr_prev <= 1'b0;
    end else begin
        if (((v_next >= P_V_PEAK)) && !_thr_prev) begin
            spike_out <= 1'b1;
            v_reg <= v_next;
            w_reg <= w_next;
            v_out <= v_reg;
            w_out <= w_reg;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            w_reg <= w_next;
            w_out <= w_next;
        end
        _thr_prev <= ((v_next >= P_V_PEAK));
    end
end

endmodule
