// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron()
// Fixed-point: Q32.0 (32-bit signed)
`timescale 1ns / 1ps

module sc_mccullochpittsneuron #(
    parameter signed [31:0] P_THETA = 32'sd1
)(
    input wire clk,
    input wire rst_n,
    input wire signed [31:0] I_t,
    output reg spike_out
);





always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        spike_out <= 1'b0;
    end else begin
        if ((I_t >= P_THETA)) begin
            spike_out <= 1'b1;
        end else begin
            spike_out <= 1'b0;
        end
    end
end

endmodule
