// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = I / c_m)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_perfect_integrator #(
    parameter signed [15:0] P_C_M = 16'sd256,
    parameter signed [15:0] P_V_THRESHOLD = 16'sd256,
    parameter signed [15:0] P_V_RESET = 16'sd0
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out
);

reg signed [15:0] v_reg;

wire signed [15:0] _dop0 = I_t;
wire signed [15:0] _dden0 = P_C_M;
wire signed [31:0] _dnum0 = $signed({{16{_dop0[15]}}, _dop0}) <<< 8;
wire signed [31:0] _div0 = _dnum0 / $signed({{16{_dden0[15]}}, _dden0});
wire signed [15:0] _dres0 = _div0[15:0];
wire signed [31:0] _dt_mul_v = (_dres0) * 16'sd26;
wire signed [15:0] _dt_trunc_v = (_dt_mul_v >>> 8);

wire signed [15:0] dv = _dt_trunc_v;

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd0;
        v_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_next >= P_V_THRESHOLD)) begin
            spike_out <= 1'b1;
            v_reg <= P_V_RESET;
            v_out <= v_reg;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
        end
    end
end

endmodule
