// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = v**2 + I)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_quadratic_if #(
    parameter signed [15:0] P_V_RESET = 16'sd65280,
    parameter signed [15:0] P_V_PEAK = 16'sd256
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out
);

reg signed [15:0] v_reg;

wire signed [31:0] _mul0 = v_reg * v_reg;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _dt_mul_v = ((_t0 + I_t)) * 16'sd3;
wire signed [15:0] _dt_trunc_v = (_dt_mul_v >>> 8);

wire signed [15:0] dv = _dt_trunc_v;

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd65280;
        v_out <= 16'sd65280;
        spike_out <= 1'b0;
    end else begin
        if ((v_next >= P_V_PEAK)) begin
            spike_out <= 1'b1;
            v_reg <= (-16'sd256);
            v_out <= (-16'sd256);
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
        end
    end
end

endmodule
