// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dx/dt = (alpha / (1.0 - x) + y + I) if x <= 0 else (alpha + y + I if x < alpha + y + I else -1.0), dy/dt = y - mu * (x + 1.0) + mu * sigma)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_rulkov_map #(
    parameter signed [15:0] P_ALPHA = 16'sd1024,
    parameter signed [15:0] P_SIGMA = 16'sd65126,
    parameter signed [15:0] P_MU = 16'sd0
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] x_out,
    output reg signed [15:0] y_out
);

reg signed [15:0] x_reg;
reg signed [15:0] y_reg;
reg _thr_prev;

wire signed [15:0] _dop0 = P_ALPHA;
wire signed [15:0] _dden0 = (16'sd256 - x_reg);
wire signed [31:0] _dnum0 = $signed({{16{_dop0[15]}}, _dop0}) <<< 8;
wire signed [31:0] _div0 = _dnum0 / $signed({{16{_dden0[15]}}, _dden0});
wire signed [15:0] _dres0 = _div0[15:0];
wire signed [31:0] _mul1 = P_MU * (x_reg + 16'sd256);
wire signed [15:0] _t0 = (_mul1 >>> 8);
wire signed [31:0] _mul2 = P_MU * P_SIGMA;
wire signed [15:0] _t1 = (_mul2 >>> 8);

wire signed [15:0] dx = (((x_reg <= 16'sd0)) ? (((_dres0 + y_reg) + I_t)) : ((((x_reg < ((P_ALPHA + y_reg) + I_t))) ? (((P_ALPHA + y_reg) + I_t)) : ((-16'sd256)))));
wire signed [15:0] dy = ((y_reg - _t0) + _t1);

wire signed [16:0] x_raw = dx;
wire signed [15:0] x_next = (x_raw > 17'sd32767) ? 16'sd32767 : (x_raw < (-17'sd32768)) ? (-16'sd32768) : x_raw[15:0];
wire signed [16:0] y_raw = dy;
wire signed [15:0] y_next = (y_raw > 17'sd32767) ? 16'sd32767 : (y_raw < (-17'sd32768)) ? (-16'sd32768) : y_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        x_reg <= 16'sd65280;
        x_out <= 16'sd65280;
        y_reg <= 16'sd64768;
        y_out <= 16'sd64768;
        spike_out <= 1'b0;
        _thr_prev <= 1'b0;
    end else begin
        if (((x_next >= 16'sd0)) && !_thr_prev) begin
            spike_out <= 1'b1;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
        end else begin
            spike_out <= 1'b0;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
        end
        _thr_prev <= ((x_next >= 16'sd0));
    end
end

endmodule
