// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = -(17.81 + 47.71 * v + 32.63 * v * v) * (v - 0.55) - 26.0 * r * (v + 0.92) + I, dr/dt = (-r + 1.35 * v + 1.03) / tau_r)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_resetting_wilson_hr #(
    parameter signed [15:0] P_TAU_R = 16'sd486,
    parameter signed [15:0] P_V_PEAK = 16'sd102
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out,
    output reg signed [15:0] r_out
);

reg signed [15:0] v_reg;
reg signed [15:0] r_reg;

wire signed [31:0] _mul0 = 16'sd12214 * v_reg;
wire signed [15:0] _t0 = (_mul0 >>> 8);
wire signed [31:0] _mul1 = 16'sd8353 * v_reg;
wire signed [15:0] _t1 = (_mul1 >>> 8);
wire signed [31:0] _mul2 = _t1 * v_reg;
wire signed [15:0] _t2 = (_mul2 >>> 8);
wire signed [31:0] _mul3 = (-((16'sd4559 + _t0) + _t2)) * (v_reg - 16'sd141);
wire signed [15:0] _t3 = (_mul3 >>> 8);
wire signed [31:0] _mul4 = 16'sd6656 * r_reg;
wire signed [15:0] _t4 = (_mul4 >>> 8);
wire signed [31:0] _mul5 = _t4 * (v_reg + 16'sd236);
wire signed [15:0] _t5 = (_mul5 >>> 8);
wire signed [15:0] _k1_v = ((_t3 - _t5) + I_t);
wire signed [31:0] _mul6 = 16'sd346 * v_reg;
wire signed [15:0] _t6 = (_mul6 >>> 8);
wire signed [15:0] _dop7 = (((-r_reg) + _t6) + 16'sd264);
wire signed [15:0] _dden7 = P_TAU_R;
wire signed [31:0] _dnum7 = $signed({{16{_dop7[15]}}, _dop7}) <<< 8;
wire signed [31:0] _div7 = _dnum7 / $signed({{16{_dden7[15]}}, _dden7});
wire signed [15:0] _dres7 = _div7[15:0];
wire signed [15:0] _k1_r = _dres7;
wire signed [31:0] _rk1mul_v = _k1_v * 16'sd6;
wire signed [15:0] _rk1tr_v = (_rk1mul_v >>> 8);
wire signed [15:0] _s1_v = v_reg + _rk1tr_v;
wire signed [31:0] _rk1mul_r = _k1_r * 16'sd6;
wire signed [15:0] _rk1tr_r = (_rk1mul_r >>> 8);
wire signed [15:0] _s1_r = r_reg + _rk1tr_r;
wire signed [31:0] _mul8 = 16'sd12214 * _s1_v;
wire signed [15:0] _t7 = (_mul8 >>> 8);
wire signed [31:0] _mul9 = 16'sd8353 * _s1_v;
wire signed [15:0] _t8 = (_mul9 >>> 8);
wire signed [31:0] _mul10 = _t8 * _s1_v;
wire signed [15:0] _t9 = (_mul10 >>> 8);
wire signed [31:0] _mul11 = (-((16'sd4559 + _t7) + _t9)) * (_s1_v - 16'sd141);
wire signed [15:0] _t10 = (_mul11 >>> 8);
wire signed [31:0] _mul12 = 16'sd6656 * _s1_r;
wire signed [15:0] _t11 = (_mul12 >>> 8);
wire signed [31:0] _mul13 = _t11 * (_s1_v + 16'sd236);
wire signed [15:0] _t12 = (_mul13 >>> 8);
wire signed [15:0] _k2_v = ((_t10 - _t12) + I_t);
wire signed [31:0] _mul14 = 16'sd346 * _s1_v;
wire signed [15:0] _t13 = (_mul14 >>> 8);
wire signed [15:0] _dop15 = (((-_s1_r) + _t13) + 16'sd264);
wire signed [15:0] _dden15 = P_TAU_R;
wire signed [31:0] _dnum15 = $signed({{16{_dop15[15]}}, _dop15}) <<< 8;
wire signed [31:0] _div15 = _dnum15 / $signed({{16{_dden15[15]}}, _dden15});
wire signed [15:0] _dres15 = _div15[15:0];
wire signed [15:0] _k2_r = _dres15;
wire signed [31:0] _rk2mul_v = _k2_v * 16'sd6;
wire signed [15:0] _rk2tr_v = (_rk2mul_v >>> 8);
wire signed [15:0] _s2_v = v_reg + _rk2tr_v;
wire signed [31:0] _rk2mul_r = _k2_r * 16'sd6;
wire signed [15:0] _rk2tr_r = (_rk2mul_r >>> 8);
wire signed [15:0] _s2_r = r_reg + _rk2tr_r;
wire signed [31:0] _mul16 = 16'sd12214 * _s2_v;
wire signed [15:0] _t14 = (_mul16 >>> 8);
wire signed [31:0] _mul17 = 16'sd8353 * _s2_v;
wire signed [15:0] _t15 = (_mul17 >>> 8);
wire signed [31:0] _mul18 = _t15 * _s2_v;
wire signed [15:0] _t16 = (_mul18 >>> 8);
wire signed [31:0] _mul19 = (-((16'sd4559 + _t14) + _t16)) * (_s2_v - 16'sd141);
wire signed [15:0] _t17 = (_mul19 >>> 8);
wire signed [31:0] _mul20 = 16'sd6656 * _s2_r;
wire signed [15:0] _t18 = (_mul20 >>> 8);
wire signed [31:0] _mul21 = _t18 * (_s2_v + 16'sd236);
wire signed [15:0] _t19 = (_mul21 >>> 8);
wire signed [15:0] _k3_v = ((_t17 - _t19) + I_t);
wire signed [31:0] _mul22 = 16'sd346 * _s2_v;
wire signed [15:0] _t20 = (_mul22 >>> 8);
wire signed [15:0] _dop23 = (((-_s2_r) + _t20) + 16'sd264);
wire signed [15:0] _dden23 = P_TAU_R;
wire signed [31:0] _dnum23 = $signed({{16{_dop23[15]}}, _dop23}) <<< 8;
wire signed [31:0] _div23 = _dnum23 / $signed({{16{_dden23[15]}}, _dden23});
wire signed [15:0] _dres23 = _div23[15:0];
wire signed [15:0] _k3_r = _dres23;
wire signed [31:0] _rk3mul_v = _k3_v * 16'sd13;
wire signed [15:0] _rk3tr_v = (_rk3mul_v >>> 8);
wire signed [15:0] _s3_v = v_reg + _rk3tr_v;
wire signed [31:0] _rk3mul_r = _k3_r * 16'sd13;
wire signed [15:0] _rk3tr_r = (_rk3mul_r >>> 8);
wire signed [15:0] _s3_r = r_reg + _rk3tr_r;
wire signed [31:0] _mul24 = 16'sd12214 * _s3_v;
wire signed [15:0] _t21 = (_mul24 >>> 8);
wire signed [31:0] _mul25 = 16'sd8353 * _s3_v;
wire signed [15:0] _t22 = (_mul25 >>> 8);
wire signed [31:0] _mul26 = _t22 * _s3_v;
wire signed [15:0] _t23 = (_mul26 >>> 8);
wire signed [31:0] _mul27 = (-((16'sd4559 + _t21) + _t23)) * (_s3_v - 16'sd141);
wire signed [15:0] _t24 = (_mul27 >>> 8);
wire signed [31:0] _mul28 = 16'sd6656 * _s3_r;
wire signed [15:0] _t25 = (_mul28 >>> 8);
wire signed [31:0] _mul29 = _t25 * (_s3_v + 16'sd236);
wire signed [15:0] _t26 = (_mul29 >>> 8);
wire signed [15:0] _k4_v = ((_t24 - _t26) + I_t);
wire signed [31:0] _mul30 = 16'sd346 * _s3_v;
wire signed [15:0] _t27 = (_mul30 >>> 8);
wire signed [15:0] _dop31 = (((-_s3_r) + _t27) + 16'sd264);
wire signed [15:0] _dden31 = P_TAU_R;
wire signed [31:0] _dnum31 = $signed({{16{_dop31[15]}}, _dop31}) <<< 8;
wire signed [31:0] _div31 = _dnum31 / $signed({{16{_dden31[15]}}, _dden31});
wire signed [15:0] _dres31 = _div31[15:0];
wire signed [15:0] _k4_r = _dres31;
wire signed [18:0] _rkw_v = _k1_v + _k2_v + _k2_v + _k3_v + _k3_v + _k4_v;
wire signed [34:0] _rk6mul_v = _rkw_v * 16'sd2;
wire signed [18:0] _rkw_r = _k1_r + _k2_r + _k2_r + _k3_r + _k3_r + _k4_r;
wire signed [34:0] _rk6mul_r = _rkw_r * 16'sd2;

wire signed [15:0] dv = (_rk6mul_v >>> 8);
wire signed [15:0] dr = (_rk6mul_r >>> 8);

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < (-17'sd32768)) ? (-16'sd32768) : v_raw[15:0];
wire signed [16:0] r_raw = r_reg + dr;
wire signed [15:0] r_next = (r_raw > 17'sd32767) ? 16'sd32767 : (r_raw < (-17'sd32768)) ? (-16'sd32768) : r_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd65357;
        v_out <= 16'sd65357;
        r_reg <= 16'sd26;
        r_out <= 16'sd26;
        spike_out <= 1'b0;
    end else begin
        if ((v_next >= P_V_PEAK)) begin
            spike_out <= 1'b1;
            v_reg <= (-16'sd179);
            v_out <= (-16'sd179);
            r_reg <= r_next;
            r_out <= r_next;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            r_reg <= r_next;
            r_out <= r_next;
        end
    end
end

endmodule
