// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = (-(v - v_rest) + i1 + i2 + I) / tau_v, dtheta/dt = (theta_inf - theta + a * (v - v_rest)) / tau_theta, di1/dt = -i1 / tau_1, di2/dt = -i2 / tau_2)
// Fixed-point: Q16.16 (32-bit signed)
`timescale 1ns / 1ps

module sc_scaled_reset_adaptive_if #(
    parameter signed [31:0] P_V_REST = 32'sd0,
    parameter signed [31:0] P_V_RESET = 32'sd0,
    parameter signed [31:0] P_THETA_RESET = 32'sd85197,
    parameter signed [31:0] P_THETA_INF = 32'sd65536,
    parameter signed [31:0] P_TAU_V = 32'sd655360,
    parameter signed [31:0] P_TAU_THETA = 32'sd2621440,
    parameter signed [31:0] P_TAU_1 = 32'sd983040,
    parameter signed [31:0] P_TAU_2 = 32'sd5242880,
    parameter signed [31:0] P_A = 32'sd6554,
    parameter signed [31:0] P_B = 32'sd6554,
    parameter signed [31:0] P_R1 = 32'sd13107,
    parameter signed [31:0] P_R2 = 32'sd4294957466
)(
    input wire clk,
    input wire rst_n,
    input wire signed [31:0] I_t,
    output reg spike_out,
    output reg signed [31:0] v_out,
    output reg signed [31:0] theta_out,
    output reg signed [31:0] i1_out,
    output reg signed [31:0] i2_out
);

reg signed [31:0] v_reg;
reg signed [31:0] theta_reg;
reg signed [31:0] i1_reg;
reg signed [31:0] i2_reg;

wire signed [31:0] _dop0 = ((((-(v_reg - P_V_REST)) + i1_reg) + i2_reg) + I_t);
wire signed [31:0] _dden0 = P_TAU_V;
wire signed [63:0] _dnum0 = $signed({{32{_dop0[31]}}, _dop0}) <<< 16;
wire signed [63:0] _div0 = _dnum0 / $signed({{32{_dden0[31]}}, _dden0});
wire signed [31:0] _dres0 = _div0[31:0];
wire signed [31:0] _k1_v = _dres0;
wire signed [63:0] _mul1 = P_A * (v_reg - P_V_REST);
wire signed [31:0] _t0 = (_mul1 >>> 16);
wire signed [31:0] _dop2 = ((P_THETA_INF - theta_reg) + _t0);
wire signed [31:0] _dden2 = P_TAU_THETA;
wire signed [63:0] _dnum2 = $signed({{32{_dop2[31]}}, _dop2}) <<< 16;
wire signed [63:0] _div2 = _dnum2 / $signed({{32{_dden2[31]}}, _dden2});
wire signed [31:0] _dres2 = _div2[31:0];
wire signed [31:0] _k1_theta = _dres2;
wire signed [31:0] _dop3 = (-i1_reg);
wire signed [31:0] _dden3 = P_TAU_1;
wire signed [63:0] _dnum3 = $signed({{32{_dop3[31]}}, _dop3}) <<< 16;
wire signed [63:0] _div3 = _dnum3 / $signed({{32{_dden3[31]}}, _dden3});
wire signed [31:0] _dres3 = _div3[31:0];
wire signed [31:0] _k1_i1 = _dres3;
wire signed [31:0] _dop4 = (-i2_reg);
wire signed [31:0] _dden4 = P_TAU_2;
wire signed [63:0] _dnum4 = $signed({{32{_dop4[31]}}, _dop4}) <<< 16;
wire signed [63:0] _div4 = _dnum4 / $signed({{32{_dden4[31]}}, _dden4});
wire signed [31:0] _dres4 = _div4[31:0];
wire signed [31:0] _k1_i2 = _dres4;
wire signed [63:0] _rk1mul_v = _k1_v * 32'sd32768;
wire signed [31:0] _rk1tr_v = (_rk1mul_v >>> 16);
wire signed [31:0] _s1_v = v_reg + _rk1tr_v;
wire signed [63:0] _rk1mul_theta = _k1_theta * 32'sd32768;
wire signed [31:0] _rk1tr_theta = (_rk1mul_theta >>> 16);
wire signed [31:0] _s1_theta = theta_reg + _rk1tr_theta;
wire signed [63:0] _rk1mul_i1 = _k1_i1 * 32'sd32768;
wire signed [31:0] _rk1tr_i1 = (_rk1mul_i1 >>> 16);
wire signed [31:0] _s1_i1 = i1_reg + _rk1tr_i1;
wire signed [63:0] _rk1mul_i2 = _k1_i2 * 32'sd32768;
wire signed [31:0] _rk1tr_i2 = (_rk1mul_i2 >>> 16);
wire signed [31:0] _s1_i2 = i2_reg + _rk1tr_i2;
wire signed [31:0] _dop5 = ((((-(_s1_v - P_V_REST)) + _s1_i1) + _s1_i2) + I_t);
wire signed [31:0] _dden5 = P_TAU_V;
wire signed [63:0] _dnum5 = $signed({{32{_dop5[31]}}, _dop5}) <<< 16;
wire signed [63:0] _div5 = _dnum5 / $signed({{32{_dden5[31]}}, _dden5});
wire signed [31:0] _dres5 = _div5[31:0];
wire signed [31:0] _k2_v = _dres5;
wire signed [63:0] _mul6 = P_A * (_s1_v - P_V_REST);
wire signed [31:0] _t1 = (_mul6 >>> 16);
wire signed [31:0] _dop7 = ((P_THETA_INF - _s1_theta) + _t1);
wire signed [31:0] _dden7 = P_TAU_THETA;
wire signed [63:0] _dnum7 = $signed({{32{_dop7[31]}}, _dop7}) <<< 16;
wire signed [63:0] _div7 = _dnum7 / $signed({{32{_dden7[31]}}, _dden7});
wire signed [31:0] _dres7 = _div7[31:0];
wire signed [31:0] _k2_theta = _dres7;
wire signed [31:0] _dop8 = (-_s1_i1);
wire signed [31:0] _dden8 = P_TAU_1;
wire signed [63:0] _dnum8 = $signed({{32{_dop8[31]}}, _dop8}) <<< 16;
wire signed [63:0] _div8 = _dnum8 / $signed({{32{_dden8[31]}}, _dden8});
wire signed [31:0] _dres8 = _div8[31:0];
wire signed [31:0] _k2_i1 = _dres8;
wire signed [31:0] _dop9 = (-_s1_i2);
wire signed [31:0] _dden9 = P_TAU_2;
wire signed [63:0] _dnum9 = $signed({{32{_dop9[31]}}, _dop9}) <<< 16;
wire signed [63:0] _div9 = _dnum9 / $signed({{32{_dden9[31]}}, _dden9});
wire signed [31:0] _dres9 = _div9[31:0];
wire signed [31:0] _k2_i2 = _dres9;
wire signed [63:0] _rk2mul_v = _k2_v * 32'sd32768;
wire signed [31:0] _rk2tr_v = (_rk2mul_v >>> 16);
wire signed [31:0] _s2_v = v_reg + _rk2tr_v;
wire signed [63:0] _rk2mul_theta = _k2_theta * 32'sd32768;
wire signed [31:0] _rk2tr_theta = (_rk2mul_theta >>> 16);
wire signed [31:0] _s2_theta = theta_reg + _rk2tr_theta;
wire signed [63:0] _rk2mul_i1 = _k2_i1 * 32'sd32768;
wire signed [31:0] _rk2tr_i1 = (_rk2mul_i1 >>> 16);
wire signed [31:0] _s2_i1 = i1_reg + _rk2tr_i1;
wire signed [63:0] _rk2mul_i2 = _k2_i2 * 32'sd32768;
wire signed [31:0] _rk2tr_i2 = (_rk2mul_i2 >>> 16);
wire signed [31:0] _s2_i2 = i2_reg + _rk2tr_i2;
wire signed [31:0] _dop10 = ((((-(_s2_v - P_V_REST)) + _s2_i1) + _s2_i2) + I_t);
wire signed [31:0] _dden10 = P_TAU_V;
wire signed [63:0] _dnum10 = $signed({{32{_dop10[31]}}, _dop10}) <<< 16;
wire signed [63:0] _div10 = _dnum10 / $signed({{32{_dden10[31]}}, _dden10});
wire signed [31:0] _dres10 = _div10[31:0];
wire signed [31:0] _k3_v = _dres10;
wire signed [63:0] _mul11 = P_A * (_s2_v - P_V_REST);
wire signed [31:0] _t2 = (_mul11 >>> 16);
wire signed [31:0] _dop12 = ((P_THETA_INF - _s2_theta) + _t2);
wire signed [31:0] _dden12 = P_TAU_THETA;
wire signed [63:0] _dnum12 = $signed({{32{_dop12[31]}}, _dop12}) <<< 16;
wire signed [63:0] _div12 = _dnum12 / $signed({{32{_dden12[31]}}, _dden12});
wire signed [31:0] _dres12 = _div12[31:0];
wire signed [31:0] _k3_theta = _dres12;
wire signed [31:0] _dop13 = (-_s2_i1);
wire signed [31:0] _dden13 = P_TAU_1;
wire signed [63:0] _dnum13 = $signed({{32{_dop13[31]}}, _dop13}) <<< 16;
wire signed [63:0] _div13 = _dnum13 / $signed({{32{_dden13[31]}}, _dden13});
wire signed [31:0] _dres13 = _div13[31:0];
wire signed [31:0] _k3_i1 = _dres13;
wire signed [31:0] _dop14 = (-_s2_i2);
wire signed [31:0] _dden14 = P_TAU_2;
wire signed [63:0] _dnum14 = $signed({{32{_dop14[31]}}, _dop14}) <<< 16;
wire signed [63:0] _div14 = _dnum14 / $signed({{32{_dden14[31]}}, _dden14});
wire signed [31:0] _dres14 = _div14[31:0];
wire signed [31:0] _k3_i2 = _dres14;
wire signed [63:0] _rk3mul_v = _k3_v * 32'sd65536;
wire signed [31:0] _rk3tr_v = (_rk3mul_v >>> 16);
wire signed [31:0] _s3_v = v_reg + _rk3tr_v;
wire signed [63:0] _rk3mul_theta = _k3_theta * 32'sd65536;
wire signed [31:0] _rk3tr_theta = (_rk3mul_theta >>> 16);
wire signed [31:0] _s3_theta = theta_reg + _rk3tr_theta;
wire signed [63:0] _rk3mul_i1 = _k3_i1 * 32'sd65536;
wire signed [31:0] _rk3tr_i1 = (_rk3mul_i1 >>> 16);
wire signed [31:0] _s3_i1 = i1_reg + _rk3tr_i1;
wire signed [63:0] _rk3mul_i2 = _k3_i2 * 32'sd65536;
wire signed [31:0] _rk3tr_i2 = (_rk3mul_i2 >>> 16);
wire signed [31:0] _s3_i2 = i2_reg + _rk3tr_i2;
wire signed [31:0] _dop15 = ((((-(_s3_v - P_V_REST)) + _s3_i1) + _s3_i2) + I_t);
wire signed [31:0] _dden15 = P_TAU_V;
wire signed [63:0] _dnum15 = $signed({{32{_dop15[31]}}, _dop15}) <<< 16;
wire signed [63:0] _div15 = _dnum15 / $signed({{32{_dden15[31]}}, _dden15});
wire signed [31:0] _dres15 = _div15[31:0];
wire signed [31:0] _k4_v = _dres15;
wire signed [63:0] _mul16 = P_A * (_s3_v - P_V_REST);
wire signed [31:0] _t3 = (_mul16 >>> 16);
wire signed [31:0] _dop17 = ((P_THETA_INF - _s3_theta) + _t3);
wire signed [31:0] _dden17 = P_TAU_THETA;
wire signed [63:0] _dnum17 = $signed({{32{_dop17[31]}}, _dop17}) <<< 16;
wire signed [63:0] _div17 = _dnum17 / $signed({{32{_dden17[31]}}, _dden17});
wire signed [31:0] _dres17 = _div17[31:0];
wire signed [31:0] _k4_theta = _dres17;
wire signed [31:0] _dop18 = (-_s3_i1);
wire signed [31:0] _dden18 = P_TAU_1;
wire signed [63:0] _dnum18 = $signed({{32{_dop18[31]}}, _dop18}) <<< 16;
wire signed [63:0] _div18 = _dnum18 / $signed({{32{_dden18[31]}}, _dden18});
wire signed [31:0] _dres18 = _div18[31:0];
wire signed [31:0] _k4_i1 = _dres18;
wire signed [31:0] _dop19 = (-_s3_i2);
wire signed [31:0] _dden19 = P_TAU_2;
wire signed [63:0] _dnum19 = $signed({{32{_dop19[31]}}, _dop19}) <<< 16;
wire signed [63:0] _div19 = _dnum19 / $signed({{32{_dden19[31]}}, _dden19});
wire signed [31:0] _dres19 = _div19[31:0];
wire signed [31:0] _k4_i2 = _dres19;
wire signed [34:0] _rkw_v = _k1_v + _k2_v + _k2_v + _k3_v + _k3_v + _k4_v;
wire signed [66:0] _rk6mul_v = _rkw_v * 32'sd10923;
wire signed [34:0] _rkw_theta = _k1_theta + _k2_theta + _k2_theta + _k3_theta + _k3_theta + _k4_theta;
wire signed [66:0] _rk6mul_theta = _rkw_theta * 32'sd10923;
wire signed [34:0] _rkw_i1 = _k1_i1 + _k2_i1 + _k2_i1 + _k3_i1 + _k3_i1 + _k4_i1;
wire signed [66:0] _rk6mul_i1 = _rkw_i1 * 32'sd10923;
wire signed [34:0] _rkw_i2 = _k1_i2 + _k2_i2 + _k2_i2 + _k3_i2 + _k3_i2 + _k4_i2;
wire signed [66:0] _rk6mul_i2 = _rkw_i2 * 32'sd10923;
wire signed [63:0] _mul20 = P_B * (v_next - P_V_REST);
wire signed [31:0] _t4 = (_mul20 >>> 16);

wire signed [31:0] dv = (_rk6mul_v >>> 16);
wire signed [31:0] dtheta = (_rk6mul_theta >>> 16);
wire signed [31:0] di1 = (_rk6mul_i1 >>> 16);
wire signed [31:0] di2 = (_rk6mul_i2 >>> 16);

wire signed [32:0] v_raw = v_reg + dv;
wire signed [31:0] v_next = (v_raw > 33'sd2147483647) ? 32'sd2147483647 : (v_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : v_raw[31:0];
wire signed [32:0] theta_raw = theta_reg + dtheta;
wire signed [31:0] theta_next = (theta_raw > 33'sd2147483647) ? 32'sd2147483647 : (theta_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : theta_raw[31:0];
wire signed [32:0] i1_raw = i1_reg + di1;
wire signed [31:0] i1_next = (i1_raw > 33'sd2147483647) ? 32'sd2147483647 : (i1_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : i1_raw[31:0];
wire signed [32:0] i2_raw = i2_reg + di2;
wire signed [31:0] i2_next = (i2_raw > 33'sd2147483647) ? 32'sd2147483647 : (i2_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : i2_raw[31:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 32'sd0;
        v_out <= 32'sd0;
        theta_reg <= 32'sd65536;
        theta_out <= 32'sd65536;
        i1_reg <= 32'sd0;
        i1_out <= 32'sd0;
        i2_reg <= 32'sd0;
        i2_out <= 32'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_next >= theta_next)) begin
            spike_out <= 1'b1;
            v_reg <= (P_V_RESET + _t4);
            v_out <= (P_V_RESET + _t4);
            theta_reg <= ((theta_next > P_THETA_RESET) ? theta_next : P_THETA_RESET);
            theta_out <= ((theta_next > P_THETA_RESET) ? theta_next : P_THETA_RESET);
            i1_reg <= (i1_next + P_R1);
            i1_out <= (i1_next + P_R1);
            i2_reg <= (i2_next + P_R2);
            i2_out <= (i2_next + P_R2);
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
            theta_reg <= theta_next;
            theta_out <= theta_next;
            i1_reg <= i1_next;
            i1_out <= i1_next;
            i2_reg <= i2_next;
            i2_out <= i2_next;
        end
    end
end

endmodule
