// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Generated fixed-point RTL
// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dx/dt = (alpha / (1.0 - x) + y + I) if x <= 0 else (alpha + y + I if x < alpha + y + I else -1.0), dy/dt = y - mu * (x + 1.0) + mu * sigma)
// Fixed-point: Q16.16 (32-bit signed)
`timescale 1ns / 1ps

module sc_upward_crossing_rulkov_map #(
    parameter signed [31:0] P_ALPHA = 32'sd262144,
    parameter signed [31:0] P_SIGMA = 32'sd4294862438,
    parameter signed [31:0] P_MU = 32'sd66,
    parameter signed [31:0] P_X_THRESHOLD = 32'sd0
)(
    input wire clk,
    input wire rst_n,
    input wire signed [31:0] I_t,
    output reg spike_out,
    output reg signed [31:0] x_out,
    output reg signed [31:0] y_out
);

reg signed [31:0] x_reg;
reg signed [31:0] y_reg;
reg _thr_prev;

wire signed [31:0] _dop0 = P_ALPHA;
wire signed [31:0] _dden0 = (32'sd65536 - x_reg);
wire signed [63:0] _dnum0 = $signed({{32{_dop0[31]}}, _dop0}) <<< 16;
wire signed [63:0] _div0 = _dnum0 / $signed({{32{_dden0[31]}}, _dden0});
wire signed [31:0] _dres0 = _div0[31:0];
wire signed [63:0] _mul1 = P_MU * (x_reg + 32'sd65536);
wire signed [31:0] _t0 = (_mul1 >>> 16);
wire signed [63:0] _mul2 = P_MU * P_SIGMA;
wire signed [31:0] _t1 = (_mul2 >>> 16);

wire signed [31:0] dx = (((x_reg <= 32'sd0)) ? (((_dres0 + y_reg) + I_t)) : ((((x_reg < ((P_ALPHA + y_reg) + I_t))) ? (((P_ALPHA + y_reg) + I_t)) : ((-32'sd65536)))));
wire signed [31:0] dy = ((y_reg - _t0) + _t1);

wire signed [32:0] x_raw = dx;
wire signed [31:0] x_next = (x_raw > 33'sd2147483647) ? 32'sd2147483647 : (x_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : x_raw[31:0];
wire signed [32:0] y_raw = dy;
wire signed [31:0] y_next = (y_raw > 33'sd2147483647) ? 32'sd2147483647 : (y_raw < (-33'sd2147483648)) ? (-32'sd2147483648) : y_raw[31:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        x_reg <= 32'sd4294901760;
        x_out <= 32'sd4294901760;
        y_reg <= 32'sd4294770688;
        y_out <= 32'sd4294770688;
        spike_out <= 1'b0;
        _thr_prev <= 1'b0;
    end else begin
        if (((x_next >= P_X_THRESHOLD)) && !_thr_prev) begin
            spike_out <= 1'b1;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
        end else begin
            spike_out <= 1'b0;
            x_reg <= x_next;
            x_out <= x_next;
            y_reg <= y_next;
            y_out <= y_next;
        end
        _thr_prev <= ((x_next >= P_X_THRESHOLD));
    end
end

endmodule
