# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# Copyright (c) Concepts 1996-2026 Miroslav Sotek. All rights reserved.
# Copyright (c) Code 2020-2026 Miroslav Sotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore - TestVerilogSyntax from former test_equation_compiler.py

"""Focused suite: TestVerilogSyntax from former test_equation_compiler.py."""

from __future__ import annotations

from tests.equation_compiler_support import *  # noqa: F403

class TestVerilogSyntax:
    def test_module_structure(self):
        _, verilog = equation_to_fpga(
            "dv/dt = I",
            init={"v": 0.0},
            module_name="syntax_check",
        )
        # Check module/endmodule
        assert verilog.count("endmodule") == 1
        # begin/end balance (endmodule contains "end", so subtract 1)
        assert verilog.count("begin") == verilog.count("end") - 1
        # Has timescale
        assert "`timescale" in verilog
        # Has always block
        assert "always @(posedge clk" in verilog

    def test_auto_generated_comment(self):
        _, verilog = equation_to_fpga(
            "dv/dt = I",
            init={"v": 0.0},
        )
        assert "Auto-generated by SC-NeuroCore" in verilog

    def test_custom_data_width(self):
        neuron = EquationNeuron(
            equations={"v": "I"},
            state={"v": 0.0},
            dt=1.0,
        )
        verilog = compile_to_verilog(neuron, data_width=32, fraction=16)
        assert "[31:0]" in verilog
