# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore - Focused free-test suite (emitter_inventory) from former test_catalogue_formal.py

from __future__ import annotations

from tests.catalogue_formal_support import *  # noqa: F403


def test_emitter_lists_every_perfect_model() -> None:
    """Emitter CLASS_TO_SCHEMA must cover every live dual-axis perfect class."""
    import importlib.util
    import sys

    name = "emit_catalogue_formal"
    spec = importlib.util.spec_from_file_location(name, EMITTER)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    # Dataclass evaluation requires the module to be registered first.
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    perfect = _perfect_class_names()
    mapped = set(mod.CLASS_TO_SCHEMA)
    missing = perfect - mapped
    assert not missing, f"perfect models missing from formal emitter: {sorted(missing)}"


def test_catalogue_formal_inventory_matches_perfect_count() -> None:
    """Committed catalogue jobs equal the number of dual-axis perfect models."""
    sby_jobs = sorted(CATALOGUE.glob("*.sby"))
    assert CATALOGUE.is_dir(), "hdl/formal/catalogue missing — run emit_catalogue_formal.py"
    assert len(sby_jobs) == len(_perfect_class_names())
    for sby in sby_jobs:
        module = sby.stem
        assert (CATALOGUE / f"{module}.v").is_file(), f"missing RTL for {module}"
        assert (CATALOGUE / f"{module}_formal.v").is_file(), f"missing harness for {module}"
        text = sby.read_text(encoding="utf-8")
        assert "mode bmc" in text
        assert "smtbmc z3" in text


def test_catalogue_formal_rtl_is_equation_compiler_output() -> None:
    """Each RTL file is equation-compiler generated (not empty stub)."""
    for rtl in sorted(CATALOGUE.glob("sc_*.v")):
        if rtl.name.endswith("_formal.v"):
            continue
        text = rtl.read_text(encoding="utf-8")
        assert "Auto-generated by SC-NeuroCore equation compiler" in text
        assert "module " in text
        assert "spike_out" in text
