# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Wilson-HR independent reference contract

"""Independent reference-trace parity for Wilson-HR."""

from __future__ import annotations

import hashlib
import json
import struct
from collections.abc import Callable
from pathlib import Path

import pytest

from sc_neurocore.neurons.models.sc_resetting_wilson_hr import SCResettingWilsonHRNeuron
from sc_neurocore.neurons.reference_traces import ReferenceTraceSpec, load_reference_trace_spec
from tests.cosim_reference_wilson_hr import (
    _sc_resetting_wilson_hr_rk4_features,
    _wilson_hr_rk4_features,
)


_PARITY_CASES: list[tuple[str, str, str, str, Callable[[ReferenceTraceSpec], dict[str, float]]]] = [
    (
        "wilson_hr_driven_spiking_doi",
        "wilson_hr",
        "independent_rk4_reference",
        "doi:10.1006/jtbi.1999.1002",
        lambda spec: _wilson_hr_rk4_features(
            current=spec.protocol.inputs["I"], dt=spec.protocol.dt, steps=spec.protocol.steps
        ),
    ),
    (
        "sc_resetting_wilson_hr_project",
        "sc_resetting_wilson_hr",
        "independent_rk4_reference",
        "SC-NeuroCore project recurrence",
        lambda spec: _sc_resetting_wilson_hr_rk4_features(
            current=spec.protocol.inputs["I"], dt=spec.protocol.dt, steps=spec.protocol.steps
        ),
    ),
]


@pytest.mark.parametrize(
    ("trace_name", "schema_name", "kind", "citation", "reference"),
    _PARITY_CASES,
    ids=[case[1] for case in _PARITY_CASES],
)
def test_trace_features_match_independent_reference(
    trace_name: str,
    schema_name: str,
    kind: str,
    citation: str,
    reference: Callable[[ReferenceTraceSpec], dict[str, float]],
) -> None:
    """Each committed trace must reproduce an independent re-derivation to ``1e-12``.

    The per-case ``reference`` callable recomputes the expected feature map from the
    model's maintained RK4 equations without importing its production class, so a
    passing assertion proves the committed corpus is independently reproduced rather
    than regenerated by the schema runner itself. The committed feature set must match
    the reference set exactly and every value to ``1e-12``.
    """
    spec = load_reference_trace_spec(trace_name)

    expected = reference(spec)

    assert spec.schema_name == schema_name
    assert spec.provenance.kind == kind
    assert spec.provenance.citation == citation
    assert set(expected) == set(spec.expected_features)
    for feature_name, feature_value in expected.items():
        assert spec.expected_features[feature_name] == pytest.approx(feature_value, abs=1e-12)


def test_retained_sc_receipt_digest_matches_public_model() -> None:
    """Bind the complete retained-SC state/event rows to the committed digest."""
    receipt = json.loads(
        (
            Path(__file__).parents[1]
            / "src/sc_neurocore/neurons/reference_trace_data/sc_resetting_wilson_hr_project.json"
        ).read_text(encoding="utf-8")
    )
    neuron = SCResettingWilsonHRNeuron(dt=float(receipt["protocol"]["dt"]))
    current = float(receipt["protocol"]["inputs"]["I"])
    digest = hashlib.sha256()
    events = 0
    for _ in range(int(receipt["protocol"]["steps"])):
        event = neuron.step(current)
        events += event
        digest.update(struct.pack("<ddB", neuron.v, neuron.r, event))
    assert events == int(receipt["expected_features"]["spike_count"])
    assert digest.hexdigest() == receipt["oracle"]["trace_sha256"]
