# SPDX-License-Identifier: AGPL-3.0-or-later | Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li

"""Spike train statistics -- modular analysis toolkit."""

from __future__ import annotations

from .basic import (
    spike_times,
    isi,
    firing_rate,
    spike_count,
    bin_spike_train,
)
from .variability import (
    cv_isi,
    cv2,
    local_variation,
    lvr,
    fano_factor,
    isi_entropy,
    lempel_ziv_complexity,
    approximate_entropy,
    sample_entropy,
    permutation_entropy,
    hurst_exponent,
    allan_factor,
    rescaled_range,
    complexity_pdf,
    optimal_bin_width,
    optimal_kernel_bandwidth,
)
from .rate import (
    instantaneous_rate,
    population_rate,
    psth,
)
from .distance import (
    van_rossum_distance,
    victor_purpura_distance,
    isi_distance,
    spike_distance,
    spike_sync,
    spike_sync_profile,
    spike_profile,
    isi_profile,
    adaptive_spike_distance,
    schreiber_similarity,
    hunter_milton_similarity,
    earth_movers_distance,
    multi_neuron_victor_purpura,
    generalized_victor_purpura,
    spike_distance_matrix,
)
from .correlation import (
    cross_correlation,
    pairwise_correlation,
    event_synchronization,
    spike_train_coherence,
    spike_time_tiling_coefficient,
    covariance_matrix,
    autocorrelation_time,
    noise_correlation,
    signal_correlation,
    spike_count_covariance,
    joint_psth,
    coincidence_index,
)
from .spectral import (
    power_spectrum,
)
from .temporal import (
    burst_detection,
    first_spike_latency,
    response_onset,
    change_point_detection,
)
from .stimulus import (
    spike_triggered_average,
    spike_triggered_covariance,
    spatial_information,
    place_field_detection,
    tuning_curve,
)
from .lfp import (
    phase_locking_value,
    spike_field_coherence,
    spike_phase_histogram,
)
from .surrogates import (
    surrogate_isi_shuffle,
    surrogate_dither,
    surrogate_trial_shuffle,
    homogeneous_poisson,
    inhomogeneous_poisson,
    gamma_process,
    compound_poisson_process,
    surrogate_joint_isi,
    surrogate_bin_shuffling,
    surrogate_spike_train_shifting,
)
from .information import (
    mutual_information,
    transfer_entropy,
    spike_train_entropy,
    noise_entropy,
    stimulus_specific_information,
    kozachenko_leonenko_mi,
    time_rescaling_ks_test,
)
from .causality import (
    pairwise_granger_causality,
    conditional_granger_causality,
    spectral_granger_causality,
    partial_directed_coherence,
    directed_transfer_function,
)
from .dimensionality import (
    spike_train_pca,
    demixed_pca,
    factor_analysis,
)
from .decoding import (
    population_vector_decode,
    bayesian_decode,
    maximum_likelihood_decode,
    linear_discriminant_decode,
    naive_bayes_decode,
)
from .network import (
    functional_connectivity,
    unitary_events,
    cell_assembly_detection,
    synfire_chain_detection,
)
from .point_process import (
    conditional_intensity,
    isi_hazard_function,
    isi_survivor_function,
    renewal_density,
)
from .sorting_quality import (
    isolation_distance,
    l_ratio,
    silhouette_score,
    d_prime,
    isi_violation_rate,
    presence_ratio,
    amplitude_cutoff,
    snr,
    nn_hit_rate,
    drift_metric,
)
from .waveform import (
    waveform_width,
    waveform_amplitude,
    waveform_repolarization_slope,
    waveform_recovery_slope,
    waveform_halfwidth,
    waveform_pt_ratio,
)
from .statistics import (
    significance_bootstrap,
)
from .patterns import (
    spike_directionality,
    spike_train_order,
    cubic_higher_order,
)
from .spade import (
    spade_detect,
)
from .gpfa import (
    gpfa,
    gpfa_transform,
)

__all__ = [
    "spike_times",
    "isi",
    "firing_rate",
    "spike_count",
    "bin_spike_train",
    "cv_isi",
    "cv2",
    "local_variation",
    "lvr",
    "fano_factor",
    "isi_entropy",
    "lempel_ziv_complexity",
    "approximate_entropy",
    "sample_entropy",
    "permutation_entropy",
    "hurst_exponent",
    "allan_factor",
    "rescaled_range",
    "complexity_pdf",
    "optimal_bin_width",
    "optimal_kernel_bandwidth",
    "instantaneous_rate",
    "population_rate",
    "psth",
    "van_rossum_distance",
    "victor_purpura_distance",
    "isi_distance",
    "spike_distance",
    "spike_sync",
    "spike_sync_profile",
    "spike_profile",
    "isi_profile",
    "adaptive_spike_distance",
    "schreiber_similarity",
    "hunter_milton_similarity",
    "earth_movers_distance",
    "multi_neuron_victor_purpura",
    "generalized_victor_purpura",
    "spike_distance_matrix",
    "cross_correlation",
    "pairwise_correlation",
    "event_synchronization",
    "spike_train_coherence",
    "spike_time_tiling_coefficient",
    "covariance_matrix",
    "autocorrelation_time",
    "noise_correlation",
    "signal_correlation",
    "spike_count_covariance",
    "joint_psth",
    "coincidence_index",
    "power_spectrum",
    "burst_detection",
    "first_spike_latency",
    "response_onset",
    "change_point_detection",
    "spike_triggered_average",
    "spike_triggered_covariance",
    "spatial_information",
    "place_field_detection",
    "tuning_curve",
    "phase_locking_value",
    "spike_field_coherence",
    "spike_phase_histogram",
    "surrogate_isi_shuffle",
    "surrogate_dither",
    "surrogate_trial_shuffle",
    "homogeneous_poisson",
    "inhomogeneous_poisson",
    "gamma_process",
    "compound_poisson_process",
    "surrogate_joint_isi",
    "surrogate_bin_shuffling",
    "surrogate_spike_train_shifting",
    "mutual_information",
    "transfer_entropy",
    "spike_train_entropy",
    "noise_entropy",
    "stimulus_specific_information",
    "kozachenko_leonenko_mi",
    "time_rescaling_ks_test",
    "pairwise_granger_causality",
    "conditional_granger_causality",
    "spectral_granger_causality",
    "partial_directed_coherence",
    "directed_transfer_function",
    "spike_train_pca",
    "demixed_pca",
    "factor_analysis",
    "population_vector_decode",
    "bayesian_decode",
    "maximum_likelihood_decode",
    "linear_discriminant_decode",
    "naive_bayes_decode",
    "functional_connectivity",
    "unitary_events",
    "cell_assembly_detection",
    "synfire_chain_detection",
    "conditional_intensity",
    "isi_hazard_function",
    "isi_survivor_function",
    "renewal_density",
    "isolation_distance",
    "l_ratio",
    "silhouette_score",
    "d_prime",
    "isi_violation_rate",
    "presence_ratio",
    "amplitude_cutoff",
    "snr",
    "nn_hit_rate",
    "drift_metric",
    "waveform_width",
    "waveform_amplitude",
    "waveform_repolarization_slope",
    "waveform_recovery_slope",
    "waveform_halfwidth",
    "waveform_pt_ratio",
    "significance_bootstrap",
    "spike_directionality",
    "spike_train_order",
    "cubic_higher_order",
    "spade_detect",
    "gpfa",
    "gpfa_transform",
]
