# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for aer_codec

fn compress(spikes: Int) -> Int:
    var _compress_line = 'spikes = asarray(spikes, dtype=int8)'
    var _compress_line = 'T, N = spikes.shape'
    var _compress_line = 'original_bits = T * N'
    var _compress_line = '# Adaptive: if >50% density, invert (encode silences instead'
    var _compress_line = 'n_ones = int(sum(spikes))'
    var _compress_line = 'density = n_ones / max(T * N, 1)'
    var _compress_line = 'inverted = density > 0.5'
    var _compress_line = 'encode_matrix = 1 - spikes if inverted else spikes'
    var _compress_line = '# Extract events as (timestamp, neuron_id) sorted by time th'
    var _compress_line = 'times, neurons = nonzero(encode_matrix)'
    var _compress_line = '# Already sorted by time (row-major), then by neuron within '
    var _compress_line = 'n_events = len(times)'
    var _compress_line = 'neuron_bits = ('
    var _compress_line = 'neuron_bits if neuron_bits > 0 else max(1, int(ceil(log2(max'
    var _compress_line = ')'
    var _compress_line = 'neuron_bytes = (neuron_bits + 7) // 8'
    var _compress_line = '# Escape marker is all-1s bytes. If max valid ID (N-1) fills'
    var _compress_line = '# bits in neuron_bytes, bump size to avoid escape collision.'
    var _compress_line = 'while (1 << (neuron_bytes * 8)) - 1 <= (N - 1):'
    var _compress_line = 'neuron_bytes += 1'
    var _compress_line = '# Header: magic(4) + T(4) + N(4) + n_events(4) + neuron_byte'
    var _compress_line = 'magic = HEADER_MAGIC_INV if inverted else HEADER_MAGIC'
    var _compress_line = 'header = magic + struct.pack("!IIIB", T, N, n_events, neuron'
    var _compress_line = 'if n_events == 0:'
    var _compress_line = 'encoded = header'
    var _compress_line = 'else:'
    var _compress_line = '# Delta-encode timestamps'
    var _compress_line = 'parts = []'
    var _compress_line = 'prev_t = 0'
    var _compress_line = 'ts_max = (1 << timestamp_bits) - 1'
    var _compress_line = 'for i in range(n_events):'
    var _compress_line = 't = int(times[i])'
    var _compress_line = 'nid = int(neurons[i])'
    var _compress_line = 'dt = t - prev_t'
    var _compress_line = '# Emit escape codes for large gaps'
    var _compress_line = 'while dt > ts_max:'
    var _compress_line = 'parts.append(struct.pack("!H", ts_max))'
    var _compress_line = 'parts.append(b"\\xff" * neuron_bytes)  # escape marker'
    var _compress_line = 'dt -= ts_max'
    var _compress_line = 'parts.append(struct.pack("!H", dt))'
    var _compress_line = 'parts.append(nid.to_bytes(neuron_bytes, "big"))'
    var _compress_line = 'prev_t = t'
    var _compress_line = 'encoded = header + b"".join(parts)'
    var _compress_line = 'compressed_bits = len(encoded) * 8'
    var _compress_line = 'ratio = original_bits / max(compressed_bits, 1)'
    var _compress_line = 'bpe = len(encoded) / max(n_events, 1)'
    return 0  # return encoded, AERCompressionResult(
    var _compress_line = 'original_bits=original_bits,'
    var _compress_line = 'compressed_bits=compressed_bits,'
    var _compress_line = 'compression_ratio=ratio,'
    var _compress_line = 'n_spikes=n_ones,'
    var _compress_line = 'n_neurons=N,'
    var _compress_line = 'n_timesteps=T,'
    var _compress_line = 'lossless=True,'
    var _compress_line = 'n_events=n_events,'
    var _compress_line = 'bytes_per_event=bpe,'
    var _compress_line = 'codec_type="aer",'
    var _compress_line = ')'

fn decompress(data: Int, T: Int, N: Int) -> Int:
    var _decompress_line = 'magic = data[:4]'
    var _decompress_line = 'if magic not in (HEADER_MAGIC, HEADER_MAGIC_INV):'
    var _decompress_line = 'raise ValueError('
    var _decompress_line = 'f"Invalid header magic: {magic!r}, expected {HEADER_MAGIC!r}'
    var _decompress_line = ')'
    var _decompress_line = 'inverted = magic == HEADER_MAGIC_INV'
    var _decompress_line = 'T_stored, N_stored, n_events, neuron_bytes = struct.unpack("'
    var _decompress_line = 'if T == 0:'
    var _decompress_line = 'T = T_stored'
    var _decompress_line = 'if N == 0:'
    var _decompress_line = 'N = N_stored'
    var _decompress_line = 'escape_marker = b"\\xff" * neuron_bytes'
    var _decompress_line = 'decoded = zeros((T, N), dtype=int8)'
    var _decompress_line = 'offset = 17'
    var _decompress_line = 'current_t = 0'
    var _decompress_line = 'events_read = 0'
    var _decompress_line = 'while events_read < n_events and offset + 2 + neuron_bytes <'
    var _decompress_line = 'dt = struct.unpack("!H", data[offset : offset + 2])[0]'
    var _decompress_line = 'nid_bytes = data[offset + 2 : offset + 2 + neuron_bytes]'
    var _decompress_line = 'offset += 2 + neuron_bytes'
    var _decompress_line = 'if nid_bytes == escape_marker:'
    var _decompress_line = 'current_t += dt'
    var _decompress_line = 'continue'
    var _decompress_line = 'current_t += dt'
    var _decompress_line = 'nid = int.from_bytes(nid_bytes, "big")'
    var _decompress_line = 'if 0 <= current_t < T and 0 <= nid < N:'
    var _decompress_line = 'decoded[current_t, nid] = 1'
    var _decompress_line = 'events_read += 1'
    var _decompress_line = 'if inverted:'
    return 0  # return 1 - decoded
    return 0  # return decoded

