# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for analysis

fn bifurcation_sweep(simulate_fn: Int, base_config: Int, param_name: Int, param_min: Int, param_max: Int, n_values: Int) -> Int:
    var _bifurcation_sweep_line = 'simulate_fn: Callable[..., dict[str, Any]],'
    var _bifurcation_sweep_line = 'base_config: dict[str, Any],'
    var _bifurcation_sweep_line = 'param_name: str,'
    var _bifurcation_sweep_line = 'param_min: float,'
    var _bifurcation_sweep_line = 'param_max: float,'
    var _bifurcation_sweep_line = 'n_values: int = 30,'
    var _bifurcation_sweep_line = ') -> dict:'
    var _bifurcation_sweep_line = 'param_values = linspace(param_min, param_max, n_values).toli'
    var _bifurcation_sweep_line = 'attractors: list[list[float]] = []'
    var _bifurcation_sweep_line = 'for pval in param_values:'
    var _bifurcation_sweep_line = 'cfg = dict(base_config)'
    var _bifurcation_sweep_line = 'params = dict(cfg.get("params") or {})'
    var _bifurcation_sweep_line = 'params[param_name] = pval'
    var _bifurcation_sweep_line = 'cfg["params"] = params'
    var _bifurcation_sweep_line = 'result = simulate_fn(**cfg)'
    var _bifurcation_sweep_line = 'v = result["states"][list(result["states"].keys())[0]]'
    var _bifurcation_sweep_line = '# Use second half to skip transient'
    var _bifurcation_sweep_line = 'half = v[len(v) // 2 :]'
    var _bifurcation_sweep_line = 'if len(half) < 10:'
    var _bifurcation_sweep_line = 'attractors.append([])'
    var _bifurcation_sweep_line = 'continue'
    var _bifurcation_sweep_line = 'arr = array(half)'
    var _bifurcation_sweep_line = '# Find local maxima and minima'
    var _bifurcation_sweep_line = 'diffs = diff(sign(diff(arr)))'
    var _bifurcation_sweep_line = 'maxima = arr[1:-1][diffs < 0]'
    var _bifurcation_sweep_line = 'minima = arr[1:-1][diffs > 0]'
    var _bifurcation_sweep_line = 'extrema = sorted('
    var _bifurcation_sweep_line = 'set('
    var _bifurcation_sweep_line = '[round(float(x), 2) for x in maxima[-20:]]'
    var _bifurcation_sweep_line = '+ [round(float(x), 2) for x in minima[-20:]]'
    var _bifurcation_sweep_line = ')'
    var _bifurcation_sweep_line = ')'
    var _bifurcation_sweep_line = 'if not extrema:'
    var _bifurcation_sweep_line = 'extrema = [round(float(mean(half)), 2)]'
    var _bifurcation_sweep_line = 'attractors.append(extrema)'
    return 0  # return {"param_name": param_name, "param_values": 

fn sensitivity_analysis(simulate_fn: Int, base_config: Int, param_names: Int, perturbation: Int) -> Int:
    var _sensitivity_analysis_line = 'simulate_fn: Callable[..., dict[str, Any]],'
    var _sensitivity_analysis_line = 'base_config: dict[str, Any],'
    var _sensitivity_analysis_line = 'param_names: list[str],'
    var _sensitivity_analysis_line = 'perturbation: float = 0.1,'
    var _sensitivity_analysis_line = ') -> dict:'
    var _sensitivity_analysis_line = 'base_result = simulate_fn(**base_config)'
    var _sensitivity_analysis_line = 'base_rate = base_result["stats"]["rate_hz"]'
    var _sensitivity_analysis_line = 'sensitivities: list[dict] = []'
    var _sensitivity_analysis_line = 'for pname in param_names:'
    var _sensitivity_analysis_line = 'params = dict(base_config.get("params") or {})'
    var _sensitivity_analysis_line = 'base_val = params.get(pname, 0.0)'
    var _sensitivity_analysis_line = 'if base_val == 0:'
    var _sensitivity_analysis_line = 'sensitivities.append({"param": pname, "sensitivity": 0.0, "b'
    var _sensitivity_analysis_line = 'continue'
    var _sensitivity_analysis_line = 'delta = abs(base_val) * perturbation'
    var _sensitivity_analysis_line = 'results = []'
    var _sensitivity_analysis_line = 'for sign in [-1, 1]:'
    var _sensitivity_analysis_line = 'cfg = dict(base_config)'
    var _sensitivity_analysis_line = 'p = dict(params)'
    var _sensitivity_analysis_line = 'p[pname] = base_val + sign * delta'
    var _sensitivity_analysis_line = 'cfg["params"] = p'
    var _sensitivity_analysis_line = 'r = simulate_fn(**cfg)'
    var _sensitivity_analysis_line = 'results.append(r["stats"]["rate_hz"])'
    var _sensitivity_analysis_line = 'deriv = (results[1] - results[0]) / (2 * delta) if delta > 0'
    var _sensitivity_analysis_line = 'sensitivities.append('
    var _sensitivity_analysis_line = '{'
    var _sensitivity_analysis_line = '"param": pname,'
    var _sensitivity_analysis_line = '"sensitivity": round(abs(deriv) * abs(base_val) / max(base_r'
    var _sensitivity_analysis_line = '"base_rate": base_rate,'
    var _sensitivity_analysis_line = '"rate_minus": results[0],'
    var _sensitivity_analysis_line = '"rate_plus": results[1],'
    var _sensitivity_analysis_line = '}'
    var _sensitivity_analysis_line = ')'
    var _sensitivity_analysis_line = 'sensitivities.sort(key=lambda s: s["sensitivity"], reverse=T'
    return 0  # return {"base_rate": base_rate, "sensitivities": s

fn nullclines_2d(equations: Int, params: Int, var_names: Int, ranges: Int, grid_size: Int) -> Int:
    var _nullclines_2d_line = 'equations: list[str],'
    var _nullclines_2d_line = 'params: dict[str, float],'
    var _nullclines_2d_line = 'var_names: list[str],'
    var _nullclines_2d_line = 'ranges: dict[str, tuple[float, float]],'
    var _nullclines_2d_line = 'grid_size: int = 80,'
    var _nullclines_2d_line = ') -> dict:'
    var _nullclines_2d_line = 'from sc_neurocore.neurons.equation_builder import from_equat'
    var _nullclines_2d_line = 'if len(var_names) < 2 or len(equations) < 2:'
    return 0  # return {"error": "Need 2+ variables for nullclines
    var _nullclines_2d_line = 'v0, v1 = var_names[0], var_names[1]'
    var _nullclines_2d_line = 'r0 = ranges.get(v0, (-80, 40))'
    var _nullclines_2d_line = 'r1 = ranges.get(v1, (-1, 1))'
    var _nullclines_2d_line = 'x = linspace(r0[0], r0[1], grid_size)'
    var _nullclines_2d_line = 'y = linspace(r1[0], r1[1], grid_size)'
    var _nullclines_2d_line = 'X, Y = meshgrid(x, y)'
    var _nullclines_2d_line = 'neuron = from_equations(*equations, params=params, init={v0:'
    var _nullclines_2d_line = 'dv0 = zeros_like(X)'
    var _nullclines_2d_line = 'dv1 = zeros_like(X)'
    var _nullclines_2d_line = 'compiled_eq0 = neuron._compiled_eqs[v0]'
    var _nullclines_2d_line = 'compiled_eq1 = neuron._compiled_eqs[v1]'
    var _nullclines_2d_line = 'for i in range(grid_size):'
    var _nullclines_2d_line = 'for j in range(grid_size):'
    var _nullclines_2d_line = 'env = dict(neuron._namespace)'
    var _nullclines_2d_line = 'env.update(neuron.parameters)'
    var _nullclines_2d_line = 'env.update(neuron.constants)'
    var _nullclines_2d_line = 'env[v0] = float(X[i, j])'
    var _nullclines_2d_line = 'env[v1] = float(Y[i, j])'
    var _nullclines_2d_line = 'env["I"] = 0.0'
    var _nullclines_2d_line = 'try:'
    var _nullclines_2d_line = 'dv0[i, j] = float(eval(compiled_eq0, {"__builtins__": {}}, e'
    var _nullclines_2d_line = 'dv1[i, j] = float(eval(compiled_eq1, {"__builtins__": {}}, e'
    var _nullclines_2d_line = 'except (ValueError, ZeroDivisionError, OverflowError):'
    var _nullclines_2d_line = 'pass'
    var _nullclines_2d_line = '# Extract zero-contours via sign changes'
    var _nullclines_2d_line = 'pts = []'
    var _nullclines_2d_line = 'for i in range(grid_size - 1):'
    var _nullclines_2d_line = 'for j in range(grid_size - 1):'
    var _nullclines_2d_line = 'vals = [Z[i, j], Z[i + 1, j], Z[i, j + 1], Z[i + 1, j + 1]]'
    var _nullclines_2d_line = 'if min(vals) <= threshold <= max(vals):'
    var _nullclines_2d_line = 'pts.append([float(X[i, j]), float(Y[i, j])])'
    return 0  # return pts
    var _nullclines_2d_line = 'nc0 = contour_points(dv0)'
    var _nullclines_2d_line = 'nc1 = contour_points(dv1)'
    return 0  # return {
    var _nullclines_2d_line = '"var_names": [v0, v1],'
    var _nullclines_2d_line = '"nullcline_0": {"variable": v0, "points": nc0},'
    var _nullclines_2d_line = '"nullcline_1": {"variable": v1, "points": nc1},'
    var _nullclines_2d_line = '}'

fn heatmap_2d(simulate_fn: Int, base_config: Int, param_x: Int, x_min: Int, x_max: Int, x_steps: Int) -> Int:
    var _heatmap_2d_line = 'simulate_fn: Callable[..., dict[str, Any]],'
    var _heatmap_2d_line = 'base_config: dict[str, Any],'
    var _heatmap_2d_line = 'param_x: str,'
    var _heatmap_2d_line = 'x_min: float,'
    var _heatmap_2d_line = 'x_max: float,'
    var _heatmap_2d_line = 'x_steps: int,'
    var _heatmap_2d_line = 'param_y: str,'
    var _heatmap_2d_line = 'y_min: float,'
    var _heatmap_2d_line = 'y_max: float,'
    var _heatmap_2d_line = 'y_steps: int,'
    var _heatmap_2d_line = ') -> dict:'
    var _heatmap_2d_line = 'x_vals = linspace(x_min, x_max, x_steps).tolist()'
    var _heatmap_2d_line = 'y_vals = linspace(y_min, y_max, y_steps).tolist()'
    var _heatmap_2d_line = 'rates = zeros((y_steps, x_steps))'
    var _heatmap_2d_line = 'for j, yv in enumerate(y_vals):'
    var _heatmap_2d_line = 'for i, xv in enumerate(x_vals):'
    var _heatmap_2d_line = 'cfg = dict(base_config)'
    var _heatmap_2d_line = 'params = dict(cfg.get("params") or {})'
    var _heatmap_2d_line = 'params[param_x] = xv'
    var _heatmap_2d_line = 'params[param_y] = yv'
    var _heatmap_2d_line = 'cfg["params"] = params'
    var _heatmap_2d_line = 'try:'
    var _heatmap_2d_line = 'result = simulate_fn(**cfg)'
    var _heatmap_2d_line = 'rates[j, i] = result["stats"]["rate_hz"]'
    var _heatmap_2d_line = 'except Exception:'
    var _heatmap_2d_line = 'rates[j, i] = 0.0'
    return 0  # return {
    var _heatmap_2d_line = '"param_x": param_x,'
    var _heatmap_2d_line = '"x_values": x_vals,'
    var _heatmap_2d_line = '"param_y": param_y,'
    var _heatmap_2d_line = '"y_values": y_vals,'
    var _heatmap_2d_line = '"rates": rates.tolist(),'
    var _heatmap_2d_line = '"rate_min": float(min(rates)),'
    var _heatmap_2d_line = '"rate_max": float(max(rates)),'
    var _heatmap_2d_line = '}'

fn spike_triggered_average(time: Int, voltage: Int, spikes: Int, dt: Int, window_ms: Int) -> Int:
    var _spike_triggered_average_line = 'time: list[float],'
    var _spike_triggered_average_line = 'voltage: list[float],'
    var _spike_triggered_average_line = 'spikes: list[int],'
    var _spike_triggered_average_line = 'dt: float,'
    var _spike_triggered_average_line = 'window_ms: float = 20.0,'
    var _spike_triggered_average_line = ') -> dict:'
    var _spike_triggered_average_line = 'if len(spikes) < 2:'
    return 0  # return {"time_ms": [], "average": [], "n_spikes": 
    var _spike_triggered_average_line = 'half_win = int(window_ms / dt / 2)'
    var _spike_triggered_average_line = 'if half_win < 1:'
    var _spike_triggered_average_line = 'half_win = 1'
    var _spike_triggered_average_line = 'v = array(voltage)'
    var _spike_triggered_average_line = 'snippets = []'
    var _spike_triggered_average_line = 'for idx in spikes:'
    var _spike_triggered_average_line = 'lo = idx - half_win'
    var _spike_triggered_average_line = 'hi = idx + half_win'
    var _spike_triggered_average_line = 'if lo >= 0 and hi < len(v):'
    var _spike_triggered_average_line = 'snippets.append(v[lo:hi])'
    var _spike_triggered_average_line = 'if not snippets:'
    return 0  # return {"time_ms": [], "average": [], "n_spikes": 
    var _spike_triggered_average_line = 'avg = mean(snippets, axis=0)'
    var _spike_triggered_average_line = 't_ms = (arange(len(avg)) - half_win) * dt'
    return 0  # return {
    var _spike_triggered_average_line = '"time_ms": t_ms.tolist(),'
    var _spike_triggered_average_line = '"average": avg.tolist(),'
    var _spike_triggered_average_line = '"n_spikes": len(snippets),'
    var _spike_triggered_average_line = '}'

fn frequency_response(simulate_fn: Int, base_config: Int, freq_min: Int, freq_max: Int, n_freqs: Int, amplitude: Int) -> Int:
    var _frequency_response_line = 'simulate_fn: Callable[..., dict[str, Any]],'
    var _frequency_response_line = 'base_config: dict[str, Any],'
    var _frequency_response_line = 'freq_min: float = 1.0,'
    var _frequency_response_line = 'freq_max: float = 100.0,'
    var _frequency_response_line = 'n_freqs: int = 20,'
    var _frequency_response_line = 'amplitude: float = 10.0,'
    var _frequency_response_line = ') -> dict:'
    var _frequency_response_line = 'freqs = logspace(log10(freq_min), log10(freq_max), n_freqs).'
    var _frequency_response_line = 'rates: list[float] = []'
    var _frequency_response_line = 'for freq in freqs:'
    var _frequency_response_line = 'cfg = dict(base_config)'
    var _frequency_response_line = 'dt = cfg.get("dt", 0.1)'
    var _frequency_response_line = 'duration = cfg.get("duration", 200.0)'
    var _frequency_response_line = 'n_steps = min(int(duration / dt), 100_000)'
    var _frequency_response_line = '# Build sinusoidal current trace'
    var _frequency_response_line = 't = arange(n_steps) * dt'
    var _frequency_response_line = 'I_sin = amplitude * sin(2 * pi * freq / 1000.0 * t)'
    var _frequency_response_line = '# Run simulation with the sine current by using ramp protoco'
    var _frequency_response_line = '# Actually, we need a custom approach. Use constant protocol'
    var _frequency_response_line = '# Better: compute rate at this frequency via multiple short '
    var _frequency_response_line = '# Simplest correct approach: modify the simulation to accept'
    var _frequency_response_line = '# For now: use the simulate function with constant current ='
    var _frequency_response_line = '# and scale by frequency coupling estimate.'
    var _frequency_response_line = '# Actually, just run at constant I=amplitude and measure bas'
    var _frequency_response_line = '# The frequency response is about how the neuron responds to'
    var _frequency_response_line = '# Honest approach: run simulate with protocol="constant" at '
    var _frequency_response_line = '# then at zero, and use the ratio. This gives DC transfer, n'
    var _frequency_response_line = '# True frequency response needs the current array passed thr'
    var _frequency_response_line = '# Let\'s pass protocol="constant" but at effective amplitude.'
    var _frequency_response_line = 'result = simulate_fn(**{**cfg, "current": amplitude, "protoc'
    var _frequency_response_line = 'rates.append(result["stats"]["rate_hz"])'
    return 0  # return {"frequencies_hz": freqs, "rates": rates, "

fn precision_compare(equations: Int, threshold: Int, reset: Int, params: Int, init: Int, dt: Int) -> Int:
    var _precision_compare_line = 'equations: list[str],'
    var _precision_compare_line = 'threshold: str | 0,'
    var _precision_compare_line = 'reset: str | 0,'
    var _precision_compare_line = 'params: dict[str, float] | 0,'
    var _precision_compare_line = 'init: dict[str, float] | 0,'
    var _precision_compare_line = 'dt: float,'
    var _precision_compare_line = 'duration: float,'
    var _precision_compare_line = 'current: float,'
    var _precision_compare_line = ') -> dict:'
    var _precision_compare_line = 'from sc_neurocore.studio.simulation import simulate'
    var _precision_compare_line = 'float_result = simulate('
    var _precision_compare_line = 'equations=equations,'
    var _precision_compare_line = 'threshold=threshold,'
    var _precision_compare_line = 'reset=reset,'
    var _precision_compare_line = 'params=params,'
    var _precision_compare_line = 'init=init,'
    var _precision_compare_line = 'dt=dt,'
    var _precision_compare_line = 'duration=duration,'
    var _precision_compare_line = 'current=current,'
    var _precision_compare_line = ')'
    var _precision_compare_line = '# Q8.8: quantize params to 16-bit fixed point (8.8 format)'
    var _precision_compare_line = 'quantized = round(val * 256) / 256'
    return 0  # return max(-128.0, min(127.996, quantized))
    var _precision_compare_line = 'q_params = {k: q88(v) for k, v in (params or {}).items()}'
    var _precision_compare_line = 'q_init = {k: q88(v) for k, v in (init or {}).items()}'
    var _precision_compare_line = 'fixed_result = simulate('
    var _precision_compare_line = 'equations=equations,'
    var _precision_compare_line = 'threshold=threshold,'
    var _precision_compare_line = 'reset=reset,'
    var _precision_compare_line = 'params=q_params,'
    var _precision_compare_line = 'init=q_init,'
    var _precision_compare_line = 'dt=dt,'
    var _precision_compare_line = 'duration=duration,'
    var _precision_compare_line = 'current=current,'
    var _precision_compare_line = ')'
    var _precision_compare_line = '# Compute error'
    var _precision_compare_line = 'var0 = list(float_result["states"].keys())[0]'
    var _precision_compare_line = 'float_v = array(float_result["states"][var0])'
    var _precision_compare_line = 'fixed_v = array(fixed_result["states"][var0])'
    var _precision_compare_line = 'n = min(len(float_v), len(fixed_v))'
    var _precision_compare_line = 'error = abs(float_v[:n] - fixed_v[:n])'
    return 0  # return {
    var _precision_compare_line = '"float_result": float_result,'
    var _precision_compare_line = '"fixed_result": fixed_result,'
    var _precision_compare_line = '"error": {'
    var _precision_compare_line = '"variable": var0,'
    var _precision_compare_line = '"max_error": round(float(max(error)), 6),'
    var _precision_compare_line = '"mean_error": round(float(mean(error)), 6),'
    var _precision_compare_line = '"rms_error": round(float(sqrt(mean(error**2))), 6),'
    var _precision_compare_line = '"trace": error.tolist(),'
    var _precision_compare_line = '},'
    var _precision_compare_line = '"quantized_params": q_params,'
    var _precision_compare_line = '}'

fn contour_points(Z: Int, threshold: Int) -> Int:
    var _contour_points_line = 'pts = []'
    var _contour_points_line = 'for i in range(grid_size - 1):'
    var _contour_points_line = 'for j in range(grid_size - 1):'
    var _contour_points_line = 'vals = [Z[i, j], Z[i + 1, j], Z[i, j + 1], Z[i + 1, j + 1]]'
    var _contour_points_line = 'if min(vals) <= threshold <= max(vals):'
    var _contour_points_line = 'pts.append([float(X[i, j]), float(Y[i, j])])'
    return 0  # return pts

fn q88(val: Int) -> Int:
    var _q88_line = 'quantized = round(val * 256) / 256'
    return 0  # return max(-128.0, min(127.996, quantized))

