# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for characterize

fn characterize_model(simulate_fn: Int, base_config: Int) -> Int:
    var _characterize_model_line = '# 1. Default simulation'
    var _characterize_model_line = 'trace = simulate_fn(**base_config)'
    var _characterize_model_line = 'pattern = classify_firing_pattern(trace["spikes"], trace["n_'
    var _characterize_model_line = '# 2. f-I curve'
    var _characterize_model_line = 'base_current = base_config.get("current", 10.0)'
    var _characterize_model_line = 'i_max = max(abs(base_current) * 3, 50)'
    var _characterize_model_line = 'currents = linspace(0, i_max, 20).tolist()'
    var _characterize_model_line = 'rates: list[float] = []'
    var _characterize_model_line = 'for I in currents:'
    var _characterize_model_line = 'try:'
    var _characterize_model_line = 'r = simulate_fn(**{**base_config, "current": I})'
    var _characterize_model_line = 'rates.append(r["stats"]["rate_hz"])'
    var _characterize_model_line = 'except Exception:'
    var _characterize_model_line = 'rates.append(0.0)'
    var _characterize_model_line = '# 3. Threshold current (rheobase)'
    var _characterize_model_line = 'threshold_current = 0'
    var _characterize_model_line = 'for i, rate in enumerate(rates):'
    var _characterize_model_line = 'if rate > 0:'
    var _characterize_model_line = 'threshold_current = round(currents[i], 2)'
    var _characterize_model_line = 'break'
    var _characterize_model_line = '# 4. Max rate'
    var _characterize_model_line = 'max_rate = round(max(rates), 1) if rates else 0.0'
    var _characterize_model_line = '# 5. State variable ranges'
    var _characterize_model_line = 'state_ranges = {}'
    var _characterize_model_line = 'for var, values in trace["states"].items():'
    var _characterize_model_line = 'arr = array(values)'
    var _characterize_model_line = 'state_ranges[var] = {'
    var _characterize_model_line = '"min": round(float(min(arr)), 2),'
    var _characterize_model_line = '"max": round(float(max(arr)), 2),'
    var _characterize_model_line = '"mean": round(float(mean(arr)), 2),'
    var _characterize_model_line = '}'
    var _characterize_model_line = '# 6. Quick sensitivity (top 5)'
    var _characterize_model_line = 'params = base_config.get("params") or {}'
    var _characterize_model_line = 'sensitivities: list[dict] = []'
    var _characterize_model_line = 'for pname, pval in list(params.items())[:15]:'
    var _characterize_model_line = 'if pval == 0:'
    var _characterize_model_line = 'continue'
    var _characterize_model_line = 'delta = abs(pval) * 0.1'
    var _characterize_model_line = 'try:'
    var _characterize_model_line = 'r_lo = simulate_fn(**{**base_config, "params": {**params, pn'
    var _characterize_model_line = 'r_hi = simulate_fn(**{**base_config, "params": {**params, pn'
    var _characterize_model_line = 'rate_change = abs(r_hi["stats"]["rate_hz"] - r_lo["stats"]["'
    var _characterize_model_line = 'sensitivities.append({"param": pname, "rate_change": round(r'
    var _characterize_model_line = 'except (ValueError, ZeroDivisionError, KeyError, RuntimeErro'
    var _characterize_model_line = 'continue'
    var _characterize_model_line = 'sensitivities.sort(key=lambda s: s["rate_change"], reverse=T'
    return 0  # return {
    var _characterize_model_line = '"pattern": pattern,'
    var _characterize_model_line = '"fi_curve": {"currents": currents, "rates": rates},'
    var _characterize_model_line = '"threshold_current": threshold_current,'
    var _characterize_model_line = '"max_rate": max_rate,'
    var _characterize_model_line = '"state_ranges": state_ranges,'
    var _characterize_model_line = '"top_sensitivities": sensitivities[:5],'
    var _characterize_model_line = '"spike_count": trace["spike_count"],'
    var _characterize_model_line = '"stats": trace["stats"],'
    var _characterize_model_line = '}'

