# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for configs

fn mnist_classifier(n_hidden: Int) -> Int:
    var _mnist_classifier_line = 'lif_params = {'
    var _mnist_classifier_line = '"tau_mem": 10.0,'
    var _mnist_classifier_line = '"v_threshold": 1.0,'
    var _mnist_classifier_line = '"noise_std": 0.0,'
    var _mnist_classifier_line = '"v_rest": 0.0,'
    var _mnist_classifier_line = '"v_reset": 0.0,'
    var _mnist_classifier_line = '}'
    var _mnist_classifier_line = 'inp = Population(StochasticLIFNeuron, 784, label="input", pa'
    var _mnist_classifier_line = 'hid = Population(StochasticLIFNeuron, n_hidden, label="hidde'
    var _mnist_classifier_line = 'out = Population(StochasticLIFNeuron, 10, label="output", pa'
    var _mnist_classifier_line = 'scale_ih = sqrt(2.0 / 784)'
    var _mnist_classifier_line = 'scale_ho = sqrt(2.0 / n_hidden)'
    var _mnist_classifier_line = 'p_ih = Projection(inp, hid, weight=scale_ih * 20.0, probabil'
    var _mnist_classifier_line = 'p_ho = Projection(hid, out, weight=scale_ho * 20.0, probabil'
    var _mnist_classifier_line = 'stim = PoissonInput(784, rate_hz=500.0, weight=2.0)'
    var _mnist_classifier_line = 'stim.target = inp'
    var _mnist_classifier_line = 'mon_out = SpikeMonitor(out, label="output_spikes")'
    var _mnist_classifier_line = 'mon_hid = SpikeMonitor(hid, label="hidden_spikes")'
    return 0  # return Network(inp, hid, out, p_ih, p_ho, stim, mo

fn dvs_gesture_classifier(n_classes: Int) -> Int:
    var _dvs_gesture_classifier_line = 'lif_params = {'
    var _dvs_gesture_classifier_line = '"tau_mem": 10.0,'
    var _dvs_gesture_classifier_line = '"v_threshold": 1.0,'
    var _dvs_gesture_classifier_line = '"noise_std": 0.0,'
    var _dvs_gesture_classifier_line = '"v_rest": 0.0,'
    var _dvs_gesture_classifier_line = '"v_reset": 0.0,'
    var _dvs_gesture_classifier_line = '}'
    var _dvs_gesture_classifier_line = 'n_input = 256'
    var _dvs_gesture_classifier_line = 'inp = Population(StochasticLIFNeuron, n_input, label="dvs_in'
    var _dvs_gesture_classifier_line = 'hid = Population(StochasticLIFNeuron, 256, label="dvs_hidden'
    var _dvs_gesture_classifier_line = 'out = Population(StochasticLIFNeuron, n_classes, label="dvs_'
    var _dvs_gesture_classifier_line = 'p_ih = Projection(inp, hid, weight=0.5, probability=0.2)'
    var _dvs_gesture_classifier_line = 'p_ho = Projection(hid, out, weight=0.8, probability=0.4)'
    var _dvs_gesture_classifier_line = 'stim = PoissonInput(n_input, rate_hz=800.0, weight=2.0)'
    var _dvs_gesture_classifier_line = 'stim.target = inp'
    var _dvs_gesture_classifier_line = 'mon = SpikeMonitor(out, label="gesture_spikes")'
    return 0  # return Network(inp, hid, out, p_ih, p_ho, stim, mo

fn shd_speech_classifier() -> Int:
    var _shd_speech_classifier_line = 'lif_params = {'
    var _shd_speech_classifier_line = '"tau_mem": 10.0,'
    var _shd_speech_classifier_line = '"v_threshold": 1.0,'
    var _shd_speech_classifier_line = '"noise_std": 0.0,'
    var _shd_speech_classifier_line = '"v_rest": 0.0,'
    var _shd_speech_classifier_line = '"v_reset": 0.0,'
    var _shd_speech_classifier_line = '}'
    var _shd_speech_classifier_line = 'rec_params = {'
    var _shd_speech_classifier_line = '"tau_mem": 20.0,'
    var _shd_speech_classifier_line = '"v_threshold": 1.0,'
    var _shd_speech_classifier_line = '"noise_std": 0.0,'
    var _shd_speech_classifier_line = '"v_rest": 0.0,'
    var _shd_speech_classifier_line = '"v_reset": 0.0,'
    var _shd_speech_classifier_line = '}'
    var _shd_speech_classifier_line = 'inp = Population(StochasticLIFNeuron, 700, label="shd_input"'
    var _shd_speech_classifier_line = 'rec = Population(StochasticLIFNeuron, 256, label="shd_recurr'
    var _shd_speech_classifier_line = 'out = Population(StochasticLIFNeuron, 20, label="shd_output"'
    var _shd_speech_classifier_line = 'p_ir = Projection(inp, rec, weight=0.3, probability=0.15)'
    var _shd_speech_classifier_line = 'p_rr = Projection(rec, rec, weight=0.15, probability=0.1)'
    var _shd_speech_classifier_line = 'p_ro = Projection(rec, out, weight=0.6, probability=0.3)'
    var _shd_speech_classifier_line = 'stim = PoissonInput(700, rate_hz=500.0, weight=2.0)'
    var _shd_speech_classifier_line = 'stim.target = inp'
    var _shd_speech_classifier_line = 'mon = SpikeMonitor(out, label="shd_output_spikes")'
    var _shd_speech_classifier_line = 'mon_rec = SpikeMonitor(rec, label="shd_recurrent_spikes")'
    return 0  # return Network(inp, rec, out, p_ir, p_rr, p_ro, st

fn brunel_balanced_network(n_exc: Int, n_inh: Int, g: Int, eta: Int) -> Int:
    var _brunel_balanced_network_line = 'n_exc: int = 800,'
    var _brunel_balanced_network_line = 'n_inh: int = 200,'
    var _brunel_balanced_network_line = 'g: float = 5.0,'
    var _brunel_balanced_network_line = 'eta: float = 2.0,'
    var _brunel_balanced_network_line = ') -> Network:'
    var _brunel_balanced_network_line = '# Brunel 2000, Table 1: tau_m=20ms, V_thr=20mV, V_reset=10mV'
    var _brunel_balanced_network_line = 'lif_params = {'
    var _brunel_balanced_network_line = '"tau_mem": 20.0,'
    var _brunel_balanced_network_line = '"v_threshold": 1.0,'
    var _brunel_balanced_network_line = '"v_reset": 0.0,'
    var _brunel_balanced_network_line = '"v_rest": 0.0,'
    var _brunel_balanced_network_line = '"noise_std": 0.0,'
    var _brunel_balanced_network_line = '}'
    var _brunel_balanced_network_line = 'exc = Population(StochasticLIFNeuron, n_exc, label="exc", pa'
    var _brunel_balanced_network_line = 'inh = Population(StochasticLIFNeuron, n_inh, label="inh", pa'
    var _brunel_balanced_network_line = '# J_E = 0.1 (normalised); J_I = -g * J_E'
    var _brunel_balanced_network_line = 'j_e = 0.1'
    var _brunel_balanced_network_line = 'j_i = -g * j_e'
    var _brunel_balanced_network_line = 'eps = 0.1'
    var _brunel_balanced_network_line = 'p_ee = Projection(exc, exc, weight=j_e, probability=eps, del'
    var _brunel_balanced_network_line = 'p_ei = Projection(exc, inh, weight=j_e, probability=eps, del'
    var _brunel_balanced_network_line = 'p_ie = Projection(inh, exc, weight=j_i, probability=eps, del'
    var _brunel_balanced_network_line = 'p_ii = Projection(inh, inh, weight=j_i, probability=eps, del'
    var _brunel_balanced_network_line = '# External Poisson drive: strong enough to drive threshold c'
    var _brunel_balanced_network_line = 'stim_e = PoissonInput(n_exc, rate_hz=1000.0, weight=2.0)'
    var _brunel_balanced_network_line = 'stim_e.target = exc'
    var _brunel_balanced_network_line = 'stim_i = PoissonInput(n_inh, rate_hz=1000.0, weight=2.0)'
    var _brunel_balanced_network_line = 'stim_i.target = inh'
    var _brunel_balanced_network_line = 'mon_e = SpikeMonitor(exc, label="exc_spikes")'
    var _brunel_balanced_network_line = 'mon_i = SpikeMonitor(inh, label="inh_spikes")'
    return 0  # return Network(exc, inh, p_ee, p_ei, p_ie, p_ii, s

fn cortical_column(n_layers: Int) -> Int:
    var _cortical_column_line = 'layer_names = ["L23", "L4", "L5", "L6"]'
    var _cortical_column_line = 'exc_sizes = [50, 50, 50, 50]'
    var _cortical_column_line = 'inh_sizes = [15, 15, 10, 10]'
    var _cortical_column_line = 'n_actual = min(len(layer_names), max(1, n_layers))'
    var _cortical_column_line = 'exc_sizes = exc_sizes[:n_actual]'
    var _cortical_column_line = 'inh_sizes = inh_sizes[:n_actual]'
    var _cortical_column_line = 'layer_names = layer_names[:n_actual]'
    var _cortical_column_line = 'populations = []'
    var _cortical_column_line = 'monitors = []'
    var _cortical_column_line = 'projections = []'
    var _cortical_column_line = 'for i, name in enumerate(layer_names):'
    var _cortical_column_line = 'e = Population(PospischilNeuron, exc_sizes[i], label=f"{name'
    var _cortical_column_line = 'inh_pop = Population(GolombFSNeuron, inh_sizes[i], label=f"{'
    var _cortical_column_line = 'populations.extend([e, inh_pop])'
    var _cortical_column_line = 'monitors.append(SpikeMonitor(e, label=f"{name}_E_spikes"))'
    var _cortical_column_line = 'monitors.append(SpikeMonitor(inh_pop, label=f"{name}_I_spike'
    var _cortical_column_line = '# Intra-layer E->I, I->E, E->E'
    var _cortical_column_line = 'for i in range(len(layer_names)):'
    var _cortical_column_line = 'e_pop = populations[2 * i]'
    var _cortical_column_line = 'i_pop = populations[2 * i + 1]'
    var _cortical_column_line = 'projections.append(Projection(e_pop, i_pop, weight=2.0, prob'
    var _cortical_column_line = 'projections.append(Projection(i_pop, e_pop, weight=-3.0, pro'
    var _cortical_column_line = 'projections.append(Projection(e_pop, e_pop, weight=1.0, prob'
    var _cortical_column_line = '# Inter-layer feedforward: L4->L23, L23->L5, L5->L6'
    var _cortical_column_line = 'ff_map = [(1, 0), (0, 2), (2, 3)]'
    var _cortical_column_line = 'for src_l, tgt_l in ff_map:'
    var _cortical_column_line = 'if src_l < len(layer_names) and tgt_l < len(layer_names):'
    var _cortical_column_line = 'projections.append('
    var _cortical_column_line = 'Projection('
    var _cortical_column_line = 'populations[2 * src_l], populations[2 * tgt_l], weight=1.5, '
    var _cortical_column_line = ')'
    var _cortical_column_line = ')'
    var _cortical_column_line = '# Thalamic Poisson drive into L4 E'
    var _cortical_column_line = 'l4_e = populations[2]'
    var _cortical_column_line = 'stim = PoissonInput(l4_e.n, rate_hz=800.0, weight=8.0)'
    var _cortical_column_line = 'stim.target = l4_e'
    var _cortical_column_line = 'net = Network(seed=42)'
    var _cortical_column_line = 'for obj in populations + projections + monitors + [stim]:'
    var _cortical_column_line = 'net.add(obj)'
    return 0  # return net

fn central_pattern_generator(n_oscillators: Int) -> Int:
    var _central_pattern_generator_line = 'pops = []'
    var _central_pattern_generator_line = 'mons = []'
    var _central_pattern_generator_line = 'stims = []'
    var _central_pattern_generator_line = 'for i in range(n_oscillators):'
    var _central_pattern_generator_line = 'flex = Population('
    var _central_pattern_generator_line = 'HindmarshRoseNeuron, 5, label=f"cpg{i}_flex", params={"b": 3'
    var _central_pattern_generator_line = ')'
    var _central_pattern_generator_line = 'ext = Population('
    var _central_pattern_generator_line = 'HindmarshRoseNeuron, 5, label=f"cpg{i}_ext", params={"b": 3.'
    var _central_pattern_generator_line = ')'
    var _central_pattern_generator_line = 'pops.extend([flex, ext])'
    var _central_pattern_generator_line = 'mons.append(SpikeMonitor(flex, label=f"cpg{i}_flex_spikes"))'
    var _central_pattern_generator_line = 'mons.append(SpikeMonitor(ext, label=f"cpg{i}_ext_spikes"))'
    var _central_pattern_generator_line = 'projs = []'
    var _central_pattern_generator_line = 'for i in range(n_oscillators):'
    var _central_pattern_generator_line = 'flex = pops[2 * i]'
    var _central_pattern_generator_line = 'ext = pops[2 * i + 1]'
    var _central_pattern_generator_line = 'projs.append(Projection(flex, ext, weight=-2.0, probability='
    var _central_pattern_generator_line = 'projs.append(Projection(ext, flex, weight=-2.0, probability='
    var _central_pattern_generator_line = 'next_flex = pops[2 * ((i + 1) % n_oscillators)]'
    var _central_pattern_generator_line = 'projs.append(Projection(flex, next_flex, weight=1.0, probabi'
    var _central_pattern_generator_line = 'for i in range(n_oscillators):'
    var _central_pattern_generator_line = 'stim = PoissonInput(5, rate_hz=800.0, weight=5.0)'
    var _central_pattern_generator_line = 'stim.target = pops[2 * i]'
    var _central_pattern_generator_line = 'stims.append(stim)'
    var _central_pattern_generator_line = 'stim_ext = PoissonInput(5, rate_hz=800.0, weight=5.0)'
    var _central_pattern_generator_line = 'stim_ext.target = pops[2 * i + 1]'
    var _central_pattern_generator_line = 'stims.append(stim_ext)'
    var _central_pattern_generator_line = 'net = Network(seed=42)'
    var _central_pattern_generator_line = 'for obj in pops + projs + mons + stims:'
    var _central_pattern_generator_line = 'net.add(obj)'
    return 0  # return net

fn decision_making_circuit(n_per_pool: Int) -> Int:
    var _decision_making_circuit_line = 'pool_a = Population(HodgkinHuxleyNeuron, n_per_pool, label="'
    var _decision_making_circuit_line = 'pool_b = Population(HodgkinHuxleyNeuron, n_per_pool, label="'
    var _decision_making_circuit_line = 'n_nonsel = max(10, n_per_pool // 6)'
    var _decision_making_circuit_line = 'nonsel = Population(HodgkinHuxleyNeuron, n_nonsel, label="no'
    var _decision_making_circuit_line = 'n_inh = max(15, n_per_pool // 4)'
    var _decision_making_circuit_line = 'inh = Population(WangBuzsakiNeuron, n_inh, label="inhibitory'
    var _decision_making_circuit_line = '# Wang 2002: potentiated recurrent within pool, cross-inhibi'
    var _decision_making_circuit_line = 'projs = ['
    var _decision_making_circuit_line = 'Projection(pool_a, pool_a, weight=3.0, probability=0.15),'
    var _decision_making_circuit_line = 'Projection(pool_b, pool_b, weight=3.0, probability=0.15),'
    var _decision_making_circuit_line = 'Projection(pool_a, inh, weight=2.0, probability=0.2),'
    var _decision_making_circuit_line = 'Projection(pool_b, inh, weight=2.0, probability=0.2),'
    var _decision_making_circuit_line = 'Projection(inh, pool_a, weight=-4.0, probability=0.3),'
    var _decision_making_circuit_line = 'Projection(inh, pool_b, weight=-4.0, probability=0.3),'
    var _decision_making_circuit_line = 'Projection(nonsel, pool_a, weight=1.0, probability=0.1),'
    var _decision_making_circuit_line = 'Projection(nonsel, pool_b, weight=1.0, probability=0.1),'
    var _decision_making_circuit_line = 'Projection(nonsel, inh, weight=1.0, probability=0.1),'
    var _decision_making_circuit_line = ']'
    var _decision_making_circuit_line = 'stim_a = PoissonInput(n_per_pool, rate_hz=800.0, weight=15.0'
    var _decision_making_circuit_line = 'stim_a.target = pool_a'
    var _decision_making_circuit_line = 'stim_b = PoissonInput(n_per_pool, rate_hz=800.0, weight=15.0'
    var _decision_making_circuit_line = 'stim_b.target = pool_b'
    var _decision_making_circuit_line = 'stim_ns = PoissonInput(n_nonsel, rate_hz=600.0, weight=10.0)'
    var _decision_making_circuit_line = 'stim_ns.target = nonsel'
    var _decision_making_circuit_line = 'mon_a = SpikeMonitor(pool_a, label="pool_A_spikes")'
    var _decision_making_circuit_line = 'mon_b = SpikeMonitor(pool_b, label="pool_B_spikes")'
    return 0  # return Network(
    var _decision_making_circuit_line = 'pool_a, pool_b, nonsel, inh, *projs, stim_a, stim_b, stim_ns'
    var _decision_making_circuit_line = ')'

fn working_memory_circuit(n_neurons: Int) -> Int:
    var _working_memory_circuit_line = 'n_exc = int(0.8 * n_neurons)'
    var _working_memory_circuit_line = 'n_inh = n_neurons - n_exc'
    var _working_memory_circuit_line = 'exc = Population('
    var _working_memory_circuit_line = 'CompteWMNeuron,'
    var _working_memory_circuit_line = 'n_exc,'
    var _working_memory_circuit_line = 'label="wm_exc",'
    var _working_memory_circuit_line = 'params={"g_nmda": 0.165, "g_ampa": 0.005, "tau_nmda": 100.0,'
    var _working_memory_circuit_line = ')'
    var _working_memory_circuit_line = 'inh = Population(WangBuzsakiNeuron, n_inh, label="wm_inh")'
    var _working_memory_circuit_line = 'exc_conn = ring_topology(n_exc, k=min(20, n_exc // 4), weigh'
    var _working_memory_circuit_line = 'p_ee = Projection(exc, exc, weight=0.5, topology=exc_conn)'
    var _working_memory_circuit_line = 'p_ei = Projection(exc, inh, weight=2.0, probability=0.3)'
    var _working_memory_circuit_line = 'p_ie = Projection(inh, exc, weight=-3.0, probability=0.3)'
    var _working_memory_circuit_line = 'p_ii = Projection(inh, inh, weight=-2.0, probability=0.2)'
    var _working_memory_circuit_line = 'stim = PoissonInput(n_exc, rate_hz=800.0, weight=5.0)'
    var _working_memory_circuit_line = 'stim.target = exc'
    var _working_memory_circuit_line = 'mon_e = SpikeMonitor(exc, label="wm_exc_spikes")'
    var _working_memory_circuit_line = 'mon_i = SpikeMonitor(inh, label="wm_inh_spikes")'
    return 0  # return Network(exc, inh, p_ee, p_ei, p_ie, p_ii, s

fn auditory_processing(n_channels: Int) -> Int:
    var _auditory_processing_line = 'cochlear = Population(HodgkinHuxleyNeuron, n_channels, label'
    var _auditory_processing_line = 'onset = Population(WangBuzsakiNeuron, n_channels, label="ons'
    var _auditory_processing_line = 'integr = Population(HodgkinHuxleyNeuron, max(1, n_channels /'
    var _auditory_processing_line = 'p_co = Projection(cochlear, onset, weight=3.0, probability=0'
    var _auditory_processing_line = 'p_oo = Projection(onset, onset, weight=-2.0, probability=0.2'
    var _auditory_processing_line = 'p_oi = Projection(onset, integr, weight=3.0, probability=0.3'
    var _auditory_processing_line = 'stim = PoissonInput(n_channels, rate_hz=800.0, weight=15.0)'
    var _auditory_processing_line = 'stim.target = cochlear'
    var _auditory_processing_line = 'mon_c = SpikeMonitor(cochlear, label="cochlear_spikes")'
    var _auditory_processing_line = 'mon_i = SpikeMonitor(integr, label="integration_spikes")'
    return 0  # return Network(cochlear, onset, integr, p_co, p_oo

fn visual_cortex_v1(n_orientation: Int, n_per_orientation: Int) -> Int:
    var _visual_cortex_v1_line = 'simple_pops = []'
    var _visual_cortex_v1_line = 'complex_pops = []'
    var _visual_cortex_v1_line = 'mons = []'
    var _visual_cortex_v1_line = 'projs = []'
    var _visual_cortex_v1_line = 'n_complex = max(1, n_per_orientation // 2)'
    var _visual_cortex_v1_line = 'for i in range(n_orientation):'
    var _visual_cortex_v1_line = 'deg = i * 180 // n_orientation'
    var _visual_cortex_v1_line = 's = Population(HodgkinHuxleyNeuron, n_per_orientation, label'
    var _visual_cortex_v1_line = 'c = Population(WangBuzsakiNeuron, n_complex, label=f"complex'
    var _visual_cortex_v1_line = 'simple_pops.append(s)'
    var _visual_cortex_v1_line = 'complex_pops.append(c)'
    var _visual_cortex_v1_line = 'mons.append(SpikeMonitor(s, label=f"simple_{i}_spikes"))'
    var _visual_cortex_v1_line = 'mons.append(SpikeMonitor(c, label=f"complex_{i}_spikes"))'
    var _visual_cortex_v1_line = 'projs.append(Projection(s, c, weight=3.0, probability=0.5))'
    var _visual_cortex_v1_line = 'for i in range(n_orientation):'
    var _visual_cortex_v1_line = 'for j in range(n_orientation):'
    var _visual_cortex_v1_line = 'if i == j:'
    var _visual_cortex_v1_line = 'continue'
    var _visual_cortex_v1_line = 'dist = min(abs(i - j), n_orientation - abs(i - j))'
    var _visual_cortex_v1_line = 'w = -1.0 / (1.0 + dist)'
    var _visual_cortex_v1_line = 'projs.append(Projection(simple_pops[i], simple_pops[j], weig'
    var _visual_cortex_v1_line = 'stims = []'
    var _visual_cortex_v1_line = 'for s in simple_pops:'
    var _visual_cortex_v1_line = 'stim = PoissonInput(n_per_orientation, rate_hz=800.0, weight'
    var _visual_cortex_v1_line = 'stim.target = s'
    var _visual_cortex_v1_line = 'stims.append(stim)'
    var _visual_cortex_v1_line = 'net = Network(seed=42)'
    var _visual_cortex_v1_line = 'for obj in simple_pops + complex_pops + projs + mons + stims'
    var _visual_cortex_v1_line = 'net.add(obj)'
    return 0  # return net
