# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for demo_pattern_classification

fn run_pattern_trials(label: Int, x_inputs: Int, weight_values: Int, n_neurons: Int, T: Int, n_trials: Int) -> Int:
    var _run_pattern_trials_line = 'label: int,'
    var _run_pattern_trials_line = 'x_inputs: list[float],'
    var _run_pattern_trials_line = 'weight_values: list[float],'
    var _run_pattern_trials_line = 'n_neurons: int = 5,'
    var _run_pattern_trials_line = 'T: int = 2500,'
    var _run_pattern_trials_line = 'n_trials: int = 10,'
    var _run_pattern_trials_line = 'base_seed: int = 42,'
    var _run_pattern_trials_line = ') -> ndarray:'
    var _run_pattern_trials_line = 'rates = []'
    var _run_pattern_trials_line = 'for trial in range(n_trials):'
    var _run_pattern_trials_line = 'layer = SCDenseLayer('
    var _run_pattern_trials_line = 'n_neurons=n_neurons,'
    var _run_pattern_trials_line = 'x_inputs=x_inputs,'
    var _run_pattern_trials_line = 'weight_values=weight_values,'
    var _run_pattern_trials_line = 'x_min=0.0,'
    var _run_pattern_trials_line = 'x_max=0.1,'
    var _run_pattern_trials_line = 'w_min=0.0,'
    var _run_pattern_trials_line = 'w_max=1.0,'
    var _run_pattern_trials_line = 'length=4096,'
    var _run_pattern_trials_line = 'y_min=0.0,'
    var _run_pattern_trials_line = 'y_max=0.1,'
    var _run_pattern_trials_line = 'dt_ms=1.0,'
    var _run_pattern_trials_line = 'neuron_params=dict('
    var _run_pattern_trials_line = 'v_rest=0.0,'
    var _run_pattern_trials_line = 'v_reset=0.0,'
    var _run_pattern_trials_line = 'v_threshold=1.0,'
    var _run_pattern_trials_line = 'tau_mem=25.0,'
    var _run_pattern_trials_line = 'noise_std=0.03,'
    var _run_pattern_trials_line = 'resistance=1.0,'
    var _run_pattern_trials_line = '),'
    var _run_pattern_trials_line = 'base_seed=base_seed + label * 1000 + trial,'
    var _run_pattern_trials_line = ')'
    var _run_pattern_trials_line = 'layer.reset()'
    var _run_pattern_trials_line = 'layer.run(T)'
    var _run_pattern_trials_line = 'summary = layer.summary()'
    var _run_pattern_trials_line = 'rates.append([s["firing_rate_hz"] for s in summary["stats"]]'
    return 0  # return array(rates, dtype=float)

fn nearest_centroid_classify(sample: Int, centroid_A: Int, centroid_B: Int) -> Int:
    var _nearest_centroid_classify_line = 'sample: ndarray[Any, Any],'
    var _nearest_centroid_classify_line = 'centroid_A: ndarray[Any, Any],'
    var _nearest_centroid_classify_line = 'centroid_B: ndarray[Any, Any],'
    var _nearest_centroid_classify_line = ') -> int:'
    var _nearest_centroid_classify_line = 'dA = linalg.norm(sample - centroid_A)'
    var _nearest_centroid_classify_line = 'dB = linalg.norm(sample - centroid_B)'
    return 0  # return 0 if dA <= dB else 1

fn demo() -> Int:
    var _demo_line = '# Two different input patterns (3-channel) for the SC layer'
    var _demo_line = 'pattern_A = [0.02, 0.05, 0.08]  # e.g. "class 0"'
    var _demo_line = 'pattern_B = [0.08, 0.05, 0.02]  # e.g. "class 1" (reordered '
    var _demo_line = '# Shared weights for simplicity'
    var _demo_line = 'weight_values = [0.3, 0.6, 0.9]'
    var _demo_line = 'n_neurons = 5'
    var _demo_line = 'T_train = 2500'
    var _demo_line = 'T_test = 2500'
    var _demo_line = 'n_train = 10'
    var _demo_line = 'n_test = 20  # 10 samples per class'
    var _demo_line = '# --- TRAINING: collect firing-rate signatures for each patt'
    var _demo_line = 'rates_A = run_pattern_trials('
    var _demo_line = 'label=0,'
    var _demo_line = 'x_inputs=pattern_A,'
    var _demo_line = 'weight_values=weight_values,'
    var _demo_line = 'n_neurons=n_neurons,'
    var _demo_line = 'T=T_train,'
    var _demo_line = 'n_trials=n_train,'
    var _demo_line = 'base_seed=42,'
    var _demo_line = ')'
    var _demo_line = 'rates_B = run_pattern_trials('
    var _demo_line = 'label=1,'
    var _demo_line = 'x_inputs=pattern_B,'
    var _demo_line = 'weight_values=weight_values,'
    var _demo_line = 'n_neurons=n_neurons,'
    var _demo_line = 'T=T_train,'
    var _demo_line = 'n_trials=n_train,'
    var _demo_line = 'base_seed=42,'
    var _demo_line = ')'
    var _demo_line = 'centroid_A = rates_A.mean(axis=0)'
    var _demo_line = 'centroid_B = rates_B.mean(axis=0)'
    var _demo_line = 'print("Centroid A (firing rates per neuron):", centroid_A)'
    var _demo_line = 'print("Centroid B (firing rates per neuron):", centroid_B)'
    var _demo_line = '# --- TESTING: generate new samples and classify by nearest '
    var _demo_line = 'rates = run_pattern_trials('
    var _demo_line = 'label=label,'
    var _demo_line = 'x_inputs=pattern,'
    var _demo_line = 'weight_values=weight_values,'
    var _demo_line = 'n_neurons=n_neurons,'
    var _demo_line = 'T=T_test,'
    var _demo_line = 'n_trials=n_samples,'
    var _demo_line = 'base_seed=999,'
    var _demo_line = ')'
    var _demo_line = 'labels_true = full((n_samples,), label, dtype=int)'
    return 0  # return rates, labels_true
    var _demo_line = 'test_A, labels_A = gen_test_samples(0, pattern_A, n_samples='
    var _demo_line = 'test_B, labels_B = gen_test_samples(1, pattern_B, n_samples='
    var _demo_line = 'test_all = vstack([test_A, test_B])'
    var _demo_line = 'labels_true = concatenate([labels_A, labels_B])'
    var _demo_line = 'pred_list: list[int] = []'
    var _demo_line = 'for sample in test_all:'
    var _demo_line = 'y = nearest_centroid_classify(sample, centroid_A, centroid_B'
    var _demo_line = 'pred_list.append(y)'
    var _demo_line = 'preds = array(pred_list, dtype=int)'
    var _demo_line = 'accuracy = float((preds == labels_true).mean())'
    var _demo_line = 'print(f"\\nTest accuracy (nearest-centroid in firing-rate spa'
    var _demo_line = 'print("True labels: ", labels_true)'
    var _demo_line = 'print("Predicted:   ", preds)'

fn gen_test_samples(label: Int, pattern: Int, n_samples: Int) -> Int:
    var _gen_test_samples_line = 'rates = run_pattern_trials('
    var _gen_test_samples_line = 'label=label,'
    var _gen_test_samples_line = 'x_inputs=pattern,'
    var _gen_test_samples_line = 'weight_values=weight_values,'
    var _gen_test_samples_line = 'n_neurons=n_neurons,'
    var _gen_test_samples_line = 'T=T_test,'
    var _gen_test_samples_line = 'n_trials=n_samples,'
    var _gen_test_samples_line = 'base_seed=999,'
    var _gen_test_samples_line = ')'
    var _gen_test_samples_line = 'labels_true = full((n_samples,), label, dtype=int)'
    return 0  # return rates, labels_true

