# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for demo_swarm_control

fn _bar(value: Int, width: Int) -> Int:
    var __bar_line = 'filled = int(clip(value, 0, 1) * width)'
    return 0  # return "[" + "#" * filled + "." * (width - filled)

fn run_demo() -> Int:
    var _run_demo_line = 'print("=" * 64)'
    var _run_demo_line = 'print("  Neuromorphic Swarm Control -- Neuroevolution Demo")'
    var _run_demo_line = 'print("  SNN agents (soft-LIF) evolved via genetic algorithm'
    var _run_demo_line = 'print("=" * 64)'
    var _run_demo_line = '# --- Configuration ---'
    var _run_demo_line = 'agent_cfg = AgentConfig(n_sensory=20, n_hidden=16, n_motor=2'
    var _run_demo_line = 'env_cfg = EnvConfig('
    var _run_demo_line = 'width=100,'
    var _run_demo_line = 'height=100,'
    var _run_demo_line = 'n_agents=10,'
    var _run_demo_line = 'n_obstacles=3,'
    var _run_demo_line = 'n_targets=3,'
    var _run_demo_line = 'agent_config=agent_cfg,'
    var _run_demo_line = 'seed=7,'
    var _run_demo_line = ')'
    var _run_demo_line = 'evolver_cfg = EvolverConfig('
    var _run_demo_line = 'pop_size=12,'
    var _run_demo_line = 'n_elite=3,'
    var _run_demo_line = 'mutation_rate=0.15,'
    var _run_demo_line = 'mutation_std=0.3,'
    var _run_demo_line = 'n_eval_steps=100,'
    var _run_demo_line = 'agent_config=agent_cfg,'
    var _run_demo_line = 'env_config=env_cfg,'
    var _run_demo_line = 'seed=123,'
    var _run_demo_line = ')'
    var _run_demo_line = 'evolver = SwarmEvolver(evolver_cfg)'
    var _run_demo_line = 'print(f"\\n  Population : {evolver_cfg.pop_size}")'
    var _run_demo_line = 'print(f"  Weights/ind: {evolver.n_weights}")'
    var _run_demo_line = 'print(f"  Eval steps : {evolver_cfg.n_eval_steps}")'
    var _run_demo_line = 'print(f"  Agents     : {env_cfg.n_agents}")'
    var _run_demo_line = 'print(f"  Obstacles  : {env_cfg.n_obstacles}")'
    var _run_demo_line = 'print(f"  Targets    : {env_cfg.n_targets}")'
    var _run_demo_line = '# --- Evolution ---'
    var _run_demo_line = 'n_gen = 5'
    var _run_demo_line = 'print(f"\\n  Evolving {n_gen} generations ...\\n")'
    var _run_demo_line = 'for g in range(n_gen):'
    var _run_demo_line = 'best = evolver.evolve_generation()'
    var _run_demo_line = 'print(f"    Gen {g + 1:2d}  best fitness = {best:.4f}  {_bar'
    var _run_demo_line = 'hist = evolver.best_fitness_history'
    var _run_demo_line = 'delta = hist[-1] - hist[0]'
    var _run_demo_line = 'sign = "+" if delta >= 0 else ""'
    var _run_demo_line = 'print(f"\\n  Improvement over {n_gen} gens: {sign}{delta:.4f}'
    var _run_demo_line = '# --- Replay best individual ---'
    var _run_demo_line = 'print("\\n" + "-" * 64)'
    var _run_demo_line = 'print("  Replaying best agent for 100 steps")'
    var _run_demo_line = 'print("-" * 64)'
    var _run_demo_line = 'best_weights = evolver.get_best_weights()'
    var _run_demo_line = 'replay_env = SwarmEnvironment('
    var _run_demo_line = 'EnvConfig('
    var _run_demo_line = 'width=100,'
    var _run_demo_line = 'height=100,'
    var _run_demo_line = 'n_agents=10,'
    var _run_demo_line = 'n_obstacles=3,'
    var _run_demo_line = 'n_targets=3,'
    var _run_demo_line = 'agent_config=agent_cfg,'
    var _run_demo_line = 'seed=999,'
    var _run_demo_line = ')'
    var _run_demo_line = ')'
    var _run_demo_line = 'for agent in replay_env.agents:'
    var _run_demo_line = 'agent.weights = best_weights'
    var _run_demo_line = 'for step in range(100):'
    var _run_demo_line = 'replay_env.step(dt=1.0)'
    var _run_demo_line = 'if step % 20 == 0:'
    var _run_demo_line = 'positions = replay_env.get_positions()'
    var _run_demo_line = 'cx = positions[:, 0].mean()'
    var _run_demo_line = 'cy = positions[:, 1].mean()'
    var _run_demo_line = 'spread = sqrt(((positions - positions.mean(axis=0)) ** 2).su'
    var _run_demo_line = 'fitness = SwarmFitness.composite(replay_env)'
    var _run_demo_line = 'print('
    var _run_demo_line = 'f"    step {step:3d}  centroid=({cx:5.1f},{cy:5.1f})  "'
    var _run_demo_line = 'f"spread={spread:5.1f}  fitness={fitness:.3f}"'
    var _run_demo_line = ')'
    var _run_demo_line = '# --- Final state ---'
    var _run_demo_line = 'state = replay_env.get_state()'
    var _run_demo_line = 'print(f"\\n  Targets captured : {state[\'targets_captured\']}")'
    var _run_demo_line = 'print("  Final positions:")'
    var _run_demo_line = 'for i, (x, y) in enumerate(state["positions"]):'
    var _run_demo_line = 'print(f"    Agent {i:2d}: ({x:6.1f}, {y:6.1f})")'
    var _run_demo_line = 'print("\\n" + "=" * 64)'
    var _run_demo_line = 'print("  Demo complete.")'
    var _run_demo_line = 'print("=" * 64)'
    return 0

