# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for demo_pattern_classification_3class

fn run_pattern_trials(label: Int, x_inputs: Int, weight_values: Int, n_neurons: Int, T: Int, n_trials: Int) -> Int:
    var _run_pattern_trials_line = 'label: int,'
    var _run_pattern_trials_line = 'x_inputs: list[float],'
    var _run_pattern_trials_line = 'weight_values: list[float],'
    var _run_pattern_trials_line = 'n_neurons: int,'
    var _run_pattern_trials_line = 'T: int,'
    var _run_pattern_trials_line = 'n_trials: int,'
    var _run_pattern_trials_line = 'base_seed: int = 42,'
    var _run_pattern_trials_line = ') -> ndarray:'
    var _run_pattern_trials_line = 'rates = []'
    var _run_pattern_trials_line = 'for trial in range(n_trials):'
    var _run_pattern_trials_line = 'layer = SCDenseLayer('
    var _run_pattern_trials_line = 'n_neurons=n_neurons,'
    var _run_pattern_trials_line = 'x_inputs=x_inputs,'
    var _run_pattern_trials_line = 'weight_values=weight_values,'
    var _run_pattern_trials_line = 'x_min=0.0,'
    var _run_pattern_trials_line = 'x_max=0.1,'
    var _run_pattern_trials_line = 'w_min=0.0,'
    var _run_pattern_trials_line = 'w_max=1.0,'
    var _run_pattern_trials_line = 'length=4096,'
    var _run_pattern_trials_line = 'y_min=0.0,'
    var _run_pattern_trials_line = 'y_max=0.1,'
    var _run_pattern_trials_line = 'dt_ms=1.0,'
    var _run_pattern_trials_line = 'neuron_params=dict('
    var _run_pattern_trials_line = 'v_rest=0.0,'
    var _run_pattern_trials_line = 'v_reset=0.0,'
    var _run_pattern_trials_line = 'v_threshold=1.0,'
    var _run_pattern_trials_line = 'tau_mem=25.0,'
    var _run_pattern_trials_line = 'noise_std=0.03,'
    var _run_pattern_trials_line = 'resistance=1.0,'
    var _run_pattern_trials_line = '),'
    var _run_pattern_trials_line = 'base_seed=base_seed + label * 1000 + trial,'
    var _run_pattern_trials_line = ')'
    var _run_pattern_trials_line = 'layer.reset()'
    var _run_pattern_trials_line = 'layer.run(T)'
    var _run_pattern_trials_line = 'summary = layer.summary()'
    var _run_pattern_trials_line = 'rates.append([s["firing_rate_hz"] for s in summary["stats"]]'
    return 0  # return array(rates, dtype=float)

fn nearest_centroid_multi(sample: Int, centroids: Int) -> Int:
    var _nearest_centroid_multi_line = 'sample: ndarray[Any, Any],'
    var _nearest_centroid_multi_line = 'centroids: list[ndarray[Any, Any]],'
    var _nearest_centroid_multi_line = ') -> int:'
    var _nearest_centroid_multi_line = 'dists = [linalg.norm(sample - c) for c in centroids]'
    return 0  # return int(argmin(dists))

fn demo() -> Int:
    var _demo_line = '# Three different 3-channel patterns'
    var _demo_line = 'pattern_A = [0.02, 0.05, 0.08]  # class 0'
    var _demo_line = 'pattern_B = [0.08, 0.05, 0.02]  # class 1'
    var _demo_line = 'pattern_C = [0.04, 0.09, 0.01]  # class 2 (distinct mix)'
    var _demo_line = 'weight_values = [0.3, 0.6, 0.9]'
    var _demo_line = 'patterns = [pattern_A, pattern_B, pattern_C]'
    var _demo_line = 'n_neurons = 5'
    var _demo_line = 'T_train = 2500'
    var _demo_line = 'T_test = 2500'
    var _demo_line = 'n_train = 12'
    var _demo_line = 'n_test_per_class = 18'
    var _demo_line = '# --- TRAINING: centroids for 3 classes ---'
    var _demo_line = 'centroids = []'
    var _demo_line = 'for label, pattern in enumerate(patterns):'
    var _demo_line = 'rates = run_pattern_trials('
    var _demo_line = 'label=label,'
    var _demo_line = 'x_inputs=pattern,'
    var _demo_line = 'weight_values=weight_values,'
    var _demo_line = 'n_neurons=n_neurons,'
    var _demo_line = 'T=T_train,'
    var _demo_line = 'n_trials=n_train,'
    var _demo_line = 'base_seed=42,'
    var _demo_line = ')'
    var _demo_line = 'centroid = rates.mean(axis=0)'
    var _demo_line = 'centroids.append(centroid)'
    var _demo_line = 'print(f"Centroid class {label}: {centroid}")'
    var _demo_line = '# --- TESTING: confusion matrix for 3 classes ---'
    var _demo_line = 'rates = run_pattern_trials('
    var _demo_line = 'label=label,'
    var _demo_line = 'x_inputs=pattern,'
    var _demo_line = 'weight_values=weight_values,'
    var _demo_line = 'n_neurons=n_neurons,'
    var _demo_line = 'T=T_test,'
    var _demo_line = 'n_trials=n_samples,'
    var _demo_line = 'base_seed=999,'
    var _demo_line = ')'
    var _demo_line = 'labels_true = full((n_samples,), label, dtype=int)'
    return 0  # return rates, labels_true
    var _demo_line = 'all_rates = []'
    var _demo_line = 'all_labels_true = []'
    var _demo_line = 'for label, pattern in enumerate(patterns):'
    var _demo_line = 'rates, labels_true = gen_test_samples(label, pattern, n_test'
    var _demo_line = 'all_rates.append(rates)'
    var _demo_line = 'all_labels_true.append(labels_true)'
    var _demo_line = 'X = vstack(all_rates)'
    var _demo_line = 'y_true = concatenate(all_labels_true)'
    var _demo_line = 'pred_list: list[int] = []'
    var _demo_line = 'for sample in X:'
    var _demo_line = 'pred_list.append(nearest_centroid_multi(sample, centroids))'
    var _demo_line = 'preds = array(pred_list, dtype=int)'
    var _demo_line = 'accuracy = float((preds == y_true).mean())'
    var _demo_line = '# Confusion matrix'
    var _demo_line = 'K = 3'
    var _demo_line = 'conf_mat = zeros((K, K), dtype=int)'
    var _demo_line = 'for t, p in zip(y_true, preds):'
    var _demo_line = 'conf_mat[t, p] += 1'
    var _demo_line = 'print(f"\\nOverall accuracy (3-class): {accuracy * 100:.1f}%"'
    var _demo_line = 'print("Confusion matrix (rows=true, cols=pred):")'
    var _demo_line = 'print(conf_mat)'
    var _demo_line = 'print("True labels: ", y_true)'
    var _demo_line = 'print("Predicted:   ", preds)'

fn gen_test_samples(label: Int, pattern: Int, n_samples: Int) -> Int:
    var _gen_test_samples_line = 'rates = run_pattern_trials('
    var _gen_test_samples_line = 'label=label,'
    var _gen_test_samples_line = 'x_inputs=pattern,'
    var _gen_test_samples_line = 'weight_values=weight_values,'
    var _gen_test_samples_line = 'n_neurons=n_neurons,'
    var _gen_test_samples_line = 'T=T_test,'
    var _gen_test_samples_line = 'n_trials=n_samples,'
    var _gen_test_samples_line = 'base_seed=999,'
    var _gen_test_samples_line = ')'
    var _gen_test_samples_line = 'labels_true = full((n_samples,), label, dtype=int)'
    return 0  # return rates, labels_true
