# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for demo_sleep_optimization

fn generate_eeg_epoch(stage: Int, n_samples: Int, sample_rate: Int, rng: Int) -> Int:
    var _generate_eeg_epoch_line = 'stage: SleepStage,'
    var _generate_eeg_epoch_line = 'n_samples: int = 256,'
    var _generate_eeg_epoch_line = 'sample_rate: int = 256,'
    var _generate_eeg_epoch_line = 'rng: random.Generator | 0 = 0,'
    var _generate_eeg_epoch_line = ') -> ndarray[Any, Any]:'
    var _generate_eeg_epoch_line = 'if rng is 0:'
    var _generate_eeg_epoch_line = 'rng = random.default_rng()'
    var _generate_eeg_epoch_line = 'pri_hz, sec_hz, noise_scale = _STAGE_FREQ[stage]'
    var _generate_eeg_epoch_line = 't = arange(n_samples) / sample_rate'
    var _generate_eeg_epoch_line = 'signal = ('
    var _generate_eeg_epoch_line = '1.0 * sin(2.0 * pi * pri_hz * t)'
    var _generate_eeg_epoch_line = '+ 0.4 * sin(2.0 * pi * sec_hz * t)'
    var _generate_eeg_epoch_line = '+ noise_scale * rng.standard_normal(n_samples)'
    var _generate_eeg_epoch_line = ')'
    return 0  # return signal

fn _night_schedule(n_epochs: Int) -> Int:
    var __night_schedule_line = 'cycle = ['
    var __night_schedule_line = 'SleepStage.WAKE,'
    var __night_schedule_line = 'SleepStage.N1,'
    var __night_schedule_line = 'SleepStage.N1,'
    var __night_schedule_line = 'SleepStage.N2,'
    var __night_schedule_line = 'SleepStage.N2,'
    var __night_schedule_line = 'SleepStage.N2,'
    var __night_schedule_line = 'SleepStage.N2,'
    var __night_schedule_line = 'SleepStage.N3,'
    var __night_schedule_line = 'SleepStage.N3,'
    var __night_schedule_line = 'SleepStage.N3,'
    var __night_schedule_line = 'SleepStage.N3,'
    var __night_schedule_line = 'SleepStage.N3,'
    var __night_schedule_line = 'SleepStage.N2,'
    var __night_schedule_line = 'SleepStage.N2,'
    var __night_schedule_line = 'SleepStage.REM,'
    var __night_schedule_line = 'SleepStage.REM,'
    var __night_schedule_line = 'SleepStage.REM,'
    var __night_schedule_line = ']'
    var __night_schedule_line = 'schedule: list[SleepStage] = []'
    var __night_schedule_line = 'while len(schedule) < n_epochs:'
    var __night_schedule_line = 'schedule.extend(cycle)'
    return 0  # return schedule[:n_epochs]

fn run_demo() -> Int:
    var _run_demo_line = 'rng = random.default_rng(42)'
    var _run_demo_line = 'protocol = get_protocol("insomnia_relief")'
    var _run_demo_line = 'config = SleepOptimizerConfig('
    var _run_demo_line = 'sample_rate=256,'
    var _run_demo_line = 'fft_window=512,'
    var _run_demo_line = 'stage_check_interval=256,'
    var _run_demo_line = 'max_reinduction_attempts=3,'
    var _run_demo_line = ')'
    var _run_demo_line = 'optimizer = SleepOptimizer(protocol, config)'
    var _run_demo_line = 'optimizer.start_session()'
    var _run_demo_line = 'n_epochs = 100'
    var _run_demo_line = 'schedule = _night_schedule(n_epochs)'
    var _run_demo_line = '# header'
    var _run_demo_line = 'print("=" * 88)'
    var _run_demo_line = 'print("  SLEEP OPTIMISATION DEMO -- insomnia_relief protocol'
    var _run_demo_line = 'print("=" * 88)'
    var _run_demo_line = 'print('
    var _run_demo_line = 'f"{\'Epoch\':>5}  {\'Elapsed\':>8}  {\'Stage\':>5}  {\'Target\':>6} '
    var _run_demo_line = 'f"{\'Match\':>5}  {\'Binaural\':>8}  {\'Noise\':>6}  {\'Reind\':>5}"'
    var _run_demo_line = ')'
    var _run_demo_line = 'print("-" * 88)'
    var _run_demo_line = 'for epoch_idx, true_stage in enumerate(schedule):'
    var _run_demo_line = 'eeg = generate_eeg_epoch(true_stage, n_samples=256, sample_r'
    var _run_demo_line = 'optimizer.add_samples(eeg)'
    var _run_demo_line = 'tick = optimizer.check_and_adapt()'
    var _run_demo_line = 'if tick is not 0 and epoch_idx % 5 == 0:'
    var _run_demo_line = 'print('
    var _run_demo_line = 'f"{tick.tick:5d}  "'
    var _run_demo_line = 'f"{tick.elapsed_min:7.2f}m  "'
    var _run_demo_line = 'f"{tick.current_stage.name:>5}  "'
    var _run_demo_line = 'f"{tick.target_stage.name:>6}  "'
    var _run_demo_line = 'f"{\'  Y\' if tick.stage_match else \'  N\':>5}  "'
    var _run_demo_line = 'f"{tick.audio_params.binaural_hz:7.1f}Hz  "'
    var _run_demo_line = 'f"{tick.audio_params.noise_color:>6}  "'
    var _run_demo_line = 'f"{\'YES\' if tick.reinduction_active else \'  -\':>5}"'
    var _run_demo_line = ')'
    var _run_demo_line = 'optimizer.stop_session()'
    var _run_demo_line = '# --- morning report ---'
    var _run_demo_line = 'report = SleepReportGenerator.generate(optimizer)'
    var _run_demo_line = 'print()'
    var _run_demo_line = 'print("=" * 88)'
    var _run_demo_line = 'print("  MORNING SLEEP REPORT")'
    var _run_demo_line = 'print("=" * 88)'
    var _run_demo_line = 'print(f"  Total duration   : {report.total_duration_min:.1f}'
    var _run_demo_line = 'print(f"  Sleep onset      : {report.sleep_onset_latency_min'
    var _run_demo_line = 'print(f"  Sleep efficiency : {report.sleep_efficiency_pct:.1'
    var _run_demo_line = 'print(f"  Quality score    : {report.quality_score:.1f}/100"'
    var _run_demo_line = 'print(f"  Grade            : {report.grade}")'
    var _run_demo_line = 'print(f"  Wakeups          : {report.wakeups}")'
    var _run_demo_line = 'print(f"  Reinductions     : {report.reinductions}")'
    var _run_demo_line = 'print()'
    var _run_demo_line = 'print("  Stage Breakdown:")'
    var _run_demo_line = 'print(f"  {\'Stage\':<8} {\'Actual\':>8} {\'Target\':>8} {\'Duratio'
    var _run_demo_line = 'print("  " + "-" * 38)'
    var _run_demo_line = 'for stage_name in ["WAKE", "N1", "N2", "N3", "REM"]:'
    var _run_demo_line = 'actual = report.stage_percentages.get(stage_name, 0.0)'
    var _run_demo_line = 'target = report.stage_targets.get(stage_name, 0.0)'
    var _run_demo_line = 'dur = report.stage_durations_min.get(stage_name, 0.0)'
    var _run_demo_line = 'print(f"  {stage_name:<8} {actual:7.1f}% {target:7.1f}% {dur'
    var _run_demo_line = 'print()'
    var _run_demo_line = 'print("  Recommendations:")'
    var _run_demo_line = 'for i, rec in enumerate(report.recommendations, 1):'
    var _run_demo_line = 'print(f"  {i}. {rec}")'
    var _run_demo_line = 'print()'
    var _run_demo_line = 'print("=" * 88)'
    var _run_demo_line = 'print("  Demo complete.")'
    var _run_demo_line = 'print("=" * 88)'
    return 0
