# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for demo_adaptive_audio

fn _generate_eeg_chunk(rng: Int, n_samples: Int, target_hz: Int, sample_rate: Int, entrained_strength: Int, noise_level: Int) -> Int:
    var __generate_eeg_chunk_line = 'rng: random.RandomState,'
    var __generate_eeg_chunk_line = 'n_samples: int,'
    var __generate_eeg_chunk_line = 'target_hz: float,'
    var __generate_eeg_chunk_line = 'sample_rate: int,'
    var __generate_eeg_chunk_line = 'entrained_strength: float = 0.5,'
    var __generate_eeg_chunk_line = 'noise_level: float = 0.3,'
    var __generate_eeg_chunk_line = ') -> ndarray[Any, Any]:'
    var __generate_eeg_chunk_line = 't = arange(n_samples) / sample_rate'
    var __generate_eeg_chunk_line = '# Target sinusoid'
    var __generate_eeg_chunk_line = 'signal = entrained_strength * sin(2 * pi * target_hz * t)'
    var __generate_eeg_chunk_line = '# Background: mix of brain bands'
    var __generate_eeg_chunk_line = 'signal += 0.15 * sin(2 * pi * 2.5 * t)  # delta'
    var __generate_eeg_chunk_line = 'signal += 0.10 * sin(2 * pi * 6.0 * t)  # theta'
    var __generate_eeg_chunk_line = 'signal += 0.08 * sin(2 * pi * 20.0 * t)  # beta'
    var __generate_eeg_chunk_line = '# Noise'
    var __generate_eeg_chunk_line = 'signal += noise_level * rng.randn(n_samples)'
    return 0  # return signal

fn run_demo() -> Int:
    var _run_demo_line = 'rng = random.RandomState(42)'
    var _run_demo_line = '# ── 1. Create components ──────────────────────────────────'
    var _run_demo_line = 'profile = UserProfile('
    var _run_demo_line = 'user_id="demo_user",'
    var _run_demo_line = 'chronotype=Chronotype.BEAR,'
    var _run_demo_line = ')'
    var _run_demo_line = 'ssgf_cfg = SSGFConfig('
    var _run_demo_line = 'N=16,'
    var _run_demo_line = 'z_dim=120,'
    var _run_demo_line = 'lr_z=0.01,'
    var _run_demo_line = 'sigma_g=0.3,'
    var _run_demo_line = 'micro_steps=10,'
    var _run_demo_line = 'dt=0.001,'
    var _run_demo_line = 'noise=0.2,'
    var _run_demo_line = 'K_base=0.45,'
    var _run_demo_line = 'K_alpha=0.3,'
    var _run_demo_line = 'field_pressure=0.1,'
    var _run_demo_line = 'seed=42,'
    var _run_demo_line = ')'
    var _run_demo_line = 'ssgf = SSGFEngine(ssgf_cfg)'
    var _run_demo_line = 'evs_cfg = EVSConfig('
    var _run_demo_line = 'sample_rate=256,'
    var _run_demo_line = 'fft_window=512,'
    var _run_demo_line = 'baseline_duration_s=2.0,  # short for demo'
    var _run_demo_line = 'update_interval_samples=128,'
    var _run_demo_line = ')'
    var _run_demo_line = 'evs = EVSEngine(evs_cfg)'
    var _run_demo_line = 'adaptive = AdaptiveAudioEngine(ssgf, evs, profile)'
    var _run_demo_line = 'target_hz = profile.get_best_target_hz()'
    var _run_demo_line = '# ── 2. Baseline ───────────────────────────────────────────'
    var _run_demo_line = 'print("=" * 72)'
    var _run_demo_line = 'print("  SSGF Adaptive Audio Demo")'
    var _run_demo_line = 'print("  Chronotype: BEAR | Target: %.1f Hz (alpha)" % targe'
    var _run_demo_line = 'print("=" * 72)'
    var _run_demo_line = 'print("\\n  Recording baseline...")'
    var _run_demo_line = 'evs.start_baseline()'
    var _run_demo_line = 'baseline_samples = int(evs_cfg.baseline_duration_s * evs_cfg'
    var _run_demo_line = 'baseline_eeg = _generate_eeg_chunk('
    var _run_demo_line = 'rng,'
    var _run_demo_line = 'baseline_samples,'
    var _run_demo_line = 'target_hz,'
    var _run_demo_line = 'evs_cfg.sample_rate,'
    var _run_demo_line = 'entrained_strength=0.1,  # low during baseline'
    var _run_demo_line = 'noise_level=0.5,'
    var _run_demo_line = ')'
    var _run_demo_line = 'for v in baseline_eeg:'
    var _run_demo_line = 'evs.add_sample(float(v))'
    var _run_demo_line = 'print("  Baseline done: %s" % ({k: "%.4f" % v for k, v in ev'
    var _run_demo_line = 'evs.set_target(target_hz)'
    var _run_demo_line = '# ── 3. Run 50 adaptive ticks ──────────────────────────────'
    var _run_demo_line = 'print('
    var _run_demo_line = '"\\n  %s  %s  %s  %s  %s  %s  %s"'
    var _run_demo_line = '% ('
    var _run_demo_line = '"Tick".rjust(6),'
    var _run_demo_line = '"Phase".ljust(10),'
    var _run_demo_line = '"EVS".rjust(6),'
    var _run_demo_line = '"Verif".rjust(6),'
    var _run_demo_line = '"Bin.Hz".rjust(7),'
    var _run_demo_line = '"R".rjust(7),'
    var _run_demo_line = '"Theurgic".rjust(8),'
    var _run_demo_line = ')'
    var _run_demo_line = ')'
    var _run_demo_line = 'print("  " + "-" * 62)'
    var _run_demo_line = 'samples_per_tick = evs_cfg.update_interval_samples'
    var _run_demo_line = 'for tick in range(1, 51):'
    var _run_demo_line = '# Simulate increasing entrainment over time'
    var _run_demo_line = 'progress = tick / 50.0'
    var _run_demo_line = 'entrained_strength = 0.2 + 0.6 * progress'
    var _run_demo_line = 'noise_level = 0.5 - 0.3 * progress'
    var _run_demo_line = 'chunk = _generate_eeg_chunk('
    var _run_demo_line = 'rng,'
    var _run_demo_line = 'samples_per_tick,'
    var _run_demo_line = 'target_hz,'
    var _run_demo_line = 'evs_cfg.sample_rate,'
    var _run_demo_line = 'entrained_strength=entrained_strength,'
    var _run_demo_line = 'noise_level=noise_level,'
    var _run_demo_line = ')'
    var _run_demo_line = 'for v in chunk:'
    var _run_demo_line = 'evs.add_sample(float(v))'
    var _run_demo_line = 'snapshot = evs.compute()'
    var _run_demo_line = 'if snapshot is 0:'
    var _run_demo_line = 'continue'
    var _run_demo_line = 'audio = adaptive.on_evs_update(snapshot)'
    var _run_demo_line = 'verified_str = " YES" if snapshot.is_verified else "  no"'
    var _run_demo_line = 'theurgic_str = " YES" if audio.get("theurgic_mode", False) e'
    var _run_demo_line = 'print('
    var _run_demo_line = '"  %s  %s  %s  %s  %s  %s  %s"'
    var _run_demo_line = '% ('
    var _run_demo_line = 'str(tick).rjust(6),'
    var _run_demo_line = 'adaptive.current_phase.value.ljust(10),'
    var _run_demo_line = '("%.1f" % snapshot.evs_score).rjust(6),'
    var _run_demo_line = 'verified_str.rjust(6),'
    var _run_demo_line = '("%.2f" % audio["binaural_hz"]).rjust(7),'
    var _run_demo_line = '("%.4f" % audio["intensity"]).rjust(7),'
    var _run_demo_line = 'theurgic_str.rjust(8),'
    var _run_demo_line = ')'
    var _run_demo_line = ')'
    var _run_demo_line = '# ── 4. Session Report ─────────────────────────────────────'
    var _run_demo_line = 'report = adaptive.get_session_report()'
    var _run_demo_line = 'print("\\n" + "=" * 72)'
    var _run_demo_line = 'print("  Session Report")'
    var _run_demo_line = 'print("=" * 72)'
    var _run_demo_line = 'print("  Total ticks:    %d" % report.total_ticks)'
    var _run_demo_line = 'print("  Average EVS:    %.2f" % report.avg_evs)'
    var _run_demo_line = 'print("  Peak EVS:       %.2f" % report.peak_evs)'
    var _run_demo_line = 'print("  Verified %%:     %.1f%%" % report.verified_pct)'
    var _run_demo_line = 'print("  Grade:          %s" % report.grade)'
    var _run_demo_line = 'print("  Adaptations:    %d" % report.adaptations)'
    var _run_demo_line = 'print("  Phase durations: %s" % report.phase_durations)'
    var _run_demo_line = 'print('
    var _run_demo_line = '"  Final audio:    %s"'
    var _run_demo_line = '% {'
    var _run_demo_line = 'k: ("%.3f" % v if isinstance(v, float) else str(v))'
    var _run_demo_line = 'for k, v in report.final_audio.items()'
    var _run_demo_line = '}'
    var _run_demo_line = ')'
    var _run_demo_line = '# ── 5. Update profile ─────────────────────────────────────'
    var _run_demo_line = 'profile.update_from_session('
    var _run_demo_line = 'avg_evs=report.avg_evs,'
    var _run_demo_line = 'peak_evs=report.peak_evs,'
    var _run_demo_line = 'best_target_hz=target_hz,'
    var _run_demo_line = 'band_powers=evs._baseline_powers,'
    var _run_demo_line = ')'
    var _run_demo_line = 'print("\\n  Profile after session:")'
    var _run_demo_line = 'print("    Sessions:       %d" % profile.session_count)'
    var _run_demo_line = 'print("    Target Hz:      %.2f" % profile.get_best_target_h'
    var _run_demo_line = 'print("    Chronotype:     %s" % profile.chronotype.value)'
    var _run_demo_line = 'print("\\n" + "=" * 72)'
    var _run_demo_line = 'print("  Demo complete.")'
    var _run_demo_line = 'print("=" * 72)'
    return 0
