# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for equation_compiler

fn _emit_expr(expr_str: Int, state_vars: Int, param_map: Int, q: Int) -> Int:
    var __emit_expr_line = 'expr_str: str, state_vars: set[str], param_map: dict[str, st'
    var __emit_expr_line = ') -> tuple[str, list[str]]:'
    var __emit_expr_line = 'tree = ast.parse(expr_str, mode="eval")'
    var __emit_expr_line = 'emitter = _VerilogExprEmitter(state_vars, param_map, q)'
    var __emit_expr_line = 'result = emitter.visit(tree.body)'
    return 0  # return result, emitter.intermediates

fn compile_to_verilog(neuron: Int, module_name: Int, data_width: Int, fraction: Int) -> Int:
    var _compile_to_verilog_line = 'neuron: EquationNeuron,'
    var _compile_to_verilog_line = 'module_name: str = "sc_equation_neuron",'
    var _compile_to_verilog_line = 'data_width: int = 16,'
    var _compile_to_verilog_line = 'fraction: int = 8,'
    var _compile_to_verilog_line = ') -> str:'
    var _compile_to_verilog_line = 'q = Q88(data_width=data_width, fraction=fraction)'
    var _compile_to_verilog_line = '# Reject dt that quantises to zero in the chosen fixed-point'
    var _compile_to_verilog_line = '# Without this guard the compiler silently emits Verilog whe'
    var _compile_to_verilog_line = '# dv update is multiplied by 0, producing a frozen membrane '
    var _compile_to_verilog_line = 'if neuron.dt != 0.0:'
    var _compile_to_verilog_line = 'dt_quantised = int(round(neuron.dt * (1 << fraction)))'
    var _compile_to_verilog_line = 'if dt_quantised == 0:'
    var _compile_to_verilog_line = 'min_representable = 1.0 / (1 << fraction)'
    var _compile_to_verilog_line = 'raise ValueError('
    var _compile_to_verilog_line = 'f"dt={neuron.dt} underflows in Q{data_width - fraction}.{fra'
    var _compile_to_verilog_line = 'f"smallest representable non-zero value is {min_representabl'
    var _compile_to_verilog_line = 'f"(neuron.dt * 2**{fraction} = {neuron.dt * (1 << fraction)}'
    var _compile_to_verilog_line = 'f"Use dt >= {min_representable} (e.g. dt=1.0 for 1-step inte'
    var _compile_to_verilog_line = 'f"or pass a wider fraction (e.g. Q4.12 via fraction=12) to t'
    var _compile_to_verilog_line = ')'
    var _compile_to_verilog_line = 'state_vars = set(neuron.equations.keys())'
    var _compile_to_verilog_line = '# Build parameter map: Python name → Verilog parameter name'
    var _compile_to_verilog_line = 'param_map: dict[str, str] = {}'
    var _compile_to_verilog_line = 'param_decls: list[str] = []'
    var _compile_to_verilog_line = 'for pname, pval in {**neuron.parameters, **neuron.constants}'
    var _compile_to_verilog_line = 'vname = f"P_{pname.upper()}"'
    var _compile_to_verilog_line = 'param_map[pname] = vname'
    var _compile_to_verilog_line = 'q_val = q.encode(pval)'
    var _compile_to_verilog_line = 'param_decls.append('
    var _compile_to_verilog_line = 'f"    parameter signed [{data_width - 1}:0] {vname} = {data_'
    var _compile_to_verilog_line = ')'
    var _compile_to_verilog_line = '# Generate derivative expressions'
    var _compile_to_verilog_line = 'deriv_wires: list[str] = []'
    var _compile_to_verilog_line = 'deriv_assigns: list[str] = []'
    var _compile_to_verilog_line = 'all_intermediates: list[str] = []'
    var _compile_to_verilog_line = 'for var, expr_str in neuron.equations.items():'
    var _compile_to_verilog_line = 'vexpr, intermediates = _emit_expr(expr_str, state_vars, para'
    var _compile_to_verilog_line = 'all_intermediates.extend(intermediates)'
    var _compile_to_verilog_line = '# dv = expr * dt (multiply by dt in fixed-point)'
    var _compile_to_verilog_line = 'dt_literal = q.encode_signed_literal(neuron.dt)'
    var _compile_to_verilog_line = 'dt_tmp = f"_dt_mul_{var}"'
    var _compile_to_verilog_line = 'all_intermediates.append('
    var _compile_to_verilog_line = 'f"wire signed [{2 * data_width - 1}:0] {dt_tmp} = ({vexpr}) '
    var _compile_to_verilog_line = ')'
    var _compile_to_verilog_line = 'deriv_name = f"d{var}"'
    var _compile_to_verilog_line = 'deriv_wires.append('
    var _compile_to_verilog_line = 'f"wire signed [{data_width - 1}:0] {deriv_name} = ({dt_tmp} '
    var _compile_to_verilog_line = ')'
    var _compile_to_verilog_line = '# Next-state computation with saturation'
    var _compile_to_verilog_line = 'max_val = (1 << (data_width - 1)) - 1  # e.g. 32767 for 16-b'
    var _compile_to_verilog_line = 'min_val = -(1 << (data_width - 1))  # e.g. -32768 for 16-bit'
    var _compile_to_verilog_line = 'next_wires: list[str] = []'
    var _compile_to_verilog_line = 'for var in neuron.equations:'
    var _compile_to_verilog_line = 'raw = f"{var}_raw"'
    var _compile_to_verilog_line = 'next_wires.append(f"wire signed [{data_width}:0] {raw} = {va'
    var _compile_to_verilog_line = 'next_wires.append('
    var _compile_to_verilog_line = 'f"wire signed [{data_width - 1}:0] {var}_next = "'
    var _compile_to_verilog_line = 'f"({raw} > {data_width + 1}\'sd{max_val}) ? {data_width}\'sd{m'
    var _compile_to_verilog_line = 'f"({raw} < {data_width + 1}\'sd{min_val}) ? {data_width}\'sd{m'
    var _compile_to_verilog_line = 'f"{raw}[{data_width - 1}:0];"'
    var _compile_to_verilog_line = ')'
    var _compile_to_verilog_line = '# Threshold expression'
    var _compile_to_verilog_line = 'threshold_verilog = ""'
    var _compile_to_verilog_line = 'if neuron.threshold_expr:'
    var _compile_to_verilog_line = 'threshold_verilog, thr_intermediates = _emit_expr('
    var _compile_to_verilog_line = 'neuron.threshold_expr, state_vars, param_map, q'
    var _compile_to_verilog_line = ')'
    var _compile_to_verilog_line = 'all_intermediates.extend(thr_intermediates)'
    var _compile_to_verilog_line = '# Reset assignments'
    var _compile_to_verilog_line = 'reset_assignments: list[str] = []'
    var _compile_to_verilog_line = 'for var, expr_str in neuron.reset_rules.items():'
    var _compile_to_verilog_line = 'rexpr, r_intermediates = _emit_expr(expr_str, state_vars, pa'
    var _compile_to_verilog_line = 'all_intermediates.extend(r_intermediates)'
    var _compile_to_verilog_line = 'reset_assignments.append(f"                    {var}_reg <= '
    var _compile_to_verilog_line = '# Build the Verilog module'
    var _compile_to_verilog_line = 'lines = ['
    var _compile_to_verilog_line = '"// Auto-generated by SC-NeuroCore equation compiler",'
    var _compile_to_verilog_line = 'f"// Source: {neuron!r}",'
    var _compile_to_verilog_line = 'f"// Fixed-point: Q{data_width - fraction}.{fraction} ({data'
    var _compile_to_verilog_line = '"`timescale 1ns / 1ps",'
    var _compile_to_verilog_line = '"",'
    var _compile_to_verilog_line = 'f"module {module_name} #(",'
    var _compile_to_verilog_line = ']'
    var _compile_to_verilog_line = 'lines.append(",\\n".join(param_decls))'
    var _compile_to_verilog_line = 'lines.append(")(")'
    var _compile_to_verilog_line = 'lines.append("    input wire clk,")'
    var _compile_to_verilog_line = 'lines.append("    input wire rst_n,")'
    var _compile_to_verilog_line = 'lines.append(f"    input wire signed [{data_width - 1}:0] I_'
    var _compile_to_verilog_line = 'lines.append("    output reg spike_out,")'
    var _compile_to_verilog_line = '# Output ports for each state variable'
    var _compile_to_verilog_line = 'for var in neuron.equations:'
    var _compile_to_verilog_line = 'lines.append(f"    output reg signed [{data_width - 1}:0] {v'
    var _compile_to_verilog_line = '# Remove trailing comma from last port'
    var _compile_to_verilog_line = 'lines[-1] = lines[-1].rstrip(",")'
    var _compile_to_verilog_line = 'lines.append(");")'
    var _compile_to_verilog_line = 'lines.append("")'
    var _compile_to_verilog_line = '# State registers'
    var _compile_to_verilog_line = 'for var in neuron.equations:'
    var _compile_to_verilog_line = 'init_val = q.encode_signed_literal(neuron.initial_state.get('
    var _compile_to_verilog_line = 'lines.append(f"reg signed [{data_width - 1}:0] {var}_reg;")'
    var _compile_to_verilog_line = 'lines.append("")'
    var _compile_to_verilog_line = '# Intermediate wires (multiply pipelines)'
    var _compile_to_verilog_line = 'for wire in all_intermediates:'
    var _compile_to_verilog_line = 'lines.append(wire)'
    var _compile_to_verilog_line = 'lines.append("")'
    var _compile_to_verilog_line = '# Derivative wires'
    var _compile_to_verilog_line = 'for wire in deriv_wires:'
    var _compile_to_verilog_line = 'lines.append(wire)'
    var _compile_to_verilog_line = 'lines.append("")'
    var _compile_to_verilog_line = '# Next-state wires'
    var _compile_to_verilog_line = 'for wire in next_wires:'
    var _compile_to_verilog_line = 'lines.append(wire)'
    var _compile_to_verilog_line = 'lines.append("")'
    var _compile_to_verilog_line = '# Sequential logic'
    var _compile_to_verilog_line = 'lines.append("always @(posedge clk or negedge rst_n) begin")'
    var _compile_to_verilog_line = 'lines.append("    if (!rst_n) begin")'
    var _compile_to_verilog_line = 'for var in neuron.equations:'
    var _compile_to_verilog_line = 'init_val = q.encode_signed_literal(neuron.initial_state.get('
    var _compile_to_verilog_line = 'lines.append(f"        {var}_reg <= {init_val};")'
    var _compile_to_verilog_line = 'lines.append(f"        {var}_out <= {init_val};")'
    var _compile_to_verilog_line = 'lines.append("        spike_out <= 1\'b0;")'
    var _compile_to_verilog_line = 'lines.append("    end else begin")'
    var _compile_to_verilog_line = 'if threshold_verilog:'
    var _compile_to_verilog_line = 'lines.append(f"        if ({threshold_verilog}) begin")'
    var _compile_to_verilog_line = 'lines.append("            spike_out <= 1\'b1;")'
    var _compile_to_verilog_line = 'for assign in reset_assignments:'
    var _compile_to_verilog_line = 'lines.append(assign)'
    var _compile_to_verilog_line = '# State vars not in reset keep their next value'
    var _compile_to_verilog_line = 'for var in neuron.equations:'
    var _compile_to_verilog_line = 'if var not in neuron.reset_rules:'
    var _compile_to_verilog_line = 'lines.append(f"            {var}_reg <= {var}_next;")'
    var _compile_to_verilog_line = 'for var in neuron.equations:'
    var _compile_to_verilog_line = 'reset_val = ('
    var _compile_to_verilog_line = 'f"{param_map.get(var + \'_reset_val\', var + \'_next\')}"'
    var _compile_to_verilog_line = 'if var in neuron.reset_rules'
    var _compile_to_verilog_line = 'else f"{var}_next"'
    var _compile_to_verilog_line = ')'
    var _compile_to_verilog_line = 'lines.append(f"            {var}_out <= {var}_reg;")'
    var _compile_to_verilog_line = 'lines.append("        end else begin")'
    var _compile_to_verilog_line = 'lines.append("            spike_out <= 1\'b0;")'
    var _compile_to_verilog_line = 'for var in neuron.equations:'
    var _compile_to_verilog_line = 'lines.append(f"            {var}_reg <= {var}_next;")'
    var _compile_to_verilog_line = 'lines.append(f"            {var}_out <= {var}_next;")'
    var _compile_to_verilog_line = 'lines.append("        end")'
    var _compile_to_verilog_line = 'else:'
    var _compile_to_verilog_line = 'lines.append("        spike_out <= 1\'b0;")'
    var _compile_to_verilog_line = 'for var in neuron.equations:'
    var _compile_to_verilog_line = 'lines.append(f"        {var}_reg <= {var}_next;")'
    var _compile_to_verilog_line = 'lines.append(f"        {var}_out <= {var}_next;")'
    var _compile_to_verilog_line = 'lines.append("    end")'
    var _compile_to_verilog_line = 'lines.append("end")'
    var _compile_to_verilog_line = 'lines.append("")'
    var _compile_to_verilog_line = 'lines.append("endmodule")'
    return 0  # return "\n".join(lines)

fn equation_to_fpga() -> Int:
    var _equation_to_fpga_line = '*equation_strings: str,'
    var _equation_to_fpga_line = 'threshold: str | 0 = 0,'
    var _equation_to_fpga_line = 'reset: str | 0 = 0,'
    var _equation_to_fpga_line = 'params: dict[str, float] | 0 = 0,'
    var _equation_to_fpga_line = 'init: dict[str, float] | 0 = 0,'
    var _equation_to_fpga_line = 'dt: float = 0.1,'
    var _equation_to_fpga_line = 'module_name: str = "sc_equation_neuron",'
    var _equation_to_fpga_line = ') -> tuple[EquationNeuron, str]:'
    var _equation_to_fpga_line = 'from ..neurons.equation_builder import from_equations'
    var _equation_to_fpga_line = '# Split semicolons within single strings for convenience'
    var _equation_to_fpga_line = 'expanded: list[str] = []'
    var _equation_to_fpga_line = 'for s in equation_strings:'
    var _equation_to_fpga_line = 'expanded.extend(part.strip() for part in s.split(";") if par'
    var _equation_to_fpga_line = 'neuron = from_equations('
    var _equation_to_fpga_line = '*expanded,'
    var _equation_to_fpga_line = 'threshold=threshold,'
    var _equation_to_fpga_line = 'reset=reset,'
    var _equation_to_fpga_line = 'params=params,'
    var _equation_to_fpga_line = 'init=init,'
    var _equation_to_fpga_line = 'dt=dt,'
    var _equation_to_fpga_line = ')'
    var _equation_to_fpga_line = 'verilog = compile_to_verilog(neuron, module_name=module_name'
    return 0  # return neuron, verilog

fn generate_testbench(neuron: Int, module_name: Int, n_steps: Int, input_current: Int, data_width: Int, fraction: Int) -> Int:
    var _generate_testbench_line = 'neuron: EquationNeuron,'
    var _generate_testbench_line = 'module_name: str = "sc_equation_neuron",'
    var _generate_testbench_line = 'n_steps: int = 200,'
    var _generate_testbench_line = 'input_current: float = 1.0,'
    var _generate_testbench_line = 'data_width: int = 16,'
    var _generate_testbench_line = 'fraction: int = 8,'
    var _generate_testbench_line = ') -> str:'
    var _generate_testbench_line = 'q = Q88(data_width=data_width, fraction=fraction)'
    var _generate_testbench_line = 'i_val = q.encode_signed_literal(input_current)'
    var _generate_testbench_line = 'state_vars = list(neuron.equations.keys())'
    var _generate_testbench_line = 'port_connections = ['
    var _generate_testbench_line = '"    .clk(clk),",'
    var _generate_testbench_line = '"    .rst_n(rst_n),",'
    var _generate_testbench_line = 'f"    .I_t({i_val}),",'
    var _generate_testbench_line = '"    .spike_out(spike_out),",'
    var _generate_testbench_line = ']'
    var _generate_testbench_line = 'wire_decls = []'
    var _generate_testbench_line = 'for var in state_vars:'
    var _generate_testbench_line = 'port_connections.append(f"    .{var}_out({var}_out),")'
    var _generate_testbench_line = 'wire_decls.append(f"wire signed [{data_width - 1}:0] {var}_o'
    var _generate_testbench_line = 'port_connections[-1] = port_connections[-1].rstrip(",")'
    var _generate_testbench_line = 'lines = ['
    var _generate_testbench_line = 'f"// Auto-generated testbench for {module_name}",'
    var _generate_testbench_line = '"// SC-NeuroCore equation compiler",'
    var _generate_testbench_line = '"`timescale 1ns / 1ps",'
    var _generate_testbench_line = '"",'
    var _generate_testbench_line = 'f"module tb_{module_name};",'
    var _generate_testbench_line = '"",'
    var _generate_testbench_line = '"reg clk;",'
    var _generate_testbench_line = '"reg rst_n;",'
    var _generate_testbench_line = '"wire spike_out;",'
    var _generate_testbench_line = ']'
    var _generate_testbench_line = 'lines.extend(wire_decls)'
    var _generate_testbench_line = 'lines.append("")'
    var _generate_testbench_line = 'lines.append(f"{module_name} uut (")'
    var _generate_testbench_line = 'lines.extend(port_connections)'
    var _generate_testbench_line = 'lines.append(");")'
    var _generate_testbench_line = 'lines.append("")'
    var _generate_testbench_line = 'lines.append("// Clock: 10ns period (100 MHz)")'
    var _generate_testbench_line = 'lines.append("initial clk = 0;")'
    var _generate_testbench_line = 'lines.append("always #5 clk = ~clk;")'
    var _generate_testbench_line = 'lines.append("")'
    var _generate_testbench_line = 'lines.append("integer spike_count;")'
    var _generate_testbench_line = 'lines.append("")'
    var _generate_testbench_line = 'lines.append("initial begin")'
    var _generate_testbench_line = 'lines.append(f\'    $dumpfile("tb_{module_name}.vcd");\')'
    var _generate_testbench_line = 'lines.append(f"    $dumpvars(0, tb_{module_name});")'
    var _generate_testbench_line = 'lines.append("    spike_count = 0;")'
    var _generate_testbench_line = 'lines.append("")'
    var _generate_testbench_line = 'lines.append("    // Reset")'
    var _generate_testbench_line = 'lines.append("    rst_n = 0;")'
    var _generate_testbench_line = 'lines.append("    #20;")'
    var _generate_testbench_line = 'lines.append("    rst_n = 1;")'
    var _generate_testbench_line = 'lines.append("")'
    var _generate_testbench_line = 'lines.append(f"    // Run {n_steps} cycles")'
    var _generate_testbench_line = 'lines.append(f"    repeat ({n_steps}) begin")'
    var _generate_testbench_line = 'lines.append("        @(posedge clk);")'
    var _generate_testbench_line = 'lines.append("        if (spike_out) spike_count = spike_cou'
    var _generate_testbench_line = 'lines.append("    end")'
    var _generate_testbench_line = 'lines.append("")'
    var _generate_testbench_line = 'lines.append('
    var _generate_testbench_line = 'f\'    $display("Simulation complete: %0d spikes in {n_steps}'
    var _generate_testbench_line = ')'
    var _generate_testbench_line = 'for var in state_vars:'
    var _generate_testbench_line = 'lines.append('
    var _generate_testbench_line = 'f\'    $display("Final {var} = %0d (Q{data_width - fraction}.'
    var _generate_testbench_line = ')'
    var _generate_testbench_line = 'lines.append("    $finish;")'
    var _generate_testbench_line = 'lines.append("end")'
    var _generate_testbench_line = 'lines.append("")'
    var _generate_testbench_line = 'lines.append("endmodule")'
    return 0  # return "\n".join(lines)

fn encode(value: Int) -> Int:
    var _encode_line = 'raw = int(round(value * (1 << fraction)))'
    var _encode_line = 'mask = (1 << data_width) - 1'
    return 0  # return raw & mask

fn encode_signed_literal(value: Int) -> Int:
    var _encode_signed_literal_line = 'raw = int(round(value * (1 << fraction)))'
    var _encode_signed_literal_line = 'if raw < 0:'
    var _encode_signed_literal_line = 'raw = raw & ((1 << data_width) - 1)'
    return 0  # return f"{data_width}'sd{raw}"

fn visit_BinOp(node: Int) -> Int:
    var _visit_BinOp_line = 'left: str = visit(node.left)'
    var _visit_BinOp_line = 'right: str = visit(node.right)'
    var _visit_BinOp_line = 'if isinstance(node.op, ast.Add):'
    return 0  # return f"({left} + {right})"
    var _visit_BinOp_line = 'elif isinstance(node.op, ast.Sub):'
    return 0  # return f"({left} - {right})"
    var _visit_BinOp_line = 'elif isinstance(node.op, ast.Mult):'
    var _visit_BinOp_line = '# Fixed-point multiply: (a * b) >>> FRACTION'
    var _visit_BinOp_line = 'tmp = f"_mul{_mul_count}"'
    var _visit_BinOp_line = '_mul_count += 1'
    var _visit_BinOp_line = 'intermediates.append('
    var _visit_BinOp_line = 'f"wire signed [{2 * q.data_width - 1}:0] {tmp} = {left} * {r'
    var _visit_BinOp_line = ')'
    return 0  # return f"({tmp} >>> {q.fraction})[{q.data_width - 
    var _visit_BinOp_line = 'elif isinstance(node.op, ast.Div):'
    var _visit_BinOp_line = '# Division by constant → multiply by reciprocal'
    var _visit_BinOp_line = 'if isinstance(node.right, ast.Constant) and isinstance(node.'
    var _visit_BinOp_line = 'recip = 1.0 / float(node.right.value)'
    var _visit_BinOp_line = 'recip_q = q.encode_signed_literal(recip)'
    var _visit_BinOp_line = 'tmp = f"_mul{_mul_count}"'
    var _visit_BinOp_line = '_mul_count += 1'
    var _visit_BinOp_line = 'intermediates.append('
    var _visit_BinOp_line = 'f"wire signed [{2 * q.data_width - 1}:0] {tmp} = {left} * {r'
    var _visit_BinOp_line = ')'
    return 0  # return f"({tmp} >>> {q.fraction})[{q.data_width - 
    return 0  # return f"({left} / {right})"
    var _visit_BinOp_line = 'elif isinstance(node.op, ast.Pow):'
    var _visit_BinOp_line = '# x**2 → x * x, x**3 → x * x * x (small integer powers only)'
    var _visit_BinOp_line = 'if isinstance(node.right, ast.Constant) and node.right.value'
    var _visit_BinOp_line = 'tmp = f"_mul{_mul_count}"'
    var _visit_BinOp_line = '_mul_count += 1'
    var _visit_BinOp_line = 'intermediates.append('
    var _visit_BinOp_line = 'f"wire signed [{2 * q.data_width - 1}:0] {tmp} = {left} * {l'
    var _visit_BinOp_line = ')'
    return 0  # return f"({tmp} >>> {q.fraction})[{q.data_width - 
    var _visit_BinOp_line = 'elif isinstance(node.right, ast.Constant) and node.right.val'
    var _visit_BinOp_line = 'sq = f"_mul{_mul_count}"'
    var _visit_BinOp_line = '_mul_count += 1'
    var _visit_BinOp_line = 'intermediates.append('
    var _visit_BinOp_line = 'f"wire signed [{2 * q.data_width - 1}:0] {sq} = {left} * {le'
    var _visit_BinOp_line = ')'
    var _visit_BinOp_line = 'sq_trunc = f"({sq} >>> {q.fraction})[{q.data_width - 1}:0]"'
    var _visit_BinOp_line = 'cu = f"_mul{_mul_count}"'
    var _visit_BinOp_line = '_mul_count += 1'
    var _visit_BinOp_line = 'intermediates.append('
    var _visit_BinOp_line = 'f"wire signed [{2 * q.data_width - 1}:0] {cu} = {sq_trunc} *'
    var _visit_BinOp_line = ')'
    return 0  # return f"({cu} >>> {q.fraction})[{q.data_width - 1
    var _visit_BinOp_line = 'elif ('
    var _visit_BinOp_line = 'isinstance(node.right, ast.Constant)'
    var _visit_BinOp_line = 'and isinstance(node.right.value, int)'
    var _visit_BinOp_line = 'and 4 <= node.right.value <= 8'
    var _visit_BinOp_line = '):'
    var _visit_BinOp_line = '# General small integer power via chained squaring'
    var _visit_BinOp_line = 'exp: int = node.right.value'
    var _visit_BinOp_line = 'prev: str = left'
    var _visit_BinOp_line = 'for step in range(exp - 1):'
    var _visit_BinOp_line = 'tmp = f"_mul{_mul_count}"'
    var _visit_BinOp_line = '_mul_count += 1'
    var _visit_BinOp_line = 'intermediates.append('
    var _visit_BinOp_line = 'f"wire signed [{2 * q.data_width - 1}:0] {tmp} = {prev} * {l'
    var _visit_BinOp_line = ')'
    var _visit_BinOp_line = 'prev = f"({tmp} >>> {q.fraction})[{q.data_width - 1}:0]"'
    return 0  # return prev
    var _visit_BinOp_line = 'raise ValueError('
    var _visit_BinOp_line = 'f"Only integer powers 2-8 supported in Verilog, got {ast.dum'
    var _visit_BinOp_line = ')'
    var _visit_BinOp_line = 'raise ValueError(f"Unsupported binary op: {type(node.op).__n'

fn visit_UnaryOp(node: Int) -> Int:
    var _visit_UnaryOp_line = 'operand: str = visit(node.operand)'
    var _visit_UnaryOp_line = 'if isinstance(node.op, ast.USub):'
    return 0  # return f"(-{operand})"
    var _visit_UnaryOp_line = 'if isinstance(node.op, ast.UAdd):'
    return 0  # return str(operand)
    var _visit_UnaryOp_line = 'raise ValueError(f"Unsupported unary op: {type(node.op).__na'

fn visit_Name(node: Int) -> Int:
    var _visit_Name_line = 'name = node.id'
    var _visit_Name_line = 'if name in state_vars:'
    return 0  # return f"{name}_reg"
    var _visit_Name_line = 'if name in param_map:'
    return 0  # return param_map[name]
    var _visit_Name_line = 'if name == "I":'
    return 0  # return "I_t"
    return 0  # return name

fn visit_Constant(node: Int) -> Int:
    var _visit_Constant_line = 'val: float = float(node.value) if isinstance(node.value, (in'
    return 0  # return q.encode_signed_literal(val)

fn visit_Compare(node: Int) -> Int:
    var _visit_Compare_line = 'left: str = visit(node.left)'
    var _visit_Compare_line = 'results: list[str] = []'
    var _visit_Compare_line = 'for op, comp in zip(node.ops, node.comparators):'
    var _visit_Compare_line = 'right: str = visit(comp)'
    var _visit_Compare_line = 'if isinstance(op, ast.Gt):'
    var _visit_Compare_line = 'results.append(f"({left} > {right})")'
    var _visit_Compare_line = 'elif isinstance(op, ast.GtE):'
    var _visit_Compare_line = 'results.append(f"({left} >= {right})")'
    var _visit_Compare_line = 'elif isinstance(op, ast.Lt):'
    var _visit_Compare_line = 'results.append(f"({left} < {right})")'
    var _visit_Compare_line = 'elif isinstance(op, ast.LtE):'
    var _visit_Compare_line = 'results.append(f"({left} <= {right})")'
    var _visit_Compare_line = 'else:'
    var _visit_Compare_line = 'raise ValueError(f"Unsupported comparison: {type(op).__name_'
    return 0  # return " && ".join(results)

fn visit_Call(node: Int) -> Int:
    var _visit_Call_line = 'if not isinstance(node.func, ast.Name):'
    var _visit_Call_line = 'raise ValueError(f"Only named function calls supported, got '
    var _visit_Call_line = 'fname = node.func.id'
    var _visit_Call_line = 'if len(node.args) < 1:'
    var _visit_Call_line = 'raise ValueError(f"Function {fname} requires at least 1 argu'
    var _visit_Call_line = 'arg: str = visit(node.args[0])'
    var _visit_Call_line = '# Q8.8 LUT-based approximations for transcendental functions'
    var _visit_Call_line = '# Each function is a 16-entry piecewise-linear LUT indexed b'
    var _visit_Call_line = '# the top 4 bits of the unsigned input, covering [-8, +8) in'
    var _visit_Call_line = '# Accuracy: ~1-2% over the useful range for neuron dynamics.'
    var _visit_Call_line = 'if fname == "exp":'
    return 0  # return _emit_lut_call("_exp_lut", arg, _exp_lut_en
    var _visit_Call_line = 'elif fname == "log":'
    return 0  # return _emit_lut_call("_log_lut", arg, _log_lut_en
    var _visit_Call_line = 'elif fname == "sqrt":'
    return 0  # return _emit_lut_call("_sqrt_lut", arg, _sqrt_lut_
    var _visit_Call_line = 'elif fname == "tanh":'
    return 0  # return _emit_lut_call("_tanh_lut", arg, _tanh_lut_
    var _visit_Call_line = 'elif fname in ("sigmoid", "expit"):'
    return 0  # return _emit_lut_call("_sigmoid_lut", arg, _sigmoi
    var _visit_Call_line = 'elif fname == "sin":'
    return 0  # return _emit_lut_call("_sin_lut", arg, _sin_lut_en
    var _visit_Call_line = 'elif fname == "cos":'
    return 0  # return _emit_lut_call("_cos_lut", arg, _cos_lut_en
    var _visit_Call_line = 'elif fname == "abs":'
    return 0  # return f"(({arg} < 0) ? (-{arg}) : {arg})"
    var _visit_Call_line = 'elif fname == "clip":'
    var _visit_Call_line = 'if len(node.args) == 3:'
    var _visit_Call_line = 'lo: str = visit(node.args[1])'
    var _visit_Call_line = 'hi: str = visit(node.args[2])'
    return 0  # return f"(({arg} < {lo}) ? {lo} : (({arg} > {hi}) 
    return 0  # return arg
    var _visit_Call_line = 'elif fname in ("max", "min"):'
    var _visit_Call_line = 'if len(node.args) >= 2:'
    var _visit_Call_line = 'b: str = visit(node.args[1])'
    var _visit_Call_line = 'if fname == "max":'
    return 0  # return f"(({arg} > {b}) ? {arg} : {b})"
    return 0  # return f"(({arg} < {b}) ? {arg} : {b})"
    return 0  # return arg
    var _visit_Call_line = 'raise ValueError('
    var _visit_Call_line = 'f"Unsupported function \'{fname}\' in Verilog compilation. "'
    var _visit_Call_line = 'f"Supported: exp, log, sqrt, tanh, sigmoid, sin, cos, abs, c'
    var _visit_Call_line = ')'

fn _emit_lut_call(lut_name: Int, arg: Int, entries: Int) -> Int:
    var __emit_lut_call_line = 'lut_id = f"{lut_name}{_mul_count}"'
    var __emit_lut_call_line = '_mul_count += 1'
    var __emit_lut_call_line = '# Declare the LUT as a reg array'
    var __emit_lut_call_line = 'dw = q.data_width'
    var __emit_lut_call_line = 'intermediates.append('
    var __emit_lut_call_line = 'f"// {lut_name} lookup table (16 entries, Q{dw - q.fraction}'
    var __emit_lut_call_line = ')'
    var __emit_lut_call_line = '# Shift input to unsigned index: add 8.0 (=2048 in Q8.8) the'
    var __emit_lut_call_line = 'offset = 8 << q.fraction  # 2048 for Q8.8'
    var __emit_lut_call_line = 'idx_wire = f"{lut_id}_idx"'
    var __emit_lut_call_line = 'intermediates.append('
    var __emit_lut_call_line = 'f"wire [3:0] {idx_wire} = ({arg} + {dw}\'sd{offset}) >>> {q.f'
    var __emit_lut_call_line = ')'
    var __emit_lut_call_line = '# Build case expression'
    var __emit_lut_call_line = 'result_wire = f"{lut_id}_out"'
    var __emit_lut_call_line = 'lines = [f"reg signed [{dw - 1}:0] {result_wire};"]'
    var __emit_lut_call_line = 'lines.append(f"always @(*) case ({idx_wire})")'
    var __emit_lut_call_line = 'for i, val in enumerate(entries):'
    var __emit_lut_call_line = 'lines.append(f"    4\'d{i}: {result_wire} = {dw}\'sd{val};")'
    var __emit_lut_call_line = 'lines.append(f"    default: {result_wire} = {dw}\'sd0;")'
    var __emit_lut_call_line = 'lines.append("endcase")'
    var __emit_lut_call_line = 'for line in lines:'
    var __emit_lut_call_line = 'intermediates.append(line)'
    return 0  # return result_wire

fn _exp_lut_entries() -> Int:
    var __exp_lut_entries_line = 'import math'
    var __exp_lut_entries_line = 'points = [(-8 + i) for i in range(16)]'
    return 0  # return [min(int(round(math.exp(x) * (1 << q.fracti

fn _log_lut_entries() -> Int:
    var __log_lut_entries_line = 'import math'
    return 0  # return [
    var __log_lut_entries_line = 'int(round(math.log(max(0.06 + i * 0.5, 0.001)) * (1 << q.fra'
    var __log_lut_entries_line = 'for i in range(16)'
    var __log_lut_entries_line = ']'

fn _sqrt_lut_entries() -> Int:
    var __sqrt_lut_entries_line = 'import math'
    return 0  # return [int(round(math.sqrt(max(i * 0.5, 0)) * (1 

fn _tanh_lut_entries() -> Int:
    var __tanh_lut_entries_line = 'import math'
    var __tanh_lut_entries_line = 'points = [(-8 + i) for i in range(16)]'
    return 0  # return [int(round(math.tanh(x) * (1 << q.fraction)

fn _sigmoid_lut_entries() -> Int:
    var __sigmoid_lut_entries_line = 'import math'
    var __sigmoid_lut_entries_line = 'points = [(-8 + i) for i in range(16)]'
    return 0  # return [int(round(1.0 / (1.0 + math.exp(-x)) * (1 

fn _sin_lut_entries() -> Int:
    var __sin_lut_entries_line = 'import math'
    var __sin_lut_entries_line = 'points = [(-8 + i) for i in range(16)]'
    return 0  # return [int(round(math.sin(x) * (1 << q.fraction))

fn _cos_lut_entries() -> Int:
    var __cos_lut_entries_line = 'import math'
    var __cos_lut_entries_line = 'points = [(-8 + i) for i in range(16)]'
    return 0  # return [int(round(math.cos(x) * (1 << q.fraction))

fn generic_visit(node: Int) -> Int:
    var _generic_visit_line = 'raise ValueError(f"Unsupported AST node for Verilog: {type(n'
    return 0

