# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for export

fn _check_exportable(network: Int) -> Int:
    var __check_exportable_line = 'for pop in network.populations:'
    var __check_exportable_line = 'name = pop._model_cls.__name__'
    var __check_exportable_line = 'if name not in _LIF_MODELS:'
    var __check_exportable_line = 'raise SCHardwareError('
    var __check_exportable_line = 'f"Model \'{name}\' cannot be exported to Verilog. Supported: {'
    var __check_exportable_line = ')'
    return 0

fn _emit_lif_module(pop: Int, idx: Int) -> Int:
    var __emit_lif_module_line = 'n = pop.n'
    var __emit_lif_module_line = 'sample = pop.neurons[0]'
    var __emit_lif_module_line = 'v_thresh = int(getattr(sample, "v_threshold", 1) * 256)'
    var __emit_lif_module_line = 'v_reset = int(getattr(sample, "v_reset", 0) * 256)'
    var __emit_lif_module_line = 'tau = int(getattr(sample, "tau", 20))'
    return 0  # return (
    var __emit_lif_module_line = 'f"// Population {idx}: {pop.label} ({n} neurons)\\n"'
    var __emit_lif_module_line = 'f"sc_lif_array #(\\n"'
    var __emit_lif_module_line = 'f"    .N({n}),\\n"'
    var __emit_lif_module_line = 'f"    .V_THRESH({v_thresh}),\\n"'
    var __emit_lif_module_line = 'f"    .V_RESET({v_reset}),\\n"'
    var __emit_lif_module_line = 'f"    .TAU({tau})\\n"'
    var __emit_lif_module_line = 'f") pop_{idx} (\\n"'
    var __emit_lif_module_line = 'f"    .clk(clk),\\n"'
    var __emit_lif_module_line = 'f"    .rst_n(rst_n),\\n"'
    var __emit_lif_module_line = 'f"    .current_in(current_{idx}),\\n"'
    var __emit_lif_module_line = 'f"    .spike_out(spike_{idx})\\n"'
    var __emit_lif_module_line = 'f");\\n"'
    var __emit_lif_module_line = ')'

fn _emit_top(network: Int, target: Int) -> Int:
    var __emit_top_line = 'n_pops = len(network.populations)'
    var __emit_top_line = 'lines = ['
    var __emit_top_line = 'f"// Auto-generated by SC-NeuroCore — target: {target}\\n",'
    var __emit_top_line = '"module sc_network_top (\\n",'
    var __emit_top_line = '"    input wire clk,\\n",'
    var __emit_top_line = '"    input wire rst_n,\\n",'
    var __emit_top_line = ']'
    var __emit_top_line = 'for i, pop in enumerate(network.populations):'
    var __emit_top_line = 'lines.append(f"    input wire [{pop.n * 8 - 1}:0] current_{i'
    var __emit_top_line = 'for i, pop in enumerate(network.populations):'
    var __emit_top_line = 'comma = "" if i == n_pops - 1 else ","'
    var __emit_top_line = 'lines.append(f"    output wire [{pop.n - 1}:0] spike_{i}{com'
    var __emit_top_line = 'lines.append(");\\n\\n")'
    var __emit_top_line = 'for i, pop in enumerate(network.populations):'
    var __emit_top_line = 'lines.append(_emit_lif_module(pop, i))'
    var __emit_top_line = 'lines.append("\\n")'
    var __emit_top_line = 'lines.append("endmodule\\n")'
    return 0  # return "".join(lines)

fn export_verilog(network: Int, output_dir: Int, target: Int) -> Int:
    var _export_verilog_line = '_check_exportable(network)'
    var _export_verilog_line = 'os.makedirs(output_dir, exist_ok=True)'
    var _export_verilog_line = 'top_v = _emit_top(network, target)'
    var _export_verilog_line = 'top_path = os.path.join(output_dir, "sc_network_top.v")'
    var _export_verilog_line = 'with open(top_path, "w") as f:'
    var _export_verilog_line = 'f.write(top_v)'
    var _export_verilog_line = 'params_path = os.path.join(output_dir, "params.vh")'
    var _export_verilog_line = 'with open(params_path, "w") as f:'
    var _export_verilog_line = 'f.write(f"// SC-NeuroCore network parameters — target: {targ'
    var _export_verilog_line = 'for i, pop in enumerate(network.populations):'
    var _export_verilog_line = 'f.write(f"`define POP_{i}_SIZE {pop.n}\\n")'
    return 0  # return top_path
