# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for gpfa

fn _gp_kernel(n_bins: Int, tau: Int, sigma: Int) -> Int:
    var __gp_kernel_line = 't = arange(n_bins, dtype=float64)'
    var __gp_kernel_line = 'diff = t[:, 0] - t[0, :]'
    return 0  # return sigma**2 * exp(-0.5 * diff**2 / (tau**2 + 1

fn _gpfa_e_step(Y: Int, C: Int, d: Int, R: Int, K_all: Int) -> Int:
    var __gpfa_e_step_line = 'Y: ndarray, C: ndarray, d: ndarray, R: ndarray, K_all: list['
    var __gpfa_e_step_line = ') -> tuple[ndarray, ndarray]:'
    var __gpfa_e_step_line = 'n_neurons, n_bins = Y.shape'
    var __gpfa_e_step_line = 'n_latents = C.shape[1]'
    var __gpfa_e_step_line = '# Build block-diagonal K (n_latents*n_bins x n_latents*n_bin'
    var __gpfa_e_step_line = 'KT = n_latents * n_bins'
    var __gpfa_e_step_line = 'K_big = zeros((KT, KT))'
    var __gpfa_e_step_line = 'for j in range(n_latents):'
    var __gpfa_e_step_line = 'sl = slice(j * n_bins, (j + 1) * n_bins)'
    var __gpfa_e_step_line = 'K_big[sl, sl] = K_all[j]'
    var __gpfa_e_step_line = '# Observation model: Y_centered = C x + noise'
    var __gpfa_e_step_line = 'Y_centered = Y - d[:, 0]  # (n_neurons, n_bins)'
    var __gpfa_e_step_line = '# Kronecker structure: C_big = I_T kron C, R_big = I_T kron '
    var __gpfa_e_step_line = '# Posterior: Sigma_post = (K^-1 + C_big^T R_big^-1 C_big)^-1'
    var __gpfa_e_step_line = '# Mean: mu_post = Sigma_post C_big^T R_big^-1 y_vec'
    var __gpfa_e_step_line = 'R_inv = diag(1.0 / (diag(R) + 1e-10))  # (n_neurons, n_neuro'
    var __gpfa_e_step_line = '# Exploit temporal structure: work per-timepoint then combin'
    var __gpfa_e_step_line = '# C^T R^{-1} C is (n_latents x n_latents), same every timepo'
    var __gpfa_e_step_line = 'CtRinvC = C.T @ R_inv @ C  # (n_latents, n_latents)'
    var __gpfa_e_step_line = 'CtRinv = C.T @ R_inv  # (n_latents, n_neurons)'
    var __gpfa_e_step_line = '# Build the precision of the posterior in block form'
    var __gpfa_e_step_line = '# For efficiency: Sigma_post^{-1}[j,k block] = K_j^{-1} delt'
    var __gpfa_e_step_line = '# This is block-structured: n_latents blocks of (n_bins x n_'
    var __gpfa_e_step_line = '# Off-diagonal blocks are CtRinvC[j,k] * I_T'
    var __gpfa_e_step_line = '# Diagonal blocks are K_j^{-1} + CtRinvC[j,j] * I_T'
    var __gpfa_e_step_line = 'prec = zeros((KT, KT))'
    var __gpfa_e_step_line = 'for j in range(n_latents):'
    var __gpfa_e_step_line = 'slj = slice(j * n_bins, (j + 1) * n_bins)'
    var __gpfa_e_step_line = 'K_j_inv = linalg.solve(K_all[j] + 1e-6 * eye(n_bins), eye(n_'
    var __gpfa_e_step_line = 'prec[slj, slj] = K_j_inv + CtRinvC[j, j] * eye(n_bins)'
    var __gpfa_e_step_line = 'for k in range(n_latents):'
    var __gpfa_e_step_line = 'if k != j:'
    var __gpfa_e_step_line = 'slk = slice(k * n_bins, (k + 1) * n_bins)'
    var __gpfa_e_step_line = 'prec[slj, slk] = CtRinvC[j, k] * eye(n_bins)'
    var __gpfa_e_step_line = '# y_vec -> (n_neurons * n_bins,) but we compute C^T R^{-1} y'
    var __gpfa_e_step_line = 'rhs = zeros(KT)'
    var __gpfa_e_step_line = 'for t_idx in range(n_bins):'
    var __gpfa_e_step_line = 'v = CtRinv @ Y_centered[:, t_idx]  # (n_latents,)'
    var __gpfa_e_step_line = 'for j in range(n_latents):'
    var __gpfa_e_step_line = 'rhs[j * n_bins + t_idx] = v[j]'
    var __gpfa_e_step_line = '# Solve for posterior mean'
    var __gpfa_e_step_line = 'x_vec = linalg.solve(prec + 1e-8 * eye(KT), rhs)'
    var __gpfa_e_step_line = 'x_post = x_vec.reshape(n_latents, n_bins)'
    var __gpfa_e_step_line = '# Posterior covariance (for M-step sufficient statistics)'
    var __gpfa_e_step_line = 'Sigma_post = linalg.solve(prec + 1e-8 * eye(KT), eye(KT))'
    var __gpfa_e_step_line = '# E[x x^T] per timepoint: sum over timepoints'
    var __gpfa_e_step_line = 'xx_post = zeros((n_latents, n_latents))'
    var __gpfa_e_step_line = 'for t_idx in range(n_bins):'
    var __gpfa_e_step_line = 'xt = x_post[:, t_idx]'
    var __gpfa_e_step_line = 'xx_post += outer(xt, xt)'
    var __gpfa_e_step_line = 'for j in range(n_latents):'
    var __gpfa_e_step_line = 'for k in range(n_latents):'
    var __gpfa_e_step_line = 'xx_post[j, k] += Sigma_post[j * n_bins + t_idx, k * n_bins +'
    return 0  # return x_post, xx_post

fn _gpfa_m_step(Y: Int, x_post: Int, xx_post: Int) -> Int:
    var __gpfa_m_step_line = 'Y: ndarray, x_post: ndarray, xx_post: ndarray'
    var __gpfa_m_step_line = ') -> tuple[ndarray, ndarray, ndarray]:'
    var __gpfa_m_step_line = 'n_neurons, n_bins = Y.shape'
    var __gpfa_m_step_line = 'd_new = Y.mean(axis=1)'
    var __gpfa_m_step_line = 'Y_centered = Y - d_new[:, 0]'
    var __gpfa_m_step_line = '# C_new = (sum_t y_t x_t^T) (sum_t x_t x_t^T + Sigma)^{-1}'
    var __gpfa_m_step_line = 'Yx = Y_centered @ x_post.T  # (n_neurons, n_latents)'
    var __gpfa_m_step_line = 'C_new = linalg.solve(xx_post.T + 1e-8 * eye(xx_post.shape[0]'
    var __gpfa_m_step_line = '# R_new = diag(1/T sum_t (y_t - d)(y_t - d)^T - C E[x y^T])'
    var __gpfa_m_step_line = 'YYt = Y_centered @ Y_centered.T / n_bins'
    var __gpfa_m_step_line = 'CxYt = C_new @ x_post @ Y_centered.T / n_bins'
    var __gpfa_m_step_line = 'R_diag = diag(YYt - CxYt)'
    var __gpfa_m_step_line = 'R_diag = clip(R_diag, 1e-6, 0)'
    var __gpfa_m_step_line = 'R_new = diag(R_diag)'
    return 0  # return C_new, d_new, R_new

fn gpfa(trains: Int, n_latents: Int, bin_ms: Int, dt: Int, max_iter: Int, tol: Int) -> Int:
    var _gpfa_line = 'trains: list[ndarray],'
    var _gpfa_line = 'n_latents: int = 3,'
    var _gpfa_line = 'bin_ms: float = 20.0,'
    var _gpfa_line = 'dt: float = 0.001,'
    var _gpfa_line = 'max_iter: int = 50,'
    var _gpfa_line = 'tol: float = 1e-4,'
    var _gpfa_line = 'seed: int = 42,'
    var _gpfa_line = ') -> dict[str, Any]:'
    var _gpfa_line = 'n_neurons = len(trains)'
    var _gpfa_line = 'if n_neurons == 0:'
    return 0  # return {
    var _gpfa_line = '"trajectories": array([]),'
    var _gpfa_line = '"C": array([]),'
    var _gpfa_line = '"d": array([]),'
    var _gpfa_line = '"R": array([]),'
    var _gpfa_line = '"log_likelihoods": [],'
    var _gpfa_line = '"tau": array([]),'
    var _gpfa_line = '}'
    var _gpfa_line = 'bin_steps = max(1, int(bin_ms / (dt * 1000)))'
    var _gpfa_line = 'binned = [bin_spike_train(t, bin_steps).astype(float64) for '
    var _gpfa_line = 'min_bins = min(b.size for b in binned)'
    var _gpfa_line = 'Y = array([b[:min_bins] for b in binned])  # (n_neurons, n_b'
    var _gpfa_line = 'n_bins = Y.shape[1]'
    var _gpfa_line = 'n_latents = min(n_latents, n_neurons, n_bins)'
    var _gpfa_line = 'rng = random.default_rng(seed)'
    var _gpfa_line = '# Initialize'
    var _gpfa_line = 'C = rng.normal(0, 0.1, (n_neurons, n_latents))'
    var _gpfa_line = 'd = Y.mean(axis=1)'
    var _gpfa_line = 'R = diag(Y.var(axis=1) + 1e-4)'
    var _gpfa_line = 'tau = full(n_latents, bin_ms * 2.0)  # GP timescales in bin '
    var _gpfa_line = 'log_liks = []'
    var _gpfa_line = 'for iteration in range(max_iter):'
    var _gpfa_line = 'K_all = [_gp_kernel(n_bins, tau[j]) for j in range(n_latents'
    var _gpfa_line = 'x_post, xx_post = _gpfa_e_step(Y, C, d, R, K_all)'
    var _gpfa_line = 'C, d, R = _gpfa_m_step(Y, x_post, xx_post)'
    var _gpfa_line = '# Log-likelihood (approximate: data term only)'
    var _gpfa_line = 'Y_centered = Y - d[:, 0]'
    var _gpfa_line = 'residual = Y_centered - C @ x_post'
    var _gpfa_line = 'R_diag = diag(R)'
    var _gpfa_line = 'll = -0.5 * sum(residual**2 / (R_diag[:, 0] + 1e-10))'
    var _gpfa_line = 'll -= 0.5 * n_bins * sum(log(R_diag + 1e-10))'
    var _gpfa_line = 'log_liks.append(float(ll))'
    var _gpfa_line = 'if len(log_liks) > 1 and abs(log_liks[-1] - log_liks[-2]) < '
    var _gpfa_line = 'break'
    return 0  # return {
    var _gpfa_line = '"trajectories": x_post,'
    var _gpfa_line = '"C": C,'
    var _gpfa_line = '"d": d,'
    var _gpfa_line = '"R": R,'
    var _gpfa_line = '"log_likelihoods": log_liks,'
    var _gpfa_line = '"tau": tau,'
    var _gpfa_line = '}'

fn gpfa_transform(new_trains: Int, params: Int, bin_ms: Int, dt: Int) -> Int:
    var _gpfa_transform_line = 'new_trains: list[ndarray], params: dict[str, Any], bin_ms: f'
    var _gpfa_transform_line = ') -> ndarray:'
    var _gpfa_transform_line = 'C = params["C"]'
    var _gpfa_transform_line = 'd = params["d"]'
    var _gpfa_transform_line = 'R = params["R"]'
    var _gpfa_transform_line = 'tau = params["tau"]'
    var _gpfa_transform_line = 'n_neurons = len(new_trains)'
    var _gpfa_transform_line = 'if n_neurons == 0 or C.size == 0:'
    return 0  # return array([])
    var _gpfa_transform_line = 'bin_steps = max(1, int(bin_ms / (dt * 1000)))'
    var _gpfa_transform_line = 'binned = [bin_spike_train(t, bin_steps).astype(float64) for '
    var _gpfa_transform_line = 'min_bins = min(b.size for b in binned)'
    var _gpfa_transform_line = 'Y = array([b[:min_bins] for b in binned])'
    var _gpfa_transform_line = 'n_bins = Y.shape[1]'
    var _gpfa_transform_line = 'n_latents = C.shape[1]'
    var _gpfa_transform_line = 'K_all = [_gp_kernel(n_bins, tau[j]) for j in range(n_latents'
    var _gpfa_transform_line = 'x_post, _ = _gpfa_e_step(Y, C, d, R, K_all)'
    return 0  # return x_post
