# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for loaders

fn _synthetic_event_dataset(n_samples: Int, spatial_size: Int, n_classes: Int, T: Int, dt_ms: Int, seed: Int) -> Int:
    var __synthetic_event_dataset_line = 'n_samples: int,'
    var __synthetic_event_dataset_line = 'spatial_size: int,'
    var __synthetic_event_dataset_line = 'n_classes: int,'
    var __synthetic_event_dataset_line = 'T: int,'
    var __synthetic_event_dataset_line = 'dt_ms: float,'
    var __synthetic_event_dataset_line = 'seed: int,'
    var __synthetic_event_dataset_line = ') -> tuple[list[ndarray], ndarray]:'
    var __synthetic_event_dataset_line = 'rng = random.default_rng(seed)'
    var __synthetic_event_dataset_line = 'labels = rng.integers(0, n_classes, size=n_samples)'
    var __synthetic_event_dataset_line = 'templates = rng.uniform(0.0, 0.3, size=(n_classes, spatial_s'
    var __synthetic_event_dataset_line = 'samples: list[ndarray] = []'
    var __synthetic_event_dataset_line = 'for i in range(n_samples):'
    var __synthetic_event_dataset_line = 'rates = templates[labels[i]].ravel()'
    var __synthetic_event_dataset_line = 'spike_train = poisson_encode(rates, T, dt_ms=dt_ms, seed=see'
    var __synthetic_event_dataset_line = 'timesteps, neuron_ids = nonzero(spike_train)'
    var __synthetic_event_dataset_line = 'y_coords, x_coords = divmod(neuron_ids, spatial_size)'
    var __synthetic_event_dataset_line = 'polarities = rng.integers(0, 2, size=len(timesteps))'
    var __synthetic_event_dataset_line = 'events = column_stack('
    var __synthetic_event_dataset_line = '['
    var __synthetic_event_dataset_line = 'x_coords,'
    var __synthetic_event_dataset_line = 'y_coords,'
    var __synthetic_event_dataset_line = 'polarities,'
    var __synthetic_event_dataset_line = 'timesteps * dt_ms,'
    var __synthetic_event_dataset_line = ']'
    var __synthetic_event_dataset_line = ').astype(float32)'
    var __synthetic_event_dataset_line = 'samples.append(events)'
    return 0  # return samples, labels

fn _check_root(root: Int, dataset_name: Int, url: Int) -> Int:
    var __check_root_line = 'p = Path(root)'
    var __check_root_line = 'if p.exists():'
    return 0  # return p
    var __check_root_line = 'raise FileNotFoundError(f"{dataset_name}: download from {url'

fn load_nmnist(root: Int, train: Int, dt_ms: Int, T: Int, synthetic: Int, n_samples: Int) -> Int:
    var _load_nmnist_line = 'root: str | Path = "data/nmnist",'
    var _load_nmnist_line = 'train: bool = True,'
    var _load_nmnist_line = 'dt_ms: float = 1.0,'
    var _load_nmnist_line = 'T: int = 300,'
    var _load_nmnist_line = 'synthetic: bool = False,'
    var _load_nmnist_line = 'n_samples: int = 100,'
    var _load_nmnist_line = 'seed: int = 42,'
    var _load_nmnist_line = ') -> tuple[list[ndarray], ndarray]:'
    var _load_nmnist_line = 'if synthetic:'
    return 0  # return _synthetic_event_dataset(
    var _load_nmnist_line = 'n_samples,'
    var _load_nmnist_line = '_NMNIST_RES,'
    var _load_nmnist_line = '10,'
    var _load_nmnist_line = 'T,'
    var _load_nmnist_line = 'dt_ms,'
    var _load_nmnist_line = 'seed,'
    var _load_nmnist_line = ')'
    var _load_nmnist_line = '_check_root(root, "N-MNIST", _NMNIST_URL)'
    var _load_nmnist_line = 'split_dir = Path(root) / ("Train" if train else "Test")'
    var _load_nmnist_line = 'if not split_dir.exists():'
    var _load_nmnist_line = 'raise FileNotFoundError('
    var _load_nmnist_line = 'f"Expected split directory {split_dir.resolve()}. Download f'
    var _load_nmnist_line = ')'
    var _load_nmnist_line = '# Real loader: N-MNIST uses .bin files, one per sample, grou'
    var _load_nmnist_line = 'samples: list[ndarray] = []'
    var _load_nmnist_line = 'label_list: list[int] = []'
    var _load_nmnist_line = 'for class_dir in sorted(split_dir.iterdir()):'
    var _load_nmnist_line = 'if not class_dir.is_dir():'
    var _load_nmnist_line = 'continue'
    var _load_nmnist_line = 'class_label = int(class_dir.name)'
    var _load_nmnist_line = 'for bin_file in sorted(class_dir.glob("*.bin")):'
    var _load_nmnist_line = 'events = _parse_nmnist_bin(bin_file, dt_ms)'
    var _load_nmnist_line = 'samples.append(events)'
    var _load_nmnist_line = 'label_list.append(class_label)'
    return 0  # return samples, array(label_list, dtype=int64)

fn _parse_nmnist_bin(path: Int, dt_ms: Int) -> Int:
    var __parse_nmnist_bin_line = 'raw = fromfile(path, dtype=uint8)'
    var __parse_nmnist_bin_line = '# Each event is 5 bytes: [addr_high, addr_low, ts2, ts1, ts0'
    var __parse_nmnist_bin_line = 'n_events = len(raw) // 5'
    var __parse_nmnist_bin_line = 'raw = raw[: n_events * 5].reshape(n_events, 5)'
    var __parse_nmnist_bin_line = 'addr = (raw[:, 0].astype(uint16) << 8) | raw[:, 1].astype(ui'
    var __parse_nmnist_bin_line = 'x = addr & 0x1F  # bits 0-4'
    var __parse_nmnist_bin_line = 'y = (addr >> 5) & 0x1F  # bits 5-9'
    var __parse_nmnist_bin_line = 'polarity = (addr >> 10) & 0x1  # bit 10'
    var __parse_nmnist_bin_line = 'ts = ('
    var __parse_nmnist_bin_line = 'raw[:, 2].astype(uint32) << 16'
    var __parse_nmnist_bin_line = '| raw[:, 3].astype(uint32) << 8'
    var __parse_nmnist_bin_line = '| raw[:, 4].astype(uint32)'
    var __parse_nmnist_bin_line = ')'
    var __parse_nmnist_bin_line = 'ts_ms = ts.astype(float32) * (dt_ms / 1000.0)'
    return 0  # return column_stack([x, y, polarity, ts_ms]).astyp

fn load_shd(root: Int, train: Int, dt_ms: Int, T: Int, synthetic: Int, n_samples: Int) -> Int:
    var _load_shd_line = 'root: str | Path = "data/shd",'
    var _load_shd_line = 'train: bool = True,'
    var _load_shd_line = 'dt_ms: float = 1.0,'
    var _load_shd_line = 'T: int = 1000,'
    var _load_shd_line = 'synthetic: bool = False,'
    var _load_shd_line = 'n_samples: int = 100,'
    var _load_shd_line = 'seed: int = 42,'
    var _load_shd_line = ') -> tuple[list[ndarray], ndarray]:'
    var _load_shd_line = 'if synthetic:'
    return 0  # return _synthetic_shd(n_samples, T, dt_ms, seed)
    var _load_shd_line = '_check_root(root, "SHD", _SHD_URL)'
    var _load_shd_line = 'fname = "shd_train.h5" if train else "shd_test.h5"'
    var _load_shd_line = 'h5_path = Path(root) / fname'
    var _load_shd_line = 'if not h5_path.exists():'
    var _load_shd_line = 'raise FileNotFoundError(f"{h5_path.resolve()} not found. Dow'
    var _load_shd_line = 'import h5py'
    var _load_shd_line = 'samples: list[ndarray] = []'
    var _load_shd_line = 'with h5py.File(h5_path, "r") as f:'
    var _load_shd_line = 'spike_times = f["spikes"]["times"]'
    var _load_shd_line = 'spike_units = f["spikes"]["units"]'
    var _load_shd_line = 'raw_labels = f["labels"][:]'
    var _load_shd_line = 'for i in range(len(raw_labels)):'
    var _load_shd_line = 'times = asarray(spike_times[i])'
    var _load_shd_line = 'units = asarray(spike_units[i])'
    var _load_shd_line = 'if len(times) > 0:'
    var _load_shd_line = 'n_bins = min(int(ceil(times.max() / (dt_ms / 1000.0))) + 1, '
    var _load_shd_line = 'else:'
    var _load_shd_line = 'n_bins = T'
    var _load_shd_line = 'train_arr = zeros((n_bins, _SHD_CHANNELS), dtype=bool)'
    var _load_shd_line = 'if len(times) > 0:'
    var _load_shd_line = 'bin_idx = clip((times / (dt_ms / 1000.0)).astype(int), 0, n_'
    var _load_shd_line = 'unit_idx = clip(units.astype(int), 0, _SHD_CHANNELS - 1)'
    var _load_shd_line = 'train_arr[bin_idx, unit_idx] = True'
    var _load_shd_line = 'samples.append(train_arr)'
    return 0  # return samples, raw_labels.astype(int64)

fn _synthetic_shd(n_samples: Int, T: Int, dt_ms: Int, seed: Int) -> Int:
    var __synthetic_shd_line = 'n_samples: int,'
    var __synthetic_shd_line = 'T: int,'
    var __synthetic_shd_line = 'dt_ms: float,'
    var __synthetic_shd_line = 'seed: int,'
    var __synthetic_shd_line = ') -> tuple[list[ndarray], ndarray]:'
    var __synthetic_shd_line = 'rng = random.default_rng(seed)'
    var __synthetic_shd_line = 'labels = rng.integers(0, 20, size=n_samples)'
    var __synthetic_shd_line = 'templates = rng.uniform(0.0, 0.1, size=(20, _SHD_CHANNELS))'
    var __synthetic_shd_line = 'samples: list[ndarray] = []'
    var __synthetic_shd_line = 'for i in range(n_samples):'
    var __synthetic_shd_line = 'spike_train = poisson_encode('
    var __synthetic_shd_line = 'templates[labels[i]],'
    var __synthetic_shd_line = 'T,'
    var __synthetic_shd_line = 'dt_ms=dt_ms,'
    var __synthetic_shd_line = 'seed=seed + i + 1,'
    var __synthetic_shd_line = ')'
    var __synthetic_shd_line = 'samples.append(spike_train)'
    return 0  # return samples, labels

fn load_dvs_cifar10(root: Int, train: Int, dt_ms: Int, T: Int, synthetic: Int, n_samples: Int) -> Int:
    var _load_dvs_cifar10_line = 'root: str | Path = "data/dvs_cifar10",'
    var _load_dvs_cifar10_line = 'train: bool = True,'
    var _load_dvs_cifar10_line = 'dt_ms: float = 1.0,'
    var _load_dvs_cifar10_line = 'T: int = 300,'
    var _load_dvs_cifar10_line = 'synthetic: bool = False,'
    var _load_dvs_cifar10_line = 'n_samples: int = 100,'
    var _load_dvs_cifar10_line = 'seed: int = 42,'
    var _load_dvs_cifar10_line = ') -> tuple[list[ndarray], ndarray]:'
    var _load_dvs_cifar10_line = 'if synthetic:'
    return 0  # return _synthetic_event_dataset(
    var _load_dvs_cifar10_line = 'n_samples,'
    var _load_dvs_cifar10_line = '_DVS_CIFAR10_RES,'
    var _load_dvs_cifar10_line = '10,'
    var _load_dvs_cifar10_line = 'T,'
    var _load_dvs_cifar10_line = 'dt_ms,'
    var _load_dvs_cifar10_line = 'seed,'
    var _load_dvs_cifar10_line = ')'
    var _load_dvs_cifar10_line = '_check_root(root, "DVS-CIFAR10", _DVS_CIFAR10_URL)'
    var _load_dvs_cifar10_line = 'split_dir = Path(root) / ("train" if train else "test")'
    var _load_dvs_cifar10_line = 'if not split_dir.exists():'
    var _load_dvs_cifar10_line = 'raise FileNotFoundError('
    var _load_dvs_cifar10_line = 'f"Expected split directory {split_dir.resolve()}. Download f'
    var _load_dvs_cifar10_line = ')'
    var _load_dvs_cifar10_line = '# Real loader: .aedat or .mat files grouped by class'
    var _load_dvs_cifar10_line = 'samples: list[ndarray] = []'
    var _load_dvs_cifar10_line = 'label_list: list[int] = []'
    var _load_dvs_cifar10_line = 'for class_dir in sorted(split_dir.iterdir()):'
    var _load_dvs_cifar10_line = 'if not class_dir.is_dir():'
    var _load_dvs_cifar10_line = 'continue'
    var _load_dvs_cifar10_line = 'class_label = int(class_dir.name)'
    var _load_dvs_cifar10_line = 'for event_file in sorted(class_dir.glob("*.npy")):'
    var _load_dvs_cifar10_line = 'events = load(event_file).astype(float32)'
    var _load_dvs_cifar10_line = 'samples.append(events)'
    var _load_dvs_cifar10_line = 'label_list.append(class_label)'
    var _load_dvs_cifar10_line = 'if not samples:'
    var _load_dvs_cifar10_line = 'raise FileNotFoundError('
    var _load_dvs_cifar10_line = 'f"No .npy event files found in {split_dir.resolve()}. "'
    var _load_dvs_cifar10_line = 'f"Convert raw data to .npy arrays with columns [x, y, pol, t'
    var _load_dvs_cifar10_line = ')'
    return 0  # return samples, array(label_list, dtype=int64)
