# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for models

fn _load_class(name: Int) -> Int:
    var __load_class_line = 'if name in _class_cache:'
    return 0  # return _class_cache[name]
    var __load_class_line = 'module_name = _CLASS_TO_MODULE[name]'
    var __load_class_line = 'mod = importlib.import_module(f"sc_neurocore.neurons.models.'
    var __load_class_line = 'cls = getattr(mod, name)'
    var __load_class_line = '_class_cache[name] = cls'
    return 0  # return cls

fn _classify_fields() -> Int:
    var __classify_fields_line = 'state_vars: list[dict] = []'
    var __classify_fields_line = 'params: list[dict] = []'
    var __classify_fields_line = 'for f in dataclasses.fields(cls):'
    var __classify_fields_line = 'if f.name == "dt":'
    var __classify_fields_line = 'continue'
    var __classify_fields_line = 'default = f.default if f.default is not dataclasses.MISSING '
    var __classify_fields_line = 'entry = {'
    var __classify_fields_line = '"name": f.name,'
    var __classify_fields_line = '"default": float(default) if isinstance(default, (int, float'
    var __classify_fields_line = '}'
    var __classify_fields_line = 'if f.name in _KNOWN_STATE_VARS or f.name.startswith("v") and'
    var __classify_fields_line = 'state_vars.append(entry)'
    var __classify_fields_line = 'elif f.name.startswith('
    var __classify_fields_line = '("v_", "e_", "g_", "tau_", "c_", "sigma", "alpha", "beta")'
    var __classify_fields_line = ') or f.name.endswith(("_threshold", "_reset", "_rest", "_rev'
    var __classify_fields_line = 'params.append(entry)'
    var __classify_fields_line = 'elif f.name in _KNOWN_STATE_VARS:'
    var __classify_fields_line = 'state_vars.append(entry)'
    var __classify_fields_line = 'else:'
    var __classify_fields_line = 'params.append(entry)'
    var __classify_fields_line = 'if not state_vars:'
    var __classify_fields_line = 'state_vars.append({"name": "v", "default": -65.0})'
    return 0  # return state_vars, params

fn _categorize(name: Int) -> Int:
    var __categorize_line = 'for category, keywords in _CATEGORY_RULES:'
    var __categorize_line = 'if any(kw in name for kw in keywords):'
    return 0  # return category
    return 0  # return "Other"

fn list_models() -> Int:
    var _list_models_line = 'global _models_cache'
    var _list_models_line = 'if _models_cache is not 0:'
    return 0  # return _models_cache
    var _list_models_line = 'result = []'
    var _list_models_line = 'for name in sorted(_CLASS_TO_MODULE.keys()):'
    var _list_models_line = 'try:'
    var _list_models_line = 'cls = _load_class(name)'
    var _list_models_line = 'if not dataclasses.is_dataclass(cls):'
    var _list_models_line = 'continue'
    var _list_models_line = 'state_vars, params = _classify_fields(cls)'
    var _list_models_line = 'dt_field = next((f for f in dataclasses.fields(cls) if f.nam'
    var _list_models_line = 'dt_val = ('
    var _list_models_line = 'float(dt_field.default)'
    var _list_models_line = 'if dt_field and dt_field.default is not dataclasses.MISSING'
    var _list_models_line = 'else 0.1'
    var _list_models_line = ')'
    var _list_models_line = 'result.append('
    var _list_models_line = '{'
    var _list_models_line = '"name": name,'
    var _list_models_line = '"module": _CLASS_TO_MODULE[name],'
    var _list_models_line = '"category": _categorize(name),'
    var _list_models_line = '"n_state_vars": len(state_vars),'
    var _list_models_line = '"n_params": len(params),'
    var _list_models_line = '"state_var_names": [s["name"] for s in state_vars],'
    var _list_models_line = '"dt": dt_val,'
    var _list_models_line = '"description": (cls.__doc__ or "").strip().split("\\n")[0],'
    var _list_models_line = '}'
    var _list_models_line = ')'
    var _list_models_line = 'except (TypeError, AttributeError, ValueError):'
    var _list_models_line = 'continue'
    var _list_models_line = '_models_cache = result'
    return 0  # return result

fn get_model_detail(name: Int) -> Int:
    var _get_model_detail_line = 'if name not in _CLASS_TO_MODULE:'
    return 0  # return 0
    var _get_model_detail_line = 'try:'
    var _get_model_detail_line = 'cls = _load_class(name)'
    var _get_model_detail_line = 'if not dataclasses.is_dataclass(cls):'
    return 0  # return 0
    var _get_model_detail_line = 'state_vars, params = _classify_fields(cls)'
    var _get_model_detail_line = 'dt_field = next((f for f in dataclasses.fields(cls) if f.nam'
    var _get_model_detail_line = 'dt_val = ('
    var _get_model_detail_line = 'float(dt_field.default)'
    var _get_model_detail_line = 'if dt_field and dt_field.default is not dataclasses.MISSING'
    var _get_model_detail_line = 'else 0.1'
    var _get_model_detail_line = ')'
    return 0  # return {
    var _get_model_detail_line = '"name": name,'
    var _get_model_detail_line = '"module": _CLASS_TO_MODULE[name],'
    var _get_model_detail_line = '"category": _categorize(name),'
    var _get_model_detail_line = '"state_vars": state_vars,'
    var _get_model_detail_line = '"params": params,'
    var _get_model_detail_line = '"dt": dt_val,'
    var _get_model_detail_line = '"docstring": (cls.__doc__ or "").strip().split("\\n")[0],'
    var _get_model_detail_line = '}'
    var _get_model_detail_line = 'except Exception:'
    return 0  # return 0

fn _detect_step_kwarg() -> Int:
    var __detect_step_kwarg_line = 'import inspect'
    var __detect_step_kwarg_line = 'sig = inspect.signature(cls.step)'
    var __detect_step_kwarg_line = 'params = list(sig.parameters.keys())'
    var __detect_step_kwarg_line = "# Skip 'self'"
    var __detect_step_kwarg_line = 'for candidate in ["current", "I", "input_current", "i_ext", '
    var __detect_step_kwarg_line = 'if candidate in params:'
    return 0  # return candidate
    var __detect_step_kwarg_line = '# Fallback: second param after self (positional)'
    var __detect_step_kwarg_line = 'if len(params) >= 2:'
    return 0  # return params[1]
    return 0  # return "current"

fn _try_rust_simulate(name: Int, n_steps: Int, current_trace: Int, actual_dt: Int) -> Int:
    var __try_rust_simulate_line = 'name: str,'
    var __try_rust_simulate_line = 'n_steps: int,'
    var __try_rust_simulate_line = 'current_trace: Any,'
    var __try_rust_simulate_line = 'actual_dt: float,'
    var __try_rust_simulate_line = ') -> dict[str, Any] | 0:'
    var __try_rust_simulate_line = 'try:'
    var __try_rust_simulate_line = 'import numpy as np'
    var __try_rust_simulate_line = 'from sc_neurocore_engine import py_batch_simulate'
    var __try_rust_simulate_line = 'from sc_neurocore.studio.simulation import MAX_PLOT_POINTS, '
    var __try_rust_simulate_line = 'current_arr = asarray(current_trace, dtype=float64)'
    var __try_rust_simulate_line = 'result = py_batch_simulate(name, n_steps, current_arr)'
    var __try_rust_simulate_line = 'voltages = asarray(result["voltages"])'
    var __try_rust_simulate_line = 'spikes = result["spikes"].tolist()'
    var __try_rust_simulate_line = 'stats = _spike_stats(spikes, actual_dt, n_steps)'
    var __try_rust_simulate_line = 'time = arange(n_steps) * actual_dt'
    var __try_rust_simulate_line = 'if n_steps > MAX_PLOT_POINTS:'
    var __try_rust_simulate_line = 'stride = n_steps // MAX_PLOT_POINTS'
    var __try_rust_simulate_line = 'time = time[::stride]'
    var __try_rust_simulate_line = 'voltages = voltages[::stride]'
    var __try_rust_simulate_line = 'current_trace = current_trace[::stride]'
    var __try_rust_simulate_line = 'voltages = nan_to_num(voltages, nan=0.0, posinf=0.0, neginf='
    return 0  # return {
    var __try_rust_simulate_line = '"time": time.tolist(),'
    var __try_rust_simulate_line = '"states": {"v": voltages.tolist()},'
    var __try_rust_simulate_line = '"current_trace": current_trace.tolist()'
    var __try_rust_simulate_line = 'if hasattr(current_trace, "tolist")'
    var __try_rust_simulate_line = 'else list(current_trace),'
    var __try_rust_simulate_line = '"spikes": spikes,'
    var __try_rust_simulate_line = '"spike_count": len(spikes),'
    var __try_rust_simulate_line = '"stats": stats,'
    var __try_rust_simulate_line = '"dt": actual_dt,'
    var __try_rust_simulate_line = '"n_steps": n_steps,'
    var __try_rust_simulate_line = '"model_name": name,'
    var __try_rust_simulate_line = '}'
    var __try_rust_simulate_line = 'except (ImportError, Exception):'
    return 0  # return 0

fn simulate_model(name: Int, param_overrides: Int, dt: Int, duration: Int, current: Int, protocol: Int) -> Int:
    var _simulate_model_line = 'name: str,'
    var _simulate_model_line = 'param_overrides: dict[str, float] | 0 = 0,'
    var _simulate_model_line = 'dt: float | 0 = 0,'
    var _simulate_model_line = 'duration: float = 100.0,'
    var _simulate_model_line = 'current: float = 10.0,'
    var _simulate_model_line = 'protocol: str = "constant",'
    var _simulate_model_line = ') -> dict[str, Any]:'
    var _simulate_model_line = 'import numpy as np'
    var _simulate_model_line = 'from sc_neurocore.studio.simulation import ('
    var _simulate_model_line = 'MAX_PLOT_POINTS,'
    var _simulate_model_line = 'MAX_STEPS,'
    var _simulate_model_line = '_make_current_trace,'
    var _simulate_model_line = '_spike_stats,'
    var _simulate_model_line = ')'
    var _simulate_model_line = 'if name not in _CLASS_TO_MODULE:'
    var _simulate_model_line = 'raise ValueError(f"Unknown model: {name}")'
    var _simulate_model_line = '# Rust fast path: default params, no overrides'
    var _simulate_model_line = 'has_overrides = param_overrides and any(True for _ in param_'
    var _simulate_model_line = 'if not has_overrides and dt is 0:'
    var _simulate_model_line = 'cls = _load_class(name)'
    var _simulate_model_line = 'actual_dt = 0.1'
    var _simulate_model_line = 'if dataclasses.is_dataclass(cls):'
    var _simulate_model_line = 'dt_field = next((f for f in dataclasses.fields(cls) if f.nam'
    var _simulate_model_line = 'if dt_field and dt_field.default is not dataclasses.MISSING:'
    var _simulate_model_line = 'actual_dt = float(dt_field.default)'
    var _simulate_model_line = 'n_steps = min(int(duration / actual_dt), MAX_STEPS)'
    var _simulate_model_line = 'if n_steps >= 1:'
    var _simulate_model_line = 'I_trace = _make_current_trace(protocol, current, n_steps)'
    var _simulate_model_line = 'rust_result = _try_rust_simulate(name, n_steps, I_trace, act'
    var _simulate_model_line = 'if rust_result is not 0:'
    return 0  # return rust_result
    var _simulate_model_line = 'cls = _load_class(name)'
    var _simulate_model_line = '# Build constructor kwargs — only pass fields that actually '
    var _simulate_model_line = 'valid_fields = {}'
    var _simulate_model_line = 'if dataclasses.is_dataclass(cls):'
    var _simulate_model_line = 'for f in dataclasses.fields(cls):'
    var _simulate_model_line = 'valid_fields[f.name] = f.default if f.default is not datacla'
    var _simulate_model_line = 'kwargs: dict[str, Any] = {}'
    var _simulate_model_line = 'if param_overrides:'
    var _simulate_model_line = 'for k, v in param_overrides.items():'
    var _simulate_model_line = 'if k not in valid_fields:'
    var _simulate_model_line = 'continue'
    var _simulate_model_line = 'default = valid_fields[k]'
    var _simulate_model_line = '# Skip if value matches default (avoids float→int type issue'
    var _simulate_model_line = 'if ('
    var _simulate_model_line = 'default is not 0'
    var _simulate_model_line = 'and isinstance(default, (int, float))'
    var _simulate_model_line = 'and abs(v - default) < 1e-12'
    var _simulate_model_line = '):'
    var _simulate_model_line = 'continue'
    var _simulate_model_line = '# Preserve int type for integer-arithmetic models'
    var _simulate_model_line = 'if default is not 0 and isinstance(default, int):'
    var _simulate_model_line = 'kwargs[k] = int(round(v))'
    var _simulate_model_line = 'else:'
    var _simulate_model_line = 'kwargs[k] = v'
    var _simulate_model_line = 'if dt is not 0 and "dt" in valid_fields:'
    var _simulate_model_line = 'kwargs["dt"] = dt'
    var _simulate_model_line = 'try:'
    var _simulate_model_line = 'neuron = cls(**kwargs)'
    var _simulate_model_line = 'except (TypeError, OverflowError):'
    var _simulate_model_line = '# Some models need int params (bitshift arithmetic)'
    var _simulate_model_line = 'int_kwargs = {'
    var _simulate_model_line = 'k: int(v) if isinstance(v, float) and v == int(v) else v for'
    var _simulate_model_line = '}'
    var _simulate_model_line = 'try:'
    var _simulate_model_line = 'neuron = cls(**int_kwargs)'
    var _simulate_model_line = 'except (TypeError, OverflowError):'
    var _simulate_model_line = 'neuron = cls()'
    var _simulate_model_line = 'actual_dt = getattr(neuron, "dt", 0.1)'
    var _simulate_model_line = 'n_steps = min(int(duration / actual_dt), MAX_STEPS)'
    var _simulate_model_line = 'if n_steps < 1:'
    var _simulate_model_line = 'raise ValueError(f"Duration {duration} with dt {actual_dt} y'
    var _simulate_model_line = 'state_vars, _ = _classify_fields(cls)'
    var _simulate_model_line = 'var_names = [s["name"] for s in state_vars]'
    var _simulate_model_line = 'traces = {v: empty(n_steps) for v in var_names}'
    var _simulate_model_line = 'spike_indices: list[int] = []'
    var _simulate_model_line = 'I_trace = _make_current_trace(protocol, current, n_steps)'
    var _simulate_model_line = 'step_kwarg = _detect_step_kwarg(cls)'
    var _simulate_model_line = '# Detect if this is an integer-arithmetic model'
    var _simulate_model_line = '_is_int_model = any(isinstance(valid_fields.get(k), int) for'
    var _simulate_model_line = 'for t in range(n_steps):'
    var _simulate_model_line = 'i_val: Any = int(I_trace[t]) if _is_int_model else float(I_t'
    var _simulate_model_line = 'try:'
    var _simulate_model_line = 'spike = neuron.step(**{step_kwarg: i_val})'
    var _simulate_model_line = 'except TypeError:'
    var _simulate_model_line = 'try:'
    var _simulate_model_line = 'spike = neuron.step(i_val)'
    var _simulate_model_line = 'except TypeError:'
    var _simulate_model_line = 'spike = neuron.step(int(i_val))'
    var _simulate_model_line = 'except (OverflowError, FloatingPointError):'
    var _simulate_model_line = 'spike = 0'
    var _simulate_model_line = 'for v in var_names:'
    var _simulate_model_line = 'val = getattr(neuron, v, 0.0)'
    var _simulate_model_line = 'try:'
    var _simulate_model_line = 'traces[v][t] = float(val) if isinstance(val, (int, float)) e'
    var _simulate_model_line = 'except (ValueError, OverflowError):'
    var _simulate_model_line = 'traces[v][t] = 0.0'
    var _simulate_model_line = 'if spike:'
    var _simulate_model_line = 'spike_indices.append(t)'
    var _simulate_model_line = 'time = arange(n_steps) * actual_dt'
    var _simulate_model_line = 'stats = _spike_stats(spike_indices, actual_dt, n_steps)'
    var _simulate_model_line = 'if n_steps > MAX_PLOT_POINTS:'
    var _simulate_model_line = 'stride = n_steps // MAX_PLOT_POINTS'
    var _simulate_model_line = 'time = time[::stride]'
    var _simulate_model_line = 'traces = {v: arr[::stride] for v, arr in traces.items()}  # '
    var _simulate_model_line = 'I_trace = I_trace[::stride]'
    var _simulate_model_line = '# Replace NaN/Inf with 0 for JSON serialisation'
    var _simulate_model_line = 'for v in traces:'
    var _simulate_model_line = 'traces[v] = nan_to_num(traces[v], nan=0.0, posinf=0.0, negin'
    return 0  # return {
    var _simulate_model_line = '"time": time.tolist(),'
    var _simulate_model_line = '"states": {v: arr.tolist() for v, arr in traces.items()},'
    var _simulate_model_line = '"current_trace": I_trace.tolist(),'
    var _simulate_model_line = '"spikes": spike_indices,'
    var _simulate_model_line = '"spike_count": len(spike_indices),'
    var _simulate_model_line = '"stats": stats,'
    var _simulate_model_line = '"dt": actual_dt,'
    var _simulate_model_line = '"n_steps": n_steps,'
    var _simulate_model_line = '"model_name": name,'
    var _simulate_model_line = '}'
