# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for onnx_exporter

fn _classify_op(layer: Int) -> Int:
    var __classify_op_line = 'name = layer.__class__.__name__'
    var __classify_op_line = 'if "Dense" in name or "Vectorized" in name:'
    return 0  # return "SC_Dense"
    return 0  # return "SC_Custom"

fn export(layers: Int, filename: Int) -> Int:
    var _export_line = 'if filename.endswith(".onnx"):'
    var _export_line = 'SCOnnxExporter._export_protobuf(layers, filename)'
    var _export_line = 'else:'
    var _export_line = 'SCOnnxExporter._export_json(layers, filename)'
    return 0

fn _export_protobuf(layers: Int, filename: Int) -> Int:
    var __export_protobuf_line = 'try:'
    var __export_protobuf_line = 'import onnx'
    var __export_protobuf_line = 'from onnx import TensorProto, helper, numpy_helper'
    var __export_protobuf_line = 'except ImportError:'
    var __export_protobuf_line = 'from sc_neurocore.exceptions import SCDependencyError'
    var __export_protobuf_line = 'raise SCDependencyError('
    var __export_protobuf_line = '"ONNX protobuf export requires onnx: pip install sc-neurocor'
    var __export_protobuf_line = ')'
    var __export_protobuf_line = 'nodes: list[Any] = []'
    var __export_protobuf_line = 'initializers: list[Any] = []'
    var __export_protobuf_line = 'prev = "input_0"'
    var __export_protobuf_line = 'n_in = layers[0].n_inputs'
    var __export_protobuf_line = 'for i, layer in enumerate(layers):'
    var __export_protobuf_line = 'out = f"output_{i}"'
    var __export_protobuf_line = 'attrs: dict[str, Any] = {'
    var __export_protobuf_line = '"n_neurons": getattr(layer, "n_neurons", -1),'
    var __export_protobuf_line = '"length": getattr(layer, "length", 256),'
    var __export_protobuf_line = '}'
    var __export_protobuf_line = 'node = helper.make_node('
    var __export_protobuf_line = '_classify_op(layer),'
    var __export_protobuf_line = 'inputs=[prev],'
    var __export_protobuf_line = 'outputs=[out],'
    var __export_protobuf_line = 'name=f"Layer_{i}",'
    var __export_protobuf_line = 'domain=_CUSTOM_DOMAIN,'
    var __export_protobuf_line = '**{k: v for k, v in attrs.items()},'
    var __export_protobuf_line = ')'
    var __export_protobuf_line = 'nodes.append(node)'
    var __export_protobuf_line = 'if hasattr(layer, "weights"):'
    var __export_protobuf_line = 'w_name = f"Layer_{i}_weights"'
    var __export_protobuf_line = 'tensor = numpy_helper.from_array('
    var __export_protobuf_line = 'asarray(layer.weights, dtype=float32), name=w_name'
    var __export_protobuf_line = ')'
    var __export_protobuf_line = 'initializers.append(tensor)'
    var __export_protobuf_line = 'node.input.append(w_name)'
    var __export_protobuf_line = 'prev = out'
    var __export_protobuf_line = 'input_vi = helper.make_tensor_value_info("input_0", TensorPr'
    var __export_protobuf_line = 'output_vi = helper.make_tensor_value_info(prev, TensorProto.'
    var __export_protobuf_line = 'graph = helper.make_graph('
    var __export_protobuf_line = 'nodes,'
    var __export_protobuf_line = '"sc_neurocore_graph",'
    var __export_protobuf_line = '[input_vi],'
    var __export_protobuf_line = '[output_vi],'
    var __export_protobuf_line = 'initializer=initializers,'
    var __export_protobuf_line = ')'
    var __export_protobuf_line = 'opset_imports = ['
    var __export_protobuf_line = 'helper.make_opsetid("", 17),'
    var __export_protobuf_line = 'helper.make_opsetid(_CUSTOM_DOMAIN, _OPSET_VERSION),'
    var __export_protobuf_line = ']'
    var __export_protobuf_line = 'model = helper.make_model(graph, opset_imports=opset_imports'
    var __export_protobuf_line = 'model.producer_name = "sc-neurocore"'
    var __export_protobuf_line = 'model.ir_version = 8'
    var __export_protobuf_line = 'onnx.save(model, filename)'
    var __export_protobuf_line = 'logger.info("Exported ONNX protobuf to %s", filename)'
    return 0

fn _export_json(layers: Int, filename: Int) -> Int:
    var __export_json_line = 'graph: dict[str, Any] = {'
    var __export_json_line = '"producer_name": "sc-neurocore",'
    var __export_json_line = '"producer_version": "2.0.0",'
    var __export_json_line = '"nodes": [],'
    var __export_json_line = '"inputs": [],'
    var __export_json_line = '"outputs": [],'
    var __export_json_line = '}'
    var __export_json_line = 'graph["inputs"].append('
    var __export_json_line = '{'
    var __export_json_line = '"name": "input_0",'
    var __export_json_line = '"type": "tensor(float)",'
    var __export_json_line = '"shape": ["batch", layers[0].n_inputs],'
    var __export_json_line = '}'
    var __export_json_line = ')'
    var __export_json_line = 'prev = "input_0"'
    var __export_json_line = 'for i, layer in enumerate(layers):'
    var __export_json_line = 'out = f"output_{i}"'
    var __export_json_line = 'node = {'
    var __export_json_line = '"op_type": _classify_op(layer),'
    var __export_json_line = '"name": f"Layer_{i}",'
    var __export_json_line = '"input": [prev],'
    var __export_json_line = '"output": [out],'
    var __export_json_line = '"attributes": {'
    var __export_json_line = '"n_neurons": getattr(layer, "n_neurons", -1),'
    var __export_json_line = '"length": getattr(layer, "length", 256),'
    var __export_json_line = '},'
    var __export_json_line = '}'
    var __export_json_line = 'if hasattr(layer, "weights"):'
    var __export_json_line = 'node["attributes"]["has_weights"] = True  # type: ignore[ind'
    var __export_json_line = 'save(f"{filename}_layer_{i}_weights.npy", layer.weights)'
    var __export_json_line = 'node["attributes"]["weights_file"] = f"{filename}_layer_{i}_'
    var __export_json_line = 'graph["nodes"].append(node)'
    var __export_json_line = 'prev = out'
    var __export_json_line = 'graph["outputs"].append({"name": prev, "type": "tensor(float'
    var __export_json_line = 'try:'
    var __export_json_line = 'with open(filename, "w") as f:'
    var __export_json_line = 'json.dump(graph, f, indent=4)'
    var __export_json_line = 'except OSError as exc:'
    var __export_json_line = 'logger.error("Failed to export ONNX schema to %s: %s", filen'
    var __export_json_line = 'raise'
    var __export_json_line = 'logger.info("Exported ONNX-schema JSON to %s", filename)'
    return 0
