# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for photonic_noc

fn export_photonic_json(design: Int, path: Int) -> Int:
    var _export_photonic_json_line = 'data = {'
    var _export_photonic_json_line = '"name": design.name,'
    var _export_photonic_json_line = '"n_nodes": design.n_nodes,'
    var _export_photonic_json_line = '"total_area_um2": design.total_area_um2,'
    var _export_photonic_json_line = '"waveguides": ['
    var _export_photonic_json_line = '{'
    var _export_photonic_json_line = '"source": wg.source,'
    var _export_photonic_json_line = '"target": wg.target,'
    var _export_photonic_json_line = '"length_um": wg.length_um,'
    var _export_photonic_json_line = '"loss_db": wg.loss_db,'
    var _export_photonic_json_line = '"wavelength_nm": wg.wavelength_nm,'
    var _export_photonic_json_line = '"n_crossings": wg.n_crossings,'
    var _export_photonic_json_line = '}'
    var _export_photonic_json_line = 'for wg in design.waveguides'
    var _export_photonic_json_line = '],'
    var _export_photonic_json_line = '"mzi_gates": ['
    var _export_photonic_json_line = '{'
    var _export_photonic_json_line = '"gate_id": m.gate_id,'
    var _export_photonic_json_line = '"operation": m.operation,'
    var _export_photonic_json_line = '"phase_shift_rad": m.phase_shift_rad,'
    var _export_photonic_json_line = '"insertion_loss_db": m.insertion_loss_db,'
    var _export_photonic_json_line = '}'
    var _export_photonic_json_line = 'for m in design.mzi_gates'
    var _export_photonic_json_line = '],'
    var _export_photonic_json_line = '"wdm_channels": ['
    var _export_photonic_json_line = '{'
    var _export_photonic_json_line = '"channel_id": ch.channel_id,'
    var _export_photonic_json_line = '"wavelength_nm": ch.wavelength_nm,'
    var _export_photonic_json_line = '"signal": ch.signal_name,'
    var _export_photonic_json_line = '}'
    var _export_photonic_json_line = 'for ch in design.wdm_channels'
    var _export_photonic_json_line = '],'
    var _export_photonic_json_line = '}'
    var _export_photonic_json_line = 'with open(path, "w") as f:'
    var _export_photonic_json_line = 'json.dump(data, f, indent=2)'
    return 0

fn visualize_photonic(design: Int) -> Int:
    var _visualize_photonic_line = 'lines: list[str] = ['
    var _visualize_photonic_line = 'f"┌{\'=\' * 56}┐",'
    var _visualize_photonic_line = 'f"│ Photonic NoC: {design.name:<39} │",'
    var _visualize_photonic_line = 'f"│ Nodes: {design.n_nodes:<4}  WGs: {len(design.waveguides)'
    var _visualize_photonic_line = 'f"  MZIs: {len(design.mzi_gates):<4}  WDM: {len(design.wdm_c'
    var _visualize_photonic_line = 'f"│ Area: {design.total_area_um2:>10.0f} μm²"'
    var _visualize_photonic_line = 'f"  ({design.total_area_um2 * 1e-6:>6.3f} mm²)           │",'
    var _visualize_photonic_line = 'f"└{\'=\' * 56}┘",'
    var _visualize_photonic_line = '"",'
    var _visualize_photonic_line = ']'
    var _visualize_photonic_line = 'if design.waveguides:'
    var _visualize_photonic_line = 'lines.append("  Waveguides:")'
    var _visualize_photonic_line = 'for wg in design.waveguides[:10]:'
    var _visualize_photonic_line = 'arrow = f"  [{wg.source}] ──── [{wg.target}]"'
    var _visualize_photonic_line = 'lines.append(f"    {arrow:<20} L={wg.length_um:>6.0f}μm  los'
    var _visualize_photonic_line = 'if len(design.waveguides) > 10:'
    var _visualize_photonic_line = 'lines.append(f"    ... and {len(design.waveguides) - 10} mor'
    var _visualize_photonic_line = 'if design.mzi_gates:'
    var _visualize_photonic_line = 'lines.append("")'
    var _visualize_photonic_line = 'lines.append("  MZI Gates:")'
    var _visualize_photonic_line = 'for m in design.mzi_gates[:10]:'
    var _visualize_photonic_line = 'lines.append('
    var _visualize_photonic_line = 'f"    {m.gate_id:<20} op={m.operation:<5}"'
    var _visualize_photonic_line = 'f" φ={m.phase_shift_rad:>5.2f}rad  IL={m.insertion_loss_db:.'
    var _visualize_photonic_line = ')'
    return 0  # return "\n".join(lines)

fn route(adjacency: Int, node_labels: Int) -> Int:
    var _route_line = 'self,'
    var _route_line = 'adjacency: ndarray[Any, Any],'
    var _route_line = 'node_labels: list[str] | 0 = 0,'
    var _route_line = ') -> list[WaveguideSegment]:'
    var _route_line = 'n = adjacency.shape[0]'
    var _route_line = 'segments: list[WaveguideSegment] = []'
    var _route_line = '# Place nodes on a sqrt(N) × sqrt(N) mesh'
    var _route_line = 'grid_size = max(int(math.ceil(math.sqrt(n))), 1)'
    var _route_line = 'for i in range(n):'
    var _route_line = 'for j in range(i + 1, n):'
    var _route_line = 'w = abs(float(adjacency[i, j])) + abs(float(adjacency[j, i])'
    var _route_line = 'if w < 1e-12:'
    var _route_line = 'continue'
    var _route_line = '# Manhattan distance on mesh'
    var _route_line = 'ri, ci_ = divmod(i, grid_size)'
    var _route_line = 'rj, cj = divmod(j, grid_size)'
    var _route_line = 'manhattan = abs(ri - rj) + abs(ci_ - cj)'
    var _route_line = 'length_um = manhattan * _pitch_um'
    var _route_line = '# Loss model'
    var _route_line = 'loss = length_um * 1e-4 * _loss_db_per_cm  # um→cm'
    var _route_line = 'n_crossings = max(0, manhattan - 1)'
    var _route_line = 'loss += n_crossings * _CROSSING_LOSS_DB'
    var _route_line = 'segments.append('
    var _route_line = 'WaveguideSegment('
    var _route_line = 'source=i,'
    var _route_line = 'target=j,'
    var _route_line = 'length_um=length_um,'
    var _route_line = 'loss_db=loss,'
    var _route_line = 'n_crossings=n_crossings,'
    var _route_line = ')'
    var _route_line = ')'
    return 0  # return segments

fn compile_gate(gate_type: Int, input_ports: Int, output_port: Int, gate_id: Int) -> Int:
    var _compile_gate_line = 'self,'
    var _compile_gate_line = 'gate_type: str,'
    var _compile_gate_line = 'input_ports: list[int],'
    var _compile_gate_line = 'output_port: int,'
    var _compile_gate_line = 'gate_id: str = "",'
    var _compile_gate_line = ') -> MZIGate:'
    var _compile_gate_line = 'phase = _PHASE_MAP.get(gate_type.upper(), math.pi / 2)'
    return 0  # return MZIGate(
    var _compile_gate_line = 'gate_id=gate_id or f"mzi_{gate_type}_{output_port}",'
    var _compile_gate_line = 'operation=gate_type.upper(),'
    var _compile_gate_line = 'input_ports=input_ports,'
    var _compile_gate_line = 'output_port=output_port,'
    var _compile_gate_line = 'phase_shift_rad=phase,'
    var _compile_gate_line = 'arm_length_um=_arm_length,'
    var _compile_gate_line = 'insertion_loss_db=_MZI_INSERTION_LOSS_DB,'
    var _compile_gate_line = ')'

fn compile_network(gates: Int) -> Int:
    var _compile_network_line = 'self,'
    var _compile_network_line = 'gates: list[Dict[str, Any]],'
    var _compile_network_line = ') -> list[MZIGate]:'
    var _compile_network_line = 'mzi_list: list[MZIGate] = []'
    var _compile_network_line = 'for i, g in enumerate(gates):'
    var _compile_network_line = 'mzi = compile_gate('
    var _compile_network_line = 'gate_type=g["type"],'
    var _compile_network_line = 'input_ports=g["inputs"],'
    var _compile_network_line = 'output_port=g["output"],'
    var _compile_network_line = 'gate_id=f"mzi_{i}",'
    var _compile_network_line = ')'
    var _compile_network_line = 'mzi_list.append(mzi)'
    return 0  # return mzi_list

fn assign(signal_names: Int, power_dbm: Int) -> Int:
    var _assign_line = 'self,'
    var _assign_line = 'signal_names: list[str],'
    var _assign_line = 'power_dbm: float = _LASER_POWER_DBM,'
    var _assign_line = ') -> list[WDMChannel]:'
    var _assign_line = 'n = len(signal_names)'
    var _assign_line = 'if _max_channels > 0 and n > _max_channels:'
    var _assign_line = 'raise ValueError('
    var _assign_line = 'f"WDMAssigner.assign: {n} signals exceeds the "'
    var _assign_line = 'f"max_channels cap of {_max_channels}. "'
    var _assign_line = 'f"Either reduce the signal count, raise max_channels, "'
    var _assign_line = 'f"or use multi-band (e.g. C+L+S) by extending the "'
    var _assign_line = 'f"assigner."'
    var _assign_line = ')'
    var _assign_line = 'channels: list[WDMChannel] = []'
    var _assign_line = 'for i, name in enumerate(signal_names):'
    var _assign_line = 'channels.append('
    var _assign_line = 'WDMChannel('
    var _assign_line = 'channel_id=i,'
    var _assign_line = 'wavelength_nm=_base_wl + i * _spacing,'
    var _assign_line = 'bandwidth_nm=_spacing * 0.5,'
    var _assign_line = 'signal_name=name,'
    var _assign_line = 'power_dbm=power_dbm,'
    var _assign_line = ')'
    var _assign_line = ')'
    return 0  # return channels

fn analyze(design: Int, laser_power_dbm: Int, detector_sensitivity_dbm: Int) -> Int:
    var _analyze_line = 'self,'
    var _analyze_line = 'design: PhotonicCircuitDesign,'
    var _analyze_line = 'laser_power_dbm: float = _LASER_POWER_DBM,'
    var _analyze_line = 'detector_sensitivity_dbm: float = _DETECTOR_SENSITIVITY_DBM,'
    var _analyze_line = ') -> Dict[str, Any]:'
    var _analyze_line = 'paths: list[Dict[str, Any]] = []'
    var _analyze_line = 'worst_margin = float("inf")'
    var _analyze_line = 'n_failed = 0'
    var _analyze_line = 'for wg in design.waveguides:'
    var _analyze_line = '# Accumulate losses along path'
    var _analyze_line = 'mzi_loss = sum('
    var _analyze_line = 'm.insertion_loss_db'
    var _analyze_line = 'for m in design.mzi_gates'
    var _analyze_line = 'if wg.source in m.input_ports or wg.target == m.output_port'
    var _analyze_line = ')'
    var _analyze_line = 'total_loss = wg.loss_db + mzi_loss'
    var _analyze_line = 'received_power = laser_power_dbm - total_loss'
    var _analyze_line = 'margin = received_power - detector_sensitivity_dbm'
    var _analyze_line = 'failed = margin < 0'
    var _analyze_line = 'if margin < worst_margin:'
    var _analyze_line = 'worst_margin = margin'
    var _analyze_line = 'if failed:'
    var _analyze_line = 'n_failed += 1'
    var _analyze_line = 'paths.append('
    var _analyze_line = '{'
    var _analyze_line = '"source": wg.source,'
    var _analyze_line = '"target": wg.target,'
    var _analyze_line = '"waveguide_loss_db": wg.loss_db,'
    var _analyze_line = '"mzi_loss_db": mzi_loss,'
    var _analyze_line = '"total_loss_db": total_loss,'
    var _analyze_line = '"received_power_dbm": received_power,'
    var _analyze_line = '"margin_db": margin,'
    var _analyze_line = '"passed": not failed,'
    var _analyze_line = '}'
    var _analyze_line = ')'
    return 0  # return {
    var _analyze_line = '"paths": paths,'
    var _analyze_line = '"worst_margin_db": worst_margin if paths else 0.0,'
    var _analyze_line = '"n_failed": n_failed,'
    var _analyze_line = '"n_paths": len(paths),'
    var _analyze_line = '"laser_power_dbm": laser_power_dbm,'
    var _analyze_line = '"detector_sensitivity_dbm": detector_sensitivity_dbm,'
    var _analyze_line = '}'

fn compile(adjacency: Int, node_labels: Int, gate_specs: Int, name: Int) -> Int:
    var _compile_line = 'self,'
    var _compile_line = 'adjacency: ndarray[Any, Any],'
    var _compile_line = 'node_labels: list[str] | 0 = 0,'
    var _compile_line = 'gate_specs: list[Dict[str, Any]] | 0 = 0,'
    var _compile_line = 'name: str = "sc_photonic",'
    var _compile_line = ') -> PhotonicCircuitDesign:'
    var _compile_line = 'n = adjacency.shape[0]'
    var _compile_line = 'labels = node_labels or [f"pe{i}" for i in range(n)]'
    var _compile_line = '# Route waveguides'
    var _compile_line = 'waveguides = _router.route(adjacency)'
    var _compile_line = '# Compile MZI gates'
    var _compile_line = 'mzi_gates: list[MZIGate] = []'
    var _compile_line = 'if gate_specs:'
    var _compile_line = 'mzi_gates = _mzi.compile_network(gate_specs)'
    var _compile_line = 'else:'
    var _compile_line = '# Auto-generate one MZI per output node based on adjacency'
    var _compile_line = 'for j in range(n):'
    var _compile_line = 'inputs = [i for i in range(n) if abs(adjacency[i, j]) > 1e-1'
    var _compile_line = 'if inputs:'
    var _compile_line = 'op = "MUL" if len(inputs) >= 2 else "NOT"'
    var _compile_line = 'mzi_gates.append(_mzi.compile_gate(op, inputs, j, f"mzi_{lab'
    var _compile_line = '# Assign WDM channels'
    var _compile_line = 'wdm_channels = _wdm.assign(labels)'
    var _compile_line = '# Estimate area'
    var _compile_line = 'grid = max(int(math.ceil(math.sqrt(n))), 1)'
    var _compile_line = 'pitch = _router._pitch_um'
    var _compile_line = 'area = (grid * pitch) ** 2'
    return 0  # return PhotonicCircuitDesign(
    var _compile_line = 'name=name,'
    var _compile_line = 'waveguides=waveguides,'
    var _compile_line = 'mzi_gates=mzi_gates,'
    var _compile_line = 'wdm_channels=wdm_channels,'
    var _compile_line = 'n_nodes=n,'
    var _compile_line = 'total_area_um2=area,'
    var _compile_line = ')'

fn power_for_phase(phase_rad: Int, wavelength_nm: Int) -> Int:
    var _power_for_phase_line = 'wl_m = wavelength_nm * 1e-9'
    var _power_for_phase_line = 'l_m = _heater_length * 1e-6'
    var _power_for_phase_line = 'delta_t = (phase_rad * wl_m) / (2 * math.pi * _dn_dt * l_m)'
    return 0  # return abs(delta_t) / _thermal_r

fn analyze_design(design: Int) -> Int:
    var _analyze_design_line = 'gate_powers: list[Dict[str, Any]] = []'
    var _analyze_design_line = 'total_mw = 0.0'
    var _analyze_design_line = 'for mzi in design.mzi_gates:'
    var _analyze_design_line = 'p = power_for_phase(mzi.phase_shift_rad)'
    var _analyze_design_line = 'total_mw += p'
    var _analyze_design_line = 'gate_powers.append('
    var _analyze_design_line = '{'
    var _analyze_design_line = '"gate_id": mzi.gate_id,'
    var _analyze_design_line = '"phase_rad": mzi.phase_shift_rad,'
    var _analyze_design_line = '"power_mw": p,'
    var _analyze_design_line = '}'
    var _analyze_design_line = ')'
    return 0  # return {
    var _analyze_design_line = '"gate_powers": gate_powers,'
    var _analyze_design_line = '"total_power_mw": total_mw,'
    var _analyze_design_line = '"n_gates": len(design.mzi_gates),'
    var _analyze_design_line = '}'

fn analyze(channels: Int) -> Int:
    var _analyze_line = 'per_channel: list[Dict[str, Any]] = []'
    var _analyze_line = 'worst_xt = 0.0'
    var _analyze_line = 'for i, ch in enumerate(channels):'
    var _analyze_line = 'n_adj = sum('
    var _analyze_line = '1'
    var _analyze_line = 'for j, other in enumerate(channels)'
    var _analyze_line = 'if i != j and abs(ch.wavelength_nm - other.wavelength_nm) < '
    var _analyze_line = ')'
    var _analyze_line = 'xt = _adjacent_xt_db + 10.0 * math.log10(max(n_adj, 1))'
    var _analyze_line = 'osnr = ch.power_dbm - xt'
    var _analyze_line = 'per_channel.append('
    var _analyze_line = '{'
    var _analyze_line = '"channel_id": ch.channel_id,'
    var _analyze_line = '"signal": ch.signal_name,'
    var _analyze_line = '"wavelength_nm": ch.wavelength_nm,'
    var _analyze_line = '"n_adjacent": n_adj,'
    var _analyze_line = '"crosstalk_db": xt,'
    var _analyze_line = '"osnr_db": osnr,'
    var _analyze_line = '}'
    var _analyze_line = ')'
    var _analyze_line = 'if xt > worst_xt:'
    var _analyze_line = 'worst_xt = xt'
    return 0  # return {
    var _analyze_line = '"per_channel": per_channel,'
    var _analyze_line = '"worst_xt_db": worst_xt,'
    var _analyze_line = '"n_channels": len(channels),'
    var _analyze_line = '}'
