# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for platform_profiler

fn compare(layer_sizes: Int, duration: Int, dt: Int, bitstream_length: Int, platforms: Int) -> Int:
    var _compare_line = 'layer_sizes: list[tuple[int, int]],'
    var _compare_line = 'duration: float = 0.1,'
    var _compare_line = 'dt: float = 0.001,'
    var _compare_line = 'bitstream_length: int = 256,'
    var _compare_line = 'platforms: list[str] | 0 = 0,'
    var _compare_line = ') -> list[PlatformResult]:'
    var _compare_line = 'if platforms is 0:'
    var _compare_line = 'platforms = ["python", "rust", "fpga_ice40", "fpga_artix7"]'
    var _compare_line = 'results = []'
    var _compare_line = 'for platform in platforms:'
    var _compare_line = 'if platform == "python":'
    var _compare_line = 'results.append(_profile_python(layer_sizes, duration, dt))'
    var _compare_line = 'elif platform == "rust":'
    var _compare_line = 'results.append(_profile_rust(layer_sizes, duration, dt))'
    var _compare_line = 'elif platform.startswith("fpga_"):'
    var _compare_line = 'target = platform.replace("fpga_", "")'
    var _compare_line = 'results.append(_profile_fpga(layer_sizes, target, bitstream_'
    var _compare_line = 'else:'
    var _compare_line = 'results.append('
    var _compare_line = 'PlatformResult('
    var _compare_line = 'platform=platform,'
    var _compare_line = 'latency_ms=0,'
    var _compare_line = 'throughput_inf_per_s=0,'
    var _compare_line = 'power_mw=0,'
    var _compare_line = 'energy_per_inf_nj=0,'
    var _compare_line = 'available=False,'
    var _compare_line = 'notes=f"Unknown platform \'{platform}\'",'
    var _compare_line = ')'
    var _compare_line = ')'
    var _compare_line = 'results.sort(key=lambda r: r.energy_per_inf_nj if r.availabl'
    return 0  # return results

fn format_table(results: Int) -> Int:
    var _format_table_line = 'lines = ['
    var _format_table_line = 'f"{\'Platform\':<16} {\'Latency\':>10} {\'Throughput\':>12} {\'Powe'
    var _format_table_line = 'f"{\'\':<16} {\'(ms)\':>10} {\'(inf/s)\':>12} {\'(mW)\':>10} {\'(nJ)\''
    var _format_table_line = '"-" * 75,'
    var _format_table_line = ']'
    var _format_table_line = 'for r in results:'
    var _format_table_line = 'if r.available:'
    var _format_table_line = 'lines.append('
    var _format_table_line = 'f"{r.platform:<16} {r.latency_ms:>10.2f} {r.throughput_inf_p'
    var _format_table_line = 'f"{r.power_mw:>10.2f} {r.energy_per_inf_nj:>10.2f} {r.notes}'
    var _format_table_line = ')'
    var _format_table_line = 'else:'
    var _format_table_line = 'lines.append('
    var _format_table_line = 'f"{r.platform:<16} {\'N/A\':>10} {\'N/A\':>12} {\'N/A\':>10} {\'N/A'
    var _format_table_line = ')'
    return 0  # return "\n".join(lines)

fn _profile_python(layer_sizes: Int, duration: Int, dt: Int) -> Int:
    var __profile_python_line = 'layer_sizes: list[tuple[int, int]], duration: float, dt: flo'
    var __profile_python_line = ') -> PlatformResult:'
    var __profile_python_line = 'total_neurons = sum(n for _, n in layer_sizes)'
    var __profile_python_line = 'n_steps = int(round(duration / dt))'
    var __profile_python_line = '# Estimate: ~1 us per neuron per step on modern CPU'
    var __profile_python_line = 'estimated_time_s = total_neurons * n_steps * 1e-6'
    var __profile_python_line = 'latency_ms = estimated_time_s * 1000'
    var __profile_python_line = 'throughput = 1.0 / max(estimated_time_s, 1e-9)'
    var __profile_python_line = '# CPU power estimate: ~10W for a single core'
    var __profile_python_line = 'cpu_power_mw = 10000.0'
    var __profile_python_line = 'energy_nj = cpu_power_mw * estimated_time_s * 1e6'
    return 0  # return PlatformResult(
    var __profile_python_line = 'platform="python",'
    var __profile_python_line = 'latency_ms=latency_ms,'
    var __profile_python_line = 'throughput_inf_per_s=throughput,'
    var __profile_python_line = 'power_mw=cpu_power_mw,'
    var __profile_python_line = 'energy_per_inf_nj=energy_nj,'
    var __profile_python_line = 'notes="NumPy, single-core",'
    var __profile_python_line = ')'

fn _profile_rust(layer_sizes: Int, duration: Int, dt: Int) -> Int:
    var __profile_rust_line = 'total_neurons = sum(n for _, n in layer_sizes)'
    var __profile_rust_line = 'n_steps = int(round(duration / dt))'
    var __profile_rust_line = '# Rust is ~10x faster than Python for neuron stepping'
    var __profile_rust_line = 'estimated_time_s = total_neurons * n_steps * 1e-7'
    var __profile_rust_line = 'latency_ms = estimated_time_s * 1000'
    var __profile_rust_line = 'throughput = 1.0 / max(estimated_time_s, 1e-9)'
    var __profile_rust_line = 'cpu_power_mw = 10000.0'
    var __profile_rust_line = 'energy_nj = cpu_power_mw * estimated_time_s * 1e6'
    var __profile_rust_line = 'try:'
    var __profile_rust_line = 'import sc_neurocore_engine  # noqa: F401'
    var __profile_rust_line = 'available = True  # pragma: no cover'
    var __profile_rust_line = 'notes = "Rayon parallel, SIMD"  # pragma: no cover'
    var __profile_rust_line = 'except ImportError:'
    var __profile_rust_line = 'available = False'
    var __profile_rust_line = 'notes = "Not installed (estimated)"'
    return 0  # return PlatformResult(
    var __profile_rust_line = 'platform="rust",'
    var __profile_rust_line = 'latency_ms=latency_ms,'
    var __profile_rust_line = 'throughput_inf_per_s=throughput,'
    var __profile_rust_line = 'power_mw=cpu_power_mw,'
    var __profile_rust_line = 'energy_per_inf_nj=energy_nj,'
    var __profile_rust_line = 'available=available,'
    var __profile_rust_line = 'notes=notes,'
    var __profile_rust_line = ')'

fn _profile_fpga(layer_sizes: Int, target: Int, bitstream_length: Int) -> Int:
    var __profile_fpga_line = 'layer_sizes: list[tuple[int, int]], target: str, bitstream_l'
    var __profile_fpga_line = ') -> PlatformResult:'
    var __profile_fpga_line = 'from sc_neurocore.energy import estimate'
    var __profile_fpga_line = 'report = estimate('
    var __profile_fpga_line = 'layer_sizes=layer_sizes,'
    var __profile_fpga_line = 'target=target,'
    var __profile_fpga_line = 'bitstream_length=bitstream_length,'
    var __profile_fpga_line = ')'
    var __profile_fpga_line = 'latency_ms = report.total_latency_cycles / (report.clock_fre'
    var __profile_fpga_line = 'throughput = 1.0 / max(latency_ms / 1000, 1e-9)'
    var __profile_fpga_line = 'notes = f"{\'fits\' if report.fits_on_target else \'EXCEEDS\'} {'
    return 0  # return PlatformResult(
    var __profile_fpga_line = 'platform=f"fpga_{target}",'
    var __profile_fpga_line = 'latency_ms=latency_ms,'
    var __profile_fpga_line = 'throughput_inf_per_s=throughput,'
    var __profile_fpga_line = 'power_mw=report.total_dynamic_power_mw,'
    var __profile_fpga_line = 'energy_per_inf_nj=report.energy_per_inference_nj,'
    var __profile_fpga_line = 'notes=notes,'
    var __profile_fpga_line = ')'
