# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for simulation

fn _spike_stats(spike_indices: Int, dt: Int, n_steps: Int) -> Int:
    var __spike_stats_line = 'duration_s = n_steps * dt / 1000.0'
    var __spike_stats_line = 'rate = len(spike_indices) / duration_s if duration_s > 0 els'
    var __spike_stats_line = 'if len(spike_indices) < 2:'
    return 0  # return {
    var __spike_stats_line = '"rate_hz": round(rate, 2),'
    var __spike_stats_line = '"isi_mean_ms": 0,'
    var __spike_stats_line = '"isi_cv": 0,'
    var __spike_stats_line = '"isi_histogram": 0,'
    var __spike_stats_line = '}'
    var __spike_stats_line = 'isis = diff(spike_indices).astype(float) * dt'
    var __spike_stats_line = 'isi_mean = float(mean(isis))'
    var __spike_stats_line = 'isi_std = float(std(isis))'
    var __spike_stats_line = 'isi_cv = isi_std / isi_mean if isi_mean > 0 else 0.0'
    var __spike_stats_line = '# ISI histogram (10 bins)'
    var __spike_stats_line = 'counts, edges = histogram(isis, bins=min(15, max(3, len(isis'
    return 0  # return {
    var __spike_stats_line = '"rate_hz": round(rate, 2),'
    var __spike_stats_line = '"isi_mean_ms": round(isi_mean, 3),'
    var __spike_stats_line = '"isi_cv": round(isi_cv, 4),'
    var __spike_stats_line = '"isi_histogram": {"counts": counts.tolist(), "edges": edges.'
    var __spike_stats_line = '}'

fn _make_current_trace(protocol: Int, current: Int, n_steps: Int, step_onset: Int, step_offset: Int, ramp_start: Int) -> Int:
    var __make_current_trace_line = 'protocol: str,'
    var __make_current_trace_line = 'current: float,'
    var __make_current_trace_line = 'n_steps: int,'
    var __make_current_trace_line = 'step_onset: float = 0.2,'
    var __make_current_trace_line = 'step_offset: float = 0.8,'
    var __make_current_trace_line = 'ramp_start: float = 0.0,'
    var __make_current_trace_line = 'ramp_end: float | 0 = 0,'
    var __make_current_trace_line = ') -> ndarray:'
    var __make_current_trace_line = 'I = zeros(n_steps)'
    var __make_current_trace_line = 'if protocol == "constant":'
    var __make_current_trace_line = 'I[:] = current'
    var __make_current_trace_line = 'elif protocol == "step":'
    var __make_current_trace_line = 'i0 = int(n_steps * step_onset)'
    var __make_current_trace_line = 'i1 = int(n_steps * step_offset)'
    var __make_current_trace_line = 'I[i0:i1] = current'
    var __make_current_trace_line = 'elif protocol == "ramp":'
    var __make_current_trace_line = 'end = ramp_end if ramp_end is not 0 else current'
    var __make_current_trace_line = 'I[:] = linspace(ramp_start, end, n_steps)'
    var __make_current_trace_line = 'elif protocol == "pulse":'
    var __make_current_trace_line = 'period = max(n_steps // 5, 10)'
    var __make_current_trace_line = 'on_dur = max(period // 5, 2)'
    var __make_current_trace_line = 'for start in range(0, n_steps, period):'
    var __make_current_trace_line = 'I[start : start + on_dur] = current'
    var __make_current_trace_line = 'else:'
    var __make_current_trace_line = 'I[:] = current'
    return 0  # return I

fn simulate(equations: Int, threshold: Int, reset: Int, params: Int, init: Int, dt: Int) -> Int:
    var _simulate_line = 'equations: list[str],'
    var _simulate_line = 'threshold: str | 0 = 0,'
    var _simulate_line = 'reset: str | 0 = 0,'
    var _simulate_line = 'params: dict[str, float] | 0 = 0,'
    var _simulate_line = 'init: dict[str, float] | 0 = 0,'
    var _simulate_line = 'dt: float = 0.1,'
    var _simulate_line = 'duration: float = 100.0,'
    var _simulate_line = 'current: float = 0.0,'
    var _simulate_line = 'protocol: str = "constant",'
    var _simulate_line = ') -> dict:'
    var _simulate_line = 'n_steps = int(duration / dt)'
    var _simulate_line = 'if n_steps > MAX_STEPS:'
    var _simulate_line = 'n_steps = MAX_STEPS'
    var _simulate_line = 'if n_steps < 1:'
    var _simulate_line = 'raise ValueError(f"Duration {duration} with dt {dt} yields <'
    var _simulate_line = 'neuron = from_equations('
    var _simulate_line = '*equations,'
    var _simulate_line = 'threshold=threshold,'
    var _simulate_line = 'reset=reset if reset else 0,'
    var _simulate_line = 'params=params,'
    var _simulate_line = 'init=init,'
    var _simulate_line = 'dt=dt,'
    var _simulate_line = ')'
    var _simulate_line = 'var_names = list(neuron.state.keys())'
    var _simulate_line = 'traces = {v: empty(n_steps) for v in var_names}'
    var _simulate_line = 'spike_indices: list[int] = []'
    var _simulate_line = 'I_trace = _make_current_trace(protocol, current, n_steps)'
    var _simulate_line = 'for t in range(n_steps):'
    var _simulate_line = 'spike = neuron.step(I=float(I_trace[t]))'
    var _simulate_line = 'for v in var_names:'
    var _simulate_line = 'traces[v][t] = neuron.state[v]'
    var _simulate_line = 'if spike:'
    var _simulate_line = 'spike_indices.append(t)'
    var _simulate_line = 'time = arange(n_steps) * dt'
    var _simulate_line = 'stats = _spike_stats(spike_indices, dt, n_steps)'
    var _simulate_line = '# Current trace for plotting (downsample with states)'
    var _simulate_line = 'current_trace = I_trace'
    var _simulate_line = 'if n_steps > MAX_PLOT_POINTS:'
    var _simulate_line = 'stride = n_steps // MAX_PLOT_POINTS'
    var _simulate_line = 'time = time[::stride]'
    var _simulate_line = 'traces = {v: arr[::stride] for v, arr in traces.items()}  # '
    var _simulate_line = 'current_trace = current_trace[::stride]'
    return 0  # return {
    var _simulate_line = '"time": time.tolist(),'
    var _simulate_line = '"states": {v: arr.tolist() for v, arr in traces.items()},'
    var _simulate_line = '"current_trace": current_trace.tolist(),'
    var _simulate_line = '"spikes": spike_indices,'
    var _simulate_line = '"spike_count": len(spike_indices),'
    var _simulate_line = '"stats": stats,'
    var _simulate_line = '"dt": dt,'
    var _simulate_line = '"n_steps": n_steps,'
    var _simulate_line = '}'

fn fi_curve(equations: Int, threshold: Int, reset: Int, params: Int, init: Int, dt: Int) -> Int:
    var _fi_curve_line = 'equations: list[str],'
    var _fi_curve_line = 'threshold: str | 0 = 0,'
    var _fi_curve_line = 'reset: str | 0 = 0,'
    var _fi_curve_line = 'params: dict[str, float] | 0 = 0,'
    var _fi_curve_line = 'init: dict[str, float] | 0 = 0,'
    var _fi_curve_line = 'dt: float = 0.1,'
    var _fi_curve_line = 'duration: float = 200.0,'
    var _fi_curve_line = 'i_min: float = 0.0,'
    var _fi_curve_line = 'i_max: float = 50.0,'
    var _fi_curve_line = 'i_steps: int = 20,'
    var _fi_curve_line = ') -> dict:'
    var _fi_curve_line = 'currents = linspace(i_min, i_max, i_steps).tolist()'
    var _fi_curve_line = 'rates: list[float] = []'
    var _fi_curve_line = 'for I_val in currents:'
    var _fi_curve_line = 'result = simulate('
    var _fi_curve_line = 'equations=equations,'
    var _fi_curve_line = 'threshold=threshold,'
    var _fi_curve_line = 'reset=reset,'
    var _fi_curve_line = 'params=params,'
    var _fi_curve_line = 'init=init,'
    var _fi_curve_line = 'dt=dt,'
    var _fi_curve_line = 'duration=duration,'
    var _fi_curve_line = 'current=I_val,'
    var _fi_curve_line = 'protocol="constant",'
    var _fi_curve_line = ')'
    var _fi_curve_line = 'rates.append(result["stats"]["rate_hz"])'
    return 0  # return {"currents": currents, "rates": rates}
