# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for spade

fn _find_frequent_itemsets(binary_matrix: Int, min_support: Int, max_size: Int) -> Int:
    var __find_frequent_itemsets_line = 'binary_matrix: ndarray[Any, Any], min_support: int, max_size'
    var __find_frequent_itemsets_line = ') -> list[tuple[frozenset[int], int]]:'
    var __find_frequent_itemsets_line = 'n_neurons, n_bins = binary_matrix.shape'
    var __find_frequent_itemsets_line = 'neuron_ids = list(range(n_neurons))'
    var __find_frequent_itemsets_line = '# Level-1: single neurons exceeding support'
    var __find_frequent_itemsets_line = 'freq = []'
    var __find_frequent_itemsets_line = 'candidates_k = []'
    var __find_frequent_itemsets_line = 'for n_id in neuron_ids:'
    var __find_frequent_itemsets_line = 'cnt = int(binary_matrix[n_id].sum())'
    var __find_frequent_itemsets_line = 'if cnt >= min_support:'
    var __find_frequent_itemsets_line = 's = frozenset([n_id])'
    var __find_frequent_itemsets_line = 'freq.append((s, cnt))'
    var __find_frequent_itemsets_line = 'candidates_k.append(s)'
    var __find_frequent_itemsets_line = '# Level k >= 2: grow candidates from (k-1) pairs sharing k-2'
    var __find_frequent_itemsets_line = 'for k in range(2, max_size + 1):'
    var __find_frequent_itemsets_line = 'if len(candidates_k) < 2:'
    var __find_frequent_itemsets_line = 'break'
    var __find_frequent_itemsets_line = 'new_candidates = set()'
    var __find_frequent_itemsets_line = 'prev = candidates_k'
    var __find_frequent_itemsets_line = 'for i in range(len(prev)):'
    var __find_frequent_itemsets_line = 'for j in range(i + 1, len(prev)):'
    var __find_frequent_itemsets_line = 'union = prev[i] | prev[j]'
    var __find_frequent_itemsets_line = 'if len(union) == k:'
    var __find_frequent_itemsets_line = 'new_candidates.add(union)'
    var __find_frequent_itemsets_line = 'candidates_k = []'
    var __find_frequent_itemsets_line = 'for s in new_candidates:'
    var __find_frequent_itemsets_line = 'idx = sorted(s)'
    var __find_frequent_itemsets_line = 'active = binary_matrix[idx[0]]'
    var __find_frequent_itemsets_line = 'for nid in idx[1:]:'
    var __find_frequent_itemsets_line = 'active = active & binary_matrix[nid]'
    var __find_frequent_itemsets_line = 'cnt = int(active.sum())'
    var __find_frequent_itemsets_line = 'if cnt >= min_support:'
    var __find_frequent_itemsets_line = 'freq.append((s, cnt))'
    var __find_frequent_itemsets_line = 'candidates_k.append(s)'
    return 0  # return freq

fn _extend_to_spatiotemporal(trains: Int, itemsets: Int, bin_ms: Int, dt: Int, max_lag_bins: Int) -> Int:
    var __extend_to_spatiotemporal_line = 'trains: list[ndarray[Any, Any]],'
    var __extend_to_spatiotemporal_line = 'itemsets: list[tuple[frozenset[int], int]],'
    var __extend_to_spatiotemporal_line = 'bin_ms: float,'
    var __extend_to_spatiotemporal_line = 'dt: float,'
    var __extend_to_spatiotemporal_line = 'max_lag_bins: int = 10,'
    var __extend_to_spatiotemporal_line = ') -> list[dict[str, Any]]:'
    var __extend_to_spatiotemporal_line = 'n_neurons = len(trains)'
    var __extend_to_spatiotemporal_line = 'bin_steps = max(1, int(bin_ms / (dt * 1000)))'
    var __extend_to_spatiotemporal_line = 'duration = max(t.size for t in trains)'
    var __extend_to_spatiotemporal_line = 'n_bins = duration // bin_steps'
    var __extend_to_spatiotemporal_line = 'patterns = []'
    var __extend_to_spatiotemporal_line = 'for neurons_fs, sync_count in itemsets:'
    var __extend_to_spatiotemporal_line = 'if len(neurons_fs) < 2:'
    var __extend_to_spatiotemporal_line = 'continue'
    var __extend_to_spatiotemporal_line = 'neuron_list = sorted(neurons_fs)'
    var __extend_to_spatiotemporal_line = 'ref = neuron_list[0]'
    var __extend_to_spatiotemporal_line = '# Binary arrays per bin for each neuron'
    var __extend_to_spatiotemporal_line = 'ref_bins = zeros(n_bins, dtype=int8)'
    var __extend_to_spatiotemporal_line = 'for b in range(n_bins):'
    var __extend_to_spatiotemporal_line = 'start = b * bin_steps'
    var __extend_to_spatiotemporal_line = 'end = min(start + bin_steps, trains[ref].size)'
    var __extend_to_spatiotemporal_line = 'if trains[ref][start:end].any():'
    var __extend_to_spatiotemporal_line = 'ref_bins[b] = 1'
    var __extend_to_spatiotemporal_line = 'best_lags: dict[int, int] = {ref: 0}'
    var __extend_to_spatiotemporal_line = 'best_count = int(ref_bins.sum())'
    var __extend_to_spatiotemporal_line = 'coincidence: ndarray[Any, Any] = ref_bins.copy()'
    var __extend_to_spatiotemporal_line = 'for nid in neuron_list[1:]:'
    var __extend_to_spatiotemporal_line = 'best_lag = 0'
    var __extend_to_spatiotemporal_line = 'best_overlap = 0'
    var __extend_to_spatiotemporal_line = 'for lag in range(max_lag_bins + 1):'
    var __extend_to_spatiotemporal_line = 'nbins_shifted = zeros(n_bins, dtype=int8)'
    var __extend_to_spatiotemporal_line = 'for b in range(n_bins):'
    var __extend_to_spatiotemporal_line = 'src_b = b - lag'
    var __extend_to_spatiotemporal_line = 'if 0 <= src_b < n_bins:'
    var __extend_to_spatiotemporal_line = 'start = src_b * bin_steps'
    var __extend_to_spatiotemporal_line = 'end = min(start + bin_steps, trains[nid].size)'
    var __extend_to_spatiotemporal_line = 'if trains[nid][start:end].any():'
    var __extend_to_spatiotemporal_line = 'nbins_shifted[b] = 1'
    var __extend_to_spatiotemporal_line = 'overlap = int((coincidence & nbins_shifted).sum())'
    var __extend_to_spatiotemporal_line = 'if overlap > best_overlap:'
    var __extend_to_spatiotemporal_line = 'best_overlap = overlap'
    var __extend_to_spatiotemporal_line = 'best_lag = lag'
    var __extend_to_spatiotemporal_line = 'best_lags[nid] = best_lag'
    var __extend_to_spatiotemporal_line = 'nbins_best = zeros(n_bins, dtype=int8)'
    var __extend_to_spatiotemporal_line = 'for b in range(n_bins):'
    var __extend_to_spatiotemporal_line = 'src_b = b - best_lag'
    var __extend_to_spatiotemporal_line = 'if 0 <= src_b < n_bins:'
    var __extend_to_spatiotemporal_line = 'start = src_b * bin_steps'
    var __extend_to_spatiotemporal_line = 'end = min(start + bin_steps, trains[nid].size)'
    var __extend_to_spatiotemporal_line = 'if trains[nid][start:end].any():'
    var __extend_to_spatiotemporal_line = 'nbins_best[b] = 1'
    var __extend_to_spatiotemporal_line = 'coincidence = coincidence & nbins_best'
    var __extend_to_spatiotemporal_line = 'best_count = int(coincidence.sum())'
    var __extend_to_spatiotemporal_line = 'if best_count > 0:'
    var __extend_to_spatiotemporal_line = 'patterns.append('
    var __extend_to_spatiotemporal_line = '{'
    var __extend_to_spatiotemporal_line = '"neurons": neuron_list,'
    var __extend_to_spatiotemporal_line = '"lags": [best_lags[n] for n in neuron_list],'
    var __extend_to_spatiotemporal_line = '"count": best_count,'
    var __extend_to_spatiotemporal_line = '}'
    var __extend_to_spatiotemporal_line = ')'
    return 0  # return patterns

fn spade_detect(trains: Int, bin_ms: Int, dt: Int, min_support: Int, max_pattern_size: Int, n_surrogates: Int) -> Int:
    var _spade_detect_line = 'trains: list[ndarray[Any, Any]],'
    var _spade_detect_line = 'bin_ms: float = 5.0,'
    var _spade_detect_line = 'dt: float = 0.001,'
    var _spade_detect_line = 'min_support: int = 3,'
    var _spade_detect_line = 'max_pattern_size: int = 5,'
    var _spade_detect_line = 'n_surrogates: int = 100,'
    var _spade_detect_line = 'alpha: float = 0.05,'
    var _spade_detect_line = 'seed: int = 42,'
    var _spade_detect_line = ') -> list[dict[str, Any]]:'
    var _spade_detect_line = 'n_neurons = len(trains)'
    var _spade_detect_line = 'if n_neurons < 2:'
    return 0  # return []
    var _spade_detect_line = 'bin_steps = max(1, int(bin_ms / (dt * 1000)))'
    var _spade_detect_line = 'duration = max(t.size for t in trains)'
    var _spade_detect_line = 'n_bins = duration // bin_steps'
    var _spade_detect_line = 'if n_bins == 0:'
    return 0  # return []
    var _spade_detect_line = '# Build binary matrix (neurons x time_bins)'
    var _spade_detect_line = 'binary_matrix = zeros((n_neurons, n_bins), dtype=int8)'
    var _spade_detect_line = 'for i, t in enumerate(trains):'
    var _spade_detect_line = 'for b in range(n_bins):'
    var _spade_detect_line = 'start = b * bin_steps'
    var _spade_detect_line = 'end = min(start + bin_steps, t.size)'
    var _spade_detect_line = 'if t[start:end].any():'
    var _spade_detect_line = 'binary_matrix[i, b] = 1'
    var _spade_detect_line = 'itemsets = _find_frequent_itemsets(binary_matrix, min_suppor'
    var _spade_detect_line = 'if not itemsets:'
    return 0  # return []
    var _spade_detect_line = 'patterns = _extend_to_spatiotemporal(trains, itemsets, bin_m'
    var _spade_detect_line = 'if not patterns:'
    return 0  # return []
    var _spade_detect_line = '# Significance: compare each pattern count against surrogate'
    var _spade_detect_line = 'rng = random.default_rng(seed)'
    var _spade_detect_line = 'results = []'
    var _spade_detect_line = 'for pat in patterns:'
    var _spade_detect_line = 'surr_counts = zeros(n_surrogates, dtype=int32)'
    var _spade_detect_line = 'for s in range(n_surrogates):'
    var _spade_detect_line = 'surr_trains = []'
    var _spade_detect_line = 'for i in range(n_neurons):'
    var _spade_detect_line = 'shifted = roll(trains[i], rng.integers(-bin_steps * 5, bin_s'
    var _spade_detect_line = 'surr_trains.append(shifted)'
    var _spade_detect_line = 'surr_binary = zeros((n_neurons, n_bins), dtype=int8)'
    var _spade_detect_line = 'for i, t in enumerate(surr_trains):'
    var _spade_detect_line = 'for b in range(n_bins):'
    var _spade_detect_line = 'start = b * bin_steps'
    var _spade_detect_line = 'end = min(start + bin_steps, t.size)'
    var _spade_detect_line = 'if t[start:end].any():'
    var _spade_detect_line = 'surr_binary[i, b] = 1'
    var _spade_detect_line = "# Count coincidences for this pattern's neurons with lags"
    var _spade_detect_line = 'neuron_list = pat["neurons"]'
    var _spade_detect_line = 'lags = pat["lags"]'
    var _spade_detect_line = 'coincidence_s: ndarray[Any, Any] = ones(n_bins, dtype=int8)'
    var _spade_detect_line = 'for nid, lag in zip(neuron_list, lags):'
    var _spade_detect_line = 'nbins_n = zeros(n_bins, dtype=int8)'
    var _spade_detect_line = 'for b in range(n_bins):'
    var _spade_detect_line = 'src_b = b - lag'
    var _spade_detect_line = 'if 0 <= src_b < n_bins:'
    var _spade_detect_line = 'nbins_n[b] = surr_binary[nid, src_b]'
    var _spade_detect_line = 'coincidence_s = coincidence_s & nbins_n'
    var _spade_detect_line = 'surr_counts[s] = coincidence_s.sum()'
    var _spade_detect_line = 'p_value = float((surr_counts >= pat["count"]).sum() + 1) / ('
    var _spade_detect_line = 'if p_value <= alpha:'
    var _spade_detect_line = 'results.append('
    var _spade_detect_line = '{'
    var _spade_detect_line = '"neurons": pat["neurons"],'
    var _spade_detect_line = '"lags": pat["lags"],'
    var _spade_detect_line = '"count": pat["count"],'
    var _spade_detect_line = '"p_value": p_value,'
    var _spade_detect_line = '}'
    var _spade_detect_line = ')'
    return 0  # return results

