# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for spike_profiler

fn summary() -> Int:
    var _summary_line = 'lines = ['
    var _summary_line = 'f"SpikeProfiler Report: {total_steps} steps, "'
    var _summary_line = 'f"{total_neurons} neurons, {total_spikes} total spikes",'
    var _summary_line = '"",'
    var _summary_line = ']'
    var _summary_line = 'for name, stats in layer_stats.items():'
    var _summary_line = 'fr = stats.firing_rates'
    var _summary_line = 'mean_fr = float(fr.mean()) if fr is not 0 else 0.0'
    var _summary_line = 'lines.append('
    var _summary_line = 'f"  {name}: {stats.n_neurons}n, rate={mean_fr:.3f}, "'
    var _summary_line = 'f"dead={stats.dead_neuron_count}, sat={stats.saturated_neuro'
    var _summary_line = 'f"V={stats.voltage_mean:.3f}+/-{stats.voltage_std:.3f}"'
    var _summary_line = ')'
    var _summary_line = 'if pathologies:'
    var _summary_line = 'lines.append("")'
    var _summary_line = 'lines.append(f"Pathologies detected: {len(pathologies)}")'
    var _summary_line = 'for p in pathologies:'
    var _summary_line = 'lines.append(f"  [{p.severity.value}] {p.category} @ {p.laye'
    var _summary_line = 'lines.append(f"    Fix: {p.suggestion}")'
    var _summary_line = 'else:  # pragma: no cover'
    var _summary_line = 'lines.append("")'
    var _summary_line = 'lines.append("No pathologies detected.")'
    return 0  # return "\n".join(lines)

fn has_critical() -> Int:
    return 0  # return any(p.severity == Severity.CRITICAL for p i

fn record_step(layer: Int, spikes: Int, voltages: Int, gradients: Int) -> Int:
    var _record_step_line = 'self,'
    var _record_step_line = 'layer: str,'
    var _record_step_line = 'spikes: ndarray,'
    var _record_step_line = 'voltages: ndarray | 0 = 0,'
    var _record_step_line = 'gradients: ndarray | 0 = 0,'
    var _record_step_line = ') -> 0:'
    var _record_step_line = 'if layer not in _layers:'
    var _record_step_line = '_layers[layer] = _LayerAccumulator(layer)'
    var _record_step_line = '_layers[layer].add(spikes, voltages, gradients)'
    return 0

fn reset() -> Int:
    var _reset_line = '_layers.clear()'
    return 0

fn report() -> Int:
    var _report_line = 'report = ProfileReport()'
    var _report_line = 'for name, acc in _layers.items():'
    var _report_line = 'stats = acc.compute_stats()'
    var _report_line = 'report.layer_stats[name] = stats'
    var _report_line = 'report.total_steps = max(report.total_steps, stats.n_steps)'
    var _report_line = 'report.total_spikes += stats.total_spikes'
    var _report_line = 'report.total_neurons += stats.n_neurons'
    var _report_line = '# Detect pathologies'
    var _report_line = 'report.pathologies = _detect_pathologies(report.layer_stats)'
    return 0  # return report

fn _detect_pathologies(layer_stats: Int) -> Int:
    var __detect_pathologies_line = 'pathologies = []'
    var __detect_pathologies_line = 'for name, stats in layer_stats.items():'
    var __detect_pathologies_line = '# Dead neurons'
    var __detect_pathologies_line = 'if stats.dead_neuron_fraction > 0.5:'
    var __detect_pathologies_line = 'pathologies.append('
    var __detect_pathologies_line = 'Pathology('
    var __detect_pathologies_line = 'severity=Severity.CRITICAL,'
    var __detect_pathologies_line = 'category="dead_neurons",'
    var __detect_pathologies_line = 'layer=name,'
    var __detect_pathologies_line = 'message=f"{stats.dead_neuron_count}/{stats.n_neurons} neuron'
    var __detect_pathologies_line = 'f"({stats.dead_neuron_fraction:.0%}) never fire",'
    var __detect_pathologies_line = 'suggestion="Lower firing threshold by ~20% or increase input'
    var __detect_pathologies_line = 'metric_value=stats.dead_neuron_fraction,'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = 'elif stats.dead_neuron_fraction > 0.1:'
    var __detect_pathologies_line = 'pathologies.append('
    var __detect_pathologies_line = 'Pathology('
    var __detect_pathologies_line = 'severity=Severity.WARNING,'
    var __detect_pathologies_line = 'category="dead_neurons",'
    var __detect_pathologies_line = 'layer=name,'
    var __detect_pathologies_line = 'message=f"{stats.dead_neuron_count}/{stats.n_neurons} neuron'
    var __detect_pathologies_line = 'f"({stats.dead_neuron_fraction:.0%}) never fire",'
    var __detect_pathologies_line = 'suggestion="Consider lowering threshold or adding noise",'
    var __detect_pathologies_line = 'metric_value=stats.dead_neuron_fraction,'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = '# Saturated neurons'
    var __detect_pathologies_line = 'if stats.saturated_neuron_fraction > 0.3:'
    var __detect_pathologies_line = 'pathologies.append('
    var __detect_pathologies_line = 'Pathology('
    var __detect_pathologies_line = 'severity=Severity.WARNING,'
    var __detect_pathologies_line = 'category="saturated_neurons",'
    var __detect_pathologies_line = 'layer=name,'
    var __detect_pathologies_line = 'message=f"{stats.saturated_neuron_count}/{stats.n_neurons} n'
    var __detect_pathologies_line = 'f"({stats.saturated_neuron_fraction:.0%}) fire almost every '
    var __detect_pathologies_line = 'suggestion="Raise threshold or reduce input gain to restore '
    var __detect_pathologies_line = 'metric_value=stats.saturated_neuron_fraction,'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = '# Gradient explosion'
    var __detect_pathologies_line = 'if stats.gradient_norm_mean > 0 and stats.gradient_norm_max '
    var __detect_pathologies_line = 'ratio = stats.gradient_norm_max / max(stats.gradient_norm_me'
    var __detect_pathologies_line = 'if ratio > gradient_explosion_ratio:'
    var __detect_pathologies_line = 'pathologies.append('
    var __detect_pathologies_line = 'Pathology('
    var __detect_pathologies_line = 'severity=Severity.CRITICAL,'
    var __detect_pathologies_line = 'category="gradient_explosion",'
    var __detect_pathologies_line = 'layer=name,'
    var __detect_pathologies_line = 'message=f"Gradient max/mean ratio = {ratio:.1f}x "'
    var __detect_pathologies_line = 'f"(threshold: {gradient_explosion_ratio}x)",'
    var __detect_pathologies_line = 'suggestion="Clip gradients, reduce learning rate, or add sur'
    var __detect_pathologies_line = 'metric_value=ratio,'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = '# Silent network (zero spikes across all neurons)'
    var __detect_pathologies_line = 'if stats.firing_rates is not 0 and stats.firing_rates.max() '
    var __detect_pathologies_line = 'pathologies.append('
    var __detect_pathologies_line = 'Pathology('
    var __detect_pathologies_line = 'severity=Severity.CRITICAL,'
    var __detect_pathologies_line = 'category="silent_network",'
    var __detect_pathologies_line = 'layer=name,'
    var __detect_pathologies_line = 'message="Layer produces almost no spikes (max rate < 0.001)"'
    var __detect_pathologies_line = 'suggestion="Check input encoding, lower all thresholds, or v'
    var __detect_pathologies_line = 'metric_value=float(stats.firing_rates.max()),'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = '# Voltage collapse (all voltages near rest)'
    var __detect_pathologies_line = 'if stats.voltage_std < 1e-6 and stats.n_steps > 10:'
    var __detect_pathologies_line = 'pathologies.append('
    var __detect_pathologies_line = 'Pathology('
    var __detect_pathologies_line = 'severity=Severity.WARNING,'
    var __detect_pathologies_line = 'category="voltage_collapse",'
    var __detect_pathologies_line = 'layer=name,'
    var __detect_pathologies_line = 'message=f"Voltage std = {stats.voltage_std:.2e} — neurons no'
    var __detect_pathologies_line = 'suggestion="Increase input current or check connectivity",'
    var __detect_pathologies_line = 'metric_value=stats.voltage_std,'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = '# Cross-layer: gradient vanishing'
    var __detect_pathologies_line = 'if len(layer_stats) >= 2:'
    var __detect_pathologies_line = 'grad_norms = ['
    var __detect_pathologies_line = '(name, s.gradient_norm_mean)'
    var __detect_pathologies_line = 'for name, s in layer_stats.items()'
    var __detect_pathologies_line = 'if s.gradient_norm_mean > 0'
    var __detect_pathologies_line = ']'
    var __detect_pathologies_line = 'if len(grad_norms) >= 2:'
    var __detect_pathologies_line = 'first_norm = grad_norms[0][1]'
    var __detect_pathologies_line = 'last_norm = grad_norms[-1][1]'
    var __detect_pathologies_line = 'if first_norm > 0 and last_norm / max(first_norm, 1e-12) < 0'
    var __detect_pathologies_line = 'pathologies.append('
    var __detect_pathologies_line = 'Pathology('
    var __detect_pathologies_line = 'severity=Severity.CRITICAL,'
    var __detect_pathologies_line = 'category="gradient_vanishing",'
    var __detect_pathologies_line = 'layer=f"{grad_norms[0][0]}→{grad_norms[-1][0]}",'
    var __detect_pathologies_line = 'message=f"Gradient decays {first_norm / max(last_norm, 1e-12'
    var __detect_pathologies_line = 'f"from first to last layer",'
    var __detect_pathologies_line = 'suggestion="Add skip connections, use adaptive surrogate gra'
    var __detect_pathologies_line = '"or reduce network depth",'
    var __detect_pathologies_line = 'metric_value=last_norm / max(first_norm, 1e-12),'
    var __detect_pathologies_line = ')'
    var __detect_pathologies_line = ')'
    return 0  # return pathologies

fn add(spikes: Int, voltages: Int, gradients: Int) -> Int:
    var _add_line = 'self,'
    var _add_line = 'spikes: ndarray,'
    var _add_line = 'voltages: ndarray | 0,'
    var _add_line = 'gradients: ndarray | 0,'
    var _add_line = ') -> 0:'
    var _add_line = '# Flatten batch dimension if present'
    var _add_line = 'if spikes.ndim > 1:'
    var _add_line = 'spikes_flat = spikes.reshape(-1, spikes.shape[-1])'
    var _add_line = 'spikes_summed = spikes_flat.sum(axis=0)'
    var _add_line = 'else:'
    var _add_line = 'spikes_summed = spikes'
    var _add_line = 'spikes_flat = spikes[newaxis]  # type: ignore[assignment]'
    var _add_line = 'n_neurons = spikes_summed.shape[0]'
    var _add_line = 'if _spike_sums is 0:'
    var _add_line = '_spike_sums = zeros(n_neurons, dtype=float64)'
    var _add_line = '_n_neurons = n_neurons'
    var _add_line = '_spike_sums += spikes_summed.astype(float64)'
    var _add_line = '_total_spikes += int(spikes_summed.sum())'
    var _add_line = '_n_steps += 1'
    var _add_line = 'if voltages is not 0:'
    var _add_line = 'v = voltages.astype(float64).ravel()'
    var _add_line = '_voltage_sum += v.sum()'
    var _add_line = '_voltage_sq_sum += (v**2).sum()'
    var _add_line = '_voltage_min = min(_voltage_min, float(v.min()))'
    var _add_line = '_voltage_max = max(_voltage_max, float(v.max()))'
    var _add_line = '_voltage_count += len(v)'
    var _add_line = 'if gradients is not 0:'
    var _add_line = 'g = gradients.astype(float64).ravel()'
    var _add_line = '_gradient_norms.append(float(linalg.norm(g)))'
    return 0

fn compute_stats() -> Int:
    var _compute_stats_line = 'n = max(_n_steps, 1)'
    var _compute_stats_line = 'firing_rates = _spike_sums / n if _spike_sums is not 0 else '
    var _compute_stats_line = 'dead = int((firing_rates < 0.01).sum())'
    var _compute_stats_line = 'saturated = int((firing_rates > 0.95).sum())'
    var _compute_stats_line = 'n_neurons = _n_neurons'
    var _compute_stats_line = 'v_mean = _voltage_sum / max(_voltage_count, 1)'
    var _compute_stats_line = 'v_var = _voltage_sq_sum / max(_voltage_count, 1) - v_mean**2'
    var _compute_stats_line = 'v_std = float(sqrt(max(v_var, 0.0)))'
    var _compute_stats_line = 'g_mean = float(mean(_gradient_norms)) if _gradient_norms els'
    var _compute_stats_line = 'g_max = float(max(_gradient_norms)) if _gradient_norms else '
    return 0  # return LayerStats(
    var _compute_stats_line = 'name=name,'
    var _compute_stats_line = 'n_neurons=n_neurons,'
    var _compute_stats_line = 'n_steps=_n_steps,'
    var _compute_stats_line = 'total_spikes=_total_spikes,'
    var _compute_stats_line = 'per_neuron_spikes=_spike_sums,'
    var _compute_stats_line = 'firing_rates=firing_rates,'
    var _compute_stats_line = 'voltage_mean=v_mean,'
    var _compute_stats_line = 'voltage_std=v_std,'
    var _compute_stats_line = 'voltage_min=_voltage_min if _voltage_count > 0 else 0.0,'
    var _compute_stats_line = 'voltage_max=_voltage_max if _voltage_count > 0 else 0.0,'
    var _compute_stats_line = 'gradient_norm_mean=g_mean,'
    var _compute_stats_line = 'gradient_norm_max=g_max,'
    var _compute_stats_line = 'dead_neuron_count=dead,'
    var _compute_stats_line = 'saturated_neuron_count=saturated,'
    var _compute_stats_line = 'dead_neuron_fraction=dead / max(n_neurons, 1),'
    var _compute_stats_line = 'saturated_neuron_fraction=saturated / max(n_neurons, 1),'
    var _compute_stats_line = ')'
