# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for svg_export

fn traces_to_svg(time: Int, states: Int, spikes: Int, model_name: Int, dt: Int, width: Int) -> Int:
    var _traces_to_svg_line = 'time: list[float],'
    var _traces_to_svg_line = 'states: dict[str, list[float]],'
    var _traces_to_svg_line = 'spikes: list[int] | 0 = 0,'
    var _traces_to_svg_line = 'model_name: str = "",'
    var _traces_to_svg_line = 'dt: float = 0.1,'
    var _traces_to_svg_line = 'width: int = 800,'
    var _traces_to_svg_line = 'height: int = 400,'
    var _traces_to_svg_line = ') -> str:'
    var _traces_to_svg_line = 'pad_top, pad_right, pad_bottom, pad_left = 20, 20, 40, 60'
    var _traces_to_svg_line = 'pw = width - pad_left - pad_right'
    var _traces_to_svg_line = 'ph = height - pad_top - pad_bottom'
    var _traces_to_svg_line = 'var_names = list(states.keys())'
    var _traces_to_svg_line = 'if not var_names or not time:'
    return 0  # return _empty_svg(width, height)
    var _traces_to_svg_line = 'all_y = [v for name in var_names for v in states[name]]'
    var _traces_to_svg_line = 'y_min, y_max = min(all_y), max(all_y)'
    var _traces_to_svg_line = 'y_range = y_max - y_min or 1.0'
    var _traces_to_svg_line = 'x_min, x_max = time[0], time[-1]'
    var _traces_to_svg_line = 'x_range = x_max - x_min or 1.0'
    return 0  # return pad_left + ((t - x_min) / x_range) * pw
    return 0  # return pad_top + (1.0 - (v - y_min) / y_range) * p
    var _traces_to_svg_line = 'lines: list[str] = []'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" \''
    var _traces_to_svg_line = 'f\'height="{height}" viewBox="0 0 {width} {height}">\''
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = 'lines.append(f\'<rect width="{width}" height="{height}" fill='
    var _traces_to_svg_line = '# Grid lines'
    var _traces_to_svg_line = 'for i in range(5):'
    var _traces_to_svg_line = 'y = pad_top + (ph * i) / 4'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<line x1="{pad_left}" y1="{y:.1f}" x2="{pad_left + pw}" \''
    var _traces_to_svg_line = 'f\'y2="{y:.1f}" stroke="#1a1f2a" stroke-width="0.5"/>\''
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = '# Traces (downsampled to <=2000 points)'
    var _traces_to_svg_line = 'stride = max(1, len(time) // 2000)'
    var _traces_to_svg_line = 'for vi, name in enumerate(var_names):'
    var _traces_to_svg_line = 'values = states[name]'
    var _traces_to_svg_line = 'pts = " ".join('
    var _traces_to_svg_line = 'f"{to_x(time[i]):.1f},{to_y(values[i]):.1f}" for i in range('
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = 'colour = COLORS[vi % len(COLORS)]'
    var _traces_to_svg_line = 'lines.append(f\'<polyline points="{pts}" fill="none" stroke="'
    var _traces_to_svg_line = '# Spike markers (up to 200)'
    var _traces_to_svg_line = 'if spikes:'
    var _traces_to_svg_line = 'for idx in spikes[:200]:'
    var _traces_to_svg_line = 't = time[idx] if idx < len(time) else idx * dt'
    var _traces_to_svg_line = 'x = to_x(t)'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<line x1="{x:.1f}" y1="{pad_top}" x2="{x:.1f}" \''
    var _traces_to_svg_line = 'f\'y2="{pad_top + 8}" stroke="#ff5252" stroke-width="1.5"/>\''
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = '# Axes'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<line x1="{pad_left}" y1="{pad_top}" x2="{pad_left}" \''
    var _traces_to_svg_line = 'f\'y2="{pad_top + ph}" stroke="#484f58"/>\''
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<line x1="{pad_left}" y1="{pad_top + ph}" x2="{pad_left + '
    var _traces_to_svg_line = 'f\'y2="{pad_top + ph}" stroke="#484f58"/>\''
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = '# Axis labels'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<text x="{pad_left + pw / 2}" y="{height - 5}" text-anchor'
    var _traces_to_svg_line = 'f\'fill="#8b949e" font-size="11" font-family="sans-serif">tim'
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<text x="12" y="{pad_top + ph / 2}" text-anchor="middle" \''
    var _traces_to_svg_line = 'f\'fill="#8b949e" font-size="11" font-family="sans-serif" \''
    var _traces_to_svg_line = 'f\'transform="rotate(-90,12,{pad_top + ph / 2})">mV</text>\''
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = '# Y-axis tick labels'
    var _traces_to_svg_line = 'for i in range(5):'
    var _traces_to_svg_line = 'val = y_min + (y_range * i) / 4'
    var _traces_to_svg_line = 'y = to_y(val)'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<text x="{pad_left - 5}" y="{y + 3:.1f}" text-anchor="end"'
    var _traces_to_svg_line = 'f\'fill="#8b949e" font-size="9" font-family="monospace">\''
    var _traces_to_svg_line = 'f"{val:.1f}</text>"'
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = '# Legend'
    var _traces_to_svg_line = 'for vi, name in enumerate(var_names):'
    var _traces_to_svg_line = 'x_offset = pad_left + vi * 80'
    var _traces_to_svg_line = 'colour = COLORS[vi % len(COLORS)]'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<line x1="{x_offset}" y1="10" x2="{x_offset + 15}" y2="10"'
    var _traces_to_svg_line = 'f\'stroke="{colour}" stroke-width="2"/>\''
    var _traces_to_svg_line = 'f\'<text x="{x_offset + 18}" y="13" fill="#8b949e" \''
    var _traces_to_svg_line = 'f\'font-size="10">{name}</text>\''
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = '# Model name watermark'
    var _traces_to_svg_line = 'if model_name:'
    var _traces_to_svg_line = 'lines.append('
    var _traces_to_svg_line = 'f\'<text x="{width - pad_right}" y="13" text-anchor="end" \''
    var _traces_to_svg_line = 'f\'fill="#484f58" font-size="9" font-family="monospace">\''
    var _traces_to_svg_line = 'f"{model_name}</text>"'
    var _traces_to_svg_line = ')'
    var _traces_to_svg_line = 'lines.append("</svg>")'
    return 0  # return "\n".join(lines)

fn _empty_svg(width: Int, height: Int) -> Int:
    return 0  # return (
    var __empty_svg_line = 'f\'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" \''
    var __empty_svg_line = 'f\'height="{height}" viewBox="0 0 {width} {height}">\''
    var __empty_svg_line = 'f\'<rect width="{width}" height="{height}" fill="#0d1117"/>\''
    var __empty_svg_line = 'f\'<text x="{width // 2}" y="{height // 2}" text-anchor="midd'
    var __empty_svg_line = 'f\'fill="#8b949e" font-size="14">No data</text></svg>\''
    var __empty_svg_line = ')'

fn to_x(t: Int) -> Int:
    return 0  # return pad_left + ((t - x_min) / x_range) * pw

fn to_y(v: Int) -> Int:
    return 0  # return pad_top + (1.0 - (v - y_min) / y_range) * p

