# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Mojo SIMD acceleration for temporal_properties

fn fires_within(spikes: Int, neuron_id: Int, stimulus_times: Int, max_latency: Int) -> Int:
    var _fires_within_line = 'spikes: ndarray,'
    var _fires_within_line = 'neuron_id: int,'
    var _fires_within_line = 'stimulus_times: list[int],'
    var _fires_within_line = 'max_latency: int,'
    var _fires_within_line = ') -> VerificationResult:'
    var _fires_within_line = 'T = spikes.shape[0]'
    var _fires_within_line = 'for t_stim in stimulus_times:'
    var _fires_within_line = 'window_end = min(t_stim + max_latency, T)'
    var _fires_within_line = 'fired = False'
    var _fires_within_line = 'for t in range(t_stim, window_end):'
    var _fires_within_line = 'if spikes[t, neuron_id] > 0:'
    var _fires_within_line = 'fired = True'
    var _fires_within_line = 'break'
    var _fires_within_line = 'if not fired:'
    return 0  # return VerificationResult(
    var _fires_within_line = 'property_name="fires_within",'
    var _fires_within_line = 'result=PropertyResult.VIOLATED,'
    var _fires_within_line = 'counterexample=Counterexample('
    var _fires_within_line = 'timestep=t_stim,'
    var _fires_within_line = 'neuron_ids=[neuron_id],'
    var _fires_within_line = 'description=f"Neuron {neuron_id} did not fire within {max_la'
    var _fires_within_line = 'f"steps of stimulus at t={t_stim}",'
    var _fires_within_line = '),'
    var _fires_within_line = 'checked_steps=T,'
    var _fires_within_line = 'message=f"Neuron {neuron_id} failed to respond at t={t_stim}'
    var _fires_within_line = ')'
    return 0  # return VerificationResult(
    var _fires_within_line = 'property_name="fires_within",'
    var _fires_within_line = 'result=PropertyResult.VERIFIED,'
    var _fires_within_line = 'checked_steps=T,'
    var _fires_within_line = 'message=f"Neuron {neuron_id} responds within {max_latency} s'
    var _fires_within_line = 'f"{len(stimulus_times)} stimuli",'
    var _fires_within_line = ')'

fn mutual_exclusion(spikes: Int, neuron_set: Int) -> Int:
    var _mutual_exclusion_line = 'spikes: ndarray,'
    var _mutual_exclusion_line = 'neuron_set: list[int],'
    var _mutual_exclusion_line = ') -> VerificationResult:'
    var _mutual_exclusion_line = 'T = spikes.shape[0]'
    var _mutual_exclusion_line = 'for t in range(T):'
    var _mutual_exclusion_line = 'active = [n for n in neuron_set if spikes[t, n] > 0]'
    var _mutual_exclusion_line = 'if len(active) > 1:'
    return 0  # return VerificationResult(
    var _mutual_exclusion_line = 'property_name="mutual_exclusion",'
    var _mutual_exclusion_line = 'result=PropertyResult.VIOLATED,'
    var _mutual_exclusion_line = 'counterexample=Counterexample('
    var _mutual_exclusion_line = 'timestep=t,'
    var _mutual_exclusion_line = 'neuron_ids=active,'
    var _mutual_exclusion_line = 'description=f"Neurons {active} fire simultaneously at t={t}"'
    var _mutual_exclusion_line = '),'
    var _mutual_exclusion_line = 'checked_steps=T,'
    var _mutual_exclusion_line = 'message=f"Mutual exclusion violated at t={t}",'
    var _mutual_exclusion_line = ')'
    return 0  # return VerificationResult(
    var _mutual_exclusion_line = 'property_name="mutual_exclusion",'
    var _mutual_exclusion_line = 'result=PropertyResult.VERIFIED,'
    var _mutual_exclusion_line = 'checked_steps=T,'
    var _mutual_exclusion_line = 'message=f"No simultaneous firing among {len(neuron_set)} neu'
    var _mutual_exclusion_line = ')'

fn rate_bound(spikes: Int, neuron_id: Int, max_rate: Int, window_size: Int) -> Int:
    var _rate_bound_line = 'spikes: ndarray,'
    var _rate_bound_line = 'neuron_id: int,'
    var _rate_bound_line = 'max_rate: float,'
    var _rate_bound_line = 'window_size: int,'
    var _rate_bound_line = ') -> VerificationResult:'
    var _rate_bound_line = 'T = spikes.shape[0]'
    var _rate_bound_line = 'neuron_spikes = spikes[:, neuron_id]'
    var _rate_bound_line = 'for t in range(T - window_size + 1):'
    var _rate_bound_line = 'window = neuron_spikes[t : t + window_size]'
    var _rate_bound_line = 'rate = float(window.sum()) / window_size'
    var _rate_bound_line = 'if rate > max_rate:'
    return 0  # return VerificationResult(
    var _rate_bound_line = 'property_name="rate_bound",'
    var _rate_bound_line = 'result=PropertyResult.VIOLATED,'
    var _rate_bound_line = 'counterexample=Counterexample('
    var _rate_bound_line = 'timestep=t,'
    var _rate_bound_line = 'neuron_ids=[neuron_id],'
    var _rate_bound_line = 'description=f"Rate {rate:.3f} > {max_rate:.3f} in window [{t'
    var _rate_bound_line = '),'
    var _rate_bound_line = 'checked_steps=T,'
    var _rate_bound_line = 'message=f"Rate bound violated at t={t}: {rate:.3f} > {max_ra'
    var _rate_bound_line = ')'
    return 0  # return VerificationResult(
    var _rate_bound_line = 'property_name="rate_bound",'
    var _rate_bound_line = 'result=PropertyResult.VERIFIED,'
    var _rate_bound_line = 'checked_steps=T,'
    var _rate_bound_line = 'message=f"Neuron {neuron_id} rate stays below {max_rate} in '
    var _rate_bound_line = ')'

fn refractory_guarantee(spikes: Int, neuron_id: Int, min_gap: Int) -> Int:
    var _refractory_guarantee_line = 'spikes: ndarray,'
    var _refractory_guarantee_line = 'neuron_id: int,'
    var _refractory_guarantee_line = 'min_gap: int,'
    var _refractory_guarantee_line = ') -> VerificationResult:'
    var _refractory_guarantee_line = 'T = spikes.shape[0]'
    var _refractory_guarantee_line = 'spike_times = where(spikes[:, neuron_id] > 0)[0]'
    var _refractory_guarantee_line = 'for i in range(len(spike_times) - 1):'
    var _refractory_guarantee_line = 'gap = spike_times[i + 1] - spike_times[i]'
    var _refractory_guarantee_line = 'if gap < min_gap:'
    return 0  # return VerificationResult(
    var _refractory_guarantee_line = 'property_name="refractory_guarantee",'
    var _refractory_guarantee_line = 'result=PropertyResult.VIOLATED,'
    var _refractory_guarantee_line = 'counterexample=Counterexample('
    var _refractory_guarantee_line = 'timestep=int(spike_times[i]),'
    var _refractory_guarantee_line = 'neuron_ids=[neuron_id],'
    var _refractory_guarantee_line = 'description=f"ISI = {gap} < {min_gap} between t={spike_times'
    var _refractory_guarantee_line = '),'
    var _refractory_guarantee_line = 'checked_steps=T,'
    var _refractory_guarantee_line = 'message=f"Refractory violated: ISI={gap} at t={spike_times[i'
    var _refractory_guarantee_line = ')'
    return 0  # return VerificationResult(
    var _refractory_guarantee_line = 'property_name="refractory_guarantee",'
    var _refractory_guarantee_line = 'result=PropertyResult.VERIFIED,'
    var _refractory_guarantee_line = 'checked_steps=T,'
    var _refractory_guarantee_line = 'message=f"All ISIs >= {min_gap} for neuron {neuron_id} ({len'
    var _refractory_guarantee_line = ')'

fn causal_order(spikes: Int, neuron_a: Int, neuron_b: Int, max_delay: Int) -> Int:
    var _causal_order_line = 'spikes: ndarray,'
    var _causal_order_line = 'neuron_a: int,'
    var _causal_order_line = 'neuron_b: int,'
    var _causal_order_line = 'max_delay: int,'
    var _causal_order_line = ') -> VerificationResult:'
    var _causal_order_line = 'T = spikes.shape[0]'
    var _causal_order_line = 'b_times = where(spikes[:, neuron_b] > 0)[0]'
    var _causal_order_line = 'a_times = set(where(spikes[:, neuron_a] > 0)[0].tolist())'
    var _causal_order_line = 'for t_b in b_times:'
    var _causal_order_line = 'found = False'
    var _causal_order_line = 'for dt in range(1, max_delay + 1):'
    var _causal_order_line = 'if (t_b - dt) in a_times:'
    var _causal_order_line = 'found = True'
    var _causal_order_line = 'break'
    var _causal_order_line = 'if not found:'
    return 0  # return VerificationResult(
    var _causal_order_line = 'property_name="causal_order",'
    var _causal_order_line = 'result=PropertyResult.VIOLATED,'
    var _causal_order_line = 'counterexample=Counterexample('
    var _causal_order_line = 'timestep=int(t_b),'
    var _causal_order_line = 'neuron_ids=[neuron_a, neuron_b],'
    var _causal_order_line = 'description=f"Neuron {neuron_b} fired at t={t_b} without neu'
    var _causal_order_line = 'f"firing in [{t_b - max_delay}, {t_b})",'
    var _causal_order_line = '),'
    var _causal_order_line = 'checked_steps=T,'
    var _causal_order_line = 'message=f"Causal order violated at t={t_b}",'
    var _causal_order_line = ')'
    return 0  # return VerificationResult(
    var _causal_order_line = 'property_name="causal_order",'
    var _causal_order_line = 'result=PropertyResult.VERIFIED,'
    var _causal_order_line = 'checked_steps=T,'
    var _causal_order_line = 'message=f"Neuron {neuron_a} precedes neuron {neuron_b} withi'
    var _causal_order_line = 'f"for all {len(b_times)} B-spikes",'
    var _causal_order_line = ')'

fn bounded_activity(spikes: Int, neuron_set: Int, window_size: Int, max_total_spikes: Int) -> Int:
    var _bounded_activity_line = 'spikes: ndarray,'
    var _bounded_activity_line = 'neuron_set: list[int],'
    var _bounded_activity_line = 'window_size: int,'
    var _bounded_activity_line = 'max_total_spikes: int,'
    var _bounded_activity_line = ') -> VerificationResult:'
    var _bounded_activity_line = 'T = spikes.shape[0]'
    var _bounded_activity_line = 'subset = spikes[:, neuron_set]'
    var _bounded_activity_line = 'for t in range(T - window_size + 1):'
    var _bounded_activity_line = 'total = int(subset[t : t + window_size].sum())'
    var _bounded_activity_line = 'if total > max_total_spikes:'
    return 0  # return VerificationResult(
    var _bounded_activity_line = 'property_name="bounded_activity",'
    var _bounded_activity_line = 'result=PropertyResult.VIOLATED,'
    var _bounded_activity_line = 'counterexample=Counterexample('
    var _bounded_activity_line = 'timestep=t,'
    var _bounded_activity_line = 'neuron_ids=neuron_set,'
    var _bounded_activity_line = 'description=f"Total spikes = {total} > {max_total_spikes} in'
    var _bounded_activity_line = 'f"window [{t}, {t + window_size})",'
    var _bounded_activity_line = '),'
    var _bounded_activity_line = 'checked_steps=T,'
    var _bounded_activity_line = 'message=f"Activity bound violated at t={t}: {total} > {max_t'
    var _bounded_activity_line = ')'
    return 0  # return VerificationResult(
    var _bounded_activity_line = 'property_name="bounded_activity",'
    var _bounded_activity_line = 'result=PropertyResult.VERIFIED,'
    var _bounded_activity_line = 'checked_steps=T,'
    var _bounded_activity_line = 'message=f"Activity stays below {max_total_spikes} in all {wi'
    var _bounded_activity_line = ')'

fn summary() -> Int:
    var _summary_line = 'icon = {"verified": "PASS", "violated": "FAIL", "unknown": "'
    var _summary_line = 'line = f"[{icon}] {property_name}: {message}"'
    var _summary_line = 'if counterexample:'
    var _summary_line = 'line += f"\\n  Counterexample at t={counterexample.timestep}:'
    return 0  # return line
