# SPDX-License-Identifier: AGPL-3.0-or-later | Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li

"""
MNIST-on-FPGA Demo
==================

End-to-end: train a digit classifier in Python, quantize to Q8.8,
simulate with stochastic bitstreams (matching RTL), and export
Verilog weight parameters for synthesis.

Uses sklearn's built-in 8×8 digits dataset (no download required).
PCA reduces 64 features -> 16 for FPGA-friendly resource usage.

Usage::

    python examples/mnist_fpga/demo.py
    python examples/mnist_fpga/demo.py --n-features 32 --stream-length 2048
    python examples/mnist_fpga/demo.py --export-verilog hdl/generated/mnist_weights.vh
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

# -- Q8.8 fixed-point helpers ------------------------------------------------

Q88_FRAC = 8
Q88_SCALE = 1 << Q88_FRAC  # 256


def float_to_q88(x: np.ndarray) -> np.ndarray:
    """Convert float array to Q8.8 signed 16-bit integers."""
    return np.clip(np.round(x * Q88_SCALE), -32768, 32767).astype(np.int16)


def q88_to_float(x: np.ndarray) -> np.ndarray:
    return x.astype(np.float64) / Q88_SCALE


# -- LFSR-based stochastic encoder (matches hdl/sc_bitstream_encoder.v) ------

LFSR_POLY = 0xB400  # x^16 + x^14 + x^13 + x^11 + 1 (maximal-length)


def lfsr_step(state: int) -> int:
    """One step of 16-bit LFSR (Galois form)."""
    feedback = state & 1
    state >>= 1
    if feedback:
        state ^= LFSR_POLY
    return state & 0xFFFF


def lfsr_bitstream(x_enc16: int, length: int, seed: int) -> np.ndarray:
    """Generate Bernoulli bitstream matching RTL sc_bitstream_encoder.

    x_enc16: 16-bit value in [0, 65535]. P(bit=1) = x_enc16 / 65536.
    """
    bits = np.zeros(length, dtype=np.uint8)
    state = seed & 0xFFFF
    if state == 0:
        state = 0xACE1
    x_abs = abs(x_enc16) & 0xFFFF
    for t in range(length):
        state = lfsr_step(state)
        bits[t] = 1 if state < x_abs else 0
    return bits


def _prob_to_enc16(p: float) -> int:
    """Convert probability [0,1] to 16-bit encoder threshold."""
    return int(np.clip(round(p * 65535), 0, 65535))


# -- Stochastic computing inference (matches RTL dense matrix layer) ---------


def sc_inference(
    x_probs: np.ndarray,
    w_float: np.ndarray,
    stream_len: int = 1024,
) -> np.ndarray:
    """Stochastic computing forward pass with sign-magnitude encoding.

    x_probs: input probabilities in [0,1] (after MinMaxScaler)
    w_float: weight matrix (n_classes, n_inputs), can be signed
    Returns per-class signed accumulator values (higher = more confident).

    AND gates compute unipolar magnitude product. Weight sign tracked separately.
    """
    n_classes, n_inputs = w_float.shape
    w_max = np.abs(w_float).max()
    if w_max == 0:
        return np.zeros(n_classes)
    w_norm = w_float / w_max  # normalise magnitudes to [0,1]

    accum = np.zeros(n_classes)

    # Generate input bitstreams (shared across all neurons)
    input_streams = np.zeros((n_inputs, stream_len), dtype=np.uint8)
    for i in range(n_inputs):
        seed = (0xACE1 + i * 7) & 0xFFFF
        enc = _prob_to_enc16(float(x_probs[i]))
        input_streams[i] = lfsr_bitstream(enc, stream_len, seed)

    for j in range(n_classes):
        exc_sum = 0.0
        inh_sum = 0.0
        for i in range(n_inputs):
            seed = (0xBEEF + j * 13 * n_inputs + i * 13) & 0xFFFF
            w_mag = abs(w_norm[j, i])
            w_enc = _prob_to_enc16(float(w_mag))
            w_stream = lfsr_bitstream(w_enc, stream_len, seed)
            popcount = int((input_streams[i] & w_stream).sum())
            if w_float[j, i] >= 0:
                exc_sum += popcount
            else:
                inh_sum += popcount
        accum[j] = exc_sum - inh_sum

    return accum


# -- Verilog weight export ---------------------------------------------------


def export_verilog_weights(weight_q88: np.ndarray, path: Path, n_features: int) -> None:
    """Generate Verilog include file with weight constants."""
    n_classes, n_inputs = weight_q88.shape
    lines = [
        "// Generated by examples/mnist_fpga/demo.py — do not edit",
        f"// {n_classes} classes × {n_inputs} inputs, Q8.8 fixed-point",
        "",
    ]
    for j in range(n_classes):
        for i in range(n_inputs):
            val = int(weight_q88[j, i]) & 0xFFFF
            lines.append(f"localparam signed [15:0] W_{j}_{i} = 16'h{val:04X};")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"  Verilog weights -> {path} ({len(lines)} lines)")


# -- Main demo ---------------------------------------------------------------


def main() -> int:
    ap = argparse.ArgumentParser(description="MNIST-on-FPGA stochastic computing demo")
    ap.add_argument("--n-features", type=int, default=16, help="PCA dimensions (default: 16)")
    ap.add_argument(
        "--stream-length", type=int, default=1024, help="bitstream length (default: 1024)"
    )
    ap.add_argument(
        "--n-test", type=int, default=100, help="test samples for SC inference (default: 100)"
    )
    ap.add_argument("--export-verilog", type=str, help="export weight .vh file")
    ap.add_argument("--json", type=str, help="write results to JSON")
    args = ap.parse_args()

    from sklearn.datasets import load_digits
    from sklearn.decomposition import PCA
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import MinMaxScaler

    print("=== SC-NeuroCore: MNIST-on-FPGA Demo ===\n")

    # 1. Load & preprocess
    X, y = load_digits(return_X_y=True)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    pca = PCA(n_components=args.n_features, random_state=42)
    X_train_pca = pca.fit_transform(X_train)
    X_test_pca = pca.transform(X_test)

    scaler = MinMaxScaler(feature_range=(0.05, 0.95))
    X_train_scaled = scaler.fit_transform(X_train_pca)
    X_test_scaled = scaler.transform(X_test_pca)

    print(f"  Dataset: sklearn digits (8×8), {len(X_train)} train / {len(X_test)} test")
    print(f"  PCA: 64 -> {args.n_features} features")
    print(f"  PCA variance retained: {pca.explained_variance_ratio_.sum():.1%}")

    # 2. Train classifier
    clf = LogisticRegression(max_iter=2000, random_state=42)
    clf.fit(X_train_scaled, y_train)
    acc_float = clf.score(X_test_scaled, y_test)
    print(f"\n  Float accuracy:     {acc_float:.1%}")

    # 3. Quantize to Q8.8
    W_float = clf.coef_  # (10, n_features)
    b_float = clf.intercept_  # (10,)
    W_q88 = float_to_q88(W_float)
    b_q88 = float_to_q88(b_float)
    W_dequant = q88_to_float(W_q88)
    b_dequant = q88_to_float(b_q88)

    # Quantized inference (matrix multiply + bias, both quantized)
    scores_q = X_test_scaled @ W_dequant.T + b_dequant
    preds_q = scores_q.argmax(axis=1)
    acc_q88 = (preds_q == y_test).mean()
    print(f"  Q8.8 accuracy:      {acc_q88:.1%}")

    max_q_error = np.abs(W_float - W_dequant).max()
    print(f"  Max quantization error: {max_q_error:.4f}")

    # 4. Stochastic computing inference
    # SC accumulators scale as L/w_max; bias must match
    print(f"\n  Running SC inference ({args.n_test} samples, L={args.stream_length})...")
    w_max = np.abs(W_float).max()
    bias_scaled = b_float * (args.stream_length / w_max)
    correct = 0
    t0 = time.perf_counter()
    for idx in range(min(args.n_test, len(X_test))):
        counts = sc_inference(X_test_scaled[idx], W_float, args.stream_length)
        counts += bias_scaled
        if counts.argmax() == y_test[idx]:
            correct += 1
    elapsed = time.perf_counter() - t0
    acc_sc = correct / min(args.n_test, len(X_test))
    print(f"  SC accuracy:        {acc_sc:.1%} ({elapsed:.1f}s)")

    # 5. Resource estimate
    # Scale from Yosys reference: sc_neurocore_top (3-in, 7-neuron) = 7,382 LUTs
    ref_synapses = 3 * 7  # 21 synapses in reference design
    ref_luts = 7_382
    n_syn = 10 * args.n_features
    lut_per_syn = ref_luts / ref_synapses  # ~351 LUTs per synapse-equivalent
    lut_est = int(n_syn * lut_per_syn)
    ff_est = int(lut_est * 2442 / 7382)  # scale FFs proportionally
    print("\n  === Resource Estimate (Xilinx 7-series) ===")
    print(f"  Synapses:        {n_syn} ({args.n_features} inputs x 10 neurons)")
    print(f"  Est. LUTs:       ~{lut_est:,}  (scaled from Yosys 3x7 = 7,382)")
    print(f"  Est. FFs:        ~{ff_est:,}")

    artix35t = 20_800
    artix100t = 63_400
    zynq7020 = 53_200
    print(f"  Fits Artix-7 35T:  {'YES' if lut_est < artix35t else 'NO'} ({artix35t:,} LUTs)")
    print(f"  Fits Artix-7 100T: {'YES' if lut_est < artix100t else 'NO'} ({artix100t:,} LUTs)")
    print(f"  Fits Zynq 7020:    {'YES' if lut_est < zynq7020 else 'NO'} ({zynq7020:,} LUTs)")

    # 6. Export
    if args.export_verilog:
        export_verilog_weights(W_q88, Path(args.export_verilog), args.n_features)

    results = {
        "n_features": args.n_features,
        "stream_length": args.stream_length,
        "n_test": min(args.n_test, len(X_test)),
        "pca_variance_retained": round(float(pca.explained_variance_ratio_.sum()), 4),
        "accuracy_float": round(float(acc_float), 4),
        "accuracy_q88": round(float(acc_q88), 4),
        "accuracy_sc": round(float(acc_sc), 4),
        "max_quantization_error": round(float(max_q_error), 6),
        "sc_inference_time_s": round(elapsed, 2),
        "resource_estimate": {
            "input_encoders": args.n_features,
            "weight_encoders": 10 * args.n_features,
            "synapses": n_syn,
            "neurons": 10,
            "est_luts": lut_est,
            "est_ffs": ff_est,
        },
    }

    if args.json:
        Path(args.json).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json).write_text(json.dumps(results, indent=2) + "\n")
        print(f"\n  Results -> {args.json}")

    print("\n  Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
