# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Adaptive runtime compiler implementation

"""Generate dual-datapath adaptive-precision Verilog."""

from __future__ import annotations

import json

from ..hdl_gen._ident import sanitize_ident
from ..neurons.equation_builder import EquationNeuron
from .equation_compiler import Q88, compile_to_verilog
from .validation import (
    _coerce_precision,
    _validate_lp_hp,
    _validate_hysteresis,
)


def compile_adaptive_precision(
    neuron: EquationNeuron,
    module_name: str = "sc_adaptive_neuron",
    lp_width: int = 16,
    lp_frac: int = 8,
    hp_width: int = 32,
    hp_frac: int = 16,
    *,
    lp_precision: str | None = None,
    hp_precision: str | None = None,
    lp_parameter_count: int | None = None,
    hp_parameter_count: int | None = None,
    threshold_up_pct: float = 0.8,
    threshold_down_pct: float = 0.5,
    signed: bool = True,
    overflow: str = "saturate",
    rounding: str = "truncate",
) -> str:
    """Compile an EquationNeuron to dual-datapath adaptive-precision Verilog."""
    lp_width, lp_frac, lp_q_label, lp_metadata, lp_precision_obj = _coerce_precision(
        lp_precision,
        default_width=lp_width,
        default_frac=lp_frac,
        tag="lp",
        parameter_count=lp_parameter_count,
    )
    hp_width, hp_frac, hp_q_label, hp_metadata, hp_precision_obj = _coerce_precision(
        hp_precision,
        default_width=hp_width,
        default_frac=hp_frac,
        tag="hp",
        parameter_count=hp_parameter_count,
    )

    _validate_lp_hp(lp_width, lp_frac, hp_width, hp_frac)

    lp_module = f"{module_name}_lp"
    hp_module = f"{module_name}_hp"

    lp_verilog = compile_to_verilog(
        neuron,
        module_name=lp_module,
        data_width=lp_width,
        fraction=lp_frac,
        signed=signed,
        overflow=overflow,
        rounding=rounding,
    )

    hp_verilog = compile_to_verilog(
        neuron,
        module_name=hp_module,
        data_width=hp_width,
        fraction=hp_frac,
        signed=signed,
        overflow=overflow,
        rounding=rounding,
    )

    q_lp = Q88(data_width=lp_width, fraction=lp_frac, signed=signed)
    max_q = int(q_lp.max_value * (1 << lp_frac))
    _validate_hysteresis(
        threshold_up_pct=threshold_up_pct,
        threshold_down_pct=threshold_down_pct,
        max_lp_code=max_q,
    )
    thresh_up = int(threshold_up_pct * max_q)
    thresh_down = int(threshold_down_pct * max_q)

    safe_name = sanitize_ident(module_name, context="module name")
    state_vars = list(neuron.equations.keys())
    primary_var = state_vars[0]
    safe_primary = sanitize_ident(primary_var, context="state variable")

    lines: list[str] = []

    lines.append("// " + "=" * 63)
    lines.append(f"// Low-Precision Datapath ({lp_q_label}, {lp_width}-bit)")
    lines.append("// " + "=" * 63)
    lines.append("")
    lines.append(lp_verilog)
    lines.append("")
    lines.append("// " + "=" * 63)
    lines.append(f"// High-Precision Datapath ({hp_q_label}, {hp_width}-bit)")
    lines.append("// " + "=" * 63)
    lines.append("")
    lines.append(hp_verilog)
    lines.append("")

    lines.append("// " + "=" * 63)
    lines.append("// Adaptive Precision Wrapper — HP-authoritative telemetry")
    lines.append("// " + "=" * 63)
    lines.append("")
    lines.append("// Auto-generated by SC-NeuroCore adaptive precision compiler")
    lines.append(f"// LP: {lp_q_label} ({lp_width}-bit), HP: {hp_q_label} ({hp_width}-bit)")
    lines.append(
        f"// Hysteresis: switch-up at {threshold_up_pct * 100:.0f}% "
        f"of LP range, switch-down at {threshold_down_pct * 100:.0f}%"
    )
    lines.append(
        "// Meta: "
        f"lp_precision={lp_precision_obj.__class__.__name__}, "
        f"hp_precision={hp_precision_obj.__class__.__name__}"
    )
    lines.append(
        "// SC-NeuroCore Adaptive Precision Manifest: "
        + json.dumps(
            {
                "schema_version": "1.0",
                "kind": "adaptive_precision_v1",
                "emitter_contract_version": "adaptive_precision_emitter.v1",
                "module_name": safe_name,
                "primary_variable": primary_var,
                "threshold_up_pct": threshold_up_pct,
                "threshold_down_pct": threshold_down_pct,
                "signed": signed,
                "overflow": overflow,
                "rounding": rounding,
                "lp_precision": lp_metadata,
                "hp_precision": hp_metadata,
            },
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    lines.append("`timescale 1ns / 1ps")
    lines.append("")
    lines.append(f"module {safe_name} (")
    lines.append("    input wire clk,")
    lines.append("    input wire rst_n,")
    lines.append(f"    input wire signed [{hp_width - 1}:0] I_t,")
    lines.append("    output reg spike_out,")

    for var in state_vars:
        safe_var = sanitize_ident(var, context="state variable")
        lines.append(f"    output reg signed [{hp_width - 1}:0] {safe_var}_out,")

    lines.append("    output wire use_hp")
    lines.append(");")
    lines.append("")

    lines.append("// LP datapath signals")
    lines.append(f"wire signed [{lp_width - 1}:0] lp_I_t = I_t[{lp_width - 1}:0];")
    lines.append("wire lp_spike;")
    for var in state_vars:
        safe_var = sanitize_ident(var, context="state variable")
        lines.append(f"wire signed [{lp_width - 1}:0] lp_{safe_var}_out;")
    lines.append("")

    lines.append("// HP datapath signals")
    lines.append(f"wire signed [{hp_width - 1}:0] hp_I_t = I_t;")
    lines.append("wire hp_spike;")
    for var in state_vars:
        safe_var = sanitize_ident(var, context="state variable")
        lines.append(f"wire signed [{hp_width - 1}:0] hp_{safe_var}_out;")
    lines.append("")

    lines.append("// Hysteresis precision telemetry")
    lines.append(
        f"// use_hp asserts when |{primary_var}| exceeds {threshold_up_pct * 100:.0f}% of LP range"
    )
    lines.append(
        f"// use_hp clears when |{primary_var}| falls below "
        f"{threshold_down_pct * 100:.0f}% of LP range"
    )
    lines.append(f"localparam signed [{lp_width - 1}:0] THRESH_UP = {lp_width}'sd{thresh_up};")
    lines.append(f"localparam signed [{lp_width - 1}:0] THRESH_DOWN = {lp_width}'sd{thresh_down};")
    lines.append("")
    lines.append("reg precision_mode;  // telemetry only; HP remains authoritative")
    lines.append("assign use_hp = precision_mode;")
    lines.append("")

    lines.append("always @(posedge clk or negedge rst_n) begin")
    lines.append("    if (!rst_n) begin")
    lines.append("        precision_mode <= 1'b0;")
    lines.append("    end else begin")
    lines.append(
        f"        if (!precision_mode && "
        f"($signed(lp_{safe_primary}_out) > THRESH_UP || "
        f"$signed(lp_{safe_primary}_out) < (-THRESH_UP))) begin"
    )
    lines.append("            precision_mode <= 1'b1;")
    lines.append("        end")
    lines.append(
        f"        else if (precision_mode && "
        f"($signed(lp_{safe_primary}_out) < THRESH_DOWN && "
        f"$signed(lp_{safe_primary}_out) > (-THRESH_DOWN))) begin"
    )
    lines.append("            precision_mode <= 1'b0;")
    lines.append("        end")
    lines.append("    end")
    lines.append("end")
    lines.append("")

    lp_safe = sanitize_ident(lp_module, context="module name")
    lines.append(f"// LP datapath instantiation ({lp_q_label})")
    lines.append(f"{lp_safe} lp_inst (")
    lines.append("    .clk(clk),")
    lines.append("    .rst_n(rst_n),")
    lines.append("    .I_t(lp_I_t),")
    lines.append("    .spike_out(lp_spike),")
    for var in state_vars:
        safe_var = sanitize_ident(var, context="state variable")
        lines.append(f"    .{safe_var}_out(lp_{safe_var}_out),")
    lines[-1] = lines[-1].rstrip(",")
    lines.append(");")
    lines.append("")

    hp_safe = sanitize_ident(hp_module, context="module name")
    lines.append(f"// HP datapath instantiation ({hp_q_label}, authoritative)")
    lines.append(f"{hp_safe} hp_inst (")
    lines.append("    .clk(clk),")
    lines.append("    .rst_n(rst_n),")
    lines.append("    .I_t(hp_I_t),")
    lines.append("    .spike_out(hp_spike),")
    for var in state_vars:
        safe_var = sanitize_ident(var, context="state variable")
        lines.append(f"    .{safe_var}_out(hp_{safe_var}_out),")
    lines[-1] = lines[-1].rstrip(",")
    lines.append(");")
    lines.append("")

    lines.append("// Output register — HP datapath is authoritative")
    lines.append("always @(posedge clk or negedge rst_n) begin")
    lines.append("    if (!rst_n) begin")
    lines.append("        spike_out <= 1'b0;")

    for var in state_vars:
        safe_var = sanitize_ident(var, context="state variable")
        init_val = int(round(neuron.initial_state.get(var, 0.0) * (1 << hp_frac)))
        lines.append(f"        {safe_var}_out <= {hp_width}'sd{init_val};")

    lines.append("    end else begin")
    lines.append("        spike_out <= hp_spike;")
    for var in state_vars:
        safe_var = sanitize_ident(var, context="state variable")
        lines.append(f"            {safe_var}_out <= hp_{safe_var}_out;")
    lines.append("    end")
    lines.append("end")
    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines)
