# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Precision formal evidence

"""Generate — and optionally machine-check — SymbiYosys evidence for precision claims.

An adaptive-precision plan assigns each synapse a fixed-point bit width and a
stochastic bitstream length under a total-error budget. This module renders that
budget into a formally checkable artefact: a synthesisable *bounded-error monitor*
(the RTL ``.v``) and a *bound assertion checker* (the SVA ``.sv``) whose immediate
``assert`` / ``assume`` statements encode the plan's safety obligations:

1. bounded error — the accumulated quantisation-plus-stochastic error never
   exceeds the claimed total error bound over the bitstream length;
2. bounded length — the length sequencer never runs past the declared bitstream
   length;
3. no overflow — the error accumulator is wide enough that the next accumulation
   never wraps, which keeps obligation 1 sound.

By default :func:`write_precision_formal_evidence_bundle` only *writes* the bundle
(deterministic, no external tools) and records ``symbiyosys_executed = False``.
Passing ``execute=True`` runs the proof through
:func:`sc_neurocore.compiler.formal_property_check.prove_property` when the formal
toolchain is present and records the real verdict; when the toolchain is absent it
records a skip reason rather than fabricating a pass.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from string import Template
from typing import Any

from .synapse_precision import SynapsePrecision

_Q16_ONE = 65536.0

# k-induction window for the unbounded proof. The monitor's strengthening lemma
# (``err_acc <= step_count * per_step``) is 1-inductive, so a small fixed depth
# converges regardless of bitstream length — unlike BMC completeness, which scales
# with the length.
_KINDUCTION_DEPTH = 8

# The RTL is a synthesisable datapath; the checker is instantiated only under the
# ``FORMAL`` macro (defined by SymbiYosys' ``read -formal``), so plain synthesis
# strips it. This is the textbook SymbiYosys structure — yosys 0.33 silently
# ignores ``bind`` directives, so the checker is instantiated explicitly instead.
_MONITOR_RTL_TEMPLATE = Template(
    """`timescale 1ns/1ps
// Adaptive-precision bounded-error monitor for ${module_name}.
// Auto-generated by SC-NeuroCore. The datapath is synthesisable; the proof
// obligations live in the ${module_name}_sva checker, instantiated under FORMAL.
module ${module_name} #(
    parameter integer MAX_TOTAL_ERROR_Q16  = ${max_total_error_q16},
    parameter integer MAX_BIT_WIDTH        = ${max_bit_width},
    parameter integer MAX_BITSTREAM_LENGTH = ${max_bitstream_length},
    parameter integer PER_STEP_BOUND_Q16   = ${per_step_bound_q16},
    parameter integer ACC_WIDTH            = ${acc_width},
    parameter integer LEN_WIDTH            = ${len_width}
)(
    input  wire                 clk,
    input  wire [ACC_WIDTH-1:0] err_step,
    output wire [ACC_WIDTH-1:0] err_acc_o,
    output wire [LEN_WIDTH-1:0] step_count_o
);
    reg [ACC_WIDTH-1:0] err_acc    = {ACC_WIDTH{1'b0}};
    reg [LEN_WIDTH-1:0] step_count = {LEN_WIDTH{1'b0}};

    always @(posedge clk) begin
        if (step_count < MAX_BITSTREAM_LENGTH[LEN_WIDTH-1:0]) begin
            err_acc    <= err_acc + err_step;
            step_count <= step_count + 1'b1;
        end
    end

    assign err_acc_o    = err_acc;
    assign step_count_o = step_count;

`ifdef FORMAL
    ${module_name}_sva #(
        .MAX_TOTAL_ERROR_Q16(MAX_TOTAL_ERROR_Q16),
        .MAX_BIT_WIDTH(MAX_BIT_WIDTH),
        .MAX_BITSTREAM_LENGTH(MAX_BITSTREAM_LENGTH),
        .PER_STEP_BOUND_Q16(PER_STEP_BOUND_Q16),
        .ACC_WIDTH(ACC_WIDTH),
        .LEN_WIDTH(LEN_WIDTH)
    ) sva_i (
        .clk(clk),
        .err_step(err_step),
        .err_acc(err_acc),
        .step_count(step_count)
    );
`endif
endmodule
"""
)

_MONITOR_SVA_TEMPLATE = Template(
    """`timescale 1ns/1ps
// Bound proof obligations for the ${module_name} adaptive-precision monitor.
// Auto-generated by SC-NeuroCore.
module ${module_name}_sva #(
    parameter integer MAX_TOTAL_ERROR_Q16  = ${max_total_error_q16},
    parameter integer MAX_BIT_WIDTH        = ${max_bit_width},
    parameter integer MAX_BITSTREAM_LENGTH = ${max_bitstream_length},
    parameter integer PER_STEP_BOUND_Q16   = ${per_step_bound_q16},
    parameter integer ACC_WIDTH            = ${acc_width},
    parameter integer LEN_WIDTH            = ${len_width}
)(
    input logic                 clk,
    input logic [ACC_WIDTH-1:0] err_step,
    input logic [ACC_WIDTH-1:0] err_acc,
    input logic [LEN_WIDTH-1:0] step_count
);
    // Structural: the selected operand bit width is positive.
    initial assert (MAX_BIT_WIDTH >= 1);

    always @(posedge clk) begin
        // Environment assumption: each per-tick error increment stays within the
        // adaptive-precision plan's per-step budget (quantisation + stochastic).
        assume (err_step <= PER_STEP_BOUND_Q16[ACC_WIDTH-1:0]);
        // Inductive lemma: accumulated error tracks the steps taken times the
        // per-step budget. This is 1-inductive (unlike obligation 1 on its own),
        // so it makes k-induction (mode prove) converge to an unbounded proof
        // instead of an inconclusive result; it is trivially true under BMC too.
        assert (err_acc <= step_count * PER_STEP_BOUND_Q16);
        // Obligation 1 (bounded error): accumulated error never exceeds the
        // claimed total error bound across the bitstream length. Follows from the
        // lemma and obligation 2: err_acc <= length * per_step <= total.
        assert (err_acc <= MAX_TOTAL_ERROR_Q16[ACC_WIDTH-1:0]);
        // Obligation 2 (bounded length): the sequencer never runs past the
        // declared bitstream length.
        assert (step_count <= MAX_BITSTREAM_LENGTH[LEN_WIDTH-1:0]);
        // Obligation 3 (no overflow): the error accumulator is wide enough that
        // the next accumulation never wraps, keeping obligation 1 sound.
        assert (({1'b0, err_acc} + {1'b0, err_step}) <= {ACC_WIDTH{1'b1}});
    end
endmodule
"""
)


@dataclass(frozen=True)
class _MonitorParameters:
    """Derived RTL parameters for the adaptive-precision bounded-error monitor.

    Attributes
    ----------
    max_total_error_q16 : int
        The claimed total error bound in Q16.16 fixed point.
    max_bit_width : int
        The largest synapse operand bit width in the plan.
    max_bitstream_length : int
        The longest stochastic bitstream in the plan (the sequencer bound and the
        number of accumulation steps).
    per_step_bound_q16 : int
        The per-tick error budget in Q16 — ``floor(max_total_error_q16 /
        max_bitstream_length)`` — so that ``length * per_step <= total`` by
        construction, which the assumption on ``err_step`` then enforces.
    acc_width : int
        Error-accumulator width in bits, sized to hold the bound plus one further
        step with a guard bit so the no-overflow obligation is faithful.
    len_width : int
        Length-counter width in bits, sized to represent ``max_bitstream_length``.
    complete_bmc_depth : int
        A BMC depth (``max_bitstream_length + 2``) at which the accumulator has
        stopped updating, so bounded checking to this depth exhausts the reachable
        state space and the proof is complete rather than merely bounded.
    """

    max_total_error_q16: int
    max_bit_width: int
    max_bitstream_length: int
    per_step_bound_q16: int
    acc_width: int
    len_width: int
    complete_bmc_depth: int

    def as_substitution(self, module_name: str) -> dict[str, object]:
        """Return the template substitution mapping for ``module_name``."""
        return {
            "module_name": module_name,
            "max_total_error_q16": self.max_total_error_q16,
            "max_bit_width": self.max_bit_width,
            "max_bitstream_length": self.max_bitstream_length,
            "per_step_bound_q16": self.per_step_bound_q16,
            "acc_width": self.acc_width,
            "len_width": self.len_width,
        }


def _monitor_parameters(
    max_total_error_bound: float, max_bit_width: int, max_bitstream_length: int
) -> _MonitorParameters:
    """Derive the monitor's fixed-point widths and bounds from a precision plan.

    Parameters
    ----------
    max_total_error_bound : float
        The largest per-synapse total error bound in the plan (fractional).
    max_bit_width : int
        The largest synapse operand bit width in the plan.
    max_bitstream_length : int
        The longest stochastic bitstream in the plan (guaranteed positive by
        :class:`~sc_neurocore.compiler.synapse_precision.SynapsePrecision`).

    Returns
    -------
    _MonitorParameters
        The derived, self-consistent RTL parameter set.
    """
    bound_q16 = int(round(max_total_error_bound * _Q16_ONE))
    per_step = bound_q16 // max_bitstream_length
    acc_span = bound_q16 + per_step
    acc_width = max(2, acc_span.bit_length() + 1)
    len_width = max(1, max_bitstream_length.bit_length()) + 1
    return _MonitorParameters(
        max_total_error_q16=bound_q16,
        max_bit_width=max_bit_width,
        max_bitstream_length=max_bitstream_length,
        per_step_bound_q16=per_step,
        acc_width=acc_width,
        len_width=len_width,
        complete_bmc_depth=max_bitstream_length + 2,
    )


def _precision_monitor_rtl(module_name: str, params: _MonitorParameters) -> str:
    """Render the synthesisable bounded-error monitor RTL for ``module_name``."""
    return _MONITOR_RTL_TEMPLATE.substitute(params.as_substitution(module_name))


def _precision_monitor_sva(module_name: str, params: _MonitorParameters) -> str:
    """Render the bound assertion checker for ``module_name``."""
    return _MONITOR_SVA_TEMPLATE.substitute(params.as_substitution(module_name))


def _execute_precision_proof(
    module_name: str,
    rtl: str,
    sva: str,
    formal_claim: dict[str, Any],
    proof_workdir: Path,
    *,
    mode: str,
    depth: int,
) -> str:
    """Run the property proof if the toolchain is present; update ``formal_claim``.

    ``mode`` selects bounded model checking (``"bmc"``, complete for the saturating
    monitor) or k-induction (``"prove"``, an unbounded proof). The proof runs inside
    ``proof_workdir`` (a subdirectory of the bundle output), so the ``sby`` run tree
    stays contained with the bundle rather than polluting the caller's working
    directory.

    Returns the evidence boundary string reflecting what actually happened —
    an executed proof or a recorded skip — never a fabricated pass.
    """
    from . import formal_property_check

    if not formal_property_check.formal_tools_available():
        formal_claim["execution_skipped_reason"] = (
            "formal toolchain (sby, yosys, z3) not available on PATH"
        )
        return "bundle_generation_only_no_symbiyosys_execution_no_silicon_claim"

    result = formal_property_check.prove_property(
        rtl,
        sva,
        top=module_name,
        mode=mode,  # type: ignore[arg-type]
        depth=depth,
        workdir=proof_workdir,
    )
    formal_claim["symbiyosys_executed"] = True
    formal_claim["formal_proof_passed"] = result.proven
    formal_claim["proof_mode"] = result.mode
    formal_claim["proof_depth"] = result.depth
    formal_claim["proof_engine"] = result.engine
    formal_claim["proof_verdict"] = result.verdict
    formal_claim["proof_unbounded"] = result.mode == "prove"
    if result.counterexample is not None:
        formal_claim["proof_counterexample"] = result.counterexample
    elif not result.proven:
        # A non-passing proof with no counterexample is an inconclusive k-induction:
        # the base case held but the induction step did not converge.
        formal_claim["proof_inconclusive_reason"] = (
            "k-induction base case held but the induction step did not converge"
        )
    if result.mode == "prove":
        return "symbiyosys_kinduction_executed_no_silicon_claim"
    return "symbiyosys_bmc_executed_no_silicon_claim"


def write_precision_formal_evidence_bundle(
    output_dir: str | Path,
    assignments: list[SynapsePrecision],
    *,
    module_name: str = "adaptive_precision_plan",
    execute: bool = False,
    unbounded: bool = False,
) -> dict[str, Any]:
    """Write a SymbiYosys evidence bundle for adaptive-precision claims.

    Renders the bounded-error monitor RTL, the bound assertion checker, a runnable
    ``.sby`` script, and a manifest describing the claim. The bundle is
    deterministic: identical arguments produce byte-identical artefacts.

    Parameters
    ----------
    output_dir : str or Path
        Directory to write the bundle into (created if absent).
    assignments : list[SynapsePrecision]
        The precision plan. Must be non-empty.
    module_name : str
        Top-level module name for the generated RTL and SVA.
    execute : bool
        When ``False`` (default) the bundle is only written and the manifest
        records ``symbiyosys_executed = False`` — no external tools are invoked,
        keeping the call deterministic and CI-safe. When ``True`` and the formal
        toolchain (``sby`` / ``yosys`` / ``z3``) is on ``PATH``, the proof is run
        and the real verdict recorded; when the toolchain is absent, a skip reason
        is recorded instead of a fabricated pass.
    unbounded : bool
        Selects the proof method for both the emitted ``.sby`` and the executed
        proof. ``False`` (default) uses bounded model checking to ``length + 2``
        cycles — complete because the accumulator saturates. ``True`` uses
        k-induction (``mode prove``), an *unbounded* proof whose depth does not
        scale with the bitstream length (the monitor carries the 1-inductive
        strengthening lemma the induction needs). k-induction can come back
        inconclusive, which is recorded honestly rather than as a pass.

    Returns
    -------
    dict[str, Any]
        The manifest that was written.

    Raises
    ------
    ValueError
        If ``assignments`` is empty.
    """
    if not assignments:
        raise ValueError("assignments must not be empty")
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    max_error = max(item.total_error_bound for item in assignments)
    max_bits = max(item.bit_width for item in assignments)
    max_length = max(item.bitstream_length for item in assignments)
    params = _monitor_parameters(max_error, max_bits, max_length)
    proof_mode = "prove" if unbounded else "bmc"
    proof_depth = _KINDUCTION_DEPTH if unbounded else params.complete_bmc_depth

    rtl_file = f"{module_name}.v"
    sva_file = f"{module_name}_sva.sv"
    sby_file = f"{module_name}.sby"
    report_file = f"{module_name}_formal_report.json"

    rtl = _precision_monitor_rtl(module_name, params)
    sva = _precision_monitor_sva(module_name, params)
    (out / rtl_file).write_text(rtl, encoding="utf-8")
    (out / sva_file).write_text(sva, encoding="utf-8")

    from .deployment import generate_sby_script

    (out / sby_file).write_text(
        generate_sby_script(
            module_name,
            sva_file=sva_file,
            mode=proof_mode,  # type: ignore[arg-type]
            depth=proof_depth,
            engine="z3",
        ),
        encoding="utf-8",
    )

    formal_claim: dict[str, Any] = {
        "max_total_error_bound": max_error,
        "max_bit_width": max_bits,
        "max_bitstream_length": max_length,
        "symbiyosys_executed": False,
        "formal_proof_passed": False,
        "hardware_measurement_claimed": False,
    }
    evidence_boundary = "bundle_generation_only_no_symbiyosys_execution_no_silicon_claim"
    if execute:
        evidence_boundary = _execute_precision_proof(
            module_name,
            rtl,
            sva,
            formal_claim,
            out / f"{module_name}_proof_work",
            mode=proof_mode,
            depth=proof_depth,
        )

    manifest = {
        "schema_version": "sc-neurocore.adaptive-precision-formal-bundle.v1",
        "evidence_classification": "compile",
        "status": "completed",
        "module_name": module_name,
        "evidence_boundary": evidence_boundary,
        "assignments_count": len(assignments),
        "formal_claim": formal_claim,
        "artifacts": {
            "rtl": rtl_file,
            "sva": sva_file,
            "sby": sby_file,
            "report": report_file,
        },
    }
    (out / f"{module_name}_formal_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest
