# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Precision formal evidence

"""Generate SymbiYosys evidence bundles for adaptive precision claims."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .synapse_precision import SynapsePrecision


def write_precision_formal_evidence_bundle(
    output_dir: str | Path,
    assignments: list[SynapsePrecision],
    *,
    module_name: str = "adaptive_precision_plan",
) -> dict[str, Any]:
    """Write a deterministic SymbiYosys evidence bundle for precision claims."""
    if not assignments:
        raise ValueError("assignments must not be empty")
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    max_error = max(item.total_error_bound for item in assignments)
    max_bits = max(item.bit_width for item in assignments)
    max_length = max(item.bitstream_length for item in assignments)

    rtl_file = f"{module_name}.v"
    sva_file = f"{module_name}_sva.sv"
    sby_file = f"{module_name}.sby"
    report_file = f"{module_name}_formal_report.json"

    (out / sva_file).write_text(
        _adaptive_precision_sva(
            module_name=module_name,
            max_total_error_bound=max_error,
            max_bit_width=max_bits,
            max_bitstream_length=max_length,
        ),
        encoding="utf-8",
    )

    from .deployment import generate_sby_script

    (out / sby_file).write_text(
        generate_sby_script(module_name, sva_file=sva_file, mode="prove", depth=32),
        encoding="utf-8",
    )

    manifest = {
        "schema_version": "sc-neurocore.adaptive-precision-formal-bundle.v1",
        "evidence_classification": "compile",
        "status": "completed",
        "module_name": module_name,
        "evidence_boundary": ("bundle_generation_only_no_symbiyosys_execution_no_silicon_claim"),
        "assignments_count": len(assignments),
        "formal_claim": {
            "max_total_error_bound": max_error,
            "max_bit_width": max_bits,
            "max_bitstream_length": max_length,
            "symbiyosys_executed": False,
            "formal_proof_passed": False,
            "hardware_measurement_claimed": False,
        },
        "artifacts": {
            "rtl": rtl_file,
            "sva": sva_file,
            "sby": sby_file,
            "report": report_file,
        },
    }
    (out / f"{module_name}_formal_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest


def _adaptive_precision_sva(
    *,
    module_name: str,
    max_total_error_bound: float,
    max_bit_width: int,
    max_bitstream_length: int,
) -> str:
    bound_q16 = int(round(max_total_error_bound * 65536.0))
    return (
        f"// Adaptive precision formal assertions for {module_name}\n"
        f"// Auto-generated by SC-NeuroCore\n"
        f"`timescale 1ns/1ps\n\n"
        f"module {module_name}_sva;\n"
        f"  localparam int MAX_TOTAL_ERROR_Q16 = {bound_q16};\n"
        f"  localparam int MAX_BIT_WIDTH = {max_bit_width};\n"
        f"  localparam int MAX_BITSTREAM_LENGTH = {max_bitstream_length};\n\n"
        f"  // Placeholder proof obligations for external binding:\n"
        f"  // 1) selected bit width shall not exceed MAX_BIT_WIDTH\n"
        f"  // 2) selected bitstream length shall not exceed MAX_BITSTREAM_LENGTH\n"
        f"  // 3) bounded-error accumulator shall stay <= MAX_TOTAL_ERROR_Q16\n"
        f"endmodule\n"
    )
