# SPDX-License-Identifier: AGPL-3.0-or-later
# © 1998–2026 Miroslav Šotek. All rights reserved.
# Contact: www.anulum.li | protoscience@anulum.li

"""SC-NeuroCore Engine — 110 Rust neuron models + SIMD primitives + IR compiler."""

try:
    from sc_neurocore_engine.sc_neurocore_engine import (
        __version__,
        simd_tier,
        set_num_threads,
        pack_bitstream,
        unpack_bitstream,
        popcount,
        pack_bitstream_numpy,
        popcount_numpy,
        unpack_bitstream_numpy,
        batch_lif_run,
        batch_lif_run_multi,
        batch_lif_run_varying,
        batch_encode,
        batch_encode_numpy,
        Lfsr16,
        BitstreamEncoder,
        FixedPointLif,
        DenseLayer,
        StdpSynapse,
        SCPNMetrics,
        BitStreamTensor,
        BrunelNetwork,
    )
except ImportError as exc:
    raise ImportError(
        "sc_neurocore_engine native module not found. "
        "Build with: cd engine && maturin develop --release"
    ) from exc

try:
    from sc_neurocore_engine.sc_neurocore_engine import (
        QuadraticIFNeuron,
        ThetaNeuron,
        PerfectIntegratorNeuron,
        GatedLIFNeuron,
        NonlinearLIFNeuron,
        SFANeuron,
        MATNeuron,
        EscapeRateNeuron,
        KLIFNeuron,
        InhibitoryLIFNeuron,
        ComplementaryLIFNeuron,
        ParametricLIFNeuron,
        NonResettingLIFNeuron,
        AdaptiveThresholdIFNeuron,
        SigmaDeltaNeuron,
        EnergyLIFNeuron,
        IntegerQIFNeuron,
        ClosedFormContinuousNeuron,
        FitzHughNagumoNeuron,
        MorrisLecarNeuron,
        HindmarshRoseNeuron,
        ResonateAndFireNeuron,
        FitzHughRinzelNeuron,
        McKeanNeuron,
        TermanWangOscillator,
        BendaHerzNeuron,
        AlphaNeuron,
        COBALIFNeuron,
        GutkinErmentroutNeuron,
        WilsonHRNeuron,
        ChayNeuron,
        ChayKeizerNeuron,
        ShermanRinzelKeizerNeuron,
        ButeraRespiratoryNeuron,
        EPropALIFNeuron,
        SuperSpikeNeuron,
        LearnableNeuronModel,
        PernarowskiNeuron,
        ChialvoMapNeuron,
        RulkovMapNeuron,
        IbarzTanakaMapNeuron,
        MedvedevMapNeuron,
        CazellesMapNeuron,
        CourageNekorkinMapNeuron,
        HodgkinHuxleyNeuron,
        TraubMilesNeuron,
        WangBuzsakiNeuron,
        ConnorStevensNeuron,
        DestexheThalamicNeuron,
        HuberBraunNeuron,
        GolombFSNeuron,
        PospischilNeuron,
        MainenSejnowskiNeuron,
        DeSchutterPurkinjeNeuron,
        PlantR15Neuron,
        PrescottNeuron,
        MihalasNieburNeuron,
        GLIFNeuron,
        GIFPopulationNeuron,
        AvRonCardiacNeuron,
        DurstewitzDopamineNeuron,
        HillTononiNeuron,
        BertramPhantomBurster,
        YamadaNeuron,
        PinskyRinzelNeuron,
        HayL5PyramidalNeuron,
        MarderSTGNeuron,
        RallCableNeuron,
        BoothRinzelNeuron,
        DendrifyNeuron,
        TwoCompartmentLIFNeuron,
        PoissonNeuron,
        InhomogeneousPoissonNeuron,
        GammaRenewalNeuron,
        StochasticIFNeuron,
        GalvesLocherbachNeuron,
        SpikeResponseNeuron,
        GLMNeuron,
        WilsonCowanUnit,
        JansenRitUnit,
        WongWangUnit,
        ErmentroutKopellPopulation,
        WendlingNeuron,
        LarterBreakspearNeuron,
        LoihiCUBANeuron,
        Loihi2Neuron,
        TrueNorthNeuron,
        BrainScaleSAdExNeuron,
        SpiNNakerLIFNeuron,
        SpiNNaker2Neuron,
        DPINeuron,
        AkidaNeuron,
        NeuroGridNeuron,
        McCullochPittsNeuron,
        SigmoidRateNeuron,
        ThresholdLinearRateNeuron,
        AstrocyteModel,
        TsodyksMarkramNeuron,
        LiquidTimeConstantNeuron,
        CompteWMNeuron,
        SiegertTransferFunction,
        FractionalLIFNeuron,
        ParallelSpikingNeuron,
        AmariNeuralField,
        LeakyCompeteFireNeuron,
        AdExNeuron,
        ExpIFNeuron,
        LapicqueNeuron,
    )

    _neurons_available = True
except ImportError:
    _neurons_available = False

from .layers import VectorizedSCLayer
from .neurons import FixedPointLIFNeuron
from .grad import SurrogateLif, DifferentiableDenseLayer
from .attention import StochasticAttention
from .graphs import StochasticGraphLayer
from .scpn import KuramotoSolver
from .ir import ScGraph, ScGraphBuilder, parse_ir
from .hdc import HDCVector
from .petri_net import PetriNetEngine

_NEURON_MODELS = [
    "QuadraticIFNeuron",
    "ThetaNeuron",
    "PerfectIntegratorNeuron",
    "GatedLIFNeuron",
    "NonlinearLIFNeuron",
    "SFANeuron",
    "MATNeuron",
    "EscapeRateNeuron",
    "KLIFNeuron",
    "InhibitoryLIFNeuron",
    "ComplementaryLIFNeuron",
    "ParametricLIFNeuron",
    "NonResettingLIFNeuron",
    "AdaptiveThresholdIFNeuron",
    "SigmaDeltaNeuron",
    "EnergyLIFNeuron",
    "IntegerQIFNeuron",
    "ClosedFormContinuousNeuron",
    "FitzHughNagumoNeuron",
    "MorrisLecarNeuron",
    "HindmarshRoseNeuron",
    "ResonateAndFireNeuron",
    "FitzHughRinzelNeuron",
    "McKeanNeuron",
    "TermanWangOscillator",
    "BendaHerzNeuron",
    "AlphaNeuron",
    "COBALIFNeuron",
    "GutkinErmentroutNeuron",
    "WilsonHRNeuron",
    "ChayNeuron",
    "ChayKeizerNeuron",
    "ShermanRinzelKeizerNeuron",
    "ButeraRespiratoryNeuron",
    "EPropALIFNeuron",
    "SuperSpikeNeuron",
    "LearnableNeuronModel",
    "PernarowskiNeuron",
    "ChialvoMapNeuron",
    "RulkovMapNeuron",
    "IbarzTanakaMapNeuron",
    "MedvedevMapNeuron",
    "CazellesMapNeuron",
    "CourageNekorkinMapNeuron",
    "HodgkinHuxleyNeuron",
    "TraubMilesNeuron",
    "WangBuzsakiNeuron",
    "ConnorStevensNeuron",
    "DestexheThalamicNeuron",
    "HuberBraunNeuron",
    "GolombFSNeuron",
    "PospischilNeuron",
    "MainenSejnowskiNeuron",
    "DeSchutterPurkinjeNeuron",
    "PlantR15Neuron",
    "PrescottNeuron",
    "MihalasNieburNeuron",
    "GLIFNeuron",
    "GIFPopulationNeuron",
    "AvRonCardiacNeuron",
    "DurstewitzDopamineNeuron",
    "HillTononiNeuron",
    "BertramPhantomBurster",
    "YamadaNeuron",
    "PinskyRinzelNeuron",
    "HayL5PyramidalNeuron",
    "MarderSTGNeuron",
    "RallCableNeuron",
    "BoothRinzelNeuron",
    "DendrifyNeuron",
    "TwoCompartmentLIFNeuron",
    "PoissonNeuron",
    "InhomogeneousPoissonNeuron",
    "GammaRenewalNeuron",
    "StochasticIFNeuron",
    "GalvesLocherbachNeuron",
    "SpikeResponseNeuron",
    "GLMNeuron",
    "WilsonCowanUnit",
    "JansenRitUnit",
    "WongWangUnit",
    "ErmentroutKopellPopulation",
    "WendlingNeuron",
    "LarterBreakspearNeuron",
    "LoihiCUBANeuron",
    "Loihi2Neuron",
    "TrueNorthNeuron",
    "BrainScaleSAdExNeuron",
    "SpiNNakerLIFNeuron",
    "SpiNNaker2Neuron",
    "DPINeuron",
    "AkidaNeuron",
    "NeuroGridNeuron",
    "McCullochPittsNeuron",
    "SigmoidRateNeuron",
    "ThresholdLinearRateNeuron",
    "AstrocyteModel",
    "TsodyksMarkramNeuron",
    "LiquidTimeConstantNeuron",
    "CompteWMNeuron",
    "SiegertTransferFunction",
    "FractionalLIFNeuron",
    "ParallelSpikingNeuron",
    "AmariNeuralField",
    "LeakyCompeteFireNeuron",
    "AdExNeuron",
    "ExpIFNeuron",
    "LapicqueNeuron",
]

__all__ = [
    "__version__",
    "simd_tier",
    "set_num_threads",
    "pack_bitstream",
    "unpack_bitstream",
    "popcount",
    "pack_bitstream_numpy",
    "popcount_numpy",
    "unpack_bitstream_numpy",
    "batch_lif_run",
    "batch_lif_run_multi",
    "batch_lif_run_varying",
    "batch_encode",
    "batch_encode_numpy",
    "Lfsr16",
    "BitstreamEncoder",
    "FixedPointLif",
    "DenseLayer",
    "StdpSynapse",
    "SCPNMetrics",
    "BitStreamTensor",
    "VectorizedSCLayer",
    "FixedPointLIFNeuron",
    "SurrogateLif",
    "DifferentiableDenseLayer",
    "StochasticAttention",
    "StochasticGraphLayer",
    "KuramotoSolver",
    "ScGraph",
    "ScGraphBuilder",
    "parse_ir",
    "HDCVector",
    "PetriNetEngine",
    "BrunelNetwork",
    *(_NEURON_MODELS if _neurons_available else []),
]
