// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — PyO3 neuron public-export contract

use std::any::TypeId;
use std::collections::HashSet;

use sc_neurocore_engine::pyo3_neurons::{
    PyATypeKNeuron, PyAdExNeuron, PyAdaptiveThresholdIFNeuron, PyAdaptiveThresholdMoENeuron,
    PyAiharaMapNeuron, PyAkidaNeuron, PyAlphaMotorNeuron, PyAlphaNeuron, PyArcaneNeuron,
    PyAstrocyteLIFNeuron, PyAttentionGatedNeuron, PyAvRonCardiacNeuron, PyBKNeuron,
    PyBalancedResonateAndFireNeuron, PyBertramPhantomBurster, PyBoothRinzelNeuron,
    PyBrainScaleSAdExNeuron, PyBrunelNetwork, PyButeraRespiratoryNeuron, PyCardiacPurkinjeFibre,
    PyCazellesMapNeuron, PyCerebellarBasketNeuron, PyChandelierNeuron, PyChayKeizerNeuron,
    PyChayNeuron, PyChialvoMapNeuron, PyClosedFormContinuousNeuron, PyCochlearHairCell,
    PyComplementaryLIFNeuron, PyCompositionalBindingNeuron, PyConePhotoreceptor,
    PyConnorStevensNeuron, PyContinuousAttractorNeuron, PyCourageNekorkinMapNeuron, PyDCNNeuron,
    PyDPINeuron, PyDeSchutterPurkinjeNeuron, PyDendrifyNeuron, PyDendriticNMDANeuron,
    PyDestexheThalamicNeuron, PyDifferentiableSurrogateNeuron, PyDirectionSelectiveRGC,
    PyDopamineStdpSynapse, PyDurstewitzDopamineNeuron, PyElBoustaniNetwork, PyEndocrineBetaCell,
    PyEnergyLIFNeuron, PyErmentroutKopellMapNeuron, PyErmentroutKopellPopulation, PyFHAxon,
    PyFitzHughNagumoNeuron, PyFitzHughRinzelNeuron, PyGIFPopulationNeuron, PyGLIFNeuron,
    PyGLMNeuron, PyGalvesLocherbachNeuron, PyGammaMotorNeuron, PyGammaRenewalNeuron,
    PyGapJunctionNeuron, PyGatedLIFNeuron, PyGolgiCell, PyGolombFSNeuron, PyGradedSynapseNeuron,
    PyGranuleCell, PyGutkinErmentroutNeuron, PyHayL5PyramidalNeuron, PyHillTononiNeuron,
    PyHindmarshRoseNeuron, PyHodgkinHuxleyNeuron, PyHuberBraunNeuron,
    PyHybridLinearAttentionNeuron, PyIbarzTanakaMapNeuron, PyIhNeuron, PyInhibitoryLIFNeuron,
    PyInhomogeneousPoissonNeuron, PyInnerHairCell, PyJansenRitUnit, PyKLIFNeuron,
    PyKilincBhattMapNeuron, PyLapicqueNeuron, PyLearnableNeuronModel, PyLoihi2Neuron,
    PyLoihiCUBANeuron, PyLugaroCell, PyMATNeuron, PyMainenSejnowskiNeuron, PyMarderSTGNeuron,
    PyMartinottiNeuron, PyMcCullochPittsNeuron, PyMcKeanNeuron, PyMedvedevMapNeuron, PyMerkelCell,
    PyMetaPlasticNeuron, PyMihalasNieburNeuron, PyMontbrioMeanField, PyMorrisLecarNeuron,
    PyMotorUnit, PyMultiTimescaleNeuron, PyMulticompartmentMCNNeuron, PyMyelinatedAxon,
    PyNMDANeuron, PyNeuroGridNeuron, PyNociceptor, PyNodeOfRanvier, PyNonResettingLIFNeuron,
    PyNonlinearLIFNeuron, PyOlfactoryReceptorNeuron, PyOuterHairCell, PyPVFastSpikingNeuron,
    PyPacinianCorpuscle, PyParametricLIFNeuron, PyPerfectIntegratorNeuron, PyPernarowskiNeuron,
    PyPersistentNaNeuron, PyPinskyRinzelNeuron, PyPlantR15Neuron, PyPospischilNeuron,
    PyPredictiveCodingNeuron, PyPrescottNeuron, PyQuadraticIFNeuron, PyQuantumInspiredLIFNeuron,
    PyRallCableNeuron, PyRenshawCell, PyResonateAndFireNeuron, PyRetinalGanglionCell,
    PyRodPhotoreceptor, PyRulkovMapNeuron, PySFANeuron, PySKNeuron, PySSTNeuron,
    PySelfReferentialNeuron, PyShermanRinzelKeizerNeuron, PyShortTermPlasticitySynapse,
    PySigmaDeltaNeuron, PySigmoidRateNeuron, PySmoothMuscleCell, PySpiNNaker2Neuron,
    PySpiNNakerLIFNeuron, PySpikeResponseNeuron, PyStellateCell, PyStochasticIFNeuron,
    PyStochasticLIFNeuron, PyTTypeCaNeuron, PyTUMNetwork, PyTasteReceptorCell,
    PyTermanWangOscillator, PyThetaNeuron, PyThresholdLinearRateNeuron, PyTraubMilesNeuron,
    PyTripletStdpSynapse, PyTrueNorthNeuron, PyTwoCompartmentLIFNeuron, PyUnipolarBrushCell,
    PyUpperMotorNeuron, PyVIPNeuron, PyWangBuzsakiNeuron, PyWilsonHRNeuron, PyYamadaNeuron,
};

#[test]
fn decomposed_wrappers_remain_distinct_public_types() {
    let exports = [
        TypeId::of::<PyAdaptiveThresholdIFNeuron>(),
        TypeId::of::<PyAiharaMapNeuron>(),
        TypeId::of::<PyAstrocyteLIFNeuron>(),
        TypeId::of::<PyAvRonCardiacNeuron>(),
        TypeId::of::<PyBalancedResonateAndFireNeuron>(),
        TypeId::of::<PyBertramPhantomBurster>(),
        TypeId::of::<PyButeraRespiratoryNeuron>(),
        TypeId::of::<PyCazellesMapNeuron>(),
        TypeId::of::<PyChayKeizerNeuron>(),
        TypeId::of::<PyChayNeuron>(),
        TypeId::of::<PyChialvoMapNeuron>(),
        TypeId::of::<PyClosedFormContinuousNeuron>(),
        TypeId::of::<PyComplementaryLIFNeuron>(),
        TypeId::of::<PyConnorStevensNeuron>(),
        TypeId::of::<PyCourageNekorkinMapNeuron>(),
        TypeId::of::<PyDeSchutterPurkinjeNeuron>(),
        TypeId::of::<PyDendriticNMDANeuron>(),
        TypeId::of::<PyDestexheThalamicNeuron>(),
        TypeId::of::<PyDurstewitzDopamineNeuron>(),
        TypeId::of::<PyEnergyLIFNeuron>(),
        TypeId::of::<PyErmentroutKopellMapNeuron>(),
        TypeId::of::<PyFitzHughNagumoNeuron>(),
        TypeId::of::<PyFitzHughRinzelNeuron>(),
        TypeId::of::<PyGIFPopulationNeuron>(),
        TypeId::of::<PyGLIFNeuron>(),
        TypeId::of::<PyGatedLIFNeuron>(),
        TypeId::of::<PyGolombFSNeuron>(),
        TypeId::of::<PyGutkinErmentroutNeuron>(),
        TypeId::of::<PyHillTononiNeuron>(),
        TypeId::of::<PyHindmarshRoseNeuron>(),
        TypeId::of::<PyHodgkinHuxleyNeuron>(),
        TypeId::of::<PyHuberBraunNeuron>(),
        TypeId::of::<PyIbarzTanakaMapNeuron>(),
        TypeId::of::<PyInhibitoryLIFNeuron>(),
        TypeId::of::<PyKLIFNeuron>(),
        TypeId::of::<PyKilincBhattMapNeuron>(),
        TypeId::of::<PyLearnableNeuronModel>(),
        TypeId::of::<PyMATNeuron>(),
        TypeId::of::<PyMainenSejnowskiNeuron>(),
        TypeId::of::<PyMcKeanNeuron>(),
        TypeId::of::<PyMedvedevMapNeuron>(),
        TypeId::of::<PyMihalasNieburNeuron>(),
        TypeId::of::<PyMorrisLecarNeuron>(),
        TypeId::of::<PyMulticompartmentMCNNeuron>(),
        TypeId::of::<PyNonResettingLIFNeuron>(),
        TypeId::of::<PyNonlinearLIFNeuron>(),
        TypeId::of::<PyParametricLIFNeuron>(),
        TypeId::of::<PyPerfectIntegratorNeuron>(),
        TypeId::of::<PyPernarowskiNeuron>(),
        TypeId::of::<PyPlantR15Neuron>(),
        TypeId::of::<PyPospischilNeuron>(),
        TypeId::of::<PyPrescottNeuron>(),
        TypeId::of::<PyQuadraticIFNeuron>(),
        TypeId::of::<PyResonateAndFireNeuron>(),
        TypeId::of::<PyRulkovMapNeuron>(),
        TypeId::of::<PySFANeuron>(),
        TypeId::of::<PyShermanRinzelKeizerNeuron>(),
        TypeId::of::<PySigmaDeltaNeuron>(),
        TypeId::of::<PyTermanWangOscillator>(),
        TypeId::of::<PyThetaNeuron>(),
        TypeId::of::<PyTraubMilesNeuron>(),
        TypeId::of::<PyWangBuzsakiNeuron>(),
        TypeId::of::<PyWilsonHRNeuron>(),
        TypeId::of::<PyYamadaNeuron>(),
        TypeId::of::<PyAlphaMotorNeuron>(),
        TypeId::of::<PyGammaMotorNeuron>(),
        TypeId::of::<PyUpperMotorNeuron>(),
        TypeId::of::<PyRenshawCell>(),
        TypeId::of::<PyMotorUnit>(),
        TypeId::of::<PyPVFastSpikingNeuron>(),
        TypeId::of::<PySSTNeuron>(),
        TypeId::of::<PyVIPNeuron>(),
        TypeId::of::<PyChandelierNeuron>(),
        TypeId::of::<PyCerebellarBasketNeuron>(),
        TypeId::of::<PyMartinottiNeuron>(),
        TypeId::of::<PyGranuleCell>(),
        TypeId::of::<PyGolgiCell>(),
        TypeId::of::<PyStellateCell>(),
        TypeId::of::<PyLugaroCell>(),
        TypeId::of::<PyUnipolarBrushCell>(),
        TypeId::of::<PyDCNNeuron>(),
        TypeId::of::<PyPersistentNaNeuron>(),
        TypeId::of::<PyIhNeuron>(),
        TypeId::of::<PyTTypeCaNeuron>(),
        TypeId::of::<PyATypeKNeuron>(),
        TypeId::of::<PyBKNeuron>(),
        TypeId::of::<PySKNeuron>(),
        TypeId::of::<PyNMDANeuron>(),
        TypeId::of::<PyMontbrioMeanField>(),
        TypeId::of::<PyBrunelNetwork>(),
        TypeId::of::<PyTUMNetwork>(),
        TypeId::of::<PyElBoustaniNetwork>(),
        TypeId::of::<PyGradedSynapseNeuron>(),
        TypeId::of::<PyGapJunctionNeuron>(),
        TypeId::of::<PyFHAxon>(),
        TypeId::of::<PyNodeOfRanvier>(),
        TypeId::of::<PyMyelinatedAxon>(),
        TypeId::of::<PyCardiacPurkinjeFibre>(),
        TypeId::of::<PySmoothMuscleCell>(),
        TypeId::of::<PyEndocrineBetaCell>(),
        TypeId::of::<PyInnerHairCell>(),
        TypeId::of::<PyOuterHairCell>(),
        TypeId::of::<PyRodPhotoreceptor>(),
        TypeId::of::<PyConePhotoreceptor>(),
        TypeId::of::<PyRetinalGanglionCell>(),
        TypeId::of::<PyMerkelCell>(),
        TypeId::of::<PyPacinianCorpuscle>(),
        TypeId::of::<PyNociceptor>(),
        TypeId::of::<PyOlfactoryReceptorNeuron>(),
        TypeId::of::<PyTasteReceptorCell>(),
        TypeId::of::<PyDirectionSelectiveRGC>(),
        TypeId::of::<PyCochlearHairCell>(),
        TypeId::of::<PyTripletStdpSynapse>(),
        TypeId::of::<PyShortTermPlasticitySynapse>(),
        TypeId::of::<PyDopamineStdpSynapse>(),
        TypeId::of::<PyAdaptiveThresholdMoENeuron>(),
        TypeId::of::<PyAdExNeuron>(),
        TypeId::of::<PyAlphaNeuron>(),
        TypeId::of::<PyArcaneNeuron>(),
        TypeId::of::<PyAttentionGatedNeuron>(),
        TypeId::of::<PyCompositionalBindingNeuron>(),
        TypeId::of::<PyContinuousAttractorNeuron>(),
        TypeId::of::<PyDifferentiableSurrogateNeuron>(),
        TypeId::of::<PyErmentroutKopellPopulation>(),
        TypeId::of::<PyHybridLinearAttentionNeuron>(),
        TypeId::of::<PyJansenRitUnit>(),
        TypeId::of::<PyLapicqueNeuron>(),
        TypeId::of::<PyMcCullochPittsNeuron>(),
        TypeId::of::<PyMetaPlasticNeuron>(),
        TypeId::of::<PyMultiTimescaleNeuron>(),
        TypeId::of::<PyPredictiveCodingNeuron>(),
        TypeId::of::<PyQuantumInspiredLIFNeuron>(),
        TypeId::of::<PySelfReferentialNeuron>(),
        TypeId::of::<PySigmoidRateNeuron>(),
        TypeId::of::<PyThresholdLinearRateNeuron>(),
        TypeId::of::<PyAkidaNeuron>(),
        TypeId::of::<PyBrainScaleSAdExNeuron>(),
        TypeId::of::<PyDPINeuron>(),
        TypeId::of::<PyLoihi2Neuron>(),
        TypeId::of::<PyLoihiCUBANeuron>(),
        TypeId::of::<PyNeuroGridNeuron>(),
        TypeId::of::<PySpiNNaker2Neuron>(),
        TypeId::of::<PySpiNNakerLIFNeuron>(),
        TypeId::of::<PyTrueNorthNeuron>(),
        TypeId::of::<PyBoothRinzelNeuron>(),
        TypeId::of::<PyDendrifyNeuron>(),
        TypeId::of::<PyHayL5PyramidalNeuron>(),
        TypeId::of::<PyMarderSTGNeuron>(),
        TypeId::of::<PyPinskyRinzelNeuron>(),
        TypeId::of::<PyRallCableNeuron>(),
        TypeId::of::<PyTwoCompartmentLIFNeuron>(),
        TypeId::of::<PyGLMNeuron>(),
        TypeId::of::<PyGalvesLocherbachNeuron>(),
        TypeId::of::<PyGammaRenewalNeuron>(),
        TypeId::of::<PyInhomogeneousPoissonNeuron>(),
        TypeId::of::<PySpikeResponseNeuron>(),
        TypeId::of::<PyStochasticIFNeuron>(),
        TypeId::of::<PyStochasticLIFNeuron>(),
    ];
    let unique: HashSet<_> = exports.into_iter().collect();

    assert_eq!(unique.len(), exports.len());
}
