// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — PyO3 neuron public-export contract

use std::any::TypeId;
use std::collections::HashSet;

use sc_neurocore_engine::pyo3_neurons::{
    PyATypeKNeuron, PyAdaptiveThresholdIFNeuron, PyAiharaMapNeuron, PyAlphaMotorNeuron,
    PyAstrocyteLIFNeuron, PyAvRonCardiacNeuron, PyBKNeuron, PyBalancedResonateAndFireNeuron,
    PyBertramPhantomBurster, PyBrunelNetwork, PyButeraRespiratoryNeuron, PyCardiacPurkinjeFibre,
    PyCazellesMapNeuron, PyCerebellarBasketNeuron, PyChandelierNeuron, PyChayKeizerNeuron,
    PyChayNeuron, PyChialvoMapNeuron, PyClosedFormContinuousNeuron, PyCochlearHairCell,
    PyComplementaryLIFNeuron, PyConePhotoreceptor, PyConnorStevensNeuron,
    PyCourageNekorkinMapNeuron, PyDCNNeuron, PyDeSchutterPurkinjeNeuron, PyDendriticNMDANeuron,
    PyDestexheThalamicNeuron, PyDirectionSelectiveRGC, PyDopamineStdpSynapse,
    PyDurstewitzDopamineNeuron, PyElBoustaniNetwork, PyEndocrineBetaCell, PyEnergyLIFNeuron,
    PyErmentroutKopellMapNeuron, PyFHAxon, PyFitzHughNagumoNeuron, PyFitzHughRinzelNeuron,
    PyGIFPopulationNeuron, PyGLIFNeuron, PyGammaMotorNeuron, PyGapJunctionNeuron, PyGatedLIFNeuron,
    PyGolgiCell, PyGolombFSNeuron, PyGradedSynapseNeuron, PyGranuleCell, PyGutkinErmentroutNeuron,
    PyHillTononiNeuron, PyHindmarshRoseNeuron, PyHodgkinHuxleyNeuron, PyHuberBraunNeuron,
    PyIbarzTanakaMapNeuron, PyIhNeuron, PyInhibitoryLIFNeuron, PyInnerHairCell, PyKLIFNeuron,
    PyKilincBhattMapNeuron, PyLearnableNeuronModel, PyLugaroCell, PyMATNeuron,
    PyMainenSejnowskiNeuron, PyMartinottiNeuron, PyMcKeanNeuron, PyMedvedevMapNeuron, PyMerkelCell,
    PyMihalasNieburNeuron, PyMontbrioMeanField, PyMorrisLecarNeuron, PyMotorUnit,
    PyMulticompartmentMCNNeuron, PyMyelinatedAxon, PyNMDANeuron, PyNociceptor, PyNodeOfRanvier,
    PyNonResettingLIFNeuron, PyNonlinearLIFNeuron, PyOlfactoryReceptorNeuron, PyOuterHairCell,
    PyPVFastSpikingNeuron, PyPacinianCorpuscle, PyParametricLIFNeuron, PyPerfectIntegratorNeuron,
    PyPernarowskiNeuron, PyPersistentNaNeuron, PyPlantR15Neuron, PyPospischilNeuron,
    PyPrescottNeuron, PyQuadraticIFNeuron, PyRenshawCell, PyResonateAndFireNeuron,
    PyRetinalGanglionCell, PyRodPhotoreceptor, PyRulkovMapNeuron, PySFANeuron, PySKNeuron,
    PySSTNeuron, PyShermanRinzelKeizerNeuron, PyShortTermPlasticitySynapse, PySigmaDeltaNeuron,
    PySmoothMuscleCell, PyStellateCell, PyTTypeCaNeuron, PyTUMNetwork, PyTasteReceptorCell,
    PyTermanWangOscillator, PyThetaNeuron, PyTraubMilesNeuron, PyTripletStdpSynapse,
    PyUnipolarBrushCell, PyUpperMotorNeuron, PyVIPNeuron, PyWangBuzsakiNeuron, PyWilsonHRNeuron,
    PyYamadaNeuron,
};

#[test]
fn decomposed_wrappers_remain_distinct_public_types() {
    let exports = [
        TypeId::of::<PyAdaptiveThresholdIFNeuron>(),
        TypeId::of::<PyAiharaMapNeuron>(),
        TypeId::of::<PyAstrocyteLIFNeuron>(),
        TypeId::of::<PyAvRonCardiacNeuron>(),
        TypeId::of::<PyBalancedResonateAndFireNeuron>(),
        TypeId::of::<PyBertramPhantomBurster>(),
        TypeId::of::<PyButeraRespiratoryNeuron>(),
        TypeId::of::<PyCazellesMapNeuron>(),
        TypeId::of::<PyChayKeizerNeuron>(),
        TypeId::of::<PyChayNeuron>(),
        TypeId::of::<PyChialvoMapNeuron>(),
        TypeId::of::<PyClosedFormContinuousNeuron>(),
        TypeId::of::<PyComplementaryLIFNeuron>(),
        TypeId::of::<PyConnorStevensNeuron>(),
        TypeId::of::<PyCourageNekorkinMapNeuron>(),
        TypeId::of::<PyDeSchutterPurkinjeNeuron>(),
        TypeId::of::<PyDendriticNMDANeuron>(),
        TypeId::of::<PyDestexheThalamicNeuron>(),
        TypeId::of::<PyDurstewitzDopamineNeuron>(),
        TypeId::of::<PyEnergyLIFNeuron>(),
        TypeId::of::<PyErmentroutKopellMapNeuron>(),
        TypeId::of::<PyFitzHughNagumoNeuron>(),
        TypeId::of::<PyFitzHughRinzelNeuron>(),
        TypeId::of::<PyGIFPopulationNeuron>(),
        TypeId::of::<PyGLIFNeuron>(),
        TypeId::of::<PyGatedLIFNeuron>(),
        TypeId::of::<PyGolombFSNeuron>(),
        TypeId::of::<PyGutkinErmentroutNeuron>(),
        TypeId::of::<PyHillTononiNeuron>(),
        TypeId::of::<PyHindmarshRoseNeuron>(),
        TypeId::of::<PyHodgkinHuxleyNeuron>(),
        TypeId::of::<PyHuberBraunNeuron>(),
        TypeId::of::<PyIbarzTanakaMapNeuron>(),
        TypeId::of::<PyInhibitoryLIFNeuron>(),
        TypeId::of::<PyKLIFNeuron>(),
        TypeId::of::<PyKilincBhattMapNeuron>(),
        TypeId::of::<PyLearnableNeuronModel>(),
        TypeId::of::<PyMATNeuron>(),
        TypeId::of::<PyMainenSejnowskiNeuron>(),
        TypeId::of::<PyMcKeanNeuron>(),
        TypeId::of::<PyMedvedevMapNeuron>(),
        TypeId::of::<PyMihalasNieburNeuron>(),
        TypeId::of::<PyMorrisLecarNeuron>(),
        TypeId::of::<PyMulticompartmentMCNNeuron>(),
        TypeId::of::<PyNonResettingLIFNeuron>(),
        TypeId::of::<PyNonlinearLIFNeuron>(),
        TypeId::of::<PyParametricLIFNeuron>(),
        TypeId::of::<PyPerfectIntegratorNeuron>(),
        TypeId::of::<PyPernarowskiNeuron>(),
        TypeId::of::<PyPlantR15Neuron>(),
        TypeId::of::<PyPospischilNeuron>(),
        TypeId::of::<PyPrescottNeuron>(),
        TypeId::of::<PyQuadraticIFNeuron>(),
        TypeId::of::<PyResonateAndFireNeuron>(),
        TypeId::of::<PyRulkovMapNeuron>(),
        TypeId::of::<PySFANeuron>(),
        TypeId::of::<PyShermanRinzelKeizerNeuron>(),
        TypeId::of::<PySigmaDeltaNeuron>(),
        TypeId::of::<PyTermanWangOscillator>(),
        TypeId::of::<PyThetaNeuron>(),
        TypeId::of::<PyTraubMilesNeuron>(),
        TypeId::of::<PyWangBuzsakiNeuron>(),
        TypeId::of::<PyWilsonHRNeuron>(),
        TypeId::of::<PyYamadaNeuron>(),
        TypeId::of::<PyAlphaMotorNeuron>(),
        TypeId::of::<PyGammaMotorNeuron>(),
        TypeId::of::<PyUpperMotorNeuron>(),
        TypeId::of::<PyRenshawCell>(),
        TypeId::of::<PyMotorUnit>(),
        TypeId::of::<PyPVFastSpikingNeuron>(),
        TypeId::of::<PySSTNeuron>(),
        TypeId::of::<PyVIPNeuron>(),
        TypeId::of::<PyChandelierNeuron>(),
        TypeId::of::<PyCerebellarBasketNeuron>(),
        TypeId::of::<PyMartinottiNeuron>(),
        TypeId::of::<PyGranuleCell>(),
        TypeId::of::<PyGolgiCell>(),
        TypeId::of::<PyStellateCell>(),
        TypeId::of::<PyLugaroCell>(),
        TypeId::of::<PyUnipolarBrushCell>(),
        TypeId::of::<PyDCNNeuron>(),
        TypeId::of::<PyPersistentNaNeuron>(),
        TypeId::of::<PyIhNeuron>(),
        TypeId::of::<PyTTypeCaNeuron>(),
        TypeId::of::<PyATypeKNeuron>(),
        TypeId::of::<PyBKNeuron>(),
        TypeId::of::<PySKNeuron>(),
        TypeId::of::<PyNMDANeuron>(),
        TypeId::of::<PyMontbrioMeanField>(),
        TypeId::of::<PyBrunelNetwork>(),
        TypeId::of::<PyTUMNetwork>(),
        TypeId::of::<PyElBoustaniNetwork>(),
        TypeId::of::<PyGradedSynapseNeuron>(),
        TypeId::of::<PyGapJunctionNeuron>(),
        TypeId::of::<PyFHAxon>(),
        TypeId::of::<PyNodeOfRanvier>(),
        TypeId::of::<PyMyelinatedAxon>(),
        TypeId::of::<PyCardiacPurkinjeFibre>(),
        TypeId::of::<PySmoothMuscleCell>(),
        TypeId::of::<PyEndocrineBetaCell>(),
        TypeId::of::<PyInnerHairCell>(),
        TypeId::of::<PyOuterHairCell>(),
        TypeId::of::<PyRodPhotoreceptor>(),
        TypeId::of::<PyConePhotoreceptor>(),
        TypeId::of::<PyRetinalGanglionCell>(),
        TypeId::of::<PyMerkelCell>(),
        TypeId::of::<PyPacinianCorpuscle>(),
        TypeId::of::<PyNociceptor>(),
        TypeId::of::<PyOlfactoryReceptorNeuron>(),
        TypeId::of::<PyTasteReceptorCell>(),
        TypeId::of::<PyDirectionSelectiveRGC>(),
        TypeId::of::<PyCochlearHairCell>(),
        TypeId::of::<PyTripletStdpSynapse>(),
        TypeId::of::<PyShortTermPlasticitySynapse>(),
        TypeId::of::<PyDopamineStdpSynapse>(),
    ];
    let unique: HashSet<_> = exports.into_iter().collect();

    assert_eq!(unique.len(), exports.len());
}
