// Auto-generated by SC-NeuroCore equation compiler
// Source: EquationNeuron(dv/dt = (-v + I) / tau)
// Fixed-point: Q8.8 (16-bit signed)
`timescale 1ns / 1ps

module sc_equation_neuron #(
    parameter signed [15:0] P_TAU = 16'sd5120,
    parameter signed [15:0] P_V_RESET_VAL = 16'sd0
)(
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] I_t,
    output reg spike_out,
    output reg signed [15:0] v_out
);

reg signed [15:0] v_reg;

wire signed [31:0] _dt_mul_v = ((((-v_reg) + I_t) / P_TAU)) * 16'sd0;

wire signed [15:0] dv = (_dt_mul_v >>> 8)[15:0];

wire signed [16:0] v_raw = v_reg + dv;
wire signed [15:0] v_next = (v_raw > 17'sd32767) ? 16'sd32767 : (v_raw < 17'sd-32768) ? 16'sd-32768 : v_raw[15:0];

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        v_reg <= 16'sd0;
        v_out <= 16'sd0;
        spike_out <= 1'b0;
    end else begin
        if ((v_reg > 16'sd256)) begin
            spike_out <= 1'b1;
                    v_reg <= P_V_RESET_VAL;
            v_out <= v_reg;
        end else begin
            spike_out <= 1'b0;
            v_reg <= v_next;
            v_out <= v_next;
        end
    end
end

endmodule