// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Auto-generated softplus LUT for Vmin_LIF — DO NOT EDIT
// Generated by tools/gen_vmin_lif_lut.py
// Q8.8 fixed-point, 64 entries, range z ∈ [0, 16.0]
// beta = 1.0, v_inf = -5.0
`define VMIN_LUT_SIZE 64
`define VMIN_LUT_RANGE_Q88 4096
`define VMIN_LUT_00 16'sd177
`define VMIN_LUT_01 16'sd211
`define VMIN_LUT_02 16'sd249
`define VMIN_LUT_03 16'sd291
`define VMIN_LUT_04 16'sd336
`define VMIN_LUT_05 16'sd384
`define VMIN_LUT_06 16'sd436
`define VMIN_LUT_07 16'sd489
`define VMIN_LUT_08 16'sd544
`define VMIN_LUT_09 16'sd602
`define VMIN_LUT_10 16'sd660
`define VMIN_LUT_11 16'sd720
`define VMIN_LUT_12 16'sd780
`define VMIN_LUT_13 16'sd842
`define VMIN_LUT_14 16'sd904
`define VMIN_LUT_15 16'sd966
`define VMIN_LUT_16 16'sd1029
`define VMIN_LUT_17 16'sd1092
`define VMIN_LUT_18 16'sd1155
`define VMIN_LUT_19 16'sd1218
`define VMIN_LUT_20 16'sd1282
`define VMIN_LUT_21 16'sd1345
`define VMIN_LUT_22 16'sd1409
`define VMIN_LUT_23 16'sd1473
`define VMIN_LUT_24 16'sd1537
`define VMIN_LUT_25 16'sd1600
`define VMIN_LUT_26 16'sd1664
`define VMIN_LUT_27 16'sd1728
`define VMIN_LUT_28 16'sd1792
`define VMIN_LUT_29 16'sd1856
`define VMIN_LUT_30 16'sd1920
`define VMIN_LUT_31 16'sd1984
`define VMIN_LUT_32 16'sd2048
`define VMIN_LUT_33 16'sd2112
`define VMIN_LUT_34 16'sd2176
`define VMIN_LUT_35 16'sd2240
`define VMIN_LUT_36 16'sd2304
`define VMIN_LUT_37 16'sd2368
`define VMIN_LUT_38 16'sd2432
`define VMIN_LUT_39 16'sd2496
`define VMIN_LUT_40 16'sd2560
`define VMIN_LUT_41 16'sd2624
`define VMIN_LUT_42 16'sd2688
`define VMIN_LUT_43 16'sd2752
`define VMIN_LUT_44 16'sd2816
`define VMIN_LUT_45 16'sd2880
`define VMIN_LUT_46 16'sd2944
`define VMIN_LUT_47 16'sd3008
`define VMIN_LUT_48 16'sd3072
`define VMIN_LUT_49 16'sd3136
`define VMIN_LUT_50 16'sd3200
`define VMIN_LUT_51 16'sd3264
`define VMIN_LUT_52 16'sd3328
`define VMIN_LUT_53 16'sd3392
`define VMIN_LUT_54 16'sd3456
`define VMIN_LUT_55 16'sd3520
`define VMIN_LUT_56 16'sd3584
`define VMIN_LUT_57 16'sd3648
`define VMIN_LUT_58 16'sd3712
`define VMIN_LUT_59 16'sd3776
`define VMIN_LUT_60 16'sd3840
`define VMIN_LUT_61 16'sd3904
`define VMIN_LUT_62 16'sd3968
`define VMIN_LUT_63 16'sd4032
