# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Studio code export from a resolved experiment

"""Generate Python that runs the experiment the Studio actually ran.

Exported code is written from a resolved
:class:`~sc_neurocore.studio.experiment_spec.ExperimentSpec`, never from a
guess about the model's constructor or step signature. The script restates the
request, re-resolves it through the public contract, refuses to continue if the
installed package resolves a different experiment, and then runs it through the
public runner.

That indirection is the point. An export that hand-writes a stepping loop has
to assume the model takes ``current=``, exposes ``v``, integrates at its
default time step and receives a constant drive — assumptions that are false
for much of the catalogue and silently produce a different experiment when they
are. Going through the contract means the exported script honours the time
step, the drive protocol, the initial state, the parameter overrides and the
randomness of the run it came from, for every model, by construction.
"""

from __future__ import annotations

import json
from typing import Any

from sc_neurocore.studio.experiment_spec import ExperimentSpec

_HEADER = '''"""Reproduce one SC-NeuroCore Studio experiment.

Generated by SC-NeuroCore Studio. The request below is the effective
experiment: time step, drive protocol, initial state, parameters and
randomness are all part of it. Editing a value changes the experiment, and
the digest check will say so.

Run:  python this_script.py
"""

from sc_neurocore.studio.experiment_spec import resolve_experiment, run_experiment
'''

_FOOTER = """
EXPERIMENT_SHA256 = {digest!r}

spec = resolve_experiment(REQUEST)
if spec.experiment_sha256 != EXPERIMENT_SHA256:
    raise SystemExit(
        "This installation resolves a different experiment than the one exported "
        f"(installed {{spec.experiment_sha256}}, exported {{EXPERIMENT_SHA256}}). "
        "Compare spec.public with the exported specification before trusting a result."
    )

result = run_experiment(spec)

print(f"{{result['spike_count']}} spikes in {{result['n_steps']}} steps "
      f"at dt {{result['dt']}} ms ({{result['stats']['rate_hz']:.1f}} Hz)")
print("final state:", result["final_state"])

# Full-resolution traces, when you want them:
# from sc_neurocore.studio.trace_projection import full_state_traces
# traces = full_state_traces(result)
"""


def _request_literal(request: dict[str, Any]) -> str:
    """Render a request mapping as a readable, deterministic Python literal."""
    lines = ["REQUEST = {"]
    for key in sorted(request):
        lines.append(f"    {json.dumps(key)}: {json.dumps(request[key])},")
    lines.append("}")
    return "\n".join(lines)


def generate_experiment_script(spec: ExperimentSpec, request: dict[str, Any]) -> str:
    """Generate a standalone script that reproduces one resolved experiment.

    Parameters
    ----------
    spec : ExperimentSpec
        The resolved experiment the script must reproduce.
    request : dict
        The request fields that re-resolve to ``spec``; a drawn seed must
        already be pinned (see
        :func:`~sc_neurocore.studio.replay_pack.pinned_request`).

    Returns
    -------
    str
        Python source. It re-resolves the request, refuses on a digest
        mismatch, runs the experiment through the public runner and reports the
        spike count, the effective time step and the final state.
    """
    body = _request_literal(request)
    footer = _FOOTER.format(digest=spec.experiment_sha256)
    return f"{_HEADER}\n\n{body}\n{footer}"


def generate_replay_script(pack_filename: str = "replay_pack.json") -> str:
    """Generate a script that replays a saved pack and compares it in full.

    Parameters
    ----------
    pack_filename : str
        Name of the ``studio.replay-pack.v2`` file the script reads, relative
        to the script's working directory.

    Returns
    -------
    str
        Python source that verifies, runs and judges the pack, and exits
        0 for reproduction, 1 for mismatch or 2 for refusal before execution.
        Refusal details are JSON on standard error, matching the public CLI.
    """
    return f'''"""Replay a saved SC-NeuroCore Studio experiment and compare it in full.

Exit status: 0 reproduced, 1 did not reproduce, 2 refused before running.

Uses the public replay command's admission checks and exit statuses.
"""

from sc_neurocore.studio.replay_pack import main

raise SystemExit(main(["--", {pack_filename!r}]))
'''


def generate_oneliner(spec: ExperimentSpec, request: dict[str, Any]) -> str:
    """Generate a copy-paste one-liner that runs the same experiment.

    Parameters
    ----------
    spec : ExperimentSpec
        The resolved experiment. Its source decides nothing here; the request
        carries everything the contract needs.
    request : dict
        The request fields that re-resolve to ``spec``.

    Returns
    -------
    str
        A single line for a notebook or a ``python -c`` invocation. It runs the
        same effective experiment as the exported script; it does not check the
        digest, so use the script when reproducibility must be proven.
    """
    literal = json.dumps(request, sort_keys=True)
    return (
        "from sc_neurocore.studio.experiment_spec import resolve_experiment, run_experiment; "
        f"r = run_experiment(resolve_experiment({literal})); "
        "print(r['spike_count'], 'spikes in', r['n_steps'], 'steps')"
    )


__all__ = [
    "generate_experiment_script",
    "generate_oneliner",
    "generate_replay_script",
]
