// Auto-generated by SC-NeuroCore IR Compiler v3.0
// Source graph: sc_dense_layer
// Do not edit — regenerate from IR source.

`timescale 1ns / 1ps

module sc_dense_layer (
    input wire clk,
    input wire rst_n,
    input wire [15:0] x_input,
    input wire [15:0] weights,
    input wire [15:0] leak_k,
    input wire [15:0] gain_k,
    output wire [6:0] spikes
);

    wire [6:0] v4_spikes;
    wire v4_running;
    wire v4_done;

    sc_dense_layer_core #(
        .N_INPUTS(3),
        .N_NEURONS(7),
        .DATA_WIDTH(16)
    ) u_dense_0 (
        .clk(clk),
        .rst_n(rst_n),
        .start_pulse(1'b1),
        .stream_len(32'd1024),
        .x_input_fp(x_input),
        .weight_fp(weights),
        .y_min_fp(16'd0),
        .y_max_fp(16'd256),
        .cfg_leak(leak_k),
        .cfg_gain(gain_k),
        .I_t(),
        .spikes(v4_spikes),
        .step_valid(),
        .run_done(v4_done),
        .running(v4_running)
    );

    assign spikes = v4_spikes;

endmodule
