// Auto-generated by SC-NeuroCore IR Compiler v3.0
// Source graph: sc_synapse
// Do not edit — regenerate from IR source.

`timescale 1ns / 1ps

module sc_synapse (
    input wire clk,
    input wire rst_n,
    input wire [15:0] x_prob,
    input wire [15:0] w_prob,
    output wire [63:0] firing_rate
);

    wire v2;
    wire v3;
    wire v4;
    wire [63:0] v5;
    wire [63:0] v6;

    sc_bitstream_encoder #(
        .DATA_WIDTH(16),
        .SEED_INIT(16'hACE1)
    ) u_enc_0 (
        .clk(clk),
        .rst_n(rst_n),
        .x_value(x_prob),
        .t_index(32'd0),
        .bit_out(v2)
    );

    sc_bitstream_encoder #(
        .DATA_WIDTH(16),
        .SEED_INIT(16'hBEEF)
    ) u_enc_1 (
        .clk(clk),
        .rst_n(rst_n),
        .x_value(w_prob),
        .t_index(32'd0),
        .bit_out(v3)
    );

    sc_bitstream_synapse u_syn_2 (
        .pre_bit(v2),
        .w_bit(v3),
        .post_bit(v4)
    );

    assign v5 = {63'd0, v4};
    assign v6 = v5 / 1024;
    assign firing_rate = v6;

endmodule
