# SPDX-License-Identifier: AGPL-3.0-or-later
"""SC-NeuroCore neuron library - 80+ models, one file per model.

Import any model:
    from sc_neurocore.neurons import HodgkinHuxleyNeuron
    from sc_neurocore.neurons.models.hodgkin_huxley import HodgkinHuxleyNeuron
"""

# Core SC neurons
from .base import BaseNeuron
from .stochastic_lif import StochasticLIFNeuron
from .fixed_point_lif import FixedPointLIFNeuron, FixedPointLFSR, FixedPointBitstreamEncoder
from .homeostatic_lif import HomeostaticLIFNeuron
from .dendritic import StochasticDendriticNeuron
from .sc_izhikevich import SCIzhikevichNeuron

# All extended models (one file per model)
from .models import (
    AdExNeuron,
    AdaptiveThresholdIFNeuron,
    AkidaNeuron,
    AlphaNeuron,
    AmariNeuralField,
    BendaHerzNeuron,
    BertramPhantomBurster,
    BoothRinzelNeuron,
    BrainScaleSAdExNeuron,
    ButeraRespiratoryNeuron,
    COBALIFNeuron,
    CazellesMapNeuron,
    ChayNeuron,
    ChialvoMapNeuron,
    CompteWMNeuron,
    ConnorStevensNeuron,
    CourageNekorkinMapNeuron,
    DPINeuron,
    DestexheThalamicNeuron,
    EnergyLIFNeuron,
    ErmentroutKopellPopulation,
    EscapeRateNeuron,
    ExpIFNeuron,
    FitzHughNagumoNeuron,
    FitzHughRinzelNeuron,
    FractionalLIFNeuron,
    GLIFNeuron,
    GLMNeuron,
    GalvesLocherbachNeuron,
    GammaRenewalNeuron,
    GatedLIFNeuron,
    GolombFSNeuron,
    GutkinErmentroutNeuron,
    HindmarshRoseNeuron,
    HodgkinHuxleyNeuron,
    HuberBraunNeuron,
    IbarzTanakaMapNeuron,
    InhomogeneousPoissonNeuron,
    JansenRitUnit,
    LapicqueNeuron,
    LeakyCompeteFireNeuron,
    LoihiCUBANeuron,
    MATNeuron,
    MainenSejnowskiNeuron,
    McCullochPittsNeuron,
    McKeanNeuron,
    MedvedevMapNeuron,
    MihalasNieburNeuron,
    MorrisLecarNeuron,
    NonResettingLIFNeuron,
    NonlinearLIFNeuron,
    ParametricLIFNeuron,
    PerfectIntegratorNeuron,
    PinskyRinzelNeuron,
    PlantR15Neuron,
    PoissonNeuron,
    PospischilNeuron,
    PrescottNeuron,
    QuadraticIFNeuron,
    ResonateAndFireNeuron,
    RulkovMapNeuron,
    SFANeuron,
    ShermanRinzelKeizerNeuron,
    SigmaDeltaNeuron,
    SigmoidRateNeuron,
    SpiNNakerLIFNeuron,
    SpikeResponseNeuron,
    StochasticIFNeuron,
    TermanWangOscillator,
    ThetaNeuron,
    ThresholdLinearRateNeuron,
    TraubMilesNeuron,
    TrueNorthNeuron,
    TsodyksMarkramNeuron,
    TwoCompartmentLIFNeuron,
    WangBuzsakiNeuron,
    WilsonCowanUnit,
    WilsonHRNeuron,
    WongWangUnit,
)

__all__ = [
    "BaseNeuron",
    "StochasticLIFNeuron",
    "FixedPointLIFNeuron",
    "FixedPointLFSR",
    "FixedPointBitstreamEncoder",
    "HomeostaticLIFNeuron",
    "StochasticDendriticNeuron",
    "SCIzhikevichNeuron",
    "AdExNeuron",
    "AdaptiveThresholdIFNeuron",
    "AkidaNeuron",
    "AlphaNeuron",
    "AmariNeuralField",
    "BendaHerzNeuron",
    "BertramPhantomBurster",
    "BoothRinzelNeuron",
    "BrainScaleSAdExNeuron",
    "ButeraRespiratoryNeuron",
    "COBALIFNeuron",
    "CazellesMapNeuron",
    "ChayNeuron",
    "ChialvoMapNeuron",
    "CompteWMNeuron",
    "ConnorStevensNeuron",
    "CourageNekorkinMapNeuron",
    "DPINeuron",
    "DestexheThalamicNeuron",
    "EnergyLIFNeuron",
    "ErmentroutKopellPopulation",
    "EscapeRateNeuron",
    "ExpIFNeuron",
    "FitzHughNagumoNeuron",
    "FitzHughRinzelNeuron",
    "FractionalLIFNeuron",
    "GLIFNeuron",
    "GLMNeuron",
    "GalvesLocherbachNeuron",
    "GammaRenewalNeuron",
    "GatedLIFNeuron",
    "GolombFSNeuron",
    "GutkinErmentroutNeuron",
    "HindmarshRoseNeuron",
    "HodgkinHuxleyNeuron",
    "HuberBraunNeuron",
    "IbarzTanakaMapNeuron",
    "InhomogeneousPoissonNeuron",
    "JansenRitUnit",
    "LapicqueNeuron",
    "LeakyCompeteFireNeuron",
    "LoihiCUBANeuron",
    "MATNeuron",
    "MainenSejnowskiNeuron",
    "McCullochPittsNeuron",
    "McKeanNeuron",
    "MedvedevMapNeuron",
    "MihalasNieburNeuron",
    "MorrisLecarNeuron",
    "NonResettingLIFNeuron",
    "NonlinearLIFNeuron",
    "ParametricLIFNeuron",
    "PerfectIntegratorNeuron",
    "PinskyRinzelNeuron",
    "PlantR15Neuron",
    "PoissonNeuron",
    "PospischilNeuron",
    "PrescottNeuron",
    "QuadraticIFNeuron",
    "ResonateAndFireNeuron",
    "RulkovMapNeuron",
    "SFANeuron",
    "ShermanRinzelKeizerNeuron",
    "SigmaDeltaNeuron",
    "SigmoidRateNeuron",
    "SpiNNakerLIFNeuron",
    "SpikeResponseNeuron",
    "StochasticIFNeuron",
    "TermanWangOscillator",
    "ThetaNeuron",
    "ThresholdLinearRateNeuron",
    "TraubMilesNeuron",
    "TrueNorthNeuron",
    "TsodyksMarkramNeuron",
    "TwoCompartmentLIFNeuron",
    "WangBuzsakiNeuron",
    "WilsonCowanUnit",
    "WilsonHRNeuron",
    "WongWangUnit",
]
