#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — Extract SHD model weights, delays, scales from PyTorch checkpoint
"""Extract Masquelier SHD model parameters from a PyTorch .pth checkpoint
into FPGA-friendly artifacts:

  weights_layer1_int8.hex   — int8 quantised weights, row-major
  weights_layer2_int8.hex
  weights_layer3_int8.hex
  weights_layer1.csr.json   — CSR sparse representation (col_idx + values)
  weights_layer2.csr.json
  weights_layer3.csr.json
  delays_layer1.hex         — integer axonal delays per source neuron
  delays_layer2.hex
  scales.json               — per-tensor quantisation scales
  network_params.vh         — Verilog `define statements with sizes
  metadata.json             — provenance + statistics

Per-tensor symmetric int8 quantisation (matches PyTorch QAT pipeline):
  scale = max(|w|) / 127
  w_q   = round(w / scale).clip(-128, 127)
  w_dequant = w_q * scale  (used to verify)

Sparsity preserved: zero weights stay zero (no random mask), CSR format
emits only non-zero entries.

Reference dynamics: see tools/gen_vmin_lif_lut.py
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass

# Lazy torch import — failing fast with a clear error if venv is not active
try:
    import torch
except ModuleNotFoundError as exc:
    sys.stderr.write(
        "ERROR: torch not installed. Activate venv-cuda first:\n  source ~/venv-cuda/bin/activate\n"
    )
    raise SystemExit(2) from exc


@dataclass(frozen=True)
class LayerSpec:
    """Layer in the SHD network."""

    name: str
    state_dict_key: str
    delay_key: str | None  # None for layers without DCLS axonal delay
    in_features: int
    out_features: int


SHD_LAYERS: tuple[LayerSpec, ...] = (
    LayerSpec("layer1_input_to_h1", "layers.1.weight", "layers.0.P", 140, 128),
    LayerSpec("layer2_h1_to_h2", "layers.6.weight", "layers.5.P", 128, 128),
    LayerSpec("layer3_h2_output", "layers.10.weight", None, 128, 20),
)


def quantise_per_tensor_symmetric(w):
    """Per-tensor symmetric int8 quantisation. Returns (int8_array, scale).

    scale = max(|w|) / 127
    w_q   = round(w / scale).clip(-128, 127)
    """
    abs_max = float(w.abs().max().item())
    if abs_max == 0.0:
        return torch.zeros_like(w, dtype=torch.int8), 0.0
    scale = abs_max / 127.0
    w_q = (w / scale).round().clamp(-128, 127).to(torch.int8)
    return w_q, scale


def write_int8_hex(weights_int8, path: str) -> None:
    """Dump int8 weights as a Verilog $readmemh-compatible hex file.

    Each line: one byte (signed int8 → unsigned hex). Row-major order.
    """
    flat = weights_int8.flatten().tolist()
    with open(path, "w") as f:
        f.write("// Auto-generated by tools/extract_shd_weights.py\n")
        f.write(f"// {len(flat)} int8 weights, row-major\n")
        for v in flat:
            byte = v if v >= 0 else (256 + v)  # signed → unsigned 8-bit
            f.write(f"{byte:02x}\n")


def to_csr(weights_int8):
    """Convert int8 dense matrix to CSR (only non-zero entries).

    Returns dict with row_ptr, col_idx, values — all standard CSR.
    """
    rows, cols = weights_int8.shape
    row_ptr = [0]
    col_idx: list[int] = []
    values: list[int] = []
    for r in range(rows):
        for c in range(cols):
            v = int(weights_int8[r, c].item())
            if v != 0:
                col_idx.append(c)
                values.append(v)
        row_ptr.append(len(values))
    return {
        "shape": [rows, cols],
        "nnz": len(values),
        "sparsity_pct": 100.0 * (1.0 - len(values) / (rows * cols)),
        "row_ptr": row_ptr,
        "col_idx": col_idx,
        "values": values,
    }


def write_delays_hex(delays_int, path: str) -> None:
    """Dump integer delays as Verilog hex file (signed 5-bit fits in [-15, +15])."""
    with open(path, "w") as f:
        f.write("// Auto-generated by tools/extract_shd_weights.py\n")
        f.write(f"// {len(delays_int)} integer axonal delays, signed 5-bit\n")
        for d in delays_int:
            d_int = int(d)
            byte = d_int if d_int >= 0 else (256 + d_int)
            f.write(f"{byte:02x}\n")


def emit_params_vh(stats: dict, path: str) -> None:
    """Emit Verilog `define header with network sizes and constants."""
    lines = [
        "// Auto-generated SHD network parameters — DO NOT EDIT",
        "// Generated by tools/extract_shd_weights.py",
        f"// Source checkpoint: {stats['checkpoint']}",
        f"// Trained val_acc: {stats['val_acc']:.2f}%",
        f"// Trained sigma: {stats['native_sigma']:.4f}",
        "",
        f"`define SHD_INPUT_SIZE  {stats['input_size']}",
        f"`define SHD_HIDDEN1     {stats['hidden1']}",
        f"`define SHD_HIDDEN2     {stats['hidden2']}",
        f"`define SHD_OUTPUT      {stats['output']}",
        f"`define SHD_MAX_DELAY   {stats['max_delay']}",
        "",
        "// Q8.8 quantisation scales (multiply int8 by these to recover float)",
    ]
    for layer_name, sc in stats["scales"].items():
        lines.append(f"// {layer_name}: scale = {sc:.6f}")
    return open(path, "w").write("\n".join(lines) + "\n")


def extract(ckpt_path: str, out_dir: str) -> dict:
    """Main extraction routine. Returns stats dictionary."""
    print(f"Loading checkpoint: {ckpt_path}")
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    state_dict = ckpt["net"]
    val_acc = float(ckpt.get("acc", float("nan")))
    epoch = int(ckpt.get("epoch", -1))
    native_sigma = float(ckpt.get("sigma", float("nan")))
    print(f"  val_acc={val_acc:.2f}%, epoch={epoch}, sigma={native_sigma:.4f}")

    os.makedirs(out_dir, exist_ok=True)

    scales: dict[str, float] = {}
    layer_stats: list[dict] = []

    for layer in SHD_LAYERS:
        w = state_dict[layer.state_dict_key].detach()
        if w.shape != (layer.out_features, layer.in_features):
            raise SystemExit(
                f"shape mismatch for {layer.name}: "
                f"got {tuple(w.shape)}, expected ({layer.out_features},{layer.in_features})"
            )

        w_q, scale = quantise_per_tensor_symmetric(w)
        scales[layer.name] = scale

        # Verify quantisation error is bounded
        w_dequant = w_q.float() * scale
        max_err = float((w - w_dequant).abs().max().item())
        rel_err = max_err / max(abs(float(w.abs().max().item())), 1e-12)

        # Sparsity statistics
        nnz = int((w_q != 0).sum().item())
        total = w_q.numel()
        sp_pct = 100.0 * (1.0 - nnz / total)

        # Emit hex + CSR
        hex_path = os.path.join(out_dir, f"weights_{layer.name}_int8.hex")
        write_int8_hex(w_q, hex_path)
        csr = to_csr(w_q)
        csr_path = os.path.join(out_dir, f"weights_{layer.name}.csr.json")
        with open(csr_path, "w") as f:
            json.dump(csr, f)

        print(
            f"  {layer.name}: shape={tuple(w.shape)}, "
            f"scale={scale:.6f}, max_err={max_err:.4e}, "
            f"sparsity={sp_pct:.1f}%, nnz={nnz}/{total}"
        )

        layer_stats.append(
            {
                "name": layer.name,
                "shape": list(w.shape),
                "scale": scale,
                "max_quant_err": max_err,
                "rel_quant_err": rel_err,
                "nnz": nnz,
                "total": total,
                "sparsity_pct": sp_pct,
            }
        )

        # Delays for this layer (if it has an axonal DCLS layer)
        if layer.delay_key is not None:
            P = state_dict[layer.delay_key].detach().squeeze()
            if P.ndim != 1:
                raise SystemExit(f"unexpected delay shape for {layer.name}: {P.shape}")
            P_int = P.round().to(torch.int8)
            frac = float((P - P.round()).abs().mean().item())
            d_path = os.path.join(out_dir, f"delays_{layer.name}.hex")
            write_delays_hex(P_int.tolist(), d_path)
            print(
                f"  {layer.name} delays: n={len(P_int)}, "
                f"range=[{int(P_int.min())},{int(P_int.max())}], "
                f"mean_frac={frac:.6f}"
            )

    # Save scales
    with open(os.path.join(out_dir, "scales.json"), "w") as f:
        json.dump(scales, f, indent=2)

    # Network params header
    stats = {
        "checkpoint": ckpt_path,
        "val_acc": val_acc,
        "epoch": epoch,
        "native_sigma": native_sigma,
        "input_size": 140,
        "hidden1": 128,
        "hidden2": 128,
        "output": 20,
        "max_delay": 31,  # max_feedforward_delay from config_SHD
        "scales": scales,
        "layers": layer_stats,
    }
    emit_params_vh(stats, os.path.join(out_dir, "network_params.vh"))

    # Metadata
    with open(os.path.join(out_dir, "metadata.json"), "w") as f:
        json.dump(stats, f, indent=2)

    print(f"\nExtraction complete. Artifacts in: {out_dir}")
    print("Files written:")
    for f in sorted(os.listdir(out_dir)):
        size = os.path.getsize(os.path.join(out_dir, f))
        print(f"  {f}  ({size} bytes)")

    return stats


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("checkpoint", help="Path to PyTorch .pth checkpoint")
    parser.add_argument("--out-dir", required=True, help="Output directory for FPGA artifacts")
    args = parser.parse_args()
    extract(args.checkpoint, args.out_dir)
