// SPDX-License-Identifier: AGPL-3.0-or-later
// Commercial license available
// © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
// © Code 2020–2026 Miroslav Šotek. All rights reserved.
// ORCID: 0009-0009-3560-0851
// Contact: www.anulum.li | protoscience@anulum.li
// SC-NeuroCore — Vmin_LIF neuron (Masquelier SHD model)
//
// Hand-coded Q8.8 fixed-point implementation of the Vmin_LIFNode used in
// the Masquelier SHD speech recognition model.
//
// Per-step dynamics (matches PyTorch JIT eval order
// jit_eval_single_step_forward_hard_reset_no_decay_input):
//
//   1. v_charged   = v * (1 - 1/tau) + x          (neuronal_charge_no_decay_input)
//   2. spike       = (v_charged >= v_threshold)   (fire on CHARGED v, BEFORE floor)
//   3. v_post_rst  = spike ? v_reset : v_charged  (hard reset)
//   4. v_next      = v_inf + softplus(v_post_rst - v_inf, beta)  (vmin floor LAST)
//
// All arithmetic is signed Q8.8 (16-bit). The softplus floor is computed
// via a 64-entry LUT (vmin_lif_lut.vh) generated by tools/gen_vmin_lif_lut.py
// with linear interpolation between entries.
//
// Bit-true reference: tools/gen_vmin_lif_lut.py vmin_lif_step_q88()
// Verified by:        tools/test_gen_vmin_lif_lut.py (33 tests)
// Cosim status:       see hdl/tb_vmin_lif_neuron.v + tools/cosim_vmin_lif_verilog.py

`timescale 1ns / 1ps
`include "vmin_lif_lut.vh"

module sc_vmin_lif_neuron #(
    parameter signed [15:0] DECAY    = 16'sd192,    // 0.75 = 1 - 1/tau, tau=4
    parameter signed [15:0] V_THRESH = 16'sd256,    // 1.0
    parameter signed [15:0] V_RESET  = 16'sd0,      // 0.0
    parameter signed [15:0] V_INF    = -16'sd1280   // -5.0
)(
    input  wire              clk,
    input  wire              rst_n,
    input  wire signed [15:0] x_in,    // synaptic input current, Q8.8
    // Registered outputs (1-cycle latency, used by tb_vmin_lif_neuron).
    output reg               spike,
    output reg  signed [15:0] v_out,
    // Combinational outputs (zero latency, used by sc_shd_top so the
    // full network can advance one full step per clock cycle).
    output wire              spike_comb,
    output wire signed [15:0] v_next_comb
);

    reg signed [15:0] v_reg;

    // ------------------------------------------------------------------
    // Step 1: neuronal_charge_no_decay_input
    //   v_charged = v_reg * (1 - 1/tau) + x_in
    // (v * decay) is Q16.16 -> arithmetic shift right by 8 to get Q8.8
    // Verilog `>>>` on signed wires matches Python `>>` on int (round toward
    // -inf), so v_decay_full[23:8] is bit-true with the Python reference.
    // ------------------------------------------------------------------
    wire signed [31:0] v_decay_full = v_reg * DECAY;
    wire signed [15:0] v_decayed    = v_decay_full[23:8];
    wire signed [16:0] v_charged_full = $signed({v_decayed[15], v_decayed}) +
                                         $signed({x_in[15],     x_in});
    // Saturation to Q8.8 range
    wire signed [15:0] v_charged =
        (v_charged_full >  17'sd32767) ?  16'sd32767 :
        (v_charged_full < -17'sd32768) ? -16'sd32768 :
                                          v_charged_full[15:0];

    // ------------------------------------------------------------------
    // Step 2: fire on CHARGED v (BEFORE the floor, JIT eval order)
    //   spike = (v_charged >= V_THRESH)
    // ------------------------------------------------------------------
    wire spike_now = (v_charged >= V_THRESH);

    // ------------------------------------------------------------------
    // Step 3: hard reset (multiplexed on charged v)
    //   v_post_reset = spike ? V_RESET : v_charged
    // ------------------------------------------------------------------
    wire signed [15:0] v_post_reset = spike_now ? V_RESET : v_charged;

    // ------------------------------------------------------------------
    // Step 4: vmin softplus floor applied to post-reset v
    //   z = v_post_reset - V_INF       (always >= 0 in operating range)
    //   sp = softplus(z) via LUT (linear interp), or z when z >= range
    //   v_next = V_INF + sp
    // ------------------------------------------------------------------
    wire signed [16:0] z_full = $signed({v_post_reset[15], v_post_reset}) -
                                 $signed({V_INF[15],         V_INF});
    wire signed [15:0] z = (z_full < 17'sd0) ? 16'sd0 :
                           (z_full > 17'sd32767) ? 16'sd32767 :
                           z_full[15:0];

    // LUT lookup with linear interpolation
    // idx_full = z * LUT_SIZE / LUT_RANGE_Q88
    // For LUT_SIZE=64, LUT_RANGE_Q88=4096:
    //   idx = (z * 64) / 4096 = z >> 6
    //   frac_num = (z * 64) - (idx * 4096) = (z << 6) - (idx << 12)
    // We use a 6-bit index (z[11:6]) and 6-bit fraction (z[5:0]).
    wire [5:0] lut_idx = z[11:6];
    wire [5:0] frac    = z[5:0];

    // Linear regime: z >= LUT_RANGE_Q88 -> softplus(z) ~= z
    wire z_above_range = (z >= `VMIN_LUT_RANGE_Q88);

    reg signed [15:0] lut_a;
    reg signed [15:0] lut_b;
    always @(*) begin
        case (lut_idx)
            6'd0:  begin lut_a = `VMIN_LUT_00; lut_b = `VMIN_LUT_01; end
            6'd1:  begin lut_a = `VMIN_LUT_01; lut_b = `VMIN_LUT_02; end
            6'd2:  begin lut_a = `VMIN_LUT_02; lut_b = `VMIN_LUT_03; end
            6'd3:  begin lut_a = `VMIN_LUT_03; lut_b = `VMIN_LUT_04; end
            6'd4:  begin lut_a = `VMIN_LUT_04; lut_b = `VMIN_LUT_05; end
            6'd5:  begin lut_a = `VMIN_LUT_05; lut_b = `VMIN_LUT_06; end
            6'd6:  begin lut_a = `VMIN_LUT_06; lut_b = `VMIN_LUT_07; end
            6'd7:  begin lut_a = `VMIN_LUT_07; lut_b = `VMIN_LUT_08; end
            6'd8:  begin lut_a = `VMIN_LUT_08; lut_b = `VMIN_LUT_09; end
            6'd9:  begin lut_a = `VMIN_LUT_09; lut_b = `VMIN_LUT_10; end
            6'd10: begin lut_a = `VMIN_LUT_10; lut_b = `VMIN_LUT_11; end
            6'd11: begin lut_a = `VMIN_LUT_11; lut_b = `VMIN_LUT_12; end
            6'd12: begin lut_a = `VMIN_LUT_12; lut_b = `VMIN_LUT_13; end
            6'd13: begin lut_a = `VMIN_LUT_13; lut_b = `VMIN_LUT_14; end
            6'd14: begin lut_a = `VMIN_LUT_14; lut_b = `VMIN_LUT_15; end
            6'd15: begin lut_a = `VMIN_LUT_15; lut_b = `VMIN_LUT_16; end
            6'd16: begin lut_a = `VMIN_LUT_16; lut_b = `VMIN_LUT_17; end
            6'd17: begin lut_a = `VMIN_LUT_17; lut_b = `VMIN_LUT_18; end
            6'd18: begin lut_a = `VMIN_LUT_18; lut_b = `VMIN_LUT_19; end
            6'd19: begin lut_a = `VMIN_LUT_19; lut_b = `VMIN_LUT_20; end
            6'd20: begin lut_a = `VMIN_LUT_20; lut_b = `VMIN_LUT_21; end
            6'd21: begin lut_a = `VMIN_LUT_21; lut_b = `VMIN_LUT_22; end
            6'd22: begin lut_a = `VMIN_LUT_22; lut_b = `VMIN_LUT_23; end
            6'd23: begin lut_a = `VMIN_LUT_23; lut_b = `VMIN_LUT_24; end
            6'd24: begin lut_a = `VMIN_LUT_24; lut_b = `VMIN_LUT_25; end
            6'd25: begin lut_a = `VMIN_LUT_25; lut_b = `VMIN_LUT_26; end
            6'd26: begin lut_a = `VMIN_LUT_26; lut_b = `VMIN_LUT_27; end
            6'd27: begin lut_a = `VMIN_LUT_27; lut_b = `VMIN_LUT_28; end
            6'd28: begin lut_a = `VMIN_LUT_28; lut_b = `VMIN_LUT_29; end
            6'd29: begin lut_a = `VMIN_LUT_29; lut_b = `VMIN_LUT_30; end
            6'd30: begin lut_a = `VMIN_LUT_30; lut_b = `VMIN_LUT_31; end
            6'd31: begin lut_a = `VMIN_LUT_31; lut_b = `VMIN_LUT_32; end
            6'd32: begin lut_a = `VMIN_LUT_32; lut_b = `VMIN_LUT_33; end
            6'd33: begin lut_a = `VMIN_LUT_33; lut_b = `VMIN_LUT_34; end
            6'd34: begin lut_a = `VMIN_LUT_34; lut_b = `VMIN_LUT_35; end
            6'd35: begin lut_a = `VMIN_LUT_35; lut_b = `VMIN_LUT_36; end
            6'd36: begin lut_a = `VMIN_LUT_36; lut_b = `VMIN_LUT_37; end
            6'd37: begin lut_a = `VMIN_LUT_37; lut_b = `VMIN_LUT_38; end
            6'd38: begin lut_a = `VMIN_LUT_38; lut_b = `VMIN_LUT_39; end
            6'd39: begin lut_a = `VMIN_LUT_39; lut_b = `VMIN_LUT_40; end
            6'd40: begin lut_a = `VMIN_LUT_40; lut_b = `VMIN_LUT_41; end
            6'd41: begin lut_a = `VMIN_LUT_41; lut_b = `VMIN_LUT_42; end
            6'd42: begin lut_a = `VMIN_LUT_42; lut_b = `VMIN_LUT_43; end
            6'd43: begin lut_a = `VMIN_LUT_43; lut_b = `VMIN_LUT_44; end
            6'd44: begin lut_a = `VMIN_LUT_44; lut_b = `VMIN_LUT_45; end
            6'd45: begin lut_a = `VMIN_LUT_45; lut_b = `VMIN_LUT_46; end
            6'd46: begin lut_a = `VMIN_LUT_46; lut_b = `VMIN_LUT_47; end
            6'd47: begin lut_a = `VMIN_LUT_47; lut_b = `VMIN_LUT_48; end
            6'd48: begin lut_a = `VMIN_LUT_48; lut_b = `VMIN_LUT_49; end
            6'd49: begin lut_a = `VMIN_LUT_49; lut_b = `VMIN_LUT_50; end
            6'd50: begin lut_a = `VMIN_LUT_50; lut_b = `VMIN_LUT_51; end
            6'd51: begin lut_a = `VMIN_LUT_51; lut_b = `VMIN_LUT_52; end
            6'd52: begin lut_a = `VMIN_LUT_52; lut_b = `VMIN_LUT_53; end
            6'd53: begin lut_a = `VMIN_LUT_53; lut_b = `VMIN_LUT_54; end
            6'd54: begin lut_a = `VMIN_LUT_54; lut_b = `VMIN_LUT_55; end
            6'd55: begin lut_a = `VMIN_LUT_55; lut_b = `VMIN_LUT_56; end
            6'd56: begin lut_a = `VMIN_LUT_56; lut_b = `VMIN_LUT_57; end
            6'd57: begin lut_a = `VMIN_LUT_57; lut_b = `VMIN_LUT_58; end
            6'd58: begin lut_a = `VMIN_LUT_58; lut_b = `VMIN_LUT_59; end
            6'd59: begin lut_a = `VMIN_LUT_59; lut_b = `VMIN_LUT_60; end
            6'd60: begin lut_a = `VMIN_LUT_60; lut_b = `VMIN_LUT_61; end
            6'd61: begin lut_a = `VMIN_LUT_61; lut_b = `VMIN_LUT_62; end
            6'd62: begin lut_a = `VMIN_LUT_62; lut_b = `VMIN_LUT_63; end
            default: begin lut_a = `VMIN_LUT_63; lut_b = `VMIN_LUT_63; end
        endcase
    end

    // Linear interpolation: a + (b-a) * frac / 64
    wire signed [15:0] lut_diff = lut_b - lut_a;
    wire signed [21:0] lut_diff_scaled = $signed(lut_diff) * $signed({1'b0, frac});
    wire signed [15:0] lut_interp = lut_a + lut_diff_scaled[21:6];

    // Final softplus value: linear regime if above LUT range
    wire signed [15:0] sp_val = z_above_range ? z : lut_interp;

    // v_next = V_INF + sp_val   (post-floor membrane potential, registered next)
    wire signed [16:0] v_next_full = $signed({V_INF[15], V_INF}) +
                                      $signed({sp_val[15], sp_val});
    wire signed [15:0] v_next =
        (v_next_full >  17'sd32767) ?  16'sd32767 :
        (v_next_full < -17'sd32768) ? -16'sd32768 :
                                       v_next_full[15:0];

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            v_reg <= 16'sd0;
            spike <= 1'b0;
            v_out <= 16'sd0;
        end else begin
            v_reg <= v_next;
            spike <= spike_now;
            v_out <= v_next;
        end
    end

    // Combinational taps of the same values (zero-latency view).
    assign spike_comb  = spike_now;
    assign v_next_comb = v_next;

endmodule
