# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SC-NeuroCore — TMR wrapper generator for Verilog modules

"""Auto-generate Triple Modular Redundancy wrappers for Verilog modules.

Given a Verilog module, this utility generates a TMR wrapper that:
1. Instantiates three copies of the target module
2. Connects all inputs in parallel
3. Routes all outputs through ``sc_tmr_voter`` majority voters
4. Exposes a per-output ``error`` flag for fault detection

Usage::

    from sc_neurocore.hdl_gen.tmr_wrapper import generate_tmr_wrapper

    wrapper_code = generate_tmr_wrapper(
        module_name="sc_aer_router",
        inputs=[("clk", 1), ("rst_n", 1), ("packet_in", 32)],
        outputs=[("packet_out", 32), ("valid", 1)],
    )
"""

from __future__ import annotations

import logging

from ._ident import sanitize_ident

logger = logging.getLogger(__name__)


def generate_tmr_wrapper(
    module_name: str,
    inputs: list[tuple[str, int]],
    outputs: list[tuple[str, int]],
    *,
    voter_module: str = "sc_tmr_voter",
) -> str:
    """Generate a TMR wrapper for a given Verilog module.

    Parameters
    ----------
    module_name : str
        Name of the target module to triplicate.
    inputs : list of (name, width) tuples
        Input ports of the target module.
    outputs : list of (name, width) tuples
        Output ports to protect with majority voting.
    voter_module : str
        Name of the voter module (default: ``sc_tmr_voter``).

    Returns
    -------
    str
        Generated Verilog source for the TMR wrapper.
    """
    safe_name = sanitize_ident(module_name, context="TMR target module")
    wrapper_name = f"{safe_name}_tmr"

    lines: list[str] = []
    lines.append(f"// Auto-generated TMR wrapper for {safe_name}")
    lines.append(f"// Generated by SC-NeuroCore tmr_wrapper.py")
    lines.append("")
    lines.append(f"module {wrapper_name} (")

    # Port declarations
    port_lines: list[str] = []
    for name, width in inputs:
        safe = sanitize_ident(name, context="input port")
        if width == 1:
            port_lines.append(f"    input  wire {safe}")
        else:
            port_lines.append(f"    input  wire [{width - 1}:0] {safe}")

    for name, width in outputs:
        safe = sanitize_ident(name, context="output port")
        if width == 1:
            port_lines.append(f"    output wire {safe}")
        else:
            port_lines.append(f"    output wire [{width - 1}:0] {safe}")

    # Error flags
    for name, _width in outputs:
        safe = sanitize_ident(name, context="output port")
        port_lines.append(f"    output wire {safe}_tmr_error")

    lines.append(",\n".join(port_lines))
    lines.append(");")
    lines.append("")

    # Declare internal wires for each replica
    for replica in range(3):
        for name, width in outputs:
            safe = sanitize_ident(name, context="output port")
            if width == 1:
                lines.append(f"    wire rep{replica}_{safe};")
            else:
                lines.append(f"    wire [{width - 1}:0] rep{replica}_{safe};")
    lines.append("")

    # Instantiate three replicas
    for replica in range(3):
        lines.append(f"    {safe_name} replica_{replica} (")
        inst_ports: list[str] = []
        for name, _width in inputs:
            safe = sanitize_ident(name, context="input port")
            inst_ports.append(f"        .{safe}({safe})")
        for name, _width in outputs:
            safe = sanitize_ident(name, context="output port")
            inst_ports.append(f"        .{safe}(rep{replica}_{safe})")
        lines.append(",\n".join(inst_ports))
        lines.append("    );")
        lines.append("")

    # Instantiate voters for each output
    for name, width in outputs:
        safe = sanitize_ident(name, context="output port")
        lines.append(f"    {voter_module} #(.DATA_WIDTH({width})) voter_{safe} (")
        lines.append(f"        .a(rep0_{safe}),")
        lines.append(f"        .b(rep1_{safe}),")
        lines.append(f"        .c(rep2_{safe}),")
        lines.append(f"        .voted({safe}),")
        lines.append(f"        .error({safe}_tmr_error)")
        lines.append("    );")
        lines.append("")

    lines.append("endmodule")
    lines.append("")

    result = "\n".join(lines)
    logger.info("Generated TMR wrapper for %s (%d inputs, %d voted outputs)",
                safe_name, len(inputs), len(outputs))
    return result
